### PR TITLE
BF: Don't unconditionally init annex for remote Git repos.

### PR DESCRIPTION
**Pull request by hanke**
This is a start of a proper fix for gh-404. It actually solves the
reported issue, but leaves open questions (see issue for more).

### CODE REVIEW

**Comment by yarikoptic** [comment]
eh, if only there some unittest to solidify such behavior?

**Comment by hanke** [comment]
Please comment on the original issue. THE behavior is significantly underdefined, hence tests are inappropriate by definition.

**Comment by yarikoptic** [comment]
I will comment on the issue.
As far as code goes, behavior is not underdefined -- it is already coded and as such requires a test.  Otherwise later change in behavior might come unnoticed.  Postponing creating tiny unit-tests for such code until some time later (which gets unlikely to happen at all) would just cause this logic being untested by unit-tests (even though some regression/integration test could later run through all code paths). My few cents

**Comment by hanke** [comment]
PR was premature -- hence closed. The PR was under the assumption that the present behavior is undesired -- but this is not established yet.

**Pull request closed without merging**
