### PR TITLE
OPT minimize initial import times and starttime of various cmdline entry points

### PR DESCRIPTION
**Pull request by yarikoptic**
Inspired by whining against adding import of sshmanager into the top init -- apparently it wasn't the "worst" of our sins ;)

Primarily OPT was done through identifying heavy imports in few spots which we import from all around (e.g. vcr in utils).
It seems to shave off seconds from total run time of some tests (e.g. of customremotes)

I wonder how we could add some tests to somewhat 'establish' baseline import / execution times?
I though that may be (with all those added tracing imports debug lines) we could at least verify that some imports do not happen when we e.g. just execute 'datalad --help' etc.  what do you think?

BTW -- everyone is optimizing imports today !!! ;)  see e.g. https://github.com/tqdm/tqdm/pull/179

### CODE REVIEW

**Comment by yarikoptic** [comment]
coverage decrease is superficial!!! ;)

**Comment by yarikoptic** [comment]
if no objections or recommendations @datalad/developers , I will merge it!

**Comment by hanke** [comment]
First!

**Comment by hanke** [comment]
Which makes Yarik owe me 5 more untested lines and one overall coverage decrease!

**Comment by yarikoptic** [comment]
nope! I had a disclaimer!!! https://github.com/datalad/datalad/pull/498#issuecomment-223466770   Decrease is due to some imports being moved inside untested (before and still) code.  For some code I have added a test (for our datalad.test) but it requires numpy, so I didn't bother pulling in the beast on travis.  I bet it would have increased coverage!!! ;)

**Pull request merged**
