### PR TITLE
Better docs: config variables and easier build

### PR DESCRIPTION
**Pull request by mih**
http://docs.datalad.org/en/docs/
http://docs.datalad.org/en/docs/config.html

Example of a properly formatted variable description:

http://docs.datalad.org/en/docs/config.html#term-datalad-api-always-render

### CODE REVIEW

**Comment by mih** [comment]
A possible next step could be to like config variables with parameters, to be able to set defaults according to user config, or even to share some description or examples for the docs.

**Comment by mih** [comment]
Intermittent failure to the issue in master.

**Comment by mih** [comment]
Now importing the lost of supported env vars into the codebase.

**Comment by yarikoptic** [comment]
Fwiw looks good to me although not sure how/when generation magic where now
Cheers

**Comment by mih** [comment]
@bpoldrack @yarikoptic This one now has a ton of variables renamed. Travis should not be affected (or rather was adjusted), but if you are setting any custom variables, or the buildbots do -- they would all need to be adjusted.

**Comment by mih** [comment]
So this must be a "feature" of an older apidoc module, maybe:

````
/home/travis/build/datalad/datalad/docs/source/generated/datalad.api.rst:46: WARNING: error while formatting arguments for datalad.api.cfg: 'ConfigManager' object has no attribute '__bases__'
````

**Comment by mih** [comment]
I am not sure about this: travis (sphinx 1.4.6, broken); debian stable (sphinx 1.3.6, broken); debian stretch (sphinx 1.4.4; works).

Interestingly, the output from autodoc is very different:

````
% diff -u docs/source/generated/datalad.api.rst broken.rst
--- docs/source/generated/datalad.api.rst	2016-09-29 11:53:44.374495504 +0200
+++ broken.rst	2016-09-29 11:57:09.232052130 +0200
@@ -10,6 +10,16 @@
 
 .. autofunction:: Dataset
 
+`add`
+-----
+
+.. autofunction:: add
+
+`add_`
+------
+
+.. autofunction:: add_
+
 `add_archive_content`
 ---------------------
 
@@ -20,6 +30,21 @@
 
 .. autofunction:: add_sibling
 
+`add_sibling_`
+--------------
+
+.. autofunction:: add_sibling_
+
+`aggregate_metadata`
+--------------------
+
+.. autofunction:: aggregate_metadata
+
+`cfg`
+-----
+
+.. autofunction:: cfg
+
 `clean`
 -------
 
@@ -30,51 +55,111 @@
 
 .. autofunction:: crawl
 
+`crawl_init`
+------------
+
+.. autofunction:: crawl_init
+
 `create`
 --------
 
 .. autofunction:: create
 
-`create_publication_target_sshwebserver`
-----------------------------------------
+`create_`
+---------
+
+.. autofunction:: create_
 
-.. autofunction:: create_publication_target_sshwebserver
+`create_sibling`
+----------------
+
+.. autofunction:: create_sibling
 
 `create_test_dataset`
 ---------------------
 
 .. autofunction:: create_test_dataset
 
+`create_test_dataset_`
+----------------------
+
+.. autofunction:: create_test_dataset_
+
 `download_url`
 --------------
 
 .. autofunction:: download_url
 
+`export`
+--------
+
+.. autofunction:: export
+
+`export_`
+---------
+
+.. autofunction:: export_
+
+`get`
+-----
+
+.. autofunction:: get
+
+`get_`
+------
+
+.. autofunction:: get_
+
 `install`
 ---------
 
 .. autofunction:: install
 
+`install_`
+----------
+
+.. autofunction:: install_
+
 `ls`
 ----
 
 .. autofunction:: ls
 
-`modify_subdataset_urls`
-------------------------
-
-.. autofunction:: modify_subdataset_urls
-
 `publish`
 ---------
 
 .. autofunction:: publish
 
+`publish_`
+----------
+
+.. autofunction:: publish_
+
+`rewrite_urls`
+--------------
+
+.. autofunction:: rewrite_urls
+
 `save`
 ------
 
 .. autofunction:: save
 
+`save_`
+-------
+
+.. autofunction:: save_
+
+`search`
+--------
+
+.. autofunction:: search
+
+`search_`
+---------
+
+.. autofunction:: search_
+
 `test`
 ------
 
@@ -85,11 +170,21 @@
 
 .. autofunction:: uninstall
 
+`uninstall_`
+------------
+
+.. autofunction:: uninstall_
+
 `unlock`
 --------
 
 .. autofunction:: unlock
 
+`unlock_`
+---------
+
+.. autofunction:: unlock_
+
 `update`
 --------
 ````

**Comment by mih** [comment]
Rebased on current master to minimize possibly relevant changes.

**Comment by mih** [comment]
And just to complete the picture: sure thing readthedocs had no trouble building the docs in this branch at any point: http://readthedocs.org/projects/datalad/builds

WTF?

**Comment by yarikoptic** [comment]
Waiting to see if RTFM helped ;-)
Old one byte had memories of a long gone create_publication_target_sshwebserver - was it that old?

**Pull request merged**
