### PR TITLE
RF: Avoid multiple GitWitlessRunner instances

### PR DESCRIPTION
**Pull request by mih**
Now GitRepo itself provides one.

### CODE REVIEW

**Review by kyleam — APPROVED** [review]
Looks good to me (assuming my push fixes the failing tests).

**Comment by mih** [comment]
It looks as if this needs more work. I am merging the other runner/config related PRs and will give this another look. Thx @kyleam for the update.

**Comment by kyleam** [comment]
> It looks as if this needs more work.

The remaining failures should be covered by my latest push (c390b56dc).

**Comment by mih** [comment]
Thx @kyleam !

**Pull request merged**
