### PR TITLE
No GitPython

### LINKED ISSUE #753: GitPython doesn't support WorkTree
as discovered while troubleshooting merge conflicts and running tests while being under a worktree "clone" (https://github.com/datalad/datalad/pull/694/files#r77371433)

``` shell
$> DATALAD_LOGLEVEL=2 nosetests -s -v /home/yoh/proj/datalad/datalad-master/datalad/distribution/tests/test_dataset.py:test_require_dataset
...
2016-09-02 12:09:17,143 [DEBUG  ] Resolved dataset: <Dataset path=/home/yoh/proj/datalad/datalad-master> (dataset.py:577)
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py(107)repo()
-> with swallow_logs():
(Pdb) n
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py(108)repo()
-> for cls, ckw, kw in (
(Pdb) n
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py(109)repo()
-> (AnnexRepo, {'allow_noninitialized': True}, {'init': False}),
(Pdb) n
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py(110)repo()
-> (GitRepo, {}, {})
(Pdb) 
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py(112)repo()
-> if cls.is_valid_repo(self._path, **ckw):
(Pdb) n
2016-09-02 12:09:23,793 [ERROR  ] <class 'git.exc.WorkTreeRepositoryUnsupported'>: /home/yoh/proj/datalad/datalad/.git/worktrees/datalad-debian (gitrepo.py:480)
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py(110)repo()
-> (GitRepo, {}, {})
```

I will fix that test to not run in curdir anyways, but this issue is to alert us of GitPython absent support of worktrees :-/

### LINKED ISSUE #2879: Brain dump on GitPython removal
I am aware that this idea is unpopular, but I am yet to be convinced that carrying around a repository instance in an otherwise entirely stateless setup is adding something valuable enough to be worth the cost. However, this is not to debate this point but rather to summarize what I know about the situation.

### Usage patterns

[ km: Updated for #2902 and #3530 ]

Direct usage of the GitPython API in non-Repo class code is most problematic. Here are those in Datalad-core that I am aware of (`repo` is the GitPython repository object):

- [ ] repo.remotes[remote].refs (create-sibling, publish)
- [ ] repo.repo.commit() (publish)
- [ ] repo.remotes[remote].refs[remote_branch_name] (publish)
- [ ] repo.close() (ls)
- [X] repo.git.show() (gone with #2902)
- [ ] repo.git.merge_base() (GitRepo)
- [X] repo.git.rev_parse() (all but two gone with #2902)
- [X] repo.git_dir (gone with #2902)
- [ ] repo.git (GitRepo, AnnexRepo)
- [X] repo.git.for_each_ref()
- [X] repo.git.log()
- [X] repo.git.ls_tree()
- [X] repo.git.cat_file

and additionally in the associated tests

- [X] repo.git.rev_list()
- [X] repo.head.commit.message
- [x] repo.commit().hexsha
- [X] repo.git.reset()
- [ ] repo.submodule() (GitRepo tests)

### Data structure/object use

Except for PushInfo and Blob these are pretty harmless, as they either do not need a Repo instance, or are more or less static objects.

- [x] git.GitConfigParser
- [x] git.remote.PushInfo
- [x] git.objects.blob.Blob
- [ ] git.exc.InvalidGitRepositoryError
- [ ] gitdb.exc.BadName
- [ ] git.exc.GitCommandError
- [ ] git.exc.NoSuchPathError

### LINKED ISSUE #2970: GitPython use in GitRepo API
This is just a protocol of my exploration. This is no implications re -core, but might be useful in the GitPython RF context.

### GitPython users

Focusing on small helpers, not the big ones like `fetch`

Checked means gone or no longer GitPy-based at the moment:

-  [x] `get_indexed_files()` and `get_files()` (the former seems obsolete, the latter last used in metadata)
-  [x] `get_commit_date()` gh-3814
- [x] `get_active_branch()`
- [x] `get_branches()`
- [x] `get_remote_branches()`
- [x] `get_file_content()` (not used, and not tested) gh-3812
- [x] `_get_files_history()` gh-3811
- [x] `_call_gitpy_with_progress()` gh-4087
- [x] `get_branch_commits()` -- this seems to be mostly used as a test helper gh-3834
- [x] `is_dirty()`
- [x] `untracked_files()`
- [x] `get_submodules()` -- only to check if HEAD exists
- [x] `get_changed_files()` #4169 
- [x] `get_missing_files()`
- [x] `get_deleted_files()`

### PR DESCRIPTION
**Pull request by mih**
The end of a long process. ~~With this PR the only piece left is `ok_clean_git()` that still uses it (158 times), but only in the tests. We have `assert_repo_status()` as a replacement, but the mapping is still effortful.~~

DataLad 0.11.8 on `time datalad create mike`
```
datalad create mike  0.58s user 0.24s system 92% cpu 0.881 total
datalad create mike  0.61s user 0.23s system 99% cpu 0.842 total
datalad create mike  0.51s user 0.27s system 93% cpu 0.825 total
```

This PR on `time datalad create mike`
```
datalad create mike  0.38s user 0.20s system 99% cpu 0.582 total
datalad create mike  0.35s user 0.16s system 99% cpu 0.511 total
datalad create mike  0.39s user 0.14s system 94% cpu 0.556 total
```

This is a 30% boost.

Fixes #2970 
Fixes #2879 
Fixes #753

### CODE REVIEW

**Comment by mih** [comment]
Windows failures are due to unexpectedly open files (familiar from previous PRs).

**Comment by yarikoptic** [comment]
Which is expected since you merged #4157 which introduced those failures and wasn't resolved.

**Comment by mih** [comment]
> Which is expected since you merged #4157 which introduced those failures and wasn't resolved.

No, those were present before and in other PRs.

**Comment by yarikoptic** [comment]
> > Which is expected since you merged #4157 which introduced those failures and wasn't resolved.
> 
> No, those were present before and in other PRs.

hm, may be there was more from others... but FWIW nfs travis run and windows  datalad.support.tests.test_annexrepo.test_find_batch_equivalence failures came up there first AFAIK

**Comment by mih** [comment]
As noted above the NFS failure is #3929 in disguise AFAICS it -- which I reported in Dec 2019. It fails to remove a file that was never part of the report. #3929 has additional info.

**Comment by mih** [comment]
More permission issues of the kind already pointed out here: https://github.com/datalad/datalad/issues/2518

**Comment by mih** [comment]
A bunch of issues were uncovered by this PR. As far as I can see none of them was actually introduced here. I have filed dedicated issues for each of them (see above). Given the number of files touched, I will proceed with smaller follow-up PRs looking at individual issues. The only affected systems are Windows short-path-reporting machines, of which we have none in real life. They should not hold up development.

**Comment by mih** [comment]
I cannot figure out we the NFS travis run stalls. We don't even report which tests are attempted. I have to focus on implementing a functional `publish` replacement now. Feel free to close this PR.

**Comment by mih** [comment]
Found one more leftover import in `datalad/distribution/publish.py`

**Comment by mih** [comment]
So the stalling test is `datalad.support.tests.test_annexrepo.test_annex_ssh`, which primarily (or only) tests `annex sync` operation with SSH remotes.

**Comment by mih** [comment]
Given that the condition of the windows tests is unbearable already, I will no longer hold this. Once travis is happy and appveyor still is, I will merge this.

**Comment by yarikoptic** [comment]
@joeyh - is there a way to install some previous version of git-annex on windows?  I see only https://downloads.kitenet.net/git-annex/windows/current/ and no previous versions.

If we could adjust our windows tests workflows to use some previously working ok version, we could at least re-establish a stable testing ground, and then address windows breakages in a dedicated PR.

**Comment by kyleam** [comment]
> If we could adjust our windows tests workflows to use some previously working ok version, we could at least re-establish a stable testing ground, and then address windows breakages in a dedicated PR.

At least some of the latest Windows failures popped up without any git-annex version change (all are 8.20200226-g2d3ef2c07).  A [change in the Git for Windows version][0] is the main difference I spotted, though I'm not convinced that it's the culprit.

[0]: https://github.com/datalad/datalad/pull/4237#issuecomment-594620181

**Comment by yarikoptic** [comment]
oh right - Windows installation of git-annex is not bundling git (unlike in osx, or git-annex-standalone in neurodebian), heh heh

**Comment by mih** [comment]
I will merge this now. Windows tests are a different matter, and we still haven't reached a point where causal attribution of behavior changes is really a thing.

**Pull request merged**
