### PR TITLE
Use MemoryKeyring in test

### LINKED ISSUE #6623: test_datalad_credential_helper  test wants interaction
while building debian package (unattended), next day spotted that it wants to talk to me

```
datalad.local.tests.test_gitcredential.test_datalad_credential_helper ... Please set a password for your new keyring: 
Please confirm the password: 
Error: blank passwords aren't allowed.
Please set a password for your new keyring: 
```

shouldn't happen, and any needed for that settings (if any) changes should be done in setup_package fixture or prevented via mocking in the test.

### PR DESCRIPTION
**Pull request by bpoldrack**
Trying to fix #6623 and possibly #7165 by using MemoryKeyring with this test.

@yarikoptic Provided CI is happy to begin with, could you please give it a try?

### CODE REVIEW

**Comment by bpoldrack** [comment]
I'll try to set the config file  for `keyring` in the tests env to declare PlaintextKeyring the default, so it wouldn't be encrypted and therefore no need to ask interactively when creating it.

**Comment by bpoldrack** [comment]
Ok, different approach, @yarikoptic : Setting the to be used backend to `PlaintextKeyring` via env var, so it's not encrypted and doesn't ask for password on creation. As far as I can tell keyring figuring the paths to use accounts correctly for the fake HOME. Setting it "fixed" this way shouldn't conflict with tests setting `MemoryKeyring` or other, because that is happening at runtime and at our wrapping layer.
WDYT?

**Comment by yarikoptic** [comment]
sounds good, especially because apparently that is what I ended up doing in debian package:

```
❯ git grep PYTHON_KEYRING_BACKEND
debian/rules:export PYTHON_KEYRING_BACKEND=keyrings.alt.file.PlaintextKeyring
debian/rules:       PYTHON_KEYRING_BACKEND=keyrings.alt.file.PlaintextKeyring PATH=$(CURDIR)/bin:$$PATH \

❯ git log -SPYTHON_KEYRING_BACKEND debian/rules
commit c280fe2646e3f0dd200507c3c295b13d6e800a1f
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Fri Jul 8 18:37:16 2022 -0400

    Various tune ups for build to succeed with testing
```

**Comment by bpoldrack** [comment]
@yarikoptic :

Redone, env var is now patched in setup_package instead of needing to be provided. Should fix #6623 and possibly make your debian patch superfluous. Can you confirm, that #7165 also is addressed?

IIRC, @TheChymera had to deal with that issue as well, right?

**Comment by yarikoptic** [comment]
confirming success -- thank you @bpoldrack !

```
(dev3) yoh@typhon:~/proj/datalad/datalad$ python -m pytest -s -v -k test_datalad_credential_helper --tb=short datalad
====================================================== test session starts ======================================================
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.0.0 -- /home/yoh/proj/datalad/datalad/venvs/dev3/bin/python
cachedir: .pytest_cache
rootdir: /home/yoh/proj/datalad/datalad, configfile: tox.ini
plugins: cov-4.0.0, fail-slow-0.3.0, xdist-3.0.2
collected 1319 items / 1318 deselected / 1 selected                                                                             

datalad/local/tests/test_gitcredential.py::test_datalad_credential_helper create(ok): . (dataset)
PASSEDVersions: annexremote=1.6.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=10.20221103+git83-g31fc11771-1~ndall+1 cmd:bundled-git=UNKNOWN cmd:git=2.30.2 cmd:ssh=8.4p1 cmd:system-git=2.30.2 cmd:system-ssh=8.4p1 datalad=0.17.9+70.gd8d538ae7 exifread=3.0.0 humanize=4.4.0 iso8601=1.1.0 keyring=23.11.0 keyrings.alt=UNKNOWN msgpack=1.0.4 mutagen=1.46.0 patoolib=1.12 platformdirs=2.5.3 requests=2.28.1 tqdm=4.64.1
Obscure filename: str=b' |;&%b5{}\'"<>\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"<>ΔЙקم๗ あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='en_US.UTF-8' PATH='/home/yoh/proj/datalad/datalad/venvs/dev3/bin:/home/yoh/git-annexes/10.20221103+git83-g31fc11771/usr/lib/git-annex.linux:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/cuda/bin' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'" PYTHON_KEYRING_BACKEND='keyrings.alt.file.PlaintextKeyring' GIT_ASKPASS='true'


============================================== 1 passed, 1318 deselected in 2.37s ===============================================
(dev3) yoh@typhon:~/proj/datalad/datalad$ 
```

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.10`](https://github.com/datalad/datalad/releases/tag/0.17.10)

**Comment by mih** [comment]
I have adjusted the PR title to match its actual content

**Pull request merged**
