### PR TITLE
NF: `clone` a faster `install` for most cases

### PR DESCRIPTION
**Pull request by mih**
Check `datalad/distribution/tests/test_clone.py` for converted install tests that represent the scope of `clone`. Major change is dramatically reduced flexibility wrt input arguments (see #1396). This leads to about ~10% of speed up for our bread-and-butter call, i.e. install one dataset (recursive or not) from one source.

It looks like we could switch to `clone` for pretty much all use in the tests, except for the test of `install`. Even if `install` represents only a fraction of the actual runtime, we are calling it a lot, so it should make things a bit faster.

Here is a demo:

````
In [1]: %run clone_speed_demo.py

# disregard the first run -- testrepos are built here (see below for the code)
In [2]: %timeit test_clone_speed()
1 loop, best of 3: 3.63 s per loop

In [3]: %timeit test_install_speed()
1 loop, best of 3: 4.02 s per loop

In [4]: %timeit test_install_speed()
1 loop, best of 3: 4.04 s per loop

In [5]: %timeit test_clone_speed()
1 loop, best of 3: 3.63 s per loop

In [6]: %timeit test_clone_speed()
1 loop, best of 3: 3.68 s per loop

In [8]: %timeit test_clone_speed()
1 loop, best of 3: 3.64 s per loop
````

Here is the code. It performs a recursive install to get a lower bound estimate. Both commands use `get` for the recursion part, albeit in a slightly different way. Not going recursive yields a ~12% speed increase.

````
from datalad.tests.utils import with_testrepos
from datalad.tests.utils import with_tempfile
from datalad.api import clone
from datalad.api import install
from datalad.api import Dataset


@with_testrepos('.*nested_submodule.*', flavors=['local-url', 'network', 'local'])
@with_tempfile(mkdir=True)
def test_clone_speed(src, path):
    Dataset(path)

    clone(src, path, recursive=True,
          result_xfm='datasets', return_type='item-or-list')


@with_testrepos('.*nested_submodule.*', flavors=['local-url', 'network', 'local'])
@with_tempfile(mkdir=True)
def test_install_speed(src, path):
    Dataset(path)

    install(path, source=src, recursive=True)
````

### CODE REVIEW

**Comment by yarikoptic** [comment]
Not sure if we sold be solving performance issues by expanding API... I am already confused by having both install and clone

**Comment by bpoldrack** [comment]
Since you are familiar with git, `clone` should not exactly be a confusing thing. So, if you want to clone, use `clone. If you want a lot of guessing magic and simultaneously add things to superdatasets and so on, use `install`.

**Comment by mih** [comment]
One more datapoint: For `nosetests3 -s datalad/tests/test_testrepos.py:test_make_studyforrest_mockup` alone I get an ~8% speedup (best of three iterations) by doing `s/install/clone/g`. In absolute numbers this is ~10s.

**Comment by yarikoptic** [comment]
```
Since you are familiar with git, clone should not exactly be a confusing thing. So, if you want to clone, use clone. If you want a lot of guessing magic and simultaneously add things to superdatasets and so on, use install.
```
that is my point -- how would I know if I need any magic or not when I am cloning/installing a remote source?  also moving testing of install in various scenarios as it is done now into testing through a new command could potentially leave install less tested and thus magic break more often.

**Comment by mih** [comment]
Please don't sweat over this PR. If needed I can move it to my clone.

**Comment by yarikoptic** [comment]
I feel deficient of having no "my clone" to move stuff to ;-)  seriously -- what would be the "function in line" of the new API command?  is it for a pro-user (or tests) to avoid using `install` when he could just use `clone` because it is faster?  or... ?

**Comment by mih** [comment]
@bpoldrack test failure for a direct mode test is the last issue. could you please have a quick look. there still seems to be a necessity that i am not aware off. thanks.

**Pull request merged**
