### PR TITLE
Fix download-url breakage reported in #2849

### PR DESCRIPTION
**Pull request by mih**
This is the least-cost path that made it work for me. Here is the compact use case:

```
datalad remove -d bf2849 --nocheck ; datalad create bf2849; datalad -C bf2849 download-url https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css
```

The dataset deletion is critical for the demo, as otherwise git-annex seems to use prior knowledge about the key and doesn't fail on second attempt, even with a `git reset --hard HEAD~1`.

Fixes gh-2849

### CODE REVIEW

**Comment by mih** [comment]
re URL: Yes, this URL doesn't come with size info. It implied incompatibility with `download-url` though -- which I think is a bit strict.

**Comment by kyleam** [comment]
> re URL: Yes, this URL doesn't come with size info. It implied incompatibility with `download-url` though

I'm not sure I understand the last sentence.  Is it saying that it is known that calling `git annex addurl` with an existing file will fail if the header doesn't have size information?

> which I think is a bit strict.

Sure, I wasn't objecting to this change.  I was trying to understand why that URL failed.  If you understood that it was due to a lack of size in the header, it'd be good to see that mentioned in the commit message.

**Comment by mih** [comment]
> > re URL: Yes, this URL doesn't come with size info. It implied incompatibility with `download-url` though
> 
> I'm not sure I understand the last sentence. Is it saying that it is known that calling `git annex addurl` with an existing file will fail if the header doesn't have size information?

Yes.

> > which I think is a bit strict.
> 
> Sure, I wasn't objecting to this change. I was trying to understand why that URL failed. If you understood that it was due to a lack of size in the header, it'd be good to see that mentioned in the commit message.

Just re-read the my message. I agree that it is not clear from the text. Sorry, will fix.

**Comment by mih** [comment]
Message is amended and force-pushed. No other code change, hence merging.

**Pull request merged**
