### PR TITLE
BFs for minor issues: access removed repo, unicode symbols in ls output

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
I will merge tomorrow unless someone says otherwise or does it before I do

**Comment by mih** [comment]
User info message is not covered in tests....

**Comment by mih** [comment]
It seems this is now causing master breakage -- strange.

**Comment by yarikoptic** [comment]
oh - missed that it cause some chaos... sorry... will fix it tomorrow

**Pull request merged**
