### PR TITLE
Undesired submodule url

### PR DESCRIPTION
**Pull request by mih**
`datalad install -d . -s ../raw sourcedata --reckless`

leads to

```diff
--- /dev/null
+++ b/.gitmodules
@@ -0,0 +1,3 @@
+[submodule "sourcedata"]
+       path = sourcedata
+       url = /home/data/psyinf/scratch/multires3t/bids/../raw
```

### CODE REVIEW

**Comment by mih** [comment]
Haha, test shows how fragile things are (Windows):

```
AssertionError: './sources' != 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_fw7rzeoz\\ds\\..\\origin'
```

so on windows it is a relative URL, just not the correct one. I assume some RI issue has prevent it to detect the original relative path as a local path...

**Comment by yarikoptic** [comment]
I think we are doomed to provide "custom handling" at that line you @mih pointed out (https://github.com/datalad/datalad/blob/master/datalad/distribution/add.py#L376).  I wonder why `git` makes it full path, I guess to avoid may be ambiguity either it is path relative to the `worktree` or to `worktree/.git`. And .git/config is not shared, so there is only little crime to it.  In our case we are adding to `.gitmodules`, which can be shared, and where full PATHs IMHO make little sense. Note that we already use "relative paths" while pointing to subdatasets.  So I think it would be ok to do analysis that if "URL" is actually a PATH, then relative path should be used?

**Comment by mih** [comment]
So in order to move forward we need to sort out #2556 and with it #2545

**Comment by yarikoptic** [comment]
#2556 and #2545 seems to be closed now -- should this be revisited @mih?

**Comment by mih** [comment]
Closing due to inactivity. Underlying issue is #3538

**Pull request closed without merging**
