### PR TITLE
Make build support code usable by extensions

### PR DESCRIPTION
**Pull request by mih**
- install code as a package
- hack things up to filter out non-extension commands

Not beautiful, but works. Starting point is admittedly also not a beauty.

### CODE REVIEW

**Comment by mih** [comment]
Now that I am playing with it more, I think this should become a real standalone package. Not all the code in `_datalad_build_support/` built for, or even meant to be used elsewhere.

**Comment by kyleam** [comment]
> I think this should become a real standalone package.

That aligns with the sentiment from gh-3600, though @yarikoptic [mentioned][0] a technical issue related to declaring build dependencies.

[0]: https://github.com/datalad/datalad/pull/3600#discussion_r314364353

**Comment by mih** [comment]
Thanks for the pointer! Will investigate subtree/module...

**Comment by mih** [comment]
This is now replaced by https://github.com/datalad/datalad-extension-template/pull/6

**Pull request closed without merging**
