### PR TITLE
ENH: Nicer search

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by mih** [comment]
@yarikoptic this PR needs you contribution.

**Comment by yarikoptic** [comment]
Some Travis runs got cancelled? Yeah, we could merge and I would be happy to contribute when I give it a spin

**Comment by mih** [comment]
Failing test doesn't expect output of progressbars

```
=====================================================================
FAIL: datalad.metadata.tests.test_search.test_within_ds_file_search
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 870, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 494, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/metadata/tests/test_search.py", line 239, in test_within_ds_file_search
    """)
AssertionError: '\rDatasets:   0%|          | 0.00/1.00 [00:00<?, ?ds/s]\rDatasets: 100%|##########| 1.00/1.00 [00:00<00:00, 110kds/s]\r                                                            \rid\nmeta\nparentds\npath\ntype\n' != 'id\nmeta\nparentds\npath\ntype\n'
...
```

**Comment by mih** [comment]
Going into master now

**Pull request merged**
