### PR TITLE
NF: Basic support for annex-native metadata manipulation and query

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by mih** [comment]
Seems we have this issue: http://stackoverflow.com/questions/41145607/some-way-to-disable-ivar-auto-cross-referencing-of-attribute-names

**Comment by mih** [comment]
Happy days!

**Comment by yarikoptic** [comment]
that was fast! ;)
also I am confused about link referencing a bug with napoleon

**Comment by mih** [comment]
Try putting:

````
Parameters
---------------
myfirstarg: path
````

in the docs. It will try to crossref `path` and fail, because we have it multiple times.

**Comment by bpoldrack** [comment]
I guess the confusion is, whether we should care for that issue or you found a way to avoid it or how it is related to this PR ... ;-)

**Comment by mih** [comment]
That is my secret. Get your own problems....!

**Comment by yarikoptic** [comment]
Who is `it` @mih? sphinx for http://docs.datalad.org/en/latest/generated ?

**Pull request merged**
