### PR TITLE
RF: centralize nose imports

### PR DESCRIPTION
**Pull request by yarikoptic**
I have left only nose imports in package level fixture (btw, seems nose2 might not even support those according to docs), and 3rd party externals we included to facilitate `datalad test` command:
```
$> git grep nose | grep import | grep -v support/third                                           
datalad/__init__.py:    from datalad.support.third.nosetester import NoseTester
datalad/__init__.py:    from nose.ext import dtcompat
datalad/__init__.py:    from nose.plugins import capture, multiprocess, plugintest
datalad/cmdline/tests/test_main.py:    # - python -c "import nose; nose.main()" -s -v datalad/cmdline/tests/test_main.py would result in:
datalad/tests/test_tests_utils.py:from .utils import ignore_nose_capturing_stdout
datalad/tests/utils.py:from nose.plugins.attrib import attr
datalad/tests/utils.py:from nose.tools import (
datalad/tests/utils.py:from nose.tools import assert_set_equal
datalad/tests/utils.py:from nose.tools import assert_is_instance
datalad/tests/utils.py:from nose import SkipTest
datalad/tests/utils.py:        from nose import SkipTest
datalad/tests/utils.py:from nose.plugins.attrib import attr
tools/checkpwd.py:from nose.plugins.base import Plugin
tools/checkpwd.py:from nose.util import src, tolist
tools/checkpwd.py:    import nose
```
Ref: #4090

### CODE REVIEW

**Comment by mih** [comment]
The rest of the package uses absolute imports (at least the code that has been touched in the last two years). I think we should use that style here too.

**Comment by yarikoptic** [comment]
> The rest of the package uses absolute imports (at least the code that has been touched in the last two years). I think we should use that style here too.
> 
> https://stackoverflow.com/a/4209771

yeap, comments there clarify that PEP8 no longer says that etc.  
I find relative imports less confusing IMHO since they **explicitly** state which package (i.e., **this** package) to import from, not some other "datalad" possibly available somewhere.  They also make those modules portable/borrowable easily into other projects, since then they could be just copied over, and all imports would still work as long as hierarchy preserved.   They particularly make lots of sense in `test_` modules, since typically you test modules defined in `..`, and breeding long import paths to just get "upstairs" is tedious.  
Having said that, I am ok to change them to absolute if that is desired to stay consistent.

**Comment by mih** [comment]
> I find relative imports less confusing IMHO since they **explicitly** state which package (i.e., **this** package) to import from, not some other "datalad" possibly available somewhere.

Yeah, I am aware of this rational, but could never get behind it. For me the RF variant it optimizes for just doesn't seem to happen. Moreover, I do not consider relative imports ala `from .utils` anyhow more obvious than `from datalad...utils`, especially with:

```
% find . -name utils.py
./datalad/interface/utils.py
./datalad/distribution/utils.py
./datalad/ui/utils.py
./datalad/support/tests/utils.py
./datalad/tests/utils.py
./datalad/downloaders/tests/utils.py
./datalad/utils.py
```

I know that you did `....tests.utils` for this purpose, but the general point still holds IMHO. And lastly:

> They particularly make lots of sense in test_ modules, since typically you test modules defined in `..`

True, but in this PR the imports are not the *subject* of the tests, but are generic utilities that are always imported from the same location, regardless of the particular test. Hence when the file moves, these imports would need to be adjusted.

Anyways: yes, I'd prefer to use absolute imports for consistency ;-)

**Comment by yarikoptic** [comment]
done

**Comment by mih** [comment]
I will shortly make a follow-up push -- if we edit these many location we should perform more normalization then just this.

**Comment by yarikoptic** [comment]
Minimal edit as is now might should conflicts which would come with more normalization

**Comment by mih** [comment]
Pushed. Also fixed few spots that were missed before.

**Comment by effigies** [comment]
Re: relative/absolute imports, the text discouraging relative imports was declared outdated by Guido in 2010: https://mail.python.org/pipermail/python-dev/2010-October/104476.html

**Comment by yarikoptic** [comment]
> Pushed. Also fixed few spots that were missed before.

whatever script your are using for normalization, it has bugs. Will push fixes shortly

**Comment by yarikoptic** [comment]
I have joined @mih on the crusade to maximize the chance of possible conflicts with master in the other staged PRs by introducing here changes unrelated to the original topic of the PR and will be pushing more of "normalization" (which BTW should also include sorting of the entries in the import "tuples") shortly.  Rationale: if we do it, we better do it once.

**Comment by mih** [comment]
Merging. Any intermediate merge is likely going to introduce conflicts.

**Pull request merged**
