### PR TITLE
drop python 3.4 and aim for 3.5 and 3.6

### PR DESCRIPTION
**Pull request by yarikoptic**
since gods say that 3.6.1 is the one!

### CODE REVIEW

**Comment by yarikoptic** [comment]
bleh... I guess we would discover only if/when backdoor travis session again :-/
```shell
40.76s$ PATH=$PWD/tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -v --with-doctest --doctest-tests --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM

/home/travis/.travis/job_stages: line 54: 10041 Killed                  PATH=$PWD/tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -v --with-doctest --doctest-tests --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM

The command "PATH=$PWD/tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -v --with-doctest --doctest-tests --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM" exited with 137.
```

**Comment by yarikoptic** [comment]
wow. @mih and @bpoldrack -- both 3.5 and 3.6 runs immediately crash

```shell
$ WRAPT_DISABLE_EXTENSIONS=1 PATH=$PWD/tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -v -A "$NOSE_SELECTION_OP(integration or usecase or slow)" --with-doctest --doctest-tests --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM

/home/travis/.travis/job_stages: line 57: 10634 Killed                  WRAPT_DISABLE_EXTENSIONS=1 PATH=$PWD/tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -v -A "$NOSE_SELECTION_OP(integration or usecase or slow)" --with-doctest --doctest-tests --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM

The command "WRAPT_DISABLE_EXTENSIONS=1 PATH=$PWD/tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -v -A "$NOSE_SELECTION_OP(integration or usecase or slow)" --with-doctest --doctest-tests --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM" exited with 137.
```

**Comment by mih** [comment]
I rebased on current master after #2248 was merged. Let's see.

**Comment by mih** [comment]
FTR: PY3.5 already passed. Exciting!

**Comment by mih** [comment]
Added one last fix of a PY3.4 that sneaked in. Otherwise tests look good. Please merge ASAP.

**Comment by yarikoptic** [comment]
coolio, thanks for figuring it all out @mih

**Comment by mih** [comment]
My pleasure!

**Comment by mih** [comment]
Test failure on OSX is connection issue.

**Pull request merged**
