### PR TITLE
BF: Prevent Repo to resolve network mount to UNC paths on windows

### PR DESCRIPTION
**Pull request by mih**
Fixes gh-5112

No idea how to programatically create a network mount on appveyor, hence fixing without a test for now. Left extensive note to prevent accidental removal.

### CODE REVIEW

**Comment by mih** [comment]
Appveyor timed out.

**Review by kyleam — APPROVED** [review]

**Comment by kyleam** [comment]
> Appveyor timed out.

I guess this might start to be a somewhat regular annoyance after gh-5080 :/  Should we split tests across the runs?

**Comment by yarikoptic** [comment]
or just switch from appveyor to github actions? although split might be easier ATM and in particular for `maint`

**Comment by mih** [comment]
> or just switch from appveyor to github actions? although split might be easier ATM and in particular for `maint`

We have used github actions rather unsuccessfully in the past. Primary reason for that is that they are a bitch to debug and behave even more different from a real win10 box than appveyor. I.e. placement of files across drives https://github.com/datalad/datalad/issues/5116.

I am not saying that those are not worth fixing, but moving to github action doesn't yield passing tests per se.

**Comment by mih** [comment]
Thx for the review @kyleam

**Comment by yarikoptic** [comment]
FWIW

>  I.e. placement of files across drives #5116.

like it could happen in real life , so IMHO only a + . debugging is a b.tch indeed.  
But if we get setup consistent so could be reproduced locally - so far I think I was able to reproduce windows issues I saw on github actions in a local VM. 
FWIW, https://github.com/datalad/git-annex/pull/7/files (after git-annex stops to FTBFS) provides workflows for all OSes, and will be merged and later extended to run datalad tests on windows as well. As on Linux and OSX the target will be `        version: [master, maint, release]` for datalad.  It would be nice to workout a way to avoid code duplication and "absorb" datalad testing specific components of that workflow also here, or in general look how we could harmonize/centralize "test datalad" github actions between that repository and this one (here - against our "base" git-annex version, there - against freshly built).

**Pull request merged**
