### PR TITLE
ENH: Add `if_dirty` option to `add`

### PR DESCRIPTION
**Pull request by mih**
Had to revert the use of `api.add()` in `save` to avoid infinite loops

### CODE REVIEW

**Comment by mih** [comment]
Question: @bpoldrack @yarikoptic should `if_dirty` of `add` default to `"ignore"`? If not, any call to add that only deals with existing local content is likely to result in nothing, because that content was added via `handle_dirty_dataset` already.

**Comment by bpoldrack** [comment]
Yes, `ignore` sounds reasonable to me. In general `save-before` doesn't make sense for `add`.

**Comment by mih** [comment]
`save-before` does make sense for anything that is not adding files that already exist untracked in the repo. So one could argue that people should not use `add` for that, but rather `save` with a list of files. And I suspect that this will be a more common pattern, as the additional `add` step is pointless for any normal person when you ignore Git's semantics.

**Comment by mih** [comment]
OK, so be it `ignore` by default.

**Pull request merged**
