### PR TITLE
WIP: Reduce error level loging output

### PR DESCRIPTION
**Pull request by bpoldrack**

### CODE REVIEW

**Comment by yarikoptic** [comment]
YES YES YES!!! **But** some other functionality got hurt as tests suggest

**Comment by bpoldrack** [comment]
Did you look at the reported details? Apparantly there a lot of timeout issues and a failing pip install and things like that. Doesn't seem to be actually failing tests.

**Comment by yarikoptic** [comment]
I did quickly look at one of our dockers -- looked like a test got stuck waiting on smth... I will run now locally

**Comment by yarikoptic** [comment]
locally failed to replicate -- could you please trigger another re-run by committing a bit more (or could be just commit --amend, git push -f I guess).  I would hate if our test bots would break master testing without us knowing how to fix it up

**Comment by yarikoptic** [comment]
for better or for worse -- https://github.com/datalad/datalad/milestones/Releases:%200.1 is empty thus we could tag the 0.1, which I will do after merging this one (redoing tests ATM).

**Pull request merged**
