### PR TITLE
No plugins -> plug-able commands 

### PR DESCRIPTION
**Pull request by mih**
It is basically figured out. Fate of `--run-before/after` is uncertain at this point (keep and RF or let die). If RF, it needs a way to store a command call in the config. Most likely using cmdline syntax and then shlex the beast and feed it to `main()` -- not sure if it is worth it. ATM I think it is not, but a beer or two might change my mind.

### CODE REVIEW

**Comment by yarikoptic** [comment]
FWIW, looking into it.

**Comment by yarikoptic** [comment]
Ok, pushed the "fix" in 719c870f9c6a41f7111657655298492b8f4d6c63 which is "import plugins instead of exec(compile( them".  Also followed up with bc04103c4a87131816683eef26f78e2ad706dc9e which is probably just a sign of something being broken and thus result being None instead of a record.  Feel free to scrape any of those.  I didn't push forward to actually finish RFing @mih started since do not want to collide with his vision of how things should work (so tests would still fail, but his wtf import example "works")

**Comment by yarikoptic** [comment]
@mih so what do you think?

**Comment by mih** [comment]
@yarikoptic I can already express my sincere THANKS! I will look into completing it soonish -- a bit of urgent stuff got in the way.

**Comment by yarikoptic** [comment]
no problem!  just didn't want it to go unnoticed.  Cheers!

**Comment by mih** [comment]
Hey, if anybody has some extra juice to convert plugins into commands (wtf and no_annex are done and can serve as models), please help out!

**Comment by kyleam** [comment]
Here's the current status:

- [X] add_readme.py
- [ ] bids2scidata.py
- [X] export_archive.py
- [X] export_to_figshare.py
- [ ] extract_metadata.py
- [X] no_annex.py
- [X] wtf.py

**Comment by mih** [comment]
Wonderful!

**Comment by kyleam** [comment]
I've got the `extract_metadata` one mostly done location.  Will push in a bit.

**Comment by mih** [comment]
perfect, won't touch it then.

**Comment by kyleam** [comment]
Here's what's still failing in the Travis run (this is from 3.6, DATALAD_REPO_VERSION=5):

```
ERROR: datalad.metadata.extractors.tests.test_bids.test_get_metadata
ERROR: datalad.metadata.extractors.tests.test_bids.test_get_metadata_with_README
ERROR: datalad.metadata.extractors.tests.test_bids.test_get_metadata_with_description_and_README
ERROR: datalad.metadata.tests.test_aggregation.test_nested_metadata
ERROR: datalad.metadata.tests.test_search.test_within_ds_file_search
ERROR: datalad.plugin.tests.test_bids2scidata.test_minimal
ERROR: datalad.plugin.tests.test_plugins.test_add_readme
```

Locally, I don't get any of those failures except for `datalad.metadata.extractors.tests.test_bids.test_get_metadata`, but the specific error I see is different.

Travis says

```
======================================================================
ERROR: datalad.metadata.extractors.tests.test_bids.test_get_metadata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 494, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/metadata/extractors/tests/test_bids.py", line 55, in test_get_metadata
    meta = MetadataExtractor(ds, []).get_metadata(True, False)[0]
  File "/home/travis/build/datalad/datalad/datalad/metadata/extractors/bids.py", line 70, in get_metadata
    bids = BIDSLayout(self.ds.path)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/grabbit/core.py", line 293, in __call__
    **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bids/grabbids/bids_layout.py", line 41, in __init__
    dynamic_getters=True, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/grabbit/core.py", line 384, in __init__
    self._load_domain(c)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/grabbit/core.py", line 397, in _load_domain
    raise ValueError("Config file missing 'name' attribute.")
ValueError: Config file missing 'name' attribute.
```

My machine says

```
======================================================================
ERROR: datalad.metadata.extractors.tests.test_bids.test_get_metadata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyle/src/python/datalad/venv-datalad/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/kyle/src/python/datalad/datalad/tests/utils.py", line 494, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/kyle/src/python/datalad/datalad/metadata/extractors/tests/test_bids.py", line 86, in test_get_metadata
    assert_equal(fmeta['subject'], '01')
KeyError: 'subject'

```

**Comment by yarikoptic** [comment]
well, with installing pybids out of git repo master we are chasing a wild rabbit here, so I would not be surprised if it is a matter of different version of pybids or grabbits on your local system.  FWIW, with the uptodate master of grabbit and pybids I am getting what travis says

**Comment by kyleam** [comment]
> FWIW, with the uptodate master of grabbit and pybids I am getting what travis says

Thanks, good to know.  Given that these are [showing up on master][0], I think all the failures here might not be related to the changes this PR.

[0]: https://travis-ci.org/datalad/datalad/builds/349699026

**Comment by yarikoptic** [comment]
FWIW -- yes with our master I also see the same failure

**Comment by yarikoptic** [comment]
FWIW, a PR merged a few hours back into pybids "fixed" the failure, now just the warning which I guess to be addressed
```
datalad.metadata.extractors.tests.test_bids.test_get_metadata ... /home/yoh/proj/bids/grabbit/grabbit/core.py:410: UserWarning: No valid root directory found for domain 'derivatives'. Falling back on the Layout's root directory. If this isn't the intended behavior, make sure the config file for this domain includes a 'root' key.
  "'root' key." % config['name'])
ok
```

**Comment by mih** [comment]
FYI: I will make substantial changes to bids2scidata over the weekend. Those changes will be unrelated to the nature of this PR, but might complicate things, if but are open at the same time.

**Comment by yarikoptic** [comment]
Travis reports just over rogue leftover import... @kyleam could you push a fix? I don't know what is left to fix, and didn't try it yet but I guess you @mih could work on top of this one even if it is not merged by then

**Comment by kyleam** [comment]
> Travis reports just over rogue leftover import... @kyleam could you push a fix?

Yep, that's from the recently merge addurls plugin.  I'll push the conversion today.

> I don't know what is left to fix

After the addurls conversion, I think the main thing is that the docs are now stale.  That could be a separate issue though.

**Comment by kyleam** [comment]
> After the addurls conversion, I think the main thing is that the docs are now stale.

I've made an attempt to update them, though I doubt any user could easily right their own plugin by using what I added as the guide.

**Comment by mih** [comment]
Thanks. Updating those docs is on my list. Didnt get to it today. Will do ASAP, but not in this PR.

**Comment by kyleam** [comment]
The [latest Travis run][0] had one failure in one py3.5 build:

```
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 836, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/support/tests/test_annexrepo.py", line 1354, in test_is_available
    assert_false(is_available("boguskey", key=True))
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 297, in newfunc
    for f in files_new
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 297, in <listcomp>
    for f in files_new
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2845, in is_available
    "Received output %r from annex, whenever expect 0 or 1" % out
ValueError: Received output None from annex, whenever expect 0 or 1
-------------------- >> begin captured logging << --------------------
```

I don't see how that could be related to this PR, so I think this is set to merge from a tests standpoint. 

[0]: https://travis-ci.org/datalad/datalad/builds/351296244?utm_source=github_status&utm_medium=notification

**Pull request merged**
