### PR TITLE
ENH: Configuration file mtime tracking to reduce `git config` call frequency

### PR DESCRIPTION
**Pull request by mih**
Fixes gh-1401
Fixes gh-1044

### CODE REVIEW

**Comment by mih** [comment]
Well, there seems to be more to it...

**Comment by mih** [comment]
Hmm, so the 16.04 `git config` doesn't have `--show-origin`?

**Comment by mih** [comment]
Bounced buildbot tests to see if nonsense OSX logs are reproducible.

**Comment by mih** [comment]
So OSX fails reliably. Given the nature of the error it seems that the entire approach is not working and the config is fundamentally broken. Not sure what to do, I have no juice to investigate this on OSX. I could disable support for mtime tracking on OSX and be done.

**Comment by yarikoptic** [comment]
I thought I have replied -- I guess again did it in email though already know that github wouldn't post those reliably for me ...  now that the problem showed itself I recalled  -- that on some OS/file systems mtime would have precision up to a second.  I think I saw it on linuxes as well. And that is what is happening on OSX:
```shell
datalads-imac:~ yoh$ touch blah; python -c 'import os, time; t1=os.stat("blah").st_mtime; time.sleep(0.5); os.system("touch blah"); t2=os.stat("blah").st_mtime; print t1, t2, t2-t1 '; rm blah
1491099043.0 1491099043.0 0.0
datalads-imac:~ yoh$ touch blah; python -c 'import os, time; t1=os.stat("blah").st_mtime; time.sleep(0.5); os.system("touch blah"); t2=os.stat("blah").st_mtime; print t1, t2, t2-t1 '; rm blah
1491099044.0 1491099045.0 1.0
```
so -- slept 0.5 sec which would some times then result in 0 and some times in 1 sec diff between mtimes.  So decision should be made not based on OS but on filesystem's properties.

**Comment by mih** [comment]
Ah, thanks! That makes sense now. I have to think about where we would want to include this kind of detection.

**Comment by mih** [comment]
From http://stackoverflow.com/questions/19059877/python-os-path-getmtime-time-not-changing:

Some statistics on the time resolution of various common file systems:

FAT32: 2s
ext3: 1s
exFAT: 10ms
NTFS: 100ns
ext4: 1ns

**Comment by mih** [comment]
Hoping that my last commit makes OSX happy again, here are the stats (refer to #1401 for comparison):

````
DATALAD_LOG_TIMESTAMP=1 DATALAD_LOG_LEVEL=DEBUG python -m nose -s -v datalad/interface/tests/test_utils.py:test_save_hierarchy 2>&1 | tools/dtime | sort -n | grep git.*config | nl 

     1	   17 2017-04-02 09:24:21,783 [DEBUG] Running: ['git', 'config', '-z', '-l', '--show-origin']
     2	   17 2017-04-02 09:24:22,718 [DEBUG] Running: ['git', 'config', '-z', '-l', '--show-origin']
     3	   17 2017-04-02 09:24:23,413 [DEBUG] Running: ['git', 'config', '--local', 'annex.backends', 'MD5E']
...
   170	  113 2017-04-02 09:24:34,005 [DEBUG] Running: ['git', 'config', '-z', '-l', '--show-origin']
   171	  116 2017-04-02 09:24:32,437 [DEBUG] Running: ['git', 'config', '-z', '-l', '--show-origin']
   172	  226 2017-04-02 09:24:19,930 [DEBUG] Running: ['git', 'config', '-z', '-l', '--show-origin']
DATALAD_LOG_TIMESTAMP=1 DATALAD_LOG_LEVEL=DEBUG python -m nose -s -v  2>&1  16,37s user 4,50s system 61% cpu 33,940 total
````

Almost doubled the number of calls again, but should now work even in FAT32 (dataset on USB stick...).

**Comment by mih** [comment]
Well, now OSX is OK (travis too), but all others fail due to a strange timeout -- which I cannot replicate locally. All healthy with the builtbots @yarikoptic ?

**Comment by yarikoptic** [comment]
at least yesterday seemed to be ok in https://github.com/datalad/datalad/pull/1444 which I will restart once more now -- if so, that means that buildbots are more or less healthy and then we will go from there

**Comment by mih** [comment]
Ok, in this case we have total linux buildbot failures, local is good travis is good. Buildbot failure is timeout.

**Comment by yarikoptic** [comment]
tried rebuilding one -- worked just fine.... so pushed a minor change to trigger full rebuild

**Pull request merged**
