### PR TITLE
Replace Boto with Boto3

### LINKED ISSUE #5597: downloaders/s3: migrate from boto (2.x) to boto3
ATM we are still using boto2, whenever boto3 had been out for a while.
We had accumulated some craft to fulfill our cases using boto2, so may be some of it could also go away.

### PR DESCRIPTION
**Pull request by mslw**
## Summary of changes

Boto package is [no longer maintained](https://github.com/boto/boto#readme) (last release is from July 2018, v.2.49.0) and has been replaced by Boto3. This PR removes the boto dependency in favour of boto3, and makes all code adjustments necessary. Closes #5597 

Three most significant changes include:

- Boto3 will be able to use credentials coming from its own configuration mechanism (`AWS_*` environment variables, `~/.aws/credentials`, `~/.aws/config`, `/etc/boto.cfg` and `~/.boto`), thus allowing AWS users to rely on their existing configuration. The preference order is DataLad credentials, boto credentials, anonymous.
- Custom retry logic for S3 connections is removed in favour of boto3's built-in Standard retry Mode (see boto3 docs: [Retries](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html)).
- Instead of old boto bucket and key objects, the functions in the downloader module will now operate primarily on a boto3 S3 client object ("low-level interface to AWS whose method map close to 1:1 with service APIs"). Although boto3 has a high-level resource object for a Bucket, its methods are different from the old boto bucket, and I found working with a client much more suitable for the kind of operations done by the downloaders code (setting credentials, asking about headers, etc.).

This may also help Python 3.10 compatibility - the linked issue has also been linked to by NixOS.

See commit messages for details on specific decisions - I tried to be verbose.

## Notes
Note: The downloader/authenticator code based on boto seems to be built around "authenticating to a bucket". Authenticator's behaviour was maintained for compatibility (it still checks bucket access permissions, as the old code did). But the transition to boto3 client object makes it apparent that authenticating to a bucket is not really what matters if all we want is to download an object. Authentication is done to S3, and then object permissions are decisive for downloading. For example, a public file (public read permission) can be in a bucket that does not block public access, but does not grant public permission to list objects either (easy and reasonable setup in S3) - in which case non-owner bucket interaction will end in 403 although the object could be retrieved.

This behavior can be easily changed, although the resulting authenticator would not perform any authentication, only set it up. In boto3, although a client object is set up with credentials, they are checked only when sending out a request (be it `head_bucket` or `download_file`.

## Help needed

The ultimate confirmation for the rework will be the test suite. S3 download tests require specific credentials with access to specific buckets. I was only able to test manually with my own credentials, and against buckets of my own (reworking the test code to be flexible with credentials and bucket names was too much for me).

However, the tests are being skipped in CI, at least in Appveyor (see e.g. [this recent build](https://ci.appveyor.com/project/mih/datalad/builds/46534685/job/y8wnccq8f58tnm8y) and ctrl-F for `downloaders/tests/test_s3`).

### CODE REVIEW

**Comment by adswa** [comment]
Just leaving a pass-by note: Travis shows this failure:

```
=========================== short test summary info ============================

FAILED ../datalad/local/tests/test_gitcredential.py::test_datalad_credential_helper - AttributeError: 'NoneType' object has no attribute 'credential'

= 1 failed, 1131 passed, 39 skipped, 3 xfailed, 17 warnings in 967.47s (0:16:07) =
```

which I couldn't reproduce locally so far

**Comment by yarikoptic** [comment]
@adswa filed an independent issue for that: https://github.com/datalad/datalad/issues/7347 confirming that likely you are not insane -- the test indeed might fail on some initial run of tests and then succeed after

**Review by bpoldrack — COMMENTED** [review]
Thanks much, @mslw!

This looks all good to me. CI failures so far are unrelated, with the only exception being `datalad-crawler` depending on boto. This however needs to be addressed in `datalad-crawler` by making that dependency explicit instead of assuming it's delivered by datalad.

WRT to tests: As far as I can tell, the only intended change in behavior that would need additional tests is: Making use of non-datalad AWS credentials, right? How do we proceed here - @yarikoptic do we have some creds already (I think so)?

Overall, I think a review by @yarikoptic would be crucial, but other than testing the "use standard AWS credential setups"-feature, thinks looks ready from my POV

**Comment by mslw** [comment]
> This looks all good to me. CI failures so far are unrelated, with the only exception being `datalad-crawler` depending on boto. This however needs to be addressed in `datalad-crawler` by making that dependency explicit instead of assuming it's delivered by datalad.
> 
> WRT to tests: As far as I can tell, the only intended change in behavior that would need additional tests is: Making use of non-datalad AWS credentials, right? How do we proceed here - @yarikoptic do we have some creds already (I think so)?

Thanks! I agree, only the non-datalad credential source is the new behavior. Ideally, all existing s3 tests should pass to show that high-level behavior is unchanged. There may be some issues with errors that are raised / tested for. But the tests are skipped in CI, so I'll have to work with @yarikoptic on testing these locally againist existing DataLad test buckets with DataLad credentials.

Unfortunately, I will be unavailable over the coming week. I can pick it up later, but I'm also open to anyone digging into it.

**Comment by mslw** [comment]
One failure, introduced by my changes, that I can see locally in the non-skipped tests is from `test_deny_access`, that checks whether downloader raises `DownloadError` from an `AccessDeniedError`. Pasting fragment of pytest output:

```
    @with_testsui(interactive=True)
    def test_deny_access():
        downloader = S3Downloader(authenticator=S3Authenticator())
    
        def deny_access(*args, **kwargs):
            raise AccessDeniedError
    
        with assert_raises(DownloadError):
            with patch.object(downloader, '_download', deny_access):
>               downloader.download("doesn't matter")

(...)

E           botocore.exceptions.ParamValidationError: Parameter validation failed:
E           Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"

FAILED downloaders/tests/test_s3.py::test_deny_access - botocore.exceptions.ParamValidationError: Parameter validation failed:
```

So it seems that we got another error from boto3 along the way. ATM I'm not sure if it's just the test that needs to change (patching?) or the tested code, or both.

**Comment by adswa** [comment]
> Meanwhile, if I merge current master (which has maint just merged ) and that https://github.com/datalad/datalad/pull/7361 PR then I can trigger errors in the tests which need refactoring (they were accessing ._bucket)

Shall we update the base of this PR to its most recent state? Then we have a better overview what breaks.

**Comment by mslw** [comment]
> > Meanwhile, if I merge current master (which has maint just merged ) and that #7361 PR then I can trigger errors in the tests which need refactoring (they were accessing ._bucket)
> 
> Shall we update the base of this PR to its most recent state? Then we have a better overview what breaks.

Thanks for nudging me to look into this PR again. I have rebased the PR locally onto current master and pushed.

The thing is, most of the relevant tests are skipped both on CI and locally (shown below), because they need credentials to access `s3://datalad-test*` buckets:

```
pytest -v downloaders/tests/test_s3.py                                            
=================================================================================================================================== test session starts ====================================================================================================================================
platform linux -- Python 3.9.2, pytest-7.2.2, pluggy-1.0.0 -- /home/mszczepanik/.virtualenvs/botox/bin/python
cachedir: .pytest_cache
rootdir: /home/mszczepanik/Documents/datalad, configfile: tox.ini
plugins: fail-slow-0.3.0, cov-4.0.0
collected 15 items                                                                                                                                                                                                                                                                         

downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad-test0-versioned/2versions-nonversioned1.txt-version2-version1] SKIPPED (This test requires known credentials for datalad-test-s3)                                                                                   [  6%]
downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad-test0-versioned/2versions-nonversioned1.txt?versionId=V4Dqhu0QTEtxmvoNkCHGrjVZVomR1Ryo-version2-version1] SKIPPED (This test requires known credentials for datalad-test-s3)                                        [ 13%]
downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad-test0-versioned/2versions-nonversioned1.txt?versionId=null-version1-version2] SKIPPED (This test requires known credentials for datalad-test-s3)                                                                    [ 20%]
downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad.test1/version1.txt-version1-nothing] SKIPPED (This test requires known credentials for datalad-test-s3)                                                                                                             [ 26%]
downloaders/tests/test_s3.py::test_mtime SKIPPED (This test requires known credentials for datalad-test-s3)                                                                                                                                                                          [ 33%]
downloaders/tests/test_s3.py::test_reuse_session SKIPPED (This test requires known credentials for datalad-test-s3)                                                                                                                                                                  [ 40%]
downloaders/tests/test_s3.py::test_parse_url PASSED                                                                                                                                                                                                                                  [ 46%]
downloaders/tests/test_s3.py::test_deny_access FAILED                                                                                                                                                                                                                                [ 53%]
downloaders/tests/test_s3.py::test_boto_host_specification SKIPPED (Test can run only on yoh's setup)                                                                                                                                                                                [ 60%]
downloaders/tests/test_s3.py::test_restricted_bucket_on_NDA SKIPPED (This test requires known credentials for NDA)                                                                                                                                                                   [ 66%]
downloaders/tests/test_s3.py::test_download_multiple_NDA SKIPPED (This test requires known credentials for NDA)                                                                                                                                                                      [ 73%]
downloaders/tests/test_s3.py::test_get_key[NDAR_Central_4-submission_23075/README-None] SKIPPED (This test requires known credentials for NDA)                                                                                                                                       [ 80%]
downloaders/tests/test_s3.py::test_get_key[datalad-test0-versioned-1version-nonversioned1.txt-None] SKIPPED (This test requires known credentials for datalad-test-s3)                                                                                                               [ 86%]
downloaders/tests/test_s3.py::test_get_key[datalad-test0-versioned-3versions-allversioned.txt-None] SKIPPED (This test requires known credentials for datalad-test-s3)                                                                                                               [ 93%]
downloaders/tests/test_s3.py::test_get_key[datalad-test0-versioned-3versions-allversioned.txt-pNsV5jJrnGATkmNrP8.i_xNH6CY4Mo5s] SKIPPED (This test requires known credentials for datalad-test-s3)                                                                                   [100%]
```

The credentials are checked by `datalad/downloaders/tests/utils.py::get_test_providers` function, which skips the tests. I cannot simply use `DATALAD_TESTS_CREDENTIALS=system` because the credentials I have don't have access rights to buckets mentioned above. (note to self: these have to be DataLad credentials, probably even "providers" configuration - this won't pick up my `~/.aws/config`).

I created analogous buckets in my account (the script which was used to create test buckets is in `datalad/support/s3.py` and I used it with small tweaks). But the tests hardcode the s3 urls they test againist in several places, so I can't just do a quick switch-up.

Long ago, when this PR was still fresh, we discussed whether I could obtain the DataLad credentials. @yarikoptic suggested, that we should first create an IAM user under the DataLad s3 account, but we never followed up on this.

With this in mind, I think I should change the tests, piece by piece, to allow swapping out s3 urls which are tested, so that I can use my own buckets. But I think I should still test with DataLad's credentials. (I could also work based on errors reported by @yarikoptic on his machine, but it's much harder not being able to debug directly).

Another thing is for me to find time to work on these tests - if I can't budget in near future, we should probably close this PR or put it back into draft mode.

**Comment by yarikoptic** [comment]
> . @yarikoptic suggested, that we should first create an IAM user under the DataLad s3 account, but we never followed up on this.

sorry -- a bit busy/missed. let's iron it out during one of the upcoming meetings?  IMHO it would be silly to recreate those just to adjust permissions

**Comment by adswa** [comment]
>  sorry -- a bit busy/missed. let's iron it out during one of the upcoming meetings? IMHO it would be silly to recreate those just to adjust permissions

I added it to the next meeting agenda.

**Comment by mslw** [comment]
Dear DataLad developers

I tried going back to this PR, and added two more commits to address one test error, related to input validation (explanations in commit messages). But I am still struggling with running the tests that try to access actual s3 buckets.

As you pointed out, at least some of the buckets are indeed public; demonstrated here with boto3 low level client api, and my own `~/.aws/config` removed:

```
>>> import boto3
>>> import botocore
>>> session = boto3.Session()
>>> session.get_credentials() is None
True
>>> s3client = session.client("s3", config=conf)
>>> conf = botocore.config.Config(signature_version=botocore.UNSIGNED)
>>> s3client.head_bucket(Bucket="datalad-test0-versioned")
{'ResponseMetadata': {'RequestId': 'ZZ74TV6K6GV4PXD1', 'HostId': 'RXoLHDlVR3xelNCQ4T5RMF2yQDZrPoGOCJTDCyLMC92A3lvDZEMlis95DkQBIM8KaQ3rPf6+fXE=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'RXoLHDlVR3xelNCQ4T5RMF2yQDZrPoGOCJTDCyLMC92A3lvDZEMlis95DkQBIM8KaQ3rPf6+fXE=', 'x-amz-request-id': 'ZZ74TV6K6GV4PXD1', 'date': 'Thu, 27 Jul 2023 16:41:38 GMT', 'x-amz-bucket-region': 'us-east-1', 'x-amz-access-point-alias': 'false', 'content-type': 'application/xml', 'server': 'AmazonS3'}, 'RetryAttempts': 0}}
s3client.head_object(Bucket="datalad-test0-versioned", Key="1version-nonversioned1.txt")
{'ResponseMetadata': {'RequestId': 'EEPH5FFGPVH55AQW', 'HostId': 'Cw7nR84EZ/ZaUIPz9TVk8rXSQ/aoS4iujnmx6ef3vAisVR4oD/ipQkvBmFX0vVMAxegbNk1uT8c=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'Cw7nR84EZ/ZaUIPz9TVk8rXSQ/aoS4iujnmx6ef3vAisVR4oD/ipQkvBmFX0vVMAxegbNk1uT8c=', 'x-amz-request-id': 'EEPH5FFGPVH55AQW', 'date': 'Thu, 27 Jul 2023 16:48:26 GMT', 'last-modified': 'Sat, 07 Nov 2015 05:23:36 GMT', 'etag': '"966634ebf2fc135707d6753692bf4b1e"', 'x-amz-version-id': 'null', 'accept-ranges': 'bytes', 'content-type': 'text/plain', 'server': 'AmazonS3', 'content-length': '8'}, 'RetryAttempts': 0}, 'AcceptRanges': 'bytes', 'LastModified': datetime.datetime(2015, 11, 7, 5, 23, 36, tzinfo=tzutc()), 'ContentLength': 8, 'ETag': '"966634ebf2fc135707d6753692bf4b1e"', 'VersionId': 'null', 'ContentType': 'text/plain', 'Metadata': {}}
```

However, attempting to download the file through DataLad (either this branch, or current release) results in:

```
❱ datalad download-url s3://datalad-test0-versioned/1version-nonversioned1.txt
[INFO   ] Downloading 's3://datalad-test0-versioned/1version-nonversioned1.txt' into '/home/mszczepanik/' 
You need to authenticate with 'datalad-test-s3' credentials. team@datalad.org provides information on how to gain access
key_id: 
```

This is not the case for an example public (i.e. 200 for both head operations) object that I own (either this branch or current release):

```
❱ datalad download-url s3://msz-datalad-test-mixed/datacat_sd_1.jpeg
[INFO   ] Downloading 's3://msz-datalad-test-mixed/datacat_sd_1.jpeg' into '/home/mszczepanik/' 
[INFO   ] S3 session: Connecting to the bucket msz-datalad-test-mixed anonymously 
download_url(ok): /home/mszczepanik/datacat_sd_1.jpeg
```

So although the objects are public, something in DataLad tries to prevent me from accessing them!

Staying with this branch from now, and digging deeper, this is what comes out of low level download code (similar to what happens in basic tests, or download_url):

```
>>> from datalad.downloaders.providers import Providers
>>> providers = Providers.from_config_files()
>>> url = 's3://datalad-test0-versioned/2versions-nonversioned1.txt'
>>> providers.get_provider(url)
Provider(authenticator=<<S3Authenticato++23 chars++one)>>, credential=<<AWS_S3(ds=None++45 chars++rg')>>, name='datalad-test-s3', url_res=['s3://datalad.test.*'])
>>> downloader = providers.get_provider(url).get_downloader(url)
>>> downloader.download(url)
[INFO   ] Downloading 's3://datalad-test0-versioned/2versions-nonversioned1.txt' into None 
You need to authenticate with 'datalad-test-s3' credentials. team@datalad.org provides information on how to gain access
key_id: 
```

When trying to run tests, I see them skipped. I tried setting `DATALAD_TESTS_CREDENTIALS=system` as suggested, but that alone did nothing for me.

When neutering [get_test_providers](https://github.com/datalad/datalad/blob/maint/datalad/downloaders/tests/utils.py) by commenting out lines 19-26 which raise `SkipTest`, I get this - presumably because of the attempts to prompt for credentials:

```
❱ pytest -s -vv ~/Documents/datalad/datalad/downloaders/tests/test_s3.py::test_s3_download_basic
(...)
========================================================== short test summary info ===========================================================
FAILED ../home/mszczepanik/Documents/datalad/datalad/downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad-test0-versioned/2versions-nonversioned1.txt-version2-version1] - AttributeError: 'QuietConsoleLog' object has no attribute 'question'
FAILED ../home/mszczepanik/Documents/datalad/datalad/downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad-test0-versioned/2versions-nonversioned1.txt?versionId=V4Dqhu0QTEtxmvoNkCHGrjVZVomR1Ryo-version2-version1] - AttributeError: 'QuietConsoleLog' object has no attribute 'question'
FAILED ../home/mszczepanik/Documents/datalad/datalad/downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad-test0-versioned/2versions-nonversioned1.txt?versionId=null-version1-version2] - AttributeError: 'QuietConsoleLog' object has no attribute 'question'
FAILED ../home/mszczepanik/Documents/datalad/datalad/downloaders/tests/test_s3.py::test_s3_download_basic[s3:/datalad.test1/version1.txt-version1-nothing] - AttributeError: 'QuietConsoleLog' object has no attribute 'question'
======================================================= 4 failed, 2 warnings in 0.66s ========================================================
```

<hr>

I am sure all this is simply caused by my own lack of understanding of the test / credential setup (or lack of skill, to put it briefly). As you see above, I have tried. I understand that some kind of configuration tries to enforce credentialled access for the test buckets. But I do not know where that config lives. I do not know what to change next.

And at this stage I'm afraid I won't even understand brief pointers.

Seeing how outdated boto2 package is, I really wanted to complete this PR. But at this point, I need to accept my defeat. It has become a time sink for me, and every attempt to keep it alive is another time sink.

What I would need at this point is help at setting up the test environment - clearly, it worked for others, but I could not make the tests work on my machine. But also it looks like I won't be able to afford time to work on the PR in August. If that's the case, I will close it after the weejend, and hope someone picks it up.

I am sorry.

**Comment by mslw** [comment]
TIL (with @yarikoptic help) that:

- The reason why DataLad refuses to work without credential is because of `downloaders/configs/providers.cfg`. This could also be played with, e.g. to see what would happen with anonymous access.
- As most of our buckets (if not all) do not limit access to specific (i.e. owner) accounts, having any valid S3 credential as ¨datalad-test-s3" credential should be sufficient. This can be entered during any operation (e.g. `download-url`, or `datalad ls` from deprecated). User's credential will then be used when running pytest with `DATALAD_TESTS_CREDENTIALS=system`.
- There were issues with vcr (casette) #7465, and #7467 disables it for specific tests. Alternatively, uninstalling vcrpy simply means that it won't be used and won't get in the way.

Whether the tests should require credentials is a question for outside this PR - ideally some would test credentialled, and some anonymous access. But the goal here is to substitute boto with boto3, and we could worry about further improvements later.

With my own credential in place, I still see failures, but the reasons need investigating. Leaving this PR in closed state because I can't work on it right now, but I count that as an obstacle cleared.

**Comment by yarikoptic-gitmate** [comment]
PR released in [`1.1.0`](https://github.com/datalad/datalad/releases/tag/1.1.0)

**Pull request closed without merging**
