### PR TITLE
A number of fixes from a quality time with Windows

### PR DESCRIPTION
**Pull request by yarikoptic**
- do not misdetect Windows paths for sshri
- enable `@with_testrepo` while on Windows and in default v6 mode for annex repos

### CODE REVIEW

**Comment by bpoldrack** [comment]
Re ssh ri:
Shouldn't it be `is_windows_path` (called in `network.py` line 324), that is to be fixed for this issue?

**Comment by yarikoptic** [comment]
it is not a "classical" windows  path, it is the abomination from those shells on Windows:

```
$> python -c 'from datalad.support.network import is_windows_path; print(is_windows_path("/C:/f/s1"))'
False

$> python -c 'from datalad.support.network import is_windows_path; print(is_windows_path("C:/f/s1"))' 
True
```
because of them we already have also special treatment of `///` already since leading `/` would be stripped by them for their own conventions

**Comment by bpoldrack** [comment]
Sure. But the logical flow here should be to consider it a windows path and therefore return 'file', right? I just think that figuring it's a path after having `is_windows_path` return `False` leads to really hard to understand code. If we need to add things here for we discover more flaws of RI detection this is gonna get messy.

**Comment by yarikoptic** [comment]
FWIW, on a sample run on our virtualbox that test (ran in isolation) didn't stall...

**Comment by yarikoptic** [comment]
wanted to restart appveyor, didn't find a better way but just to rewrite last commit. force pushed

**Comment by yarikoptic** [comment]
consistent "datalad.distribution.tests.test_dataset.test_is_installed ... " stall on appveyor -- will need to enjoy their interactive session to figure it out

**Comment by yarikoptic** [comment]
eh, appveyor is still cursed with the stalling issue in test_dataset, and only in `DATALAD_REPO_VERSION=6` mode... needs to be debugged

**Comment by yarikoptic** [comment]
one of the core problems with testing on Windows seems to be a regression of [not being able to addurl file:/// urls](http://git-annex.branchable.com/bugs/Unable_to_addurl_file__58____47____47____47___on_Windows/?updated) which we use in our `with_testrepos`

**Comment by mih** [comment]
Closing due to inactivity.

**Pull request closed without merging**
