### PR TITLE
Fix AnnexRepo.whereis key=True mode operation, and add batch mode support

### PR DESCRIPTION
**Pull request by yarikoptic**
First commit is truly a BF and destined to `maint`. The 2nd addresses the limitation (we were just raising a ValueError, not even NotImplementedError) if asked to perform in batch mode on keys.  Support for that functionality was added only recently to git-annex, and since change is small, I have decided to bundle it within the same PR against `maint`. But I would be ok to split it into `master`.  Motivation -- a need for datalad-fuse development.

attn @jwodder (I will provide more context in datalad-fuse later)

#### 🐛 Bug Fixes
- Fixes `AnnexRepo.whereis` operation in `key=True` mode whenever multiple keys are provided.
#### 💫 Enhancements and new features
- Adds support  for batch mode operation to `AnnexRepo.whereis` in `key=True` mode (requires git-annex 8.20210903 or later)

### CODE REVIEW

**Comment by yarikoptic** [comment]
eh, codecov report of `-3` lines coverage effect makes little sense to me:
- diff added lines
- red in the "map" points to test_http and there codecov reports drop of coverage for 5+3=8 lines: https://app.codecov.io/gh/datalad/datalad/compare/6379/tree/datalad/downloaders/tests/test_http.py#D1L280 and otherwise no change in coverage to actual tests which trigger those lines... so not sure what is going on exactly -- will remain the mystery ;)

**Comment by yarikoptic** [comment]
@datalad/developers this PR is ready for review and potentially a merge.  Your feedback is always welcome!

**Review by bpoldrack — APPROVED** [review]

**Comment by yarikoptic** [comment]
> Can we get a changelog @yarikoptic ?

this PR is against `maint` , so will not be participating in `master` release directly. Do I still need to add a changelog entry?

Moreover we are at 0.15.4-22-g967ff5da7 in `maint` so may be worth even kicking out a release with this PR -- there were some bugfixes, no big need/desire to hold them away from seeing a wild world.

**Comment by yarikoptic** [comment]
Attn @mih: FWIW added Changelog entries to the main description.

**Comment by mih** [comment]
Thx!

**Review by mih — APPROVED** [review]
LGTM!

**Pull request merged**
