### PR TITLE
Minor changes to Runner-class

### PR DESCRIPTION
**Pull request by bpoldrack**
PR for little corrections and the like

### CODE REVIEW

**Comment by yarikoptic** [comment]
I think travis testing stuck on that heavy output case (wasn't it a good case? ;) )
Does it pass for you locally?

**Comment by yarikoptic** [comment]
yeap -- stuck for me locally as well... just look into implementations using Popen in other packages... I remember this problem from git-bigpicture  so you could look how done there
http://github.com/esc/git-big-picture

**Comment by bpoldrack** [comment]
Didn't test it locally before. It stucks too, so I removed from PR for now.
It's very interesting, that it fails.
In that sense - it was a very good idea to test it! ;-)

2015-03-10 12:41 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by bpoldrack** [comment]
Interestingly, it should raise an Exception, since there is a little bug in the workaround-decorator. Corrected it in the other PR already. But I'm really confused, why the hell it stucks instead of simply failing.

**Pull request closed without merging**
