### PR TITLE
BF: use datalad/packages method of installing git-annex

### PR DESCRIPTION
**Pull request by yarikoptic**
"snapshot" method is installing into a temp folder and we would need to setup env var file to source etc.

I have introduced that change in recent https://github.com/datalad/datalad/pull/7682 and missed that for that original commit appveyor did fail, and subsequent commit af2bd74 CI run had only OSX brew fail which made me think appveyor is ok, but apparently it was not there at all! So I missed that failure

### CODE REVIEW

**Comment by yarikoptic** [comment]
error does not make sense to me... took awhile to realize that pinned ancient version of datalad-installer 0.2.0 is used... and that version is passed via ENV var from appveyor configuration (why???) ... changed it there to `~=1.1`... restarting

**Comment by yarikoptic** [comment]
ok -- linuxes seems to be fixed, but OSX installation is not entirely kosher -- the `git` is not seeing `git-annex` 

```
E           datalad.support.exceptions.MissingExternalDependency: No working git-annex installation of version >= 8.20200309. Visit http://handbook.datalad.org/r.html?install for instructions on how to install DataLad and git-annex.
```

whenever we did get it installed

```
[00:00:35] 2024-12-13T11:10:04-0600 [INFO    ] datalad_installer: Running: rsync -a /Volumes/git-annex/git-annex.app /Applications/
[00:00:39] 2024-12-13T11:10:09-0600 [INFO    ] datalad_installer: Running: hdiutil detach /Volumes/git-annex/
[00:00:39] "disk2" ejected.
[00:00:39] 2024-12-13T11:10:09-0600 [INFO    ] datalad_installer: git-annex is now installed at /Applications/git-annex.app/Contents/MacOS/git-annex
[00:00:39] Running "build_script" scripts
```

and in WTF we see

```
[00:01:26]   - PATH: /Users/appveyor/venv3.9.18/bin:/Users/appveyor/.rvm/gems/ruby-3.3.0/bin:/Users/appveyor/.rvm/gems/ruby-3.3.0@global/bin:/Users/appveyor/.rvm/rubies/ruby-3.3.0/bin:/Library/Frameworks/Mono.framework/Home/bin:/Users/appveyor/.nvm/versions/node/v18.19.0/bin:/Users/appveyor/.gvm/pkgsets/go1.21.6/global/bin:/Users/appveyor/.gvm/gos/go1.21.6/bin:/Users/appveyor/.gvm/pkgsets/go1.21.6/global/overlay/bin:/Users/appveyor/.gvm/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/Cellar/appveyor-build-agent/7.0.3293:/Users/appveyor/flutter/bin:/Users/appveyor/vcpkg:/usr/local/share/dotnet:/Users/appveyor/.rvm/bin
```

so no mentioning of `/Applications/git-annex.app/Contents/MacOS/git-annex`...
```

**Comment by yarikoptic** [comment]
mac now "generally" works but because we are manually treating PATH it does not affect remote session etc, thus

```
FAILED ../datalad/core/distributed/tests/test_push.py::test_publish_target_url - datalad.support.exceptions.MissingExternalDependency: No working git-annex installation. It's required on the remote machine to create a sibling
FAILED ../datalad/support/tests/test_annexrepo.py::test_annex_ssh - datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false annex find --in . --not --in ssh-remote-1 --json --json-error-messages -c annex.dotfiles=true -- foo' failed with exitcode 1 under /Users/appveyor/DLTMP/datalad_temp_test_annex_sshvijwsfjf/main [info keys: stdout_json] [err: 'Unable to parse git config from ssh-remote-1
  Remote ssh-remote-1 does not have git-annex installed; setting annex-ignore
  This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote ssh-remote-1
git-annex: cannot determine uuid for ssh-remote-1 (perhaps you need to run "git annex sync"?)']
FAILED ../datalad/support/tests/test_sshconnector.py::test_ssh_git_props - assert None
```

I guess we better tune up installation more "persistently"

**Comment by yarikoptic** [comment]
woohoo -- we are good . there is one windows run on appveyor with flaky test failing

```
=========================== short test summary info ===========================
FAILED ..\datalad\support\tests\test_parallel.py::test_producing_consumer[10] - AssertionError: assert [1, 2, '1', '4', 0, '0'] == [0, 1, 2, '0', '1', '4']
  
  At index 0 diff: 1 != 0
  
  Full diff:
    [
  -     0,
        1,
        2,
  -     '0',
        '1',
        '4',
  +     0,
  +     '0',
    ]
====== 1 failed, 424 passed, 58 skipped, 1 warning in 1821.72s (0:30:21) ======
Command exited with code 1
```
I will ignore for now.  To facilitate greenness of the CI, I  will merge it.

**Comment by yarikoptic-gitmate** [comment]
PR released in [`1.1.5`](https://github.com/datalad/datalad/releases/tag/1.1.5)

**Pull request merged**
