### PR TITLE
NF: ConfigManager.???(where='override')

### PR DESCRIPTION
**Pull request by mih**
This brings the same (and actually more) configuration override
flexibility to the Python API that the cmdline API offers via
`datalad -c key=val`.

This feature is a necessity for being able to rely on one-off
configuration (changes) to alter command behavior, whenever
a dedicated command option is not absolutely needed or shall be
avoided.

A dedicated test for overrides is also included.

Fixes gh-3970

### CODE REVIEW

**Comment by mih** [comment]
Hmm, failure doesn't replicate on a real win10 box, nor on appveyor... :(

```
======================================================================
400
FAIL: datalad.tests.test_config.test_overrides
401
----------------------------------------------------------------------
402
Traceback (most recent call last):
403
  File "C:\hostedtoolcache\windows\Python\3.7.5\x64\lib\site-packages\nose\case.py", line 198, in runTest
404
    self.test(*self.arg)
405
  File "C:\hostedtoolcache\windows\Python\3.7.5\x64\lib\site-packages\datalad\tests\test_config.py", line 367, in test_overrides
406
    assert_not_in('ups.name', cfg)
407
AssertionError: 'ups.name' unexpectedly found in <datalad.config.ConfigManager object at 0x00000203515DE688>
```

**Comment by kyleam** [comment]
> Hmm, failure doesn't replicate on a real win10 box, nor on appveyor... :(

It looks like a good number of the Travis runs show the same failure ([example]).

[example]: https://travis-ci.org/datalad/datalad/jobs/631852801#L1107

**Comment by mih** [comment]
Prev. failures were pointing to a real issue, which is fixed now.

**Comment by mih** [comment]
Thx @kyleam

**Comment by bpoldrack** [comment]
Nice solution!

**Pull request merged**
