### PR TITLE
BF: doc example runs in direct mode again

### PR DESCRIPTION
**Pull request by bpoldrack**
This fixes direct mode failure of `3rd_party_analysis_workflow`.

The actual point is to better deal with branches, managed by annex (`annex/direct/my_branch`, `adjusted/my_branch(unlocked)`, etc.)

Additionally fixes our calls to `git-annex-init`, which used to kill tracking branch information in `.git/config` if we cloned from a repository in direct mode.

As a "side-effect" further improves direct mode build when run entirely (`DATALAD_REPO_DIRECT=1 nosetests -s -v datalad`), not just the modules `tests` and `support`.
This locally results for me in:

`FAILED (SKIP=55, errors=33, failures=43)` on master
`FAILED (SKIP=52, errors=36, failures=20)` on rf-returnvalues
`FAILED (SKIP=52, errors=30, failures=23)` on this PR

### CODE REVIEW

**Comment by mih** [comment]
This needs current master to be merged to avoid test failures.

**Comment by mih** [comment]
````
======================================================================
ERROR: datalad.tests.test_utils_testrepos.test_BasicAnnexTestRepo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 579, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/test_utils_testrepos.py", line 47, in test_BasicAnnexTestRepo
    _test_BasicAnnexTestRepo(path)
  File "/home/travis/build/datalad/datalad/datalad/tests/test_utils_testrepos.py", line 29, in _test_BasicAnnexTestRepo
    ok_clean_git(trepo.path)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 208, in ok_clean_git
    eq_(sorted(r.untracked_files), sorted(untracked))
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 647, in untracked_files
    path=None)['untracked']
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 567, in get_status
    json_list = _fake_exception_wrapper(self, options_=options)
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 559, in _fake_exception_wrapper
    self.config.set("datalad.log.cmd.outputs", old_log_state)
  File "/home/travis/build/datalad/datalad/datalad/config.py", line 587, in set
    where=where, reload=reload, log_stderr=True)
  File "/home/travis/build/datalad/datalad/datalad/config.py", line 519, in _run
    out = self._runner.run(['git', 'config'] + args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 583, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 411, in run
    stdin=stdin)
  File "/opt/python/2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/opt/python/2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: coercing to Unicode: need string or buffer, bool found
````

**Comment by bpoldrack** [comment]
FTR: One of the builds just takes too long. No actual failure.

**Comment by mih** [comment]
@bpoldrack Re-ran "failing" test run and can confirm that it takes too long. Unclear if it is a general slowness or one particular test.

**Pull request merged**
