### PR TITLE
ENH: Add ability to expand downloaders from entry points

### PR DESCRIPTION
**Pull request by yarikoptic**
Would be needed if an extension to introduce some new downloader support

### CODE REVIEW

**Review by mih — APPROVED** [review]
Makes sense!

**Comment by mih** [comment]
Any reason this has not made it out of draft mode yet?

**Comment by yarikoptic** [comment]
added/adjusted docs on entry_points listing.  Taking out of the draft

**Comment by mih** [comment]
Only checked on the phone, but there was still a `pdb` call in the diff. Shouldn't be there, right?

**Comment by yarikoptic** [comment]
d'oh -- thanks! I am afraid it was there for a reason that it was not quite finished and I submitted just to seek feedback first.

well -- I think I will take it back into draft mode: I thought I already had a downloader to hook up, and most likely it was the one for fsspec (within datalad-fuse) but can't locate it ATM.  Need to craft that one and then tune up unittest to make sure all is good.

**Comment by mih** [comment]
Let's close this PR until work on it resumes. We have almost 20 PRs open.

**Pull request closed without merging**
