### PR TITLE
RF: just pip install datalad-installer

### PR DESCRIPTION
**Pull request by yarikoptic**
master branch has its own ideas and binds to some older version
```
$> git grep datalad.installer
.appveyor.yml:  # deploy the datalad installer, override version via DATALAD_INSTALLER_VERSION
.appveyor.yml:      python -m pip install "datalad-installer%DATALAD_INSTALLER_VERSION%"
.appveyor.yml:      python -m pip install datalad-installer
.appveyor.yml:  - sh: python -m pip install datalad-installer${DATALAD_INSTALLER_VERSION:-}

```
needs yet to be addressed, decided to just go with maint for now and simplify (not versioned depends etc)

### CODE REVIEW

**Comment by mih** [comment]
Just commenting, have no checked yet. It would be good to know if a diff to the extension setup exists, and if so why, and if all extensions need to be modified.

**Comment by mih** [comment]
It is at least missing the ability to switch the installer version without editing .appveyor.yml. The feature was introduces in the extension setup the last time the installer behavior broke, and all extensions had to be fix before any CI would work again.


```yml
install:
...
  # deploy the datalad installer, override version via DATALAD_INSTALLER_VERSION
  - cmd:
      IF DEFINED DATALAD_INSTALLER_VERSION (
      python -m pip install "datalad-installer%DATALAD_INSTALLER_VERSION%"
      ) ELSE (
      python -m pip install datalad-installer
      )
  - sh: python -m pip install datalad-installer${DATALAD_INSTALLER_VERSION:-}

```

it would be great if the setups converge.

**Comment by yarikoptic** [comment]
> it would be great if the setups converge.

it would be great if the setup didn't diverge ;-)  copied `master`'s .appveyor with only slight tune up for maint, and then improved upon.  So should be re-converging now

**Comment by yarikoptic** [comment]
hm, codecov offset is too big. #5688 against maint has only 0.1% . looking at diff in coverage - might relate to travis runs for high log level to not provide results, but also might relate to added `INSTALL_GITANNEX: git-annex -m datalad/packages`. so I will comment it out and give another full round to see if codecov report comes cleaner.

**Comment by yarikoptic** [comment]
ok, had to restart one appveyor on mac. now all green and codecov divergence is small. so we should be good to go

**Review by mih — APPROVED** [review]
Wonderful, thx @yarikoptic for the updates!

**Pull request merged**
