### PR TITLE
ConfigManager supports bare repos

### LINKED ISSUE #6264: `ConfigManager` cannot handle bare repo's (dataset/branch config)
It uses the path `.datalad/config` to check for the presence of a config, rather than something like `--blob`. More specifically `HEAD:.datalad/config`, which works with bare and non-bare repos.

The critical question here is how to deal with uncommitted config files. So far this was completely ignored. Any modification was immediately effective. It would probably be necessary to retain this behavior for non-bare repos -- but worth keeping in mind.

### LINKED ISSUE #6327: ConfigManager implements source file stat'ing wrong
https://github.com/datalad/datalad/blob/2b92a764fdc64b750dad68eb51c817218a1ec153/datalad/config.py#L445

better be:

```
f.exists()
```

### LINKED ISSUE #6331: `ConfigManager.get_from_source('local', ...)` broken
Whenever, the requested setting was not read from the `dataset` config store.

It tried to access a `local` config store, but it's name is actually `git`.

Seems untested.

### PR DESCRIPTION
**Pull request by mih**
#### 🐛 Bug Fixes
- Fix a broken check for file presence in the `ConfigManager` that could have caused a crash in rare cases when a config file is removed during the process runtime. Fixes #6327
- `ConfigManager.get_from_source()` now accesses the correct information when using the documented `source='local'`, avoiding a crash. Fixes #6331
#### 💫 Enhancements and new features
- `ConfigManager` now supports reading committed dataset configuration in bare repositories. Analog to reading `.datalad/config` from a worktree, `blob:HEAD:.datalad/config` is read (e.g., the config committed in the default branch). The support includes `reload()` change detection using the gitsha of this file. The behavior for non-bare repositories is unchanged. Fixes #6264

### CODE REVIEW

**Comment by mih** [comment]
Reliable failure on windows:

```
======================================================================
FAIL: datalad.tests.test_config.test_bare
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\datalad\datalad\tests\utils.py", line 851, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad\datalad\tests\utils.py", line 851, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad\datalad\tests\test_config.py", line 682, in test_bare
    assert_equal('surprise!', gr.config.get('datalad.dataset.id'))
AssertionError: 'surprise!' != 'd62fab7b-cb57-40bf-9fd7-a8b232e8dd97'
- surprise!
+ d62fab7b-cb57-40bf-9fd7-a8b232e8dd97
```

**Comment by mih** [comment]
If I cannot come back to this within a week, feel free to close.

**Comment by adswa** [comment]
Windows test failure persists:
```
======================================================================
FAIL: datalad.tests.test_config.test_bare
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\datalad\datalad\tests\utils.py", line 850, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad\datalad\tests\utils.py", line 850, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad\datalad\tests\test_config.py", line 682, in test_bare
    assert_equal('surprise!', gr.config.get('datalad.dataset.id'))
AssertionError: 'surprise!' != '6160a7af-3df4-4ede-8de0-29cd92155557'
- surprise!
+ 6160a7af-3df4-4ede-8de0-29cd92155557
```
Failure on travis seems unrelated:
```
======================================================================
ERROR: datalad.distribution.tests.test_get.test_source_candidate_subdataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-lnezowab/lib/python3.9/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/tmp/dl-miniconda-lnezowab/lib/python3.9/site-packages/nose/case.py", line 152, in runTest
    test(result)
AssertionError: Test was too slow (took 30.2888s, threshold was 30.0000s)
```

**Comment by mih** [comment]
> Windows test failure persists

Yeah, and I cannot make it show locally on windows. Will debug on appveyor

**Comment by mih** [comment]
Travis failure is unrelated https://github.com/datalad/datalad/issues/6412

**Pull request merged**
