### PR TITLE
RF: Remove global options from subcommand help pages

### PR DESCRIPTION
**Pull request by bpoldrack**
`log-level`, `pbs-runner` and `version` are global options.

### CODE REVIEW

**Comment by mih** [comment]
Thanks @bpoldrack this was bothering me for a long time...

**Comment by bpoldrack** [comment]
Failures appear to be all the same: Crawler test gets Error 502 while trying to download whatever from search.datacite.org

@yarikoptic : Can you tell what to do about it?

**Comment by yarikoptic** [comment]
I just ran into that locally yesterday, if persists, will s start pestering people

**Comment by yarikoptic** [comment]
Bloody Puritans!!! :-)

**Comment by mih** [comment]
Ok, we waited just long enough for any bugs to sink to the ground...

**Pull request merged**
