### PR TITLE
General config overrides mechanism and `-c` option for the cmdline

### PR DESCRIPTION
**Pull request by mih**
Addresses #958 

At present we have no simple way to test the few lines in `main.py`.

### CODE REVIEW

**Comment by mih** [comment]
Buildbot failure is due to the way the tests are executed there, i.e.

````
python -c 'import nose; nose.main()' -s -v datalad
````

it considers `-c` as `sys.argv[0]` and now there is an actual `-c` option in datalad. Can we use the same test invocation in the buildbots that we use on travis, i.e. via a call to `nosetests`? @yarikoptic

**Comment by mih** [comment]
These changes are now a requirement for #1350.

**Comment by yarikoptic** [comment]
how come travis is happy and all buildbots aren't?

**Comment by mih** [comment]
@yarikoptic the answer is in the message above. And in #1353

**Comment by mih** [comment]
#1353 now merged into this one.

**Comment by mih** [comment]
OK, travis and buildbots (minus the ones with general trouble) are OK. Good to merge. Count down started. Veto?

**Comment by mih** [comment]
Gracie!

**Pull request merged**
