### PR TITLE
config option for --report-status (and may be others in the reporting code)

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by yarikoptic** [comment]
just because I am extremely bored I will try to come up with a unittest so this wonderful feature does not silently go away

**Comment by yarikoptic** [comment]
oh, you didn't allow to contribute to this PR so here you go: https://github.com/mih/datalad/pull/24

**Comment by mih** [comment]
Enabled maintainer edits now.

**Comment by yarikoptic** [comment]
I forgot already where we saw/dealt with it, or just closed our eyes on it... travis run in above state has failed in heavy debug mode with following:
```
  File "/home/travis/build/datalad/datalad/datalad/metadata/aggregate.py", line 469, in _update_ds_agginfo
    save=False, result_renderer=None, return_type=list)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 466, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 454, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 411, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 478, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/distribution/add.py", line 424, in __call__
    **add_kw
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 300, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 1535, in add
    expect_stderr=True
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2394, in _run_annex_command_json
    json_objects = [j for j in json_objects if 'byte-progress' not in j]
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2392, in <genexpr>
    for line in out.splitlines() if line.startswith('{'))
  File "/opt/python/2.7.14/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/python/2.7.14/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 163 - line 1 column 328 (char 162 - 327)
```
I have restarted it, since I do not think this PR has anything to do with this, and thus shouldn't fail... if it happens - above should migrate into a separate issue and be resolved

**Pull request merged**
