### PR TITLE
OPT: do not bother sleeping when not output was received in the Runner processing of output

### PR DESCRIPTION
**Pull request by yarikoptic**
As "discussed" in #3319 
It could help quite a bit for any runs of `git-annex CMD --json` (not batched)

### CODE REVIEW

**Comment by kyleam** [comment]
So the sleep came about from e3e8665e3 (BF: sleep a bit if there were no output in log_online mode to avoid 100% load, 2018-05-08), which was a response to #2478.  Won't merging this bring back that issue?

**Comment by yarikoptic** [comment]
you are right @kyleam - thanks for looking it up.  Getting to the bottom of it. will report back shortly

**Comment by yarikoptic** [comment]
ok, mystery is not resolved but mitigated by fixing up the check in cfb1a73e58e59f3c505ba8ce5d41f8a6770fa815

FTR I also came up with abomination of an adaptable sleep but I do not think it provided any notable advantage, so decided against it but here is the sketch of a patch (with some debug printouts etc):
```patch
diff --git a/.asv b/.asv
--- a/.asv
+++ b/.asv
@@ -1 +1 @@
-Subproject commit 9bdd343b290d86bb71874d7d17e7acc24d074052
+Subproject commit 9bdd343b290d86bb71874d7d17e7acc24d074052-dirty
diff --git a/datalad/cmd.py b/datalad/cmd.py
index 2e4cf837..30c14126 100644
--- a/datalad/cmd.py
+++ b/datalad/cmd.py
@@ -305,12 +305,13 @@ class Runner(object):
                 expect_stderr or expect_fail
         )
 
+        nempty = 0
         while proc.poll() is None:
             # see for a possibly useful approach to processing output
             # in another thread http://codereview.stackexchange.com/a/17959
             # current problem is that if there is no output on stderr
             # it stalls
-            # Monitor if anything was output
+            # Monitor if anything was output and if nothing, sleep a bit
             stdout_, stderr_ = None, None
             if log_stdout_:
                 stdout_ = self._process_one_line(*stdout_args)
@@ -318,6 +319,18 @@ class Runner(object):
             if log_stderr_:
                 stderr_ = self._process_one_line(*stderr_args)
                 stderr += stderr_
+            if stdout_ is None and stderr_ is None:
+            #if not (stdout_ is not None or stderr_ is not None):
+            #if not (stdout_ or stderr_):
+                #print("HERE: %r %r" % (stdout_, stderr_))
+                # no output was generated, so sleep a tiny bit
+                time.sleep(min(0.001, 2**nempty * 0.000001))
+                nempty = min(20, nempty + 1)  # 2**20 ~= 1e6 - more than enough
+                # time.sleep(0.001)
+                pass
+            else:
+                #print("HERE EMPTY")
+                nempty = 0
 
         # Handle possible remaining output
         stdout_, stderr_ = proc.communicate()
```

**Comment by kyleam** [comment]
> ok, mystery is not resolved but mitigated by fixing up the check in [cfb1a73](https://github.com/datalad/datalad/commit/cfb1a73e58e59f3c505ba8ce5d41f8a6770fa815)

Nice, thank you.

One thing I wonder is why we even need to call `_get_output_online` when the `run(..., log_online=True, log_stdout=False, log_stderr=False)`.  Can't we let that go through to `.communicate()`?  Something like

```diff
diff --git a/datalad/cmd.py b/datalad/cmd.py
index d86ea8787..ee941f79b 100644
--- a/datalad/cmd.py
+++ b/datalad/cmd.py
@@ -514,7 +514,7 @@ def run(self, cmd, log_stdout=True, log_stderr=True, log_online=False,
                     self.protocol.end_section(prot_id, prot_exc)

             try:
-                if log_online:
+                if log_online and (log_stdout or log_stderr):
                     out = self._get_output_online(proc,
                                                   log_stdout, log_stderr,
                                                   outputstream, errstream,
```

**Comment by yarikoptic** [comment]
one of the cases which this would change behavior of (don't know yet if with any positive or negative effects) is within sshrun
```
  /home/yoh/proj/datalad/datalad/venvs/dev/bin/datalad(8)<module>()
-> main()
  /home/yoh/proj/datalad/datalad/datalad/cmdline/main.py(499)main()
-> ret = cmdlineargs.func(cmdlineargs)
  /home/yoh/proj/datalad/datalad/datalad/interface/base.py(626)call_from_parser()
-> ret = cls.__call__(**kwargs)
  /home/yoh/proj/datalad/datalad/datalad/support/sshrun.py(89)__call__()
-> out, err = ssh(cmd, stdin=stdin_, log_output=False)
  /home/yoh/proj/datalad/datalad/datalad/support/sshconnector.py(162)__call__()
-> **kwargs)
> /home/yoh/proj/datalad/datalad/datalad/cmd.py(521)run()
-> out = self._get_output_online(proc,
```
and the logic there in SSHConnection is 
```
        kwargs = dict(
            log_stdout=log_output, log_stderr=log_output,
            log_online=not log_output
        )
```
so with such a change we would never hit that `_get_output_online` when called from it.  Adding this additional condition starts to break the tests such as `datalad/support/tests/test_gitrepo.py:test_GitRepo_ssh_fetch` ... with all the mess of the runner options it is hard to figure out exactly why, so I would prefer to stick to minimal change for now, just fixing the issue.

**Comment by kyleam** [comment]
@yarikoptic:

> one of the cases which this would change behavior of (don't know yet if with any positive or negative effects) is within sshrun [...]

OK, thanks for looking into it.

> Adding this additional condition starts to break the tests such as `datalad/support/tests/test_gitrepo.py:test_GitRepo_ssh_fetch` ... with all the mess of the runner options it is hard to figure out exactly why, so I would prefer to stick to minimal change for now, just fixing the issue.

Sure, sounds fine to me.  I really was "just wondering", not objecting
to the proposed change here.

**Pull request merged**
