### PR TITLE
Eliminate uses of `pkg_resources`

### LINKED ISSUE #7435: replace uses of pkg_resources
we got
```
FAILED ../core/local/tests/test_create.py::test_create_withcfg - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../core/local/tests/test_create.py::test_bad_cfg_proc - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_addurls.py::TestAddurls::test_addurls_create_newdataset - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_addurls.py::TestAddurls::test_addurls_subdataset - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_run_procedure.py::test_run_proc_with_dict - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../resources/procedures/tests/test_noannex.py::test_noannex_simple - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../resources/procedures/tests/test_noannex.py::test_noannex_create_force - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_run_procedure.py::test_invalid_call - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_run_procedure.py::test_dirty - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_run_procedure.py::test_procedure_discovery - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_run_procedure.py::test_configs - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_run_procedure.py::test_spaces - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
FAILED ../local/tests/test_run_procedure.py::test_text2git - DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```
for which I will workaround by ignoring it for now, but should be addressed properly following the recommendations.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #7435.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thank you!  windows on appveyor isn't happy though:

```

=========================== short test summary info ===========================
FAILED ..\datalad\core\local\tests\test_create.py::test_bad_cfg_proc - NameError: name 'as_file' is not defined
FAILED ..\datalad\core\local\tests\test_create.py::test_create_withcfg - NameError: name 'as_file' is not defined
=========== 2 failed, 232 passed, 24 skipped in 1685.19s (0:28:05) ============
Command exited with code 1
```

**Comment by jwodder** [comment]
@yarikoptic Should be fixed now.

**Comment by yarikoptic** [comment]
It was green back then, debian has the dependency even in oldstable so let's proceed

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.19.3`](https://github.com/datalad/datalad/releases/tag/0.19.3)

**Pull request merged**
