### PR TITLE
Prevent cron-only Travis builds from starting on non-cron events

### LINKED ISSUE #5189: TRAVIS: make cron jobs not even start the VM
ATM we have
```yaml
before_install:
  - if [ ! -z "${_DL_CRON:-}" ]; then
      if [ ! ${TRAVIS_EVENT_TYPE} = "cron" ]; then
        echo "Exiting since should only be ran on a weekly basis by cron!";
        exit 0;
      fi
    fi
```
so it requires first for a machine to boot, waste of time.
Not yet sure exactly how but https://github.com/travis-ci/travis-ci/issues/7149#issuecomment-335825605 

```yaml
language: python
python:
  - "3.6"
matrix:
  include:
    - if: branch =~ ^deploy
      python: "2.7"
```
suggests that we could add conditional to those to not even be considered if some expression is not matched.

There is also "stages" feature https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions so may be we could have some stages (tests and extra-tests) or alike, again where some are triggered only for cron jobs.  @jwodder please have a look either you see a clean way

### PR DESCRIPTION
**Pull request by jwodder**
Closes #5189.

Docs references:
* https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
* https://docs.travis-ci.com/user/conditions-v1

### CODE REVIEW

**Comment by yarikoptic** [comment]
oh sweet!  thanks @jwodder !  verified that travis did run the other jobs (failed due to workaround was pending in #5188) please also 
- remove any mentioning/use of `_DL_CRON` then since it is of no use/purpose AFAIK with this PR changes
- rebase against `maint` -- I have just merged https://github.com/datalad/datalad/pull/5188 which should make travis green again

then when maint is green and ready, we will just merge it into master to propagate

**Comment by jwodder** [comment]
@yarikoptic 

> remove any mentioning/use of _DL_CRON then since it is of no use/purpose AFAIK with this PR changes

Actually, it is still of use; the `after_success` step at the end of `.travis.yml` sends coverage off to Codecov only if the job is not a cron-only job, and `_DL_CRON` is needed to make that determination.

**Comment by jwodder** [comment]
Rebased against maint.

**Comment by yarikoptic** [comment]
> @yarikoptic
> 
> > remove any mentioning/use of _DL_CRON then since it is of no use/purpose AFAIK with this PR changes
> 
> Actually, it is still of use; the `after_success` step at the end of `.travis.yml` sends coverage off to Codecov only if the job is not a cron-only job, and `_DL_CRON` is needed to make that determination.

RF that coverage submission to be conditioned on `if [ ! ${TRAVIS_EVENT_TYPE} = "cron" ]; then` instead and remove `_DL_CRON`?

**Comment by jwodder** [comment]
@yarikoptic That would be a behavior change: when all the jobs are run for a cron, none of them — not just the cron-only ones — would submit coverage.  Is that what you want?

**Comment by yarikoptic** [comment]
> @yarikoptic That would be a behavior change: when all the jobs are run for a cron, none of them — not just the cron-only ones — would submit coverage. Is that what you want?

oh, you are right, I have missed that.  In general I think it should be ok if none of the cron-triggered jobs submits coverage report and we just rely on the reports submitted from regular runs on a (master or maint) branch.  I still think it is worth it since would simplify our convoluted .travis.yml even if tiny bit, and avoid duplicate specification needed for cron-only jobs.

**Comment by jwodder** [comment]
@yarikoptic `_DL_CRON` removed.

**Comment by kyleam** [comment]
Nice.  Thanks @jwodder.

**Pull request merged**
