### PR TITLE
Drop python 3.6 support, remove some no longer needed kludges, merge of maint 

### PR DESCRIPTION
**Pull request by yarikoptic**
Sits on top of the merge of #6363 into master.

### CODE REVIEW

**Comment by yarikoptic** [comment]
@mih, from top of your head -- what should we do about redness of codeclimate in the example of this PR?

**Comment by mih** [comment]
Nothing. I am still trying to explore the possibilities. The messages so far are reasonable, but not applicable. Ignore and proceed, I would say

**Comment by adswa** [comment]
The Mac tests timed out with ``datalad.tests.test_testrepos.test_make_studyforrest_mockup ... `` - ping https://github.com/datalad/datalad/issues/6281

**Comment by yarikoptic** [comment]
> The Mac tests timed out with `datalad.tests.test_testrepos.test_make_studyforrest_mockup ... ` - ping #6281

eh, searched through our issues but it seems there were no prior timing out for this one.

eh, restarted incomplete on appveyour -- let's see if resurfaces... if doesn't show up, I will proceed with merge. (I've merged satellite PR in `maint`)

**Comment by yarikoptic** [comment]
marked two errors from codeclimate as no fix (md5 and loading a pickle). All green now.  To not miss some new python 3.10 gotchas to get introduced to `master`, I will proceed with merge.

**Comment by mih** [comment]
This PR has brought the appveyor job names out if sync with their config. Moreover, there are now two runs on ubuntu with py3.8 (which is the default version). I will trim this and resync the names.

**Comment by yarikoptic** [comment]
> This PR has brought the appveyor job names out if sync with their config. Moreover, there are now two runs on ubuntu with py3.8 (which is the default version). I will trim this and resync the names.

oh, didn't spot that `ID`s are reflecting python version.  Will keep it in mind for the future.

**Pull request merged**
