### PR TITLE
RM: SafeConfigParserWithIncludes

### PR DESCRIPTION
**Pull request by mih**
I could not determine where and how the functionality added by this
class over `configparser.ConfigParser` is needed. It used to be used
in datalad.config, but that was loooong ago. This change simply
removes the class (no tests to remove, because there are none), and
replaces its usage with `configparser.ConfigParser`.

Closes gh-5513

### CODE REVIEW

**Comment by bpoldrack** [comment]
Crawler! ;-)

**Comment by yarikoptic** [comment]
yeap... the cradle of the datalad... and it stems from fail2ban where I hacked it in previous lifetime.  I am not sure though if even current crawler needs any added functionality (I do remember that in inception there were need to be able to include config files within config files), so would need a look at the crawler and possibly a simple RF and release.

**Comment by mih** [comment]
If it is just the crawler, we could move the class, if needed.

**Comment by mih** [comment]
OK, so the crawler is affected, but only the crawler.

**Comment by mih** [comment]
I created companion PR https://github.com/datalad/datalad-crawler/pull/93 to see what action is best.

**Comment by mih** [comment]
Crawler tests suggest that the crawler would work fine without this class.

**Comment by yarikoptic** [comment]
FWIW, pushed 0.8.2 of the crawler out, thanks @mih for PR

**Comment by yarikoptic** [comment]
somehow conflicts came about

**Comment by mih** [comment]
Resolved conflict (modification of the file deleted here).

**Comment by mih** [comment]
This seems good to go now. I would merge unless objections are voiced.

**Pull request merged**
