### PR TITLE
UX: Report branch names and states in WTF report

### LINKED ISSUE #5731: Add information about current state and branches
"inspired" by #5724 

We might want to expand `dataset` section with `branches` which would list hexsha for all, and also add `head.{ref,hexsha}` to show the one for current state (might be detached from branches, so ref might not point to any branch).  If we decide to proceed this way, adding `git-describe` output (if any) might be also super handy.

### PR DESCRIPTION
**Pull request by adswa**
This potentially closes #5731. It adds a section "branches" to the dataset report of ``datalad wtf``, and reports all branches using the format ``<branch>[@<commit>]``.
For example:

```
(handbook2) adina@muninn in ~/repos/datalad on git:ux-5731
❱ datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/adina/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/adina/.config/python_keyring/keyringrc.cfg
    - data_root: /home/adina/.local/share/python_keyring
## datalad 
  - full_version: 0.14.4.dev496-g61bc
  - version: 0.14.4.dev496
## dataset 
  - branches: 
    - appveyor[@618f99e]
    - bf-4359[@b0a4458]
    - bf-flexibleclonecandidates[@73cbe11]
    - bf-git-gc[@9e17649]
    - doc-get[@d91c19e]
    - doc-joss[@5a49c20]
    - enh-addreadme[@96d0a68]
    - enh-addreadme2[@f53c74f]
    - enh-addreadmebackup[@f2deb2a]
    - get-command-annex-error[@8def465]
    - gh-loj[@0b0e7fe]
    - maint[@08f5c58]
    - master[@74f6f81]
    - non-interactive-log-wrap[@60e3edd]
    - rf-auto[@42052d6]
    - rf-callannex[@6c1a736]
    - test-5631[@580537c]
    - test-bf-flexibleclonecandidates[@686f27d]
    - tst-testrepos-appveyor[@dfa5ea5]
    - ux-5547[@8724226]
    - ux-5711[@be4b3c1]
    - ux-5731[@61bcf10]
    - ux-pushtarget[@a46f21e]
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/adina/repos/datalad
  - repo: GitRepo
## dependencies 
[...]
```

### CODE REVIEW

**Comment by adswa** [comment]
I haven't added any ``git describe``d output yet (which @yarikoptic suggested in the original issue), though. Would that fit under a section ``tag``, maybe?

**Comment by adswa** [comment]
Appveyor failure is "Build execution time has reached the maximum allowed time for your plan (60 minutes)."

**Review by mih — APPROVED** [review]
I like it! Thx!

I would even consider to not have the `[ ]`, but simply append the `@...` to the branch name. But it works for me as-is too.

**Comment by adswa** [comment]
We could remove the ``[ ]`` -  its potentially even easier then to grep for it. I can do after I finished my current work on #5812

**Comment by adswa** [comment]
I have removed ``[]`` and force-pushed

**Comment by mih** [comment]
Cool, thanks. Let's merge this!

**Pull request merged**
