### PR TITLE
Reincarnate appveyor coverage

### PR DESCRIPTION
**Pull request by yarikoptic**
not yet sure what to be done

TODOs
- [x] make sure we submit to appveyor across all matrix runs
- [x] remove TEMP commits

### CODE REVIEW

**Comment by yarikoptic** [comment]
@mih in your appveyorification attempts -- did you figure out submission of coverage?

**Comment by kyleam** [comment]
I think you'll also need to revert 04f93511cc (TST: Fully disable coverage on windows, due to crash, 2020-11-05) and hope that the problem it links to has disappeared.

**Comment by kyleam** [comment]
> and hope that the problem it links to has disappeared.

Unfortunately it hasn't:
https://ci.appveyor.com/project/mih/datalad/builds/36747175/job/nn56i1n5uwvboldj#L775

**Comment by yarikoptic** [comment]
ok, segfault is gone, welcome
```
python -m coverage xml
No data to report.
Command exited with code 1
```

**Comment by yarikoptic** [comment]
hm, "that went well".  one run is still running but `datalad.core` tests passed and coverage seems submitted but then ends with
```
[00:02:02]
[00:02:02]
[00:02:02]     -> View reports at https://codecov.io/github/datalad/datalad/commit/67ce8996fd3b4b0ea7b0c1a674eaa47041c706de
[00:02:02] Command executed with exception:
[00:02:02]
```
and thus marked as failed... waiting for the longer one (if I push again -- will choose some smaller/shorter tests sample) to compete to see if codecov would report anything here

**Comment by yarikoptic** [comment]
Ok, success... dropping TEMPs ;)

**Comment by mih** [comment]
Cool, thx!

**Pull request merged**
