### PR TITLE
Fix fallout from CLI update

### LINKED ISSUE #6404: `datalad -h/--help` does not list extension command
But they are functional and their own help is accessible via the CLI. Likely fallout from the CLI update.

### PR DESCRIPTION
**Pull request by mih**
- Fixes #6404
- Add compact-shims for old CLI entrypoints (needed for extension doc builds)

Does not need to appear in a release changelog.

### CODE REVIEW

**Comment by adswa** [comment]
I tried this, and it fixes the issue for me

**Comment by mih** [comment]
The benchmark impact is unavoidable. The issue here is that it did not process the extensions before, and now does.

**Comment by yarikoptic** [comment]
appveyor fail seems to be due to running out of time since aligns to an hour:
```
$> tail -n 1 /tmp/log.txt
[00:59:58] uninstall(ok): subdir/subds_unavailable_clean (dataset)
```
?  shouldn't be related this much though since we rarely invoke in tests via CLI (besides special remotes, not sure if those are anyhow affected)

**Comment by mih** [comment]
Yeah, that run pains me, need to split. But should be good to merge.

**Pull request merged**
