### PR TITLE
DATALAD_SEED

### PR DESCRIPTION
**Pull request by yarikoptic**
This pull request fixes nothing, but could help in generating reproducible test and casts runs (see eg. #2296)

### Changes
- [x] rewrite authorship for initial commits from the mighty blah
- [x] This change is complete

Please have a look @datalad/developers

### CODE REVIEW

**Comment by yarikoptic** [comment]
ha -- only 2 tests fail if we hardcode git date(s):
```shell
$> grep -A20 'FAIL:' log.txt 
FAIL: datalad.interface.tests.test_run.test_rerun_branch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1240, in newfunc
    func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 856, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 627, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/interface/tests/test_run.py", line 316, in test_rerun_branch
    ds.repo.repo.git.rev_list(revrange).split(), 3)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1185, in assert_result_count
    dumps(results, indent=1, default=lambda x: "<not serializable>")))
AssertionError: Got 2 instead of 3 expected results matching {}. Inspected 2 record(s):
[
 "24d0e616b565b7f1c4d1ebd76403f87968ea115a", 
 "35a5423274c7496ee6de0560e8ed6856864f9b60"
]
-------------------- >> begin captured logging << --------------------
--
FAIL: datalad.support.tests.test_gitrepo.test_get_tags
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 627, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/support/tests/test_gitrepo.py", line 1242, in test_get_tags
    eq_(gr.get_tags(), tags2)
AssertionError: [{'hexsha': u'166ac6e48f3d39cbe36c5ae1b47cd575decc83bf', 'name': 'annotated'}, {'hexsha': u'db98a5abb64ec760a98b6e934a5fcf412dc64bda', 'name': 'nonannotated'}] != [{'hexsha': 'db98a5abb64ec760a98b6e934a5fcf412dc64bda', 'name': 'nonannotated'}, {'hexsha': '166ac6e48f3d39cbe36c5ae1b47cd575decc83bf', 'name': 'annotated'}]
-------------------- >> begin captured logging << --------------------
datalad.utils: DEBUG: ...>utils:626>contextlib:17>utils:1169>handlers:78  Created temporary thing named /tmp/datalad_temp_test_get_tags9Z1Lnd"
datalad.network: Level 5: ...>utils:627>test_gitrepo:1223>repo:140>gitrepo:457>network:375,303>handlers:78  Parsed ri /tmp/datalad_temp_test_get_tags9Z1Lnd into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '/tmp/datalad_temp_test_get_tags9Z1Lnd', 'password': '', 'port': ''}
datalad.network: Level 5: ...>network:375,333>handlers:78  Detected file ri
datalad.gitrepo: DEBUG: ...>repo:146>gitrepo:573>handlers:78  Initialize empty Git repository at '/tmp/datalad_temp_test_get_tags9Z1Lnd'
git.cmd: DEBUG: Popen(['/usr/lib/git-annex.linux/git', 'init'], cwd=/tmp/datalad_temp_test_get_tags9Z1Lnd, universal_newlines=False, shell=None)
datalad.tests: Level 5: ...>test_gitrepo:1226>utils:153>handlers:78  Creating a tree under /tmp/datalad_temp_test_get_tags9Z1Lnd
datalad.cmd: Level 9: ...>test_gitrepo:1227>gitrepo:300,903,300,1500>cmd:664,456,578>handlers:78  Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'add', '--verbose', '--', 'file']
| cwd='/tmp/datalad_temp_test_get_tags9Z1Lnd'
...
```
The first one was encountered first locally (#2307), I wonder if that is something we should "fix" or just revert that evil last commit in this branch . what do you say @kyleam about that first one?

**Comment by kyleam** [comment]
> I wonder if that is something we should "fix" or just revert that evil last commit in this branch . what do you say @kyleam about that first one?

Definitely think we should fix it.  I just need to figure out why dates should matter there :/

**Comment by kyleam** [comment]
Uh, just to check: Did you intentionally [commit as blah in 2005][0], or did you forget to unset these after testing?

[0]: https://github.com/datalad/datalad/pull/2306/commits/25b6a7cad59a65c8b67e40d0ec3a5e859430af7e

**Comment by yarikoptic** [comment]
nah, wasn't intentional. I guess we could still fix this one up before merging, will add a checkbox to not forget (do not want to rewrite while you are pushing/testing)

**Comment by yarikoptic** [comment]
ok, rebased with rewriting author instead of the blah, will merge when tests pass and add this into 0.9.3 release since there is still time ;) (unless someone stops me)

**Pull request merged**
