### PR TITLE
Completes basic data consumer functionality on Windows

### PR DESCRIPTION
**Pull request by mih**
Copied straight from the "terminal" of greatness:

````
D:\>datalad install ///
[INFO] Cloning dataset from 'http://datasets.datalad.org/' (trying 2 location candidate(s)) to 'D:\datasets.datalad.org'
install(ok): D:\datasets.datalad.org (dataset)

D:\>cd datasets.datalad.org

D:\datasets.datalad.org>datalad get openfmri\ds000001\sub-06\anat\sub-06_inplaneT2.nii.gz
[INFO] Cloning dataset from 'http://datasets.datalad.org/openfmri/.git' (trying 1 location candidate(s)) to 'D:\datasets.datalad.org\openfmri'
install(ok): D:\datasets.datalad.org\openfmri (dataset) [Installed subdataset in order to get D:\datasets.datalad.org\openfmri\ds000001\sub-06\anat\sub-06_inpla
neT2.nii.gz]
[INFO] Cloning dataset from 'http://datasets.datalad.org/openfmri/ds000001/.git' (trying 1 location candidate(s)) to 'D:\datasets.datalad.org\openfmri\ds000001'

install(ok): D:\datasets.datalad.org\openfmri\ds000001 (dataset) [Installed subdataset in order to get D:\datasets.datalad.org\openfmri\ds000001\sub-06\anat\sub
-06_inplaneT2.nii.gz]
Total:   0%|                                                                                                                        | 0.00/679K [00:00<?, ?B/s]
Total:  39%|###########################################6                                                                     | 262K/679K [00:01<00:02, 142KB/s]
Total:  68%|############################################################################3                                    | 459K/679K [00:02<00:01, 175KB/s]
Total: 100%|#################################################################################################################| 679K/679K [00:02<00:00, 223KB/s]
Total (1 ok out of 1)100%|###################################################################################################| 679K/679K [00:02<00:00, 223KB/s]
get(ok): D:\datasets.datalad.org\openfmri\ds000001\sub-06/anat/sub-06_inplaneT2.nii.gz (file)
get(notneeded): D:\datasets.datalad.org\openfmri\ds000001\sub-06\anat\sub-06_inplaneT2.nii.gz (file) [already present]
action summary:
  get (notneeded: 1, ok: 1)
  install (ok: 2)

D:\datasets.datalad.org>cd ..

D:\>datalad remove datasets.datalad.org -r
drop(ok): D:\datasets.datalad.org\openfmri\ds000001\sub-06/anat/sub-06_inplaneT2.nii.gz (file) [checking http://openneuro.s3.amazonaws.com/ds000001/ds000001_R1.
1.0/uncompressed/sub006/anatomy/inplane001.nii.gz?versionId=null...]
drop(ok): D:\datasets.datalad.org\openfmri\ds000001 (directory)
uninstall(ok): D:\datasets.datalad.org\openfmri\ds000001 (dataset)
drop(notneeded): D:\datasets.datalad.org\openfmri [no annex'ed content]
uninstall(ok): D:\datasets.datalad.org\openfmri (dataset)
drop(notneeded): D:\datasets.datalad.org [no annex'ed content]
remove(ok): D:\datasets.datalad.org (dataset)
action summary:
  drop (notneeded: 2, ok: 2)
  remove (ok: 1)
  uninstall (ok: 2)

D:\>
````

### CODE REVIEW

**Comment by bpoldrack** [comment]
Retrying to rmtemp during `get` is still not sufficient in my case, but otherwise works for me, too.

**Comment by mih** [comment]
It took longer than 5s for you? Jeez, I thought 5s would be extreme.

**Comment by bpoldrack** [comment]
Can't tell. Even doubling to 10s doesn't solve the issue for me. But the approach solved it for you, so it's still an improvement.
Don't know yet, whether there's something else wrong with it.

**Comment by yarikoptic** [comment]
Is there a way, like lsof, to see who is holding it? Would forcing a run of gc help (ie if it is something not yet purged within current process)?

**Comment by bpoldrack** [comment]
Hehe - forget what I said. All of it. It works. :-)
While I checked out this branch, that simply wasn't what was used when I called datalad from the shell.

**Pull request merged**
