### PR TITLE
BF: fixing  (with Ben"s help) for the bugs with unicode and doctest in borrowed code

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by mih** [comment]
LGTM

**Comment by bpoldrack** [comment]
Failing test is real in the build with extensive logging.

**Comment by yarikoptic** [comment]
Failing one
```=========================
FAIL: datalad.distribution.tests.test_create_sibling.test_failon_no_permissions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 847, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 593, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 593, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_create_sibling.py", line 425, in test_failon_no_permissions
    sshurl="ssh://localhost" + opj(target_path, 'ds'))
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1174, in new_func
    % cml.out
AssertionError: Expected no errors to be logged, but log output is [ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
[ERROR] stderr| Master running (pid=31219)
```

**Comment by yarikoptic** [comment]
grr.. do not quite get how I could have brought those additional stderr messages with my changes (may be it is new annex coincidentally?) and can't reproduce the last one on my laptop to at least figure out which ssh call causes it... since Ben you had more luck with those locale-specific ones -- does this one fail for you?
```shell
DATALAD_TESTS_SSH=1 DATALAD_LOG_LEVEL=2 DATALAD_LOG_TARGET=/tmp/debug-log.txt DATALAD_LOG_CMD_OUTPUTS=1 nosetests -s -v datalad/distribution/tests/test_create_sibling.py:test_target_ssh_since
```
?

**Comment by yarikoptic** [comment]
ah @bpoldrack -- forgot to buzz you in above msg ;-)

**Comment by yarikoptic** [comment]
my plan for today is to manage address those failures one way or another, merge, release 0.8.1 ;)  objections @datalad/developers ? ;)

**Pull request merged**
