### PR TITLE
BF: Force git-annex to commit the changes before we interrogate git-annex branch

### PR DESCRIPTION
**Pull request by yarikoptic**
The use case was detected while working on
https://github.com/datalad/datalad-crawler/pull/112
to accompany
https://github.com/datalad/datalad/pull/6105 .

Due to use of alwayscommit = False to minimize number of initial commits,
the repository ended up in a "peculiar" state with no useful commits
in git-annex branch -- all changes were staged within git-annex to be
committed "eventually".

Although we could have easily "fixed" the test in datalad-crawler,
I consider the approach of going around git-annex commands to interrogate
git-annex metadata to be fragile, in particular for such a case as here:
some other command could have been ran in alwayscommit=false mode, and
information in git-annex branch might not yet reflect actual state of
git-annex.  Ideally we should avoid doing such "going around git-annex".
As a quick resolution I have decided to just trigger a possible commit
by running  git-annex info --fast.  But may be there is a better/cheaper
way to trigger git-annex to commit, @joeyh?

Questionable change is the expansion of call_annex interface.  Could be
avoided through monkey patching of self.always_commit for that call,
but that would be more ugly IMHO

FWIW
- I have looked at few other uses of `call_git` within annexrepo -- those seems to be ok, since do not stick their fingers into git-annex'es "privates".

### CODE REVIEW

**Review by mih — COMMENTED** [review]
I feel a bit dizzy.

We had a repo property (set by `__init__`).

Now we have `call_annex()` method parameters to override this, for some methods, not all.

And we now unconditionally enable it for an additional call to `info --fast`, only to discard its output in `get_special_remotes()`.

This all seems to complement the approach taken in `addurls` to override the `always_commit` value (assuming that that implementation also wanted to have this repo behavior be configurable?).

This seems rather twisted.

If I understand the use case description correctly, the situation that this PR is trying to address is intentionally created by a user. Which makes me wonder why that same user cannot stop this non-committing mode, as soon as they seem to start require commits to exist?

**Comment by joeyh** [comment]
Oh, I see you're reading git-annex:remote.log directly.

So, options are:

* Use git-annex merge or something like that to get the journal committed to
  the branch before reading from it. (A git-annex merge --only-annex
  that avoids merging the master branch would be ideal, IIRC I've
  considered adding that before.)
* Read .git/annex/journal/remote.log yourself, if it's present,
  and concat it to git-annex:remote.log to see the same thing git-annex
  will later commit.
* Add a new query command to git-annex to get whatever information you
  are reading from remote.log.

-- 
see shy jo

**Comment by yarikoptic** [comment]
>  This seems rather twisted.

yeah, I also dislike it.

> the situation that this PR is trying to address is intentionally created by a user. Which makes me wonder why that same user cannot stop this non-committing mode, as soon as they seem to start require commits to exist?

every state of *Repo is created by a user via "standard" interfaces of *Repos.  Whenever some method is not providing correct return value due to how it is implemented (e.g. by digging through git-annex branch "manually" without awareness of `.git/annex/journal`, instead of using `git annex` commands to provide that information) -- it is IMHO a bug in the software implementation of those interfaces.

> * Read .git/annex/journal/remote.log yourself, if it's present, and concat it to git-annex:remote.log to see the same thing git-annex will later commit.

I guess if we are to keep digging through git-annex privates, this might be as a *gentle* approach indeed.  Some archaeological expedition is probably due to see why we aren't just calling out to `git annex info --json --fast` (yet to check if it would provide expected output even if ran with `-c alwayscommit=false`)

**Comment by joeyh** [comment]
Your parsing of remote.log is also slightly buggy in that it does not consider
timestamps, so it may choose an old version of a remote's config rather
than the current version.

Also reading .git/annex/journal/ will miss configs of private remotes,
which are stored in a separate journal and never reach the git-annex
branch.

Extending git-annex info to get the information you need seems like the
best way to me, although we'd need to discuss just what that information
is and the best way to do it.

-- 
see shy jo

**Comment by yarikoptic** [comment]
FWIW, use of `cat-file` to get a list of special remotes was introduced in 4a4b2245bbf75fb274acc0bec2a1c69dcc439087 as part of #1644 in 2017. `annex info` information is insufficient replacement since `get_special_remotes` returns record with all the parameters of the remote (encryption, type, etc).

@joeyh - is there another `git-annex` command which would show details of the special remotes git annex knows about?

**Comment by joeyh** [comment]
There is no other command, but you can git-annex info about specific uuids of remotes and get information like "type" and "encryption".

One thing I don't want git-annex info uuid to do is dump out sensitive information like cipher= from remote.log.

**Comment by yarikoptic** [comment]
> Read .git/annex/journal/remote.log yourself, if it's present, and concat it to git-annex:remote.log to see the same thing git-annex will later commit.

implemented in https://github.com/datalad/datalad/pull/6135 which replaces this PR

**Pull request closed without merging**
