### PR TITLE
WIP: RF: new decorator approach

### PR DESCRIPTION
**Pull request by bpoldrack**
DON'T MERGE

This is preparing the evaluation of return values using a decorator and related stuff by developing the basic mechanisms. It will be integrated in PR #1350 

- [x] first, make use of the replacement for `functools.wraps` in order to allow for additional decorators for our commands
- [x] provide a rudimentary decorator for dealing with return values
- [x] solve python 3 issues
- [x] enhance `eval_results` to be able to receive its own arguments
- [x] additional decorator to build the docstrings right there instead of during import of `datalad.api`
- [ ] RF to use build_doc everywhere and remove that part from `datalad.api._generate_api`

### CODE REVIEW

**Comment by bpoldrack** [comment]
Changed to WIP again, since PY3 will take a little bit more time than expected

**Comment by bpoldrack** [comment]
Note: build_doc decorator approach doesn't really work yet. If we do it in the part that's executed when decorated function is called, we do it over and over again and the docstring is available after first execution only.
If we do it in the part that's executed when the decorator is applied, the class we need to read from is being build in this very moment and not available from the module yet.

**Comment by bpoldrack** [comment]
Re my comment above:

Solved, I think. For building the docs, we need to decorate the class instead of its `__call__` method.

**Comment by bpoldrack** [comment]
Except for RF'ing to make use of these solutions, that's it for now, I think.
Since this PR is for showing the mechanics and will go into #1350 , this might be a good point to have a look at the diff and check out how it works and is supposed to be used, @mih , @yarikoptic .

**Comment by bpoldrack** [comment]
Note, that failure is again a single build which terminated during setup. Seems to happen to random travis builds ATM.

**Comment by yarikoptic** [comment]
note that it needs merge conflicts addressed

**Comment by mih** [comment]
Given the enormity of #1350 s diff. I am not absolutely confident that all of these changes went into #1350. @bpoldrack can you give a second opinion? If they are all in, we could close this.

**Comment by bpoldrack** [comment]
Second opinion: I'm confident it's all in there.

**Pull request closed without merging**
