### PR TITLE
ENH: Prefer structured over rendered CommandError info

### PR DESCRIPTION
**Pull request by mih**
CommandError(msg=) was abused to obfuscate information on
cwd etc. Now these are dedicated properties, and a comprehensive
str representation is rendered at the latest possible stage,
avoiding intermediate overhead.

Turns

```
% datalad create blowup --bare
[INFO   ] Creating a new annex repo at /tmp/blowup
CommandError: command '['git', '-c', 'annex.largefiles=nothing', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', '--', '.gitattributes']' failed with exitcode 128
Failed to run ['git', '-c', 'annex.largefiles=nothing', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', '--', '.gitattributes'] under '/tmp/blowup'. Exit code=128. out= err=fatal: this operation must be run in a work tree

stdout=
stderr=fatal: this operation must be run in a work tree

fatal: this operation must be run in a work tree
```

into

```
% datalad create blowup --bare
[INFO   ] Creating a new annex repo at /tmp/blowup
CommandError: 'git -c annex.largefiles=nothing add --dry-run -N --ignore-missing --verbose -- .gitattributes' failed with exitcode 128 under /tmp/blowup
fatal: this operation must be run in a work tree
```

### CODE REVIEW

**Comment by yarikoptic** [comment]
Looks better. But I am surprised that it is neither in `ERROR` log message nor in the `(error)` results renderer.

<details>
<summary>like in other examples with clone or create (duplication of msg between ERROR log and results renderer aside)</summary> 

```shell
$> datalad clone ///asdlkfj  
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                                                                                                                                     
| - http://datasets.datalad.org/asdlkfj
  CommandError: command '['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj', '/tmp/asdlkfj']' failed with exitcode 128
Failed to run ['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj', '/tmp/asdlkfj'].
stdout=
stderr=Cloning into '/tmp/asdlkfj'...
fatal: repository 'http://datasets.datalad.org/asdlkfj/' not found

- http://datasets.datalad.org/asdlkfj/.git
  CommandError: command '['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj/.git', '/tmp/asdlkfj']' failed with exitcode 128
Failed to run ['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj/.git', '/tmp/asdlkfj'].
stdout=
stderr=Cloning into '/tmp/asdlkfj'...
fatal: repository 'http://datasets.datalad.org/asdlkfj/.git/' not found
 [install(/tmp/asdlkfj)] 
install(error): /tmp/asdlkfj (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- http://datasets.datalad.org/asdlkfj
  CommandError: command '['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj', '/tmp/asdlkfj']' failed with exitcode 128
Failed to run ['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj', '/tmp/asdlkfj'].
stdout=
stderr=Cloning into '/tmp/asdlkfj'...
fatal: repository 'http://datasets.datalad.org/asdlkfj/' not found

- http://datasets.datalad.org/asdlkfj/.git
  CommandError: command '['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj/.git', '/tmp/asdlkfj']' failed with exitcode 128
Failed to run ['git', 'clone', '--progress', 'http://datasets.datalad.org/asdlkfj/.git', '/tmp/asdlkfj'].
stdout=
stderr=Cloning into '/tmp/asdlkfj'...
fatal: repository 'http://datasets.datalad.org/asdlkfj/.git/' not found
]

$> datalad create /buga        
[INFO   ] Creating a new annex repo at /buga 
[ERROR  ] [Errno 13] Permission denied: '/buga' [os.py:makedirs:221] (PermissionError) 
```
</details>

**Comment by mih** [comment]
> But I am surprised that it is neither in `ERROR` log message nor in the `(error)` results renderer.

The demo that I picked isn't a regular or anticipated failure. It is a crash, hence there is nothing that sees this until the top-level catch-all.

**Comment by yarikoptic** [comment]
> The demo that I picked isn't a regular or anticipated failure. It is a crash, hence there is nothing that sees this until the top-level catch-all.

yeap, and I thought that we are catching all of those, unless in `--dbg` mode...  and we do, but `CommandError` (and `InsufficientArgumentsError`, `IncompleteResultsError`) have their own dedicated "handling" apparently: https://github.com/datalad/datalad/blob/master/datalad/cmdline/main.py#L533 (right at the point where you modifying it). I guess we might want to unify it (I see only `InsufficientArgumentsError` needing to behave separately since it is the only one due to "user mistake") later on to unify handling e.g. for https://github.com/datalad/datalad/issues/3649 .

**Comment by mih** [comment]
No idea how this change can impact the NFS test only...

```
======================================================================
1179ERROR: datalad.support.tests.test_annexrepo.test_dropkey(True,)
1180----------------------------------------------------------------------
1181Traceback (most recent call last):
1182  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
1183    self.test(*self.arg)
1184  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 588, in newfunc
1185    rmtemp(d)
1186  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 521, in rmtemp
1187    rmtree(f, *args, **kwargs)
1188  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 434, in rmtree
1189    _rmtree(path, *args, **kwargs)
1190  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 1882, in wrapped
1191    return f(*args, **kwargs)
1192  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 1922, in _rmtree
1193    return shutil.rmtree(*args, **kwargs)
1194  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 480, in rmtree
1195    _rmtree_safe_fd(fd, path, onerror)
1196  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 418, in _rmtree_safe_fd
1197    _rmtree_safe_fd(dirfd, fullname, onerror)
1198  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 418, in _rmtree_safe_fd
1199    _rmtree_safe_fd(dirfd, fullname, onerror)
1200  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 418, in _rmtree_safe_fd
1201    _rmtree_safe_fd(dirfd, fullname, onerror)
1202  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
1203    onerror(os.unlink, fullname, sys.exc_info())
1204  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
1205    os.unlink(name, dir_fd=topfd)
1206OSError: [Errno 16] Device or resource busy: '.nfs00000000002b02bc0000020b'
1207
1208
```

Same for the windows failure:

```
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_find_batch_equivalence
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\utils.py", line 588, in newfunc
    rmtemp(d)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 521, in rmtemp
    rmtree(f, *args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 434, in rmtree
    _rmtree(path, *args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 1882, in wrapped
    return f(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 1922, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\shutil.py", line 404, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\datalad_temp_tree__pqsunvu'
```

**Comment by yarikoptic** [comment]
indeed, eyeballed the diff and didn't spot anything obvious which could have left a process holding that path.  There is a helper mode `DATALAD_ASSERT_NO_OPEN_FILES` but not sure it would be of help here to pin it down :-/

**Comment by yarikoptic** [comment]
<details><summary>FWIW, NFS issue replicates locally:</summary>

```shell
$> python -m nose -s -v datalad/support/tests/test_annexrepo.py:test_dropkey
datalad.support.tests.test_annexrepo.test_dropkey(False,) ... ok
datalad.support.tests.test_annexrepo.test_dropkey(True,) ... ERROR
Versions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=7.20200204+git1-gb2c529b88-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.24.0 cmd:system-ssh=8.1p1 exifread=2.1.2 git=3.0.5 gitdb=2.0.6 humanize=0.5.1 iso8601=0.1.11 keyring=18.0.1 keyrings.alt=3.1.1 msgpack=0.5.6 mutagen=1.40.0 requests=2.21.0 wrapt=1.11.2
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' PATH='/home/yoh/gocode/bin:/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin:/home/yoh/.mutt/soft' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_dropkey(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 588, in newfunc
    rmtemp(d)
  File "/home/yoh/proj/datalad/datalad-master/datalad/utils.py", line 521, in rmtemp
    rmtree(f, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/utils.py", line 434, in rmtree
    _rmtree(path, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/utils.py", line 1882, in wrapped
    return f(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/utils.py", line 1922, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs0000000000fa337f00000013'
```
</details>

**Comment by yarikoptic** [comment]
hm, but not again!  right after initial attempt, started to redo and failed to replicate... heh heh

**Comment by yarikoptic** [comment]
oh, and there is already in the stack:
```
datalad/utils.py", line 1882, in wrapped
1191    return f(*args, **kwargs)
```
which comes from `try_multiple_dec`, so we are already trying multiple (3) times on linux and 50 on windows with interval of 0.1 sec. So the only thing which comes to mind is to double those numbers and see how it goes

**Comment by yarikoptic** [comment]
adb7d92 didn't help Windows, so I guess someone needs to figure it out properly :-/

**Comment by mih** [comment]
Windows tests are generally in a bad place right now. Will dig on a more global scale ...

**Pull request merged**
