### PR TITLE
BF(workaround): position --debug AFTER other annex_options

### PR DESCRIPTION
**Pull request by yarikoptic**
Issue filed within annex: https://git-annex.branchable.com/bugs/--debug_is_not_in_effect_if_precedes_-c/

verified that works, no dedicated test

### CODE REVIEW

**Comment by yarikoptic** [comment]
said to be fix in git annex c089f395b0c7d6416a3d4f2bf3211404acfd5b0e .
CI fails here do not make sense in relation to the change, restarted two travis run and a run on windows actions, which had
```
======================================================================
ERROR: datalad.tests.test_utils.test_get_open_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\utils.py", line 586, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\test_utils.py", line 1206, in test_get_open_files
    eq_(get_open_files(subd)[op.realpath(subd)].pid, proc.pid)
KeyError: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\datalad_temp_tree_s2oxmdpy\\d'
```
failure

**Comment by kyleam** [comment]
LGTM.  Do you want to rebase it to maint?

**Comment by yarikoptic** [comment]
If you could CP into `maint`, I am even ok to close this PR without merging.  I assume that `maint` would get a merge into `master` at some point.  Please proceed in your preferred way

**Comment by yarikoptic** [comment]
BTW, given now present `maint` branch, my milestone allocations to `0.12.3` probably wouldn't be "factual" since likely `maint` would get released as `0.12.3`.  i have moved majority of issues and prs into 0.12.x milestone, while leaving some open PRs allocated to `0.12.3` (although not all are on top of `maint`).  Please reassign as you see fit, or reassign other possibly merged PRs into 0.12.3 as what we would like to see in maint and released along with 0.12.3

**Pull request merged**
