### PR TITLE
RF: Suppress similar repeated messages in the default result renderer

### PR DESCRIPTION
**Pull request by mih**
Saving a dataset with a 1000 files will now look like this:

```
% datalad save
add(ok): 1 (file)
  [999 similar messages have been suppressed]
save(ok): . (dataset)
action summary:
  add (ok: 1000)
  save (ok: 1)
```

Failing to get a 1000 files looks like this (with `datalad.log.result-level=debug`)

```
% datalad get .
Total (0 ok, 1000 failed out of 1000):   0%|                     | 0.00/3.89k [00:01<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 1000 failed

                                                                                             get(error): 1 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;      2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
  [999 similar messages have been suppressed]
action summary:
  get (error: 1000)
```

Without the config switch, the second example would still produce a
thousand additional log messages, because we still report every error
twice. I decided to not address this in the logger, because while I can
relatively safely suppress result rendering based on a handful of result
keys, it is unclear to me what threshold we would use for the logger.
In any case, this can be done later by someone who is still suffering
from those messages ;-)

Fixes gh-2620 in spirit.

### CODE REVIEW

**Comment by kyleam** [comment]
I think this looks great for the cases where there are a bunch of results, but it doesn't seem well suited for cases where you have a handful, especially two:

```
add(ok): one (file)                       
  [1 similar messages have been suppressed]
save(ok): . (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
```

What about letting the results through until some threshold (perhaps 15?) and then trimming after that?  If the threshold ends up bothering people, we could introduce a config option for it.

**Comment by mih** [comment]
> What about letting the results through until some threshold (perhaps 15?) and then trimming after that? If the threshold ends up bothering people, we could introduce a config option for it.

Good idea! Will do!

**Comment by kyleam** [comment]
This PR isn't a proper fix for gh-3868 (behavior when not connected to the internet), but, along the lines of your second example, this change should eliminate the flood of messages mentioned there, assuming `datalad.log.result-level=debug`.

**Comment by mih** [comment]
GitHub actions seem broken right now (several attempts). Will wait for appveyor and travis and then merge. The incremental change is only of cosmetic nature:

```
% datalad get .
Total (0 ok, 1000 failed out of 1000):   0%|                     | 0.00/3.89k [00:01<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 1000 failed                                                                                             get(error): 1 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;      2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 100 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;    2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 10 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;     2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 107 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;    2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 1000 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;   2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 11 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;     2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 110 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;    2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 113 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;    2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 112 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;    2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 108 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;    2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
get(error): 104 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;    2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
  [989 similar messages have been suppressed]
action summary:
  get (error: 1000)
```

**Comment by yarikoptic** [comment]
woohoo! Me & My terminal Love it
```
$> datalad save ...
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000001.dcm (file)                                                                                                                                                                    
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000002.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000003.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000004.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000005.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000006.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000007.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000008.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000009.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000010.dcm (file)
add(ok): 022-cmrr_mbep2d_bold-s1p2-3contrasts/000011.dcm (file)
  [2389 similar messages have been suppressed]
save(ok): . (dataset)
action summary:
  add (ok: 2400)
  save (ok: 1)
```

**Pull request merged**
