### PR TITLE
ENH: travis -- remove cron run with bad scrapy (of no concern here any longer)

### PR DESCRIPTION
**Pull request by yarikoptic**
Paid for 5 concurrent jobs plan, let's see if it works anyhow

### CODE REVIEW

**Comment by yarikoptic** [comment]
grr.. just a few days but sh.t already got loose and I do not see exactly how.  Underlying issue is

```
pygithub 1.54 has requirement requests<2.25,>=2.14.0, but you'll have requests 2.25.0 which is incompatible.
```
and we do have 2.24 installed with conda but then it does get upgraded somehow to 2.25 and of cause `pip` just complains but proceeds forward

```shell
$> wget -q -O- https://api.travis-ci.com/v3/job/451984843/log.txt | grep requests
Collecting package metadata (current_repodata.json): done                       
    - requests==2.24.0=py_0
  requests           pkgs/main/noarch::requests-2.24.0-py_0
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.25.0)
Collecting requests_ftp
  Downloading requests-ftp-0.3.1.tar.gz (7.8 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from requests>=1.2->datalad==0.13.5->-r requirements-devel.txt (line 7)) (2019.3.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from requests>=1.2->datalad==0.13.5->-r requirements-devel.txt (line 7)) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from requests>=1.2->datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.10)
Building wheels for collected packages: wrapt, jsmin, requests-ftp, pyperclip, httpretty, PyYAML, python-xmp-toolkit, duecredit, pypandoc, asv, gprof2dot, nose-timer, psutil, future
  Building wheel for requests-ftp (setup.py) ... done
  Created wheel for requests-ftp: filename=requests_ftp-0.3.1-py3-none-any.whl size=8173 sha256=ca7ef6d3f28f797e88024154a37f0dc03d0f887a4a066ac394bbfe927d168535
Successfully built wrapt jsmin requests-ftp pyperclip httpretty PyYAML python-xmp-toolkit duecredit pypandoc asv gprof2dot nose-timer psutil future
ERROR: pygithub 1.54 has requirement requests<2.25,>=2.14.0, but you'll have requests 2.25.0 which is incompatible.
...
```

so only then we fail in a good number of tests because pkg_resources refuses to import with conflicting versions.

@jwodder - do you see some obvious (but not too ad-hoc like force downgrading requests to 2.24 which might or not work anyways) workaround?

**Comment by jwodder** [comment]
@yarikoptic There's a chance this might make things worse, but ... it looks like you're not using the latest pip on Travis.  Pip had a major release yesterday that enables its new dependency resolver by default, so if you install & use that pip, the conflicting versions should be taken care of.

**Comment by yarikoptic** [comment]
ok, let's try to `pip install –upgrade pip`

**Comment by yarikoptic** [comment]
<details>
<summary>at least for now looks better -- it upgrades it to 2.25 at some point (as before) and then downgrades to 2.24</summary> 

```shell
$> wget -q -O- https://api.travis-ci.com/v3/job/452052791/log.txt | grep requests       
Collecting package metadata (current_repodata.json): done                       
    - requests==2.24.0=py_0
  requests           pkgs/main/noarch::requests-2.24.0-py_0
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.25.0)
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.25.0)
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.25.0)
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.25.0)
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.25.0)
Collecting requests>=1.2
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from requests>=1.2->datalad==0.13.5->-r requirements-devel.txt (line 7)) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from requests>=1.2->datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.10)
Collecting requests_ftp
  Downloading requests-ftp-0.3.1.tar.gz (7.8 kB)
Requirement already satisfied: idna<3,>=2.5 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from requests>=1.2->datalad==0.13.5->-r requirements-devel.txt (line 7)) (2.10)
Building wheels for collected packages: wrapt, asv, duecredit, future, gprof2dot, httpretty, jsmin, nose-timer, psutil, pypandoc, pyperclip, python-xmp-toolkit, PyYAML, requests-ftp
  Building wheel for requests-ftp (setup.py) ... done
  Created wheel for requests-ftp: filename=requests_ftp-0.3.1-py3-none-any.whl size=8173 sha256=348d61f1fb918057eafd0415fadbe07e3e294a8144aa85b1e918c90639135767
Successfully built wrapt asv duecredit future gprof2dot httpretty jsmin nose-timer psutil pypandoc pyperclip python-xmp-toolkit PyYAML requests-ftp
Installing collected packages: pycparser, cffi, wrapt, urllib3, pytz, MarkupSafe, jeepney, cryptography, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, SecretStorage, requests, pyjwt, Pygments, multidict, monotonic, lxml, Jinja2, imagesize, future, docutils, deprecated, babel, alabaster, yarl, whoosh, tqdm, sphinx, soupsieve, simplejson, PyYAML, PyGithub, patool, msgpack, keyrings.alt, keyring, jsmin, iso8601, humanize, fasteners, distro, citeproc-py, boto, appdirs, annexremote, vcrpy, sphinx-rtd-theme, requests-ftp, python-xmp-toolkit, python-dateutil, pyperclip, pypandoc, psutil, Pillow, nose-timer, mutagen, httpretty, gprof2dot, exifread, duecredit, datalad, BeautifulSoup4, asv
  Attempting uninstall: requests
    Found existing installation: requests 2.25.0
    Uninstalling requests-2.25.0:
      Successfully uninstalled requests-2.25.0
Successfully installed BeautifulSoup4-4.9.3 Jinja2-2.11.2 MarkupSafe-1.1.1 Pillow-8.0.1 PyGithub-1.54 PyYAML-5.3.1 Pygments-2.7.2 SecretStorage-3.3.0 alabaster-0.7.12 annexremote-1.4.5 appdirs-1.4.4 asv-0.4.2 babel-2.9.0 boto-2.49.0 cffi-1.14.4 citeproc-py-0.5.1 cryptography-3.2.1 datalad deprecated-1.2.10 distro-1.5.0 docutils-0.16 duecredit-0.8.0 exifread-2.3.2 fasteners-0.15 future-0.18.2 gprof2dot-2019.11.30 httpretty-1.0.3 humanize-3.1.0 imagesize-1.2.0 iso8601-0.1.13 jeepney-0.6.0 jsmin-2.2.2 keyring-21.5.0 keyrings.alt-4.0.1 lxml-4.6.2 monotonic-1.5 msgpack-1.0.0 multidict-5.0.2 mutagen-1.45.1 nose-timer-1.0.0 patool-1.12 psutil-5.7.3 pycparser-2.20 pyjwt-1.7.1 pypandoc-1.5 pyperclip-1.8.1 python-dateutil-2.8.1 python-xmp-toolkit-2.0.1 pytz-2020.4 requests-2.24.0 requests-ftp-0.3.1 simplejson-3.17.2 snowballstemmer-2.0.0 soupsieve-2.0.1 sphinx-3.3.1 sphinx-rtd-theme-0.5.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 tqdm-4.54.0 urllib3-1.25.11 vcrpy-4.1.1 whoosh-2.7.4 wrapt-1.12.1 yarl-1.6.3
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from datalad==0.13.5) (2.24.0)
Requirement already satisfied: requests>=1.2 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from datalad==0.13.5) (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from requests>=1.2->datalad==0.13.5) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from requests>=1.2->datalad==0.13.5) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages (from requests>=1.2->datalad==0.13.5) (2019.11.28)
Access to XMLHttpRequest at 'file:///ds222/.git/datalad/metadata/6666cd76f96956469e7be39d750cc7d9' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
  - requests: 2.24.0

```
</details>

**Comment by yarikoptic** [comment]
github actions aren't unhappy today in general, travis is happy now, so merging!

**Pull request merged**
