### PR TITLE
RF: Change ConfigManager.get() behavior for multiple identical key specs

### PR DESCRIPTION
**Pull request by mih**
Before this change, the values of all specifications of an identical key
were returned as a tuple. Now only the last value is returned, and
`get_all=True` has to be set to get the previous behavior.

Rationale: That a single value is returned is a sensible default
expectation. Valid use cases for multiple values are few, and require
custom handling in consuming code. The previous behavior would require
protection against the multi-value-return possibility all throughout
the code base. This switch is disruptive, but makes overall operation
more robust.

Fixes gh-2628
Fixes gh-4919

### CODE REVIEW

**Review by kyleam — COMMENTED** [review]
> Rationale: That a single value is returned is a sensible default
> expectation. Valid use cases for multiple values are few, and require
> custom handling in consuming code. The previous behavior would require
> protection against the multi-value-return possibility all throughout
> the code base. This switch is disruptive, but makes overall operation
> more robust.

That matches my view.  I think the number of potential bugs/errors this squashes outweighs any disruption.  And quickly checking the extensions, I didn't spot any callers that accounted for a possible tuple return value, though it'd be good to do a more thorough check.  (Perhaps the -neuroimaging test failure is related, though I didn't look closely yet.)

I've pushed some additional changes (most notably, making `getbool` go through `get`).  Of course feel free to drop anything you don't agree with.

The test failures on Travis seem to be in `test_create_github.test_integration1_datalad_tester_org`.  I'm not sure if that's related.

**Comment by mih** [comment]
Thanks for the additional changes @kyleam I'd prefer to keep them all. I will try to have a look at the test failures later today.

**Comment by kyleam** [comment]
> And indeed, we explicitly rely on multi-value returns for configured GitHub access tokens. Pushed a fix.

Thanks.  The only failure now is the unrelated -container issue.

@bpoldrack Since we've discussed the single/multi-value config behavior in the past: does this direction look okay to you?

**Comment by bpoldrack** [comment]
> @bpoldrack Since we've discussed the single/multi-value config behavior in the past: does this direction look okay to you?

Yes, it does. In most cases only the "effective" config is relevant indeed and wherever we want to account for several we do know that this is spot where we need `get_all`. There is one piece still missing, I guess: We cannot have a "multi-config" that still allows to be overwritten by more specific config files (like: `~/.gitconfig` defines A and B, but I want to overwrite in `.git/config` by C and D). However, this doesn't become harder by this PR, so - perfectly fine with it.

**Comment by mih** [comment]
Ok, seems we're on the some page. Thx much!

**Pull request merged**
