### PR TITLE
ENH: Pass call args to results renderers (closes: gh-650)

### PR DESCRIPTION
**Pull request by hanke**

### CODE REVIEW

**Comment by hanke** [comment]
nd90 failure looks unrelated to actual changes in this PR

**Comment by yarikoptic** [comment]
nd90 - I guess PR want on top of current master and build bot doesn't merge it when testing

**Comment by yarikoptic** [comment]
Would need to get to laptop to actually see what is passed inside and merge...

**Comment by yarikoptic** [comment]
my experiment in #741 revealed another bug but showed that I was right and failure is simply due to not merged master... I guess I should reconfig buildbot to merge target branch for testing

**Pull request merged**
