### PR TITLE
ENH: Add parallel jobs options for `run` and `rerun` (applies to get, save)

### PR DESCRIPTION
**Pull request by AKSoo**
Implements #6118 . I have 2 questions.

- [x] How do I edit the docstring for `jobs_opt`? I think we need to make it clear that the parallelization only applies to input `get` and output `save`, or some people might get the idea that datalad can parallelize scripts for them.
- [ ] How do we test this option? It seems like the `ProducerConsumer` class for general parallelization is tested, but not the specific parallel options for `get` and `save`.

### CODE REVIEW

**Comment by bpoldrack** [comment]
> How do I edit the docstring for jobs_opt? I think we need to make it clear that the parallelization only applies to input get and output save, or some people might get the idea that datalad can parallelize scripts for them.

Good question. I don't think we do that anywhere (other than may be mentioning applicability in the command's docstring rather than the parameter's). The `Parameter` class isn't fit for modifications, indeed. However, it might be better to come up with a clearer wording for the general option instead. While for `run` it may be particularly misleading, it's a bit vague in general.

**Comment by mih** [comment]
> * How do I edit the docstring for `jobs_opt`? I think we need to make it clear that the parallelization only applies to input `get` and output `save`, or some people might get the idea that datalad can parallelize scripts for them.

Take a look at: https://github.com/datalad/datalad/blob/dbc34478980c808a86b5531316c986abac953e37/datalad/distributed/create_sibling_github.py#L187

You can use this approach to easily amend a docstring with a follow-up statement. Maybe that is already sufficient.

**Comment by AKSoo** [comment]
I appended a NOTE to the docstring.

As for my second question, I guess testing multiprocessing might be unnecessary and/or too difficult to unit test? If so, I would appreciate if someone could personally try the PR and double-check that both `get` and `save` use multiple jobs. I could only check by skimming debug logs.

**Review by mih — COMMENTED** [review]
The diff looks good to me, thanks! I will give it a spin later today.

**Comment by mih** [comment]
I can confirm that both `get` and `save` receive the `--jobs` specification and properly act on it.

Brief note on the impact:

The `get` operation works as one would expect, it gets multiple files at once. This is not the case for save (i.e., it does not save/add multiple files at once). In https://github.com/datalad/datalad/commit/a0bb0ef60086ea4a617549085a88a16215863119 @yarikoptic implemented parallelization for `save`, but only across datasets. In other words, if there are to-be-saved files in multiple subdatasets, these subdatasets would be saved in parallel.

Unfortunately, this is a bit of a special case. For the common case (read from subdatasets, write to top-level dataset) no parallelization is performed.

This could be easily added (by altering `save` to pass on the jobs value to the underlying `Repo` methods). However, with that dataset-parallelization in place we cannot do that in a straightforward fashion, because the `--jobs` would multiply (e.g., 4 files in 4 datasets simultaneously). I am afraid that this will need a bit of coordination first.

However, this is outside the scope of this PR (needs a `save`-internal change), hence I will merge it now.

Thanks again!

**Pull request merged**
