### PR TITLE
BF/Win: Towards a working creating sibling command

### PR DESCRIPTION
**Pull request by adswa**
There are a range of issues with create sibling (see #5211) and I'm not sure if it is possible possible to make it work, but I at least wanted to start.

- [x] use ``mkdir`` without -p on Windows
- [x] prevent failure due to not recognizing ``|| :`` as a command

### CODE REVIEW

**Comment by yarikoptic** [comment]
Looks lgtm to me. I already forgot - nobody should care about windows in maint? If we still do, rebase is desired

**Comment by adswa** [comment]
> nobody should care about windows in maint? If we still do, rebase is desired

ah, damn, I keep forgetting to think about which base to use :-) I will rebase

**Comment by kyleam** [comment]
@adswa I believe the Travis builds failures are because you rebased/pushed then changed the base on the web interface, rather than the other way around.  A force-push of a noop change should sort it out.

**Comment by adswa** [comment]
> @adswa I believe the Travis builds failures are because you rebased/pushed then changed the base on the web interface, rather than the other way around. A force-push of a noop change should sort it out.

I swear at one point I manage to do it in the correct order. Thx! Pushed an empty commit.

**Review by kyleam — APPROVED** [review]

**Pull request merged**
