### PR TITLE
`save` update, fix bug, test intended behavior, improve docs

### PR DESCRIPTION
**Pull request by mih**
#### What is the problem?
well -- we have `add` to add stuff, which also `saves`.  git allows for a convenient "commit ." which saves all changes in the current sub directory, so I thought that it would only make sense to call "datalad save -m msg ."... to my surprise it added all kinds of stuff which it should have not!

#### What steps will reproduce the problem?

```shell
hopa:~
$> datalad create /tmp/repro
[INFO   ] Creating a new annex repo at /tmp/repro 
create(ok): /tmp/repro (dataset)                                                 
(dev3) 2 13324.....................................:Mon 18 Dec 2017 09:47:55 PM EST:.
hopa:~
$> cd /tmp/repro
(dev3) 2 13325.....................................:Mon 18 Dec 2017 09:47:56 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> touch 1 2 3
(dev3) 2 13326.....................................:Mon 18 Dec 2017 09:48:03 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> datalad add -m added\ 1 1
add(ok): /tmp/repro/1 (file)00:00, ?B/s]                                         
save(ok): /tmp/repro (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
(dev3) 2 13327.....................................:Mon 18 Dec 2017 09:48:16 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> rm 1; echo 2>1

(dev3) 2 13328.....................................:Mon 18 Dec 2017 09:48:28 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> ls -l
total 0
-rw------- 1 yoh yoh 0 Dec 18 21:48 1
-rw------- 1 yoh yoh 0 Dec 18 21:48 2
-rw------- 1 yoh yoh 0 Dec 18 21:48 3
(dev3) 2 13329.....................................:Mon 18 Dec 2017 09:48:31 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> datalad save -m "123" .
save(ok): /tmp/repro (dataset)                                                   
(dev3) 2 13330.....................................:Mon 18 Dec 2017 09:48:40 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> git show --stat
commit 58562e29e3f3469f5e8b7b3f176dafe8044d6ad0 (HEAD -> master)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Mon Dec 18 21:48:40 2017 -0500

    123

 2 | 1 +
 3 | 1 +
 2 files changed, 2 insertions(+)
(dev3) 2 13331.....................................:Mon 18 Dec 2017 09:48:43 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> ls -l 
total 12
lrwxrwxrwx 1 yoh yoh 108 Dec 18 21:48 1 -> .git/annex/objects/2W/kW/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e
lrwxrwxrwx 1 yoh yoh 108 Dec 18 21:48 2 -> .git/annex/objects/2W/kW/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e
lrwxrwxrwx 1 yoh yoh 108 Dec 18 21:48 3 -> .git/annex/objects/2W/kW/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e
```
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
current master: 0.9.1-521-gf16f652d

### CODE REVIEW

**Comment by mih** [comment]
I pushed a fixed for the second part of the problem. Now it needs a test that also covers the original case.

**Comment by mih** [comment]
@bpoldrack is there any way to have a bit of test code to say "this should be untracked, this should not" without having to care what mode a repo is in? If I leave out 'staged' it fails in v5, if I put it in it fails in direct mode

https://travis-ci.org/datalad/datalad/jobs/367594201

I guess I go with the fashion and disable any test for direct mode...

**Comment by bpoldrack** [comment]
It's supposed to work the way, you did it. What seems buggy to me actually is the failing in V5. Looking into it ...

**Comment by mih** [comment]
I will now detach from this issue, as I do not feel confident deciding what should be happening. The core issue is that `datalad save .` commits untracked content. The OP thinks this is not OK, presumably because a `git commit .` wouldn't do it.  However, `save` is not just `commit`, as a quick demo (modified from above) shows -- the key is the last call:

```
(datalad3-dev) mih@meiner /tmp % datalad create /tmp/repro
[INFO   ] Creating a new annex repo at /tmp/repro 
create(ok): /tmp/repro (dataset)                                                             
(datalad3-dev) mih@meiner /tmp % cd /tmp/repro
(datalad3-dev) mih@meiner /tmp/repro (git)-[master] % touch 1 2 3
(datalad3-dev) mih@meiner /tmp/repro (git)-[master] % datalad add -m added\ 1 1
add(ok): /tmp/repro/1 (file)              
save(ok): /tmp/repro (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
(datalad3-dev) mih@meiner /tmp/repro (git)-[master] % rm 1; echo 2>1



(datalad3-dev) mih@meiner /tmp/repro (git)-[master] % git st
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        typechange: 1

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        2
        3

no changes added to commit (use "git add" and/or "git commit -a")
(datalad3-dev) mih@meiner /tmp/repro (git)-[master] % git commit .
git-annex: Cannot make a partial commit with unlocked annexed files. You should `git annex add` the files you want to commit, and then run git commit.
```

Hence we have to call `add`, but given the input of `path='.'` we cannot simply call `add('.')` this is the current behavior reported as a bug. In order to emulate `git commit` as much as possible, we would have to `diff` against HEAD and `add` anything that it reports (possibly discovering a slew of corner cases, and maybe even the reason why annex makes `git commit .` behave this way).

At the same time we have

```
  -u, --all-updated     if no explicit paths are given, save changes of all
                        known components in a datasets. [Default: True]
  -a, --all-changes     save all changes (even to not yet added files) of all
                        components in datasets that contain any of the given
                        paths [DEPRECATED!]. [Default: None]
```

(confusing docs of `-u` wrt to the default BTW). Presumably, `-a` maps to `path='.'` plus no `diff` constraint (current behavior). Not sure what `all_updated=False, path='.'` should do? Maybe it is the same as `-a`, but if so, why even support it when we have `add('.')`. ATM it cannot even be used from the cmdline -- possibly an indication that is should be removed altogether.

@bpoldrack @yarikoptic @kyleam What do you think?

**Comment by bpoldrack** [comment]
Re direct mode:
It's actually not about "this should be untracked, this should not", but about "this should be staged", which is an invalid concept in direct mode.
If the assertion really is about what's untracked, just don't specify what is supposed to be staged, but only what should (still) be untracked. So, leaving it out, would be the way to go, but: we have comparable states for direct/indirect mode only AFTER commit. Before that, they are simply conceptionally different.

**Comment by mih** [comment]
> But there is another way. You can use ok_file_under_git with annexed=True to confirm it was added, regardless of mode.

So maybe that is what `ok_clean_git()` should do for `staged=` in direct mode? Because it make little sense to be to project this logic into any test that uses `ok_clean_git()` in this way. Which would also mean that we should find a better name for `staged` that captures both states in V5 and direct mode. Maybe `known_to_git`?

**Comment by bpoldrack** [comment]
Re second to last:
I said AFTER commit. You call it on the uncommitted/unsaved thing. ;-)

Re last comment:
Agree. We can do it that way and we then should also agree to not have arguments for `ok_clean_git`, that are called "head_modified", "index_modified" as I said long ago. ;-)
May be just "known" (to the repo) to not confuse it with helpers/parameters that use "to_git" to distinguish things known to git and known to annex.

**Comment by mih** [comment]
> I said AFTER commit. You call it on the uncommitted/unsaved thing.
They call it testing the test pre-condition ;-) So you are basically saying, don't test the starting point. I don't think that counts as a solution...

**Comment by kyleam** [comment]
Re: `datalad save .` expectations, mine match what @bpoldrack describes in his last comment: save everything, including untracked.  Perhaps that's because I've never used `git commit .`.

**Comment by mih** [comment]
Thanks for your input. I do see these points, too.

However, I feel like this is too muddy on a conceptual basis. Two things:

1. For the purpose of the 0.10 release, I think the current behavior should be documented in a dedicated test (the currently broken one with minimal adjustment would be fine), and in the docs of `save` -- with no further change to the actual behavior of `save` (and #2426 needs fixing, of course).

2. For the next iteration, I'd like to do an assessment of the respective roles of `add` and `save`. Their functionality is massively overlapping with surprisingly different code paths. User-facing differences are: `add` has `--to-git`, while `save` has `--version-tag`, but that is about it.

My hunch is that we should merge the two into a single `save` command that largely behaves like the current `add(save=True)`, but with the remaining features of `save`, namely: `--version-tag` and `--all-updated=True`. Power-users always have `git add` and `git annex add` at their disposal to achieve everything that `save` might be to blunt of an instrument for -- although I cannot yet see what would be missing...

**Comment by mih** [comment]
Conclusion now implemented as code. Let's see what the tests say...

**Comment by bpoldrack** [comment]
> My hunch is that we should merge the two into a single save command that largely behaves like the current add(save=True), but with the remaining features of save, namely: --version-tag and --all-updated=True. Power-users always have git add and git annex add at their disposal to achieve everything that save might be to blunt of an instrument for

Sounds reasonable to me.

Re V6:
I think the failure actually is "correct", since in V6 the test results in something different. This is because in V6 the state of the file (unlocked/locked) is committed as well, and the test doesn't lock the file again. The assertion passes, if you call `git annex lock 1` before the call to `save`.

**Comment by bpoldrack** [comment]
Since this test is supposed to test the behaviour of `save`, I think in this case it's really the test itself, that needs to consider V6 and in this case additionally lock the file. It shouldn't neither be `save` that behaves differently here nor `ok_clean_git`.

**Comment by mih** [comment]
> The assertion passes, if you call git annex lock 1 before the call to save.

Which conveniently skips over the fact that we do not even have a function in the API that does that ;-)

Anyways, I found in the file a rather convenient paradigm to deal with this: adhoc functional call decorators:

```
known_failure_v6(ok_clean_git)(ds.path, untracked=['2', '3'])
```

I'll try to use this more often, instead of disabling entire tests.

**Comment by bpoldrack** [comment]
> Which conveniently skips over the fact that we do not even have a function in the API that does that ;-)

:-) I know, it's available on `AnnexRepo` level, but not on `Dataset` level.

However, skipping just that assertions might do for now.

**Comment by bpoldrack** [comment]
Ah - hold on. This "pattern" was used in generic tests (which yield test functions to be discovered by nose). And in those tests it's fine. But: The decorator raises `SkipTest`, which I think means, that whatever comes after that call within your test, will not be executed.

**Comment by bpoldrack** [comment]
I'd suggest to change the decorator, so it can optionally be used the way, you want to use it (Just passing and not considering a potential failure in the decorated function).
Agree to that approach?

**Pull request merged**
