### PR TITLE
Exit right away with non-0 and a message when operating from a non-existing directory

### LINKED ISSUE #3874: provide informative message when operating from a non-existing directory
We (git?) removes current directory whenever we `datalad remove` all files within it. Subsequent operation of datalad results in a scary tracebacks instead of a concise informative message or even doing what it was asked to do which relates to no directory (e.g. when asked for a `--version`):

```
(git-annex)lena:/tmp/testds[master]subdir
$> datalad remove --nocheck *
remove(ok): subdir/1
remove(ok): subdir/2
save(ok): /tmp/testds (dataset)
action summary:
  remove (ok: 2)
  save (ok: 1)

$> datalad --version
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/home/yoh/deb/gits/python-git/git/__init__.py", line 83, in <module>
    refresh()
  File "/home/yoh/deb/gits/python-git/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 224, in refresh
    cls().version()
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 689, in execute
    cwd = self._working_dir or os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev3/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 441, in main
    parser = setup_parser(args)
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 94, in setup_parser
    from ..interface.base import dedent_docstring, get_interface_groups, \
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 33, in <module>
    from datalad.interface.common_opts import eval_params
  File "/home/yoh/proj/datalad/datalad/datalad/interface/common_opts.py", line 15, in <module>
    from datalad.interface.results import known_result_xfms
  File "/home/yoh/proj/datalad/datalad/datalad/interface/results.py", line 28, in <module>
    from datalad.distribution.dataset import Dataset
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/dataset.py", line 29, in <module>
    from datalad.support.annexrepo import AnnexRepo
  File "/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py", line 43, in <module>
    from git import InvalidGitRepositoryError
  File "/home/yoh/deb/gits/python-git/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: [Errno 2] No such file or directory
```

```
$> cd /tmp/testds; datalad --version
datalad 0.11.8.dev16
```
and the same with 0.12.0rc6.dev92

### PR DESCRIPTION
**Pull request by yarikoptic**
Unfortunately AFAIK even --version cannot operate normally,
so better to exit with informative message right away if
CWD is cannot be determined

Closes #3874

### CODE REVIEW

**Comment by kyleam** [comment]
Hmm, `getpwd()` is already executed from `datalad/__init__.py`.  Would it be better to handle this there?

As of 4ec506f99 (BF: in case of PWD mode, even if operating under removed dir, report PWD, 2018-10-26, gh-2914), `getpwd()` makes sure we continue even if the current working directory doesn't exist [0]:

https://github.com/datalad/datalad/blob/bcf62fb2de1b15e4d2a32dac4fb39548e1b1e9e6/datalad/utils.py#L1439-L1446

But, given this PR, perhaps we'd want to issue the ui message from this PR there and then let the exception through?  That'd require moving the `getpwd()` call in `datalad/__init__.py` before the `ConfigManager`.

[0] ... though unlike this PR it doesn't do so in a py3-compatible way.

---

The appveyor failures are due to the added test:
```
======================================================================
ERROR: datalad.cmdline.tests.test_main.test_nonexisting_dir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmdline\tests\test_main.py", line 94, in test_nonexisting_dir
    rmtree(path)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 424, in rmtree
    _rmtree(path, *args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1885, in wrapped
    return f(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1925, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Miniconda35\envs\test-environment\lib\shutil.py", line 387, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Miniconda35\envs\test-environment\lib\shutil.py", line 385, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_qw7wx6g6'
```

**Comment by yarikoptic** [comment]
Thank you @kyleam for the analysis!  
I must confess that IIRC my decision to just fail in this PR was simply because I found (may be didn't dig deep enough into argparse) no other (better) way to make process not crash and ideally `--version` should not fail regardless of the PWD status. 

<details>
<summary>
 So I quickly checked on how to avoid it - and could be done by delaying some imports:
</summary>

```patch
commit 1c2d576c435853d4bbd0b0eebc0f7b8d07e16882
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Wed Nov 20 22:26:08 2019 -0500

    RF+OPT: Delay import of Dataset to avoid import of git
    
    git module does not tollerate being imported from a non-existing directory.
    Because of that, and prior import of Dataset through code path for trivial
    datalad --version invocation,  we would fail to report --version or --help
    in such cases.  Might be a bit too obnoxious, and apparently we already
    tollerate to some degree operation within non-present directories
    (see 4ec506f BF: in case of PWD mode, even if operating under removed dir,
    report PWD, 2018-10-26, gh-2914; thanks @kyleam for the find).
    
    By delaying those few imports of the Dataset we are apparently avoiding the
    whole code path leading to import of gitrepo and git modules, making
    --version almost twice speedier (90ms instead of 150ms).  But it nohow helps
    --help-np in terms of performance and only makes traceback even more horrid.

diff --git a/datalad/interface/base.py b/datalad/interface/base.py
index 4ec532bfa..255866407 100644
--- a/datalad/interface/base.py
+++ b/datalad/interface/base.py
@@ -33,8 +33,8 @@ from ..dochelpers import exc_str
 from datalad.interface.common_opts import eval_params
 from datalad.interface.common_opts import eval_defaults
 from datalad.support.constraints import EnsureKeyChoice
-from datalad.distribution.dataset import Dataset
-from datalad.distribution.dataset import resolve_path
+# Avoid imports here to avoid dragging GitRepo etc
+# from datalad.distribution.dataset import ...
 from datalad.plugin import _get_plugins
 from datalad.plugin import _load_plugin
 
@@ -662,6 +662,7 @@ class Interface(object):
     def get_refds_path(cls, dataset):
         """Return a resolved reference dataset path from a `dataset` argument"""
         # theoretically a dataset could come in as a relative path -> resolve
+        from datalad.distribution.dataset import Dataset, resolve_path
         if dataset is None:
             return dataset
         refds_path = dataset.path if isinstance(dataset, Dataset) \
diff --git a/datalad/interface/results.py b/datalad/interface/results.py
index 1d49184de..ab166ea31 100644
--- a/datalad/interface/results.py
+++ b/datalad/interface/results.py
@@ -25,8 +25,9 @@ from datalad.utils import with_pathsep as _with_sep
 from datalad.utils import path_is_subpath
 from datalad.support.path import robust_abspath
 
-from datalad.distribution.dataset import Dataset
 
+# Avoid imports here to avoid dragging GitRepo etc
+# from datalad.distribution.dataset import ...
 
 lgr = logging.getLogger('datalad.interface.results')
 lgr.log(5, "Importing datalad.interface.results")
@@ -136,6 +137,7 @@ class YieldDatasets(ResultXFM):
         if res.get('type', None) == 'dataset':
             if not self.success_only or \
                     res.get('status', None) in ('ok', 'notneeded'):
+                from datalad.distribution.dataset import Dataset
                 return Dataset(res['path'])
         else:
             lgr.debug('rejected by return value configuration: %s', res)
@@ -255,6 +257,7 @@ def is_result_matching_pathsource_argument(res, **kwargs):
     # we don't do any error checking here, done by the command itself
     source = kwargs.get('source', None)
     if source is not None:
+        from datalad.distribution.dataset import Dataset
         # we want to be able to deal with Dataset instances given as 'source':
         if isinstance(source, Dataset):
             source = source.path
```
</details>

but it is just the dust in the eyes since `Dataset` is a core concept and will get imported anyways for anything useful (beyond `--version`).

And with your pointer to old PR I now realize that it would contradict that previously given promise (to be robust and not crash), and I feel that making `--version` to not puke could be of value and consistency with git and git-annex operation (git annex shows getcwd erorr, but otherwise proceeds forward).  But the value of that "feature" is minor if any, so I will proceed with your recommendation and adjust PR to do check in `__init__.py`... pushed changes.

But when committing I realized how much ugliness in the `sys.exit(1)` in `__init__.py` of a python package, not sure if I like it at all ;-)!

**Comment by kyleam** [comment]
Thanks for the updates.  I haven't looked at them (or your comments above) closely, but just a comment on this:

> But when committing I realized how much ugliness in the `sys.exit(1)` in `__init__.py` of a python package, not sure if I like it at all ;-)!

Yeah, I agree that shouldn't be there. In my initial comment, I suggested letting the exception through.  What about doing that, or perhaps raising a dedicated exception?

**Comment by mih** [comment]
Closed due to inactivity.

**Pull request closed without merging**
