### PR TITLE
Remove with_testrepos from core package

### LINKED ISSUE #6752: Move `with_testrepos` to `deprecated`?
https://github.com/datalad/datalad/pull/6690 removes the last traces of its usage from the core package.

From my POV there are only few points of usage left across all extensions, and all in `deprecated`

```
./deprecated/datalad_deprecated/tests/test_auto.py:@with_testrepos('basic_annex', flavors=['clone'])
./deprecated/datalad_deprecated/tests/test_publish.py:@with_testrepos('submodule_annex', flavors=['local'])
./deprecated/datalad_deprecated/tests/test_publish.py:@with_testrepos('submodule_annex', flavors=['local'])  #TODO: Use all repos after fixing them
./deprecated/datalad_deprecated/tests/test_publish.py:@with_testrepos('basic_git', flavors=['local'])
./deprecated/datalad_deprecated/tests/test_publish.py:@with_testrepos('submodule_annex', flavors=['local'])
./deprecated/datalad_deprecated/tests/test_publish.py:@with_testrepos('submodule_annex', flavors=['local'])  #TODO: Use all repos after fixing them
./deprecated/datalad_deprecated/tests/test_publish.py:@with_testrepos('submodule_annex', flavors=['local'])
./deprecated/datalad_deprecated/tests/test_publish.py:@with_testrepos('submodule_annex', flavors=['local'])  #TODO: Use all repos after fixing them
./deprecated/build/lib/datalad_deprecated/tests/test_auto.py:@with_testrepos('basic_annex', flavors=['clone'])
```

We can either move `with_testrepos` into this extension and adjust the imports, or change those tests. In either case `with_testrepos` can be removed from the core package.

### PR DESCRIPTION
**Pull request by adswa**
Hopefully fixes #6752 and accompanies https://github.com/datalad/datalad-deprecated/pull/80. It rips out the `with_testrepos` decorator and associated tests for it. I committed in very small chunks in hopes to easier fix what I might accidentally break with this when the CI runs; I plan to squash things together when this turns out to work. 
:crossed_fingers: 

The last commit cleans up a few imports and removes imports that seemed unused.

### CODE REVIEW

**Review by bpoldrack — COMMENTED** [review]
Generally looks good to me.
However, considering the last time moving things to deprecated - could you temporarily commit a change in requirements, so that the two PRs (here and and in depreacted) are testing against each other rather than the released version of the other one, @adswa ?

Just `git+http://github.com/datalad/datalad@branch` in requirements-devel in datalad-deprecated and the same way of installing deprecated in the extension test workflow in here.

**Comment by bpoldrack** [comment]
Thanks, @adswa! Please go ahead!

**Comment by adswa** [comment]
In which order should this PR and the companion PR in deprecated be merged?

**Comment by bpoldrack** [comment]
@adswa:

> In which order should this PR and the companion PR in deprecated be merged?

Ideally deprecated first (+release), since otherwise we'd introduce CI failures with the extension tests here into master, affecting every PR.

**Comment by adswa** [comment]
DataLad deprecated now has ``with_testrepos`` and is released - merging.

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.18.0`](https://github.com/datalad/datalad/releases/tag/0.18.0)

**Pull request merged**
