### PR TITLE
Rel 0.11.4 planing

### PR DESCRIPTION
**Pull request by yarikoptic**
- [x] CHANGELOG (contributions/assistance is welcome; otherwise will do tomorow or so)
- [x] [PRs intended for 0.11.4](https://github.com/datalad/datalad/pulls?q=is%3Aopen+is%3Apr+milestone%3A"Release+0.11.4")
- [PRs "hoped" for  0.11.x and might still appear in the release](https://github.com/datalad/datalad/pulls?utf8=✓&q=is%3Aopen+is%3Apr+milestone%3A"0.11.x"+)
     - [x] https://github.com/datalad/datalad/pull/3184 - DueCredit -- not sure since might be destructive, no feedback received
     - [ ] https://github.com/datalad/datalad/pull/3180 - GitHub authentication -- would love to have but needs test(s|ing)

### CODE REVIEW

**Comment by kyleam** [comment]
>  CHANGELOG (contributions/assistance is welcome; otherwise will do tomorow or so)

I can do the initial pass today.

**Comment by kyleam** [comment]
> I can do the initial pass today.

Done.

<details>
<summary>Changes for 0.11.4</summary>

```
# Generated with
#   git log --format="?  %s%n   %h^-1" --reverse --first-parent 0.11.3..origin/0.11.x
#
#
# ?  = unprocessed and undecided
# -  = decided not to include
# +  = included
# +* = included, but might still be bits that should be added

-  Show must go on
   2606c7697^-1
-  Merge pull request #3172 from yarikoptic/enh-enable-appveyor
   905905915^-1
+  Merge pull request #3176 from yarikoptic/bf-gz-extract
   78b101144^-1
+  Merge pull request #3182 from kyleam/bf-read-tree-intrafs
   64cf06fbe^-1
-  ENH: Removed duplicate (and leading! ;)) Matteo from the past (Dartmouth)
   524f4d97c^-1
+  Merge pull request #3186 from mih/bf-3185
   143395732^-1
+  Merge pull request #3205 from driusan/Python3LorisAuthfix
   4842edc08^-1
-  BF(workaround): make _CRON job green by not caring to test upstream build of git annex
   901ab00ef^-1
+  Merge pull request #3210 from driusan/bf-annexificator
   5d7014599^-1
-  Merge pull request #3212 from kyleam/travis-nose-select
   05d357b61^-1
+  Merge pull request #3211 from yarikoptic/bf-3068
   8e2d1ab0e^-1
-  Merge pull request #3214 from yarikoptic/bf-nose-s
   176386e0f^-1
+  Merge pull request #3215 from yarikoptic/bf-fix-PWD-in-run
   d046e2b51^-1
+  Merge pull request #3220 from yarikoptic/bf-lzma-depends
   449f5075f^-1
+  Merge pull request #3222 from kyleam/search-no-hits-msg
   8f74e3bef^-1
+  Merge pull request #3223 from kyleam/run-tmpdir-placeholder
   c1fb9c6b8^-1
-  Merge pull request #3226 from yarikoptic/enh-from-master
   eef695115^-1
```

</details>

**Comment by yarikoptic** [comment]
Thank you @kyleam!

**Comment by kyleam** [comment]
I've updated the CHANGELOG to include recent PRs that were merged into maint and also ported the tools/link_issues_CHANGELOG  fixes from master.

<details>
<summary>Added entries</summary>

```
# Generated with
#   git log --format="?  %s%n   %h^-1" --reverse --first-parent eef695115..origin/0.11.x
#
#
# ?  = unprocessed and undecided
# -  = decided not to include
# +  = included
# +* = included, but might still be bits that should be added

+  Merge pull request #3184 from yarikoptic/enh_duecredit
   01821d193^-1
+  BF: do not cause a side-effect on kwargs in @eval_results (#3249)
   71d543ecd^-1
+  Merge pull request #3241 from yarikoptic/bf-meta-suggest-infofiles
   930f464bd^-1
+  Rename old constant, and define/use a few new ones to avoid hardcoded copies of the paths (#3250)
   3121766a1^-1
+  Merge pull request #3281 from kyleam/notty-no-progress
   8b61e8564^-1
```

</details>

**Comment by yarikoptic** [comment]
Thank you @kyleam !

I will kick out the release as soon as I bring back neuro.debian.net server back to its new life on datalad's web server

**Comment by kyleam** [comment]
It looks like you didn't push your local 0.11.x branch when you pushed the 0.11.4 tag.  I've pushed it now:

To github.com:datalad/datalad.git
   df0389465..22d9cb5e1  maint -> 0.11.x

**Comment by yarikoptic** [comment]
Thanks!
Fwiw, I didn't upload to NeuroDebian yet - need to finish migration first

**Pull request merged**
