### PR TITLE
UX: Have a proper error message (Closes #1359)

### LINKED ISSUE #1359: Incomprehensible error message of `remove`
````
$ datalad remove src/aligned 
[ERROR  ]  [uninstall.py:__call__:401] (AssertionError) 
````

but the actual remove operation works like charm.

### PR DESCRIPTION
**Pull request by bpoldrack**

### CODE REVIEW

**Comment by bpoldrack** [comment]
Failures: See PR #1277

**Comment by yarikoptic** [comment]
so I managed to bring some older versions of dockers up I guess for buildbot  -- I am upgrading them inplace again and then will rerun in those which failed

**Comment by bpoldrack** [comment]
Thanks! And: Good morning! :-)

**Comment by yarikoptic** [comment]
oh well --= upgraded but lazy to go restart them all one by one... travis passes and the line seems to be covered (although not sure if message is -- interested to know if python evaluates string even if no assertion failure)so let it be

**Pull request merged**
