### PR TITLE
BF: Webinterface

### PR DESCRIPTION
**Pull request by debanjum**
* Remove parent row `..` in webinterface root
* Use parent dataset type from parent metadata to color code `..` row

Closes: #917

### CODE REVIEW

**Comment by yarikoptic** [comment]
deployed it to datasets.datalad.org and .. actually came back at the top level! (left it hanging there for you to see).  colors of '..' in subdatasets look correct though - so we should be really close to breadcrumbs navigator, right? ;)

**Comment by debanjum** [comment]
just saw this still existing '..' row on the root ds. yeah breadcrumbs enh should be pushed this weekend

**Comment by mih** [comment]
Any chance for #917 to be considered in this PR?

**Comment by yarikoptic** [comment]
yeah -- would be nice... I am just learning this whole js thing... might as well do if figure out how.  First want to get ahold of meta-data

**Comment by yarikoptic** [comment]
@mih Here is how it looks atm ;)
http://www.onerussian.com/tmp/gkrellShoot_10-10-16_171425.png
I might push it to "deployment" later today

**Comment by debanjum** [comment]
All this looks really nice!

**Comment by yarikoptic** [comment]
@debanjum well -- that is what they are -- not there.  Should not in general happen on datasets.datalad.org ATM so I would just keep with a strikethrough atm.  Whenever we get to the situation where it is kinda not appropriate -- we will adjust.
I will now merge master, fix the failing test, push and if/when tests pass will try to deploy.

**Comment by yarikoptic** [comment]
after few BF and RF deployed to http://datasets.datalad.org . openfmri one looks neat imho although even somewhat noisy (might want to shorten all descriptions and look into providing extended one in tooltips or smth like that).

**Comment by yarikoptic** [comment]
tests pass, no objections so will merge

**Pull request merged**
