### PR TITLE
Prepare 0.12 release

### PR DESCRIPTION
**Pull request by mih**
This is really happening. The release date was set on Jan 11, 2020. The release is aptly named "Krakatoa" (one of the most devastating catastrophes in human history, with the second highest death toll of all volcanic eruptions, causing famines and despair, globally). I have written a draft of a very high-level summary of the changes since 0.11 to accompany the most detailed RC changelogs.

Please have a look, if you find anything important missing or suboptimally stated. Please push directly into this branch.

I'll merge, tag, and release as soon as (and if) the sun rises on Jan 11 ;-)

- [x] version bump
- [x] changelog draft
- [x] it would be good to get https://github.com/datalad/datalad/pull/3966 into this release, but not having it merged will not delay the release, but will target 0.12.1 instead.

Ping all @datalad/developers 

(I will go through all the issues that are labeled fixed, but left open, because 0.11 still has the issue, and will start closing them)

### CODE REVIEW

**Comment by mih** [comment]
Thanks @kyleam ! This looks ready. I will keep this open till tomorrow, though. In case we accumulate more last-minute fixes. Release is schedules for the morning of Jan 11 (CET).

**Comment by yarikoptic** [comment]
> This looks ready. I will keep this open till tomorrow, though. In case we accumulate more last-minute fixes. Release is schedules for the morning of Jan 11 (CET).

if you could run a test sweep build of (neuro)debian packages - would be great.  It was always a "fruitful" exercise for me to catch some lingering otherwise non-exposed issues.

**Comment by yarikoptic** [comment]
if you just tag/upload to pypi rc8 (orwhatever rc it is) - I could try it also on conda-forge... or we could do all that after and enjoy 0.12.1 ;)

**Comment by yarikoptic** [comment]
FWIW, pushed to `debian` branch a fixup for freshly filed bug 948533 in debian -- we need python3-distro build-depends (I guess).

**Comment by bpoldrack** [comment]
Re changelog: Drop of support for python2 should be mentioned, I guess.

**Comment by mih** [comment]
> Re changelog: Drop of support for python2 should be mentioned, I guess.

It is, as PY3 is exclusive now

**Comment by bpoldrack** [comment]
True. Missed that.

**Comment by mih** [comment]
Debian packaging in #4007

**Comment by mih** [comment]
Merging. Release imminent.

**Pull request merged**
