### PR TITLE
ENH: Generalize checksuming, reduce memory load

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by yarikoptic** [comment]
https://github.com/datalad/datalad/blob/7f2bc21320edf536d9fe7da2630216255be6d9e2/datalad/support/digests.py

**Comment by mih** [comment]
Is that code for "I wish this had a docstring"? ;-)

**Comment by yarikoptic** [comment]
> Is that code for "I wish this had a docstring"? ;-)

nah, for "come and sing along" ;)

**Comment by mih** [comment]
https://github.com/datalad/datalad-revolution/issues/92 is resolved.

**Pull request merged**
