### PR TITLE
RF(PY3): addurls - use "yield from"

### PR DESCRIPTION
**Pull request by yarikoptic**
Just `addurls` since I was there at the moment, but I guess there could be many other spots which could benefit from a similar RF

### CODE REVIEW

**Review by kyleam — COMMENTED** [review]
Is this sort of churn really worth it?

**Comment by yarikoptic** [comment]
not sure what you mean... it is a Python3 construct we have not used since were supporting python2.  
Looking forward I think we should prefer code to use it instead of explicit `for r in ...: yield r`.  Either it is "worth a PR", I don't see why not

**Comment by kyleam** [comment]
Looking forward is fine.  We've already starting using this in new code.  But what does going through old code, especially submitting a PR for a module here and a module there, gain us?  It's just needless churn that takes up developer, reviewer, and CI time.

**Review by kyleam — APPROVED** [review]
meta-comments aside...

**Pull request merged**
