### PR TITLE
BF: make `datalad push` not fail to push data on first try to Gin

### LINKED ISSUE #5143: datalad push fails to push data on first try to Gin
Discovered in a hacking session with @lnnrtwttkhn:
A ``datalad push`` does not push data on first attempt to a Gin remote, ``datalad publish`` does, though.

```
(handbook) adina@muninn in /tmp
❱ datalad create myds          
[INFO   ] Creating a new annex repo at /tmp/myds 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/myds (dataset)
(handbook) adina@muninn in /tmp
❱ cd myds
(handbook) adina@muninn in /tmp/myds on git:master
❱ echo 123456 > README 
(handbook) adina@muninn in /tmp/myds on git:master
❱ datalad save -m "annex README"
add(ok): README (file)                                                                                                             
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/myds on git:master
❱ datalad siblings add -s gin --url git@gin.g-node.org:/adswa/annexreadme.git
[INFO   ] Could not enable annex remote gin. This is expected if gin is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not detect whether gin carries an annex. If gin is a pure Git remote, this is expected.  
.: gin(-) [git@gin.g-node.org:/adswa/annexreadme.git (git)]
(handbook) adina@muninn in /tmp/myds on git:master
# first attempt: No data is pushed
❱ datalad push --to gin
publish(ok): . (dataset) [refs/heads/master->gin:refs/heads/master [new branch]]
publish(ok): . (dataset) [refs/heads/git-annex->gin:refs/heads/git-annex [new branch]]
(handbook) adina@muninn in /tmp/myds on git:master
# second attempt: Now data is pushed
❱ datalad push --to gin
copy(ok): README (file) [to gin...]                                             
copy(ok): README.md (file) [to gin...]                                          
publish(ok): . (dataset) [refs/heads/git-annex->gin:refs/heads/git-annex a26a676..5837d48]              
```

Now with publish:

```
❱datalad create anothertest
[INFO   ] Creating a new annex repo at /tmp/anothertest 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/anothertest (dataset)
(handbook) adina@muninn in /tmp
❱ cd anothertest
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ echo 12345634 > README
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ datalad save -m "annex README"
add(ok): README (file)                                                          
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ datalad siblings add -s gin --url git@gin.g-node.org:/adswa/testpublish.git
[INFO   ] Could not enable annex remote gin. This is expected if gin is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not detect whether gin carries an annex. If gin is a pure Git remote, this is expected.  
.: gin(-) [git@gin.g-node.org:/adswa/testpublish.git (git)]
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ datalad publish --to gin --transfer-data all
[INFO   ] Publishing Dataset(/tmp/anothertest) data to gin 
publish(ok): README (file)                                                      
[INFO   ] Publishing Dataset(/tmp/anothertest) to gin 
publish(ok): . (dataset) [pushed to gin: ['e80edf5..91638bb', '[new branch]']]  
action summary:
  publish (ok: 2)
```

### PR DESCRIPTION
**Pull request by mih**
Key commit is https://github.com/datalad/datalad/commit/7e27a1d6280df1a24f91f00a7aeacd0a47194374

Exploration is in #5143 and this PR fixes #5143

### CODE REVIEW

**Comment by adswa** [comment]
Happy to report that this fixes the issues!

```
(handbook) adina@muninn in /tmp
❱ datalad create woopwopp
[INFO   ] Creating a new annex repo at /tmp/woopwopp 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/woopwopp (dataset)
(handbook) adina@muninn in /tmp
❱ cd woopwopp 
(handbook) adina@muninn in /tmp/woopwopp on git:master
❱ echo 1234trgfQTZHBGVF > readme.md
(handbook) adina@muninn in /tmp/woopwopp on git:master
❱ datalad save -m "annex something"
add(ok): readme.md (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

(handbook) adina@muninn in /tmp/woopwopp on git:master
❱ datalad siblings add -s gin --url git@gin.g-node.org:/adswa/anothertest.git
[INFO   ] Could not enable annex remote gin. This is expected if gin is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not detect whether gin carries an annex. If gin is a pure Git remote, this is expected.  
.: gin(-) [git@gin.g-node.org:/adswa/anothertest.git (git)]
(handbook) adina@muninn in /tmp/woopwopp on git:master
❱ datalad push --to gin
copy(ok): readme.md (file) [to gin...]                                          
publish(ok): . (dataset) [refs/heads/git-annex->gin:refs/heads/git-annex 4dad75d..4640c23]                                                                      
publish(ok): . (dataset) [refs/heads/master->gin:refs/heads/master [new branch]]
(handbook) adina@muninn in /tmp/woopwopp on git:master
❱ 
```

**Review by kyleam — APPROVED** [review]
Thanks.  Looks sensible to me.

**Comment by mih** [comment]
Travis didnt even start after 14h 🙄

**Comment by mih** [comment]
Yeah, all green! Thx all.

**Pull request merged**
