### PR TITLE
ENH: Enable progress bars for unlock, fixes #6691

### LINKED ISSUE #6691: Feature request: Progress bar for `datalad unlock .`
### What is the problem?

I sometimes want to unlock an entire dataset via `datalad unlock .` (for example when all files will be overwritten, or when I am too lazy to define a proper `datalad run` command that takes care of unlocking).

For big datasets, this unlock operation can take a long time (up to several minutes) -- it would be nice if we could have a progress bar throughout the operation.

### What steps will reproduce the problem?

- `datalad clone https://gin.g-node.org/sappelhoff/eeg_manypipes_arc/`
- `cd eeg_manypipes_arc`
- `datalad unlock .`

### Datalad information

Click "details"

<details>

```
/home/stefanappelhoff/miniconda3/envs/emp/lib/python3.10/site-packages/secretstorage/util.py:46: UserWarning: Passing unwrap= to .send_and_get_reply() is deprecated and will break in a future version of Jeepney.
  return self._connection.send_and_get_reply(msg, unwrap=True)
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/stefanappelhoff/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/stefanappelhoff/.config/python_keyring/keyringrc.cfg
    - data_root: /home/stefanappelhoff/.local/share/python_keyring
## datalad 
  - version: 0.15.6
## dependencies 
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20220322-g7b64dea
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.35.1
  - cmd:system-git: 2.35.1
  - cmd:system-ssh: 9.0p1
  - humanize: 4.0.0
  - iso8601: 1.0.2
  - keyring: 23.5.0
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.3
  - requests: 2.27.1
  - wrapt: 1.14.0
## environment 
  - LANG: en_US.UTF-8
  - LC_ADDRESS: de_DE.UTF-8
  - LC_IDENTIFICATION: de_DE.UTF-8
  - LC_MEASUREMENT: de_DE.UTF-8
  - LC_MONETARY: de_DE.UTF-8
  - LC_NAME: de_DE.UTF-8
  - LC_NUMERIC: de_DE.UTF-8
  - LC_PAPER: de_DE.UTF-8
  - LC_TELEPHONE: de_DE.UTF-8
  - LC_TIME: de_DE.UTF-8
  - PATH: /home/stefanappelhoff/miniconda3/envs/emp/bin:/home/stefanappelhoff/miniconda3/condabin:/home/stefanappelhoff/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stefanappelhoff/miniconda3/bin:/home/stefanappelhoff/Desktop/bids/bids-validator/bids-validator/bin:/home/stefanappelhoff/Desktop/bids/open-trigger-box/figure1_generation:/home/stefanappelhoff/diff-so-fancy
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.0
    - ghc-8.10.7
    - http-client-0.7.9
    - persistent-sqlite-2.13.0.3
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.1.2
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220322-g7b64dea
## location 
  - path: /home/stefanappelhoff
  - type: directory
## metadata_extractors 
  - annex (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.10.4
## system 
  - distribution: ubuntu/18.04/Bionic Beaver
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 277
  - name: Linux
  - release: 5.4.0-110-generic
  - type: posix
  - version: #124~18.04.1-Ubuntu SMP Fri Apr 22 12:01:21 UTC 2022

```
</details>

### Additional context

_No response_

### Have you had any success using DataLad before?

_No response_

### PR DESCRIPTION
**Pull request by adswa**
An unlocking operation can take a considerable amount of
time, but doesn't provide feedback at all (see #6691).
By switching from _call_annex_records(), which processes
the full bunch of files at once, to _call_annex_records_items(),
which yields as soon as results are available, we can
construct a progress bar with a file counter around the
unlock operation.

The progress reporting is slightly complicated by the
fact that git annex' --json records for each file are
output before a final 'recording state in git' operations,
which can, if a large number of files was unlocked, add
considerably to the execution time of the command after
all files have been unlocked already and the progress bar
would be at 100%. Thus, this change adds an additional
progress update when all files are processed to report
on the final recording step.

Nevertheless, the progress bar seems a bit moody - it seems that the ``_call_annex_records_items()`` loop doesn't yield all files' results before the "recording state in git" stage, leading to a bit of a pause in the middle of the progress bar. Maybe @christian-monch knows what might cause this?
unlock-progressbar

Another TODO/Weirdness is a for some reason completely made up file counter (you can see it in the reported file total in the Gif as well) that I wasn't able to figure out. Every run reports a different wrong total number of files, when the total being declared in the setup of the progressbar (``nfiles``) is actually correct.

Reproducer:
``` 
datalad create abcd && abcd
for i in {1..1000}; do echo $i > file_$i ; done
datalad save
datalad unlock 
```

I think I have seen similar flaky reporting in other commands (``push``?) so I suspect its something more general with the progress bar setup.

#### 💫 Enhancements and new features
- ``datalad unlock`` gained a progress bar.

### CODE REVIEW

**Review by mih — APPROVED** [review]
LGTM, thx!

Changes like this need to be done all over the code base.

If by 'total counter' you refer to the larger number on the right, it us not a total but a speed estimate. I agree that it is generally pretty useless and inaccurate, but technically not wrong.

**Comment by adswa** [comment]
> If by 'total counter' you refer to the larger number on the right, it us not a total but a speed estimate. I agree that it is generally pretty useless and inaccurate, but technically not wrong.

oh sorry :facepalm:

**Review by bpoldrack — APPROVED** [review]
LGTM. Curious CI failures, though. They seem unrelated, but I haven't seen them before.

**Comment by adswa** [comment]
I've seen them in a few previous PRs before (e.g., #6701, #6698) but am also unsure what to make if them as well

**Comment by mih** [comment]
```
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c annex.merge-annex-branches=false annex find --not --in . --json --json-error-messages -c annex.dotfiles=true -- file1' failed with exitcode 1 under /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_tree_test_ro_operationsa5gnt_3r/clone [info keys: stdout_json] [err: 'git-annex: This repository is not initialized for use by git-annex, but .git/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.']
```

Posting this error here in order to help find this PR later. But if this has anything to do with this PR, it would be an indication of a runner issue. If there is such an issue, the runner would need to be fixed. Because AFAICS the usage pattern in this PR is pretty normal. Maybe @christian-monch can comment.

**Comment by christian-monch** [comment]
> Nevertheless, the progress bar seems a bit moody - it seems that the `_call_annex_records_items()` loop doesn't yield all files' results before the "recording state in git" stage, leading to a bit of a pause in the middle of the progress bar. Maybe @christian-monch knows what might cause this?

Sorry, but I cannot reproduce the pause locally.  Let's try to figure out why `datalad unlock` behaves so differently.

I do see a strange behavior in `datalad save` after `datalad unlock` though. It takes about a minute to complete.

**Comment by christian-monch** [comment]
> Maybe @christian-monch can comment.
Looking into the reasons for the CommandError.

**Comment by adswa** [comment]
> Sorry, but I cannot reproduce the pause locally. Let's try to figure out why `datalad unlock` behaves so differently.
> 
> I do see a strange behavior in `datalad save` after `datalad unlock` though. It takes about a minute to complete.

Thanks for looking into this! I don't see anything unusual in save - its rapid. Might suggest something the takes place during unlock for me happens during your save?
Here's my wtf, do you see what might be different from yours?
<details>

```
❱ datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/adina/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/adina/.config/python_keyring/keyringrc.cfg
    - data_root: /home/adina/.local/share/python_keyring
## datalad 
  - version: 0.16.2+181.g6bfe67007
## dependencies 
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20220504
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.35.2
  - cmd:system-git: 2.35.2
  - cmd:system-ssh: 8.4p1
  - exifread: 2.3.2
  - git: 3.1.27
  - gitdb: 4.0.9
  - humanize: 4.0.0
  - iso8601: 1.0.2
  - keyring: 23.5.0
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.3
  - mutagen: 1.45.1
  - platformdirs: 2.5.1
  - requests: 2.27.1
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/adina/env/handbook/bin:/home/adina/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/adina/.local/bin:/home/adina/bin:/snap/bin:/home/adina/repos/latexrun/:/home/adina/node_modules/.bin
## extensions 
  - container: 
    - description: Containerized environments
    - entrypoints: 
      - datalad_container.containers_add.ContainersAdd: 
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names: 
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList: 
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names: 
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove: 
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names: 
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun: 
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names: 
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 1.1.6
  - datalad_debian: 
    - description: DataLad for working with Debian packages
    - entrypoints: 
      - datalad_debian.new_distribution.NewDistribution: 
        - class: NewDistribution
        - load_error: None
        - module: datalad_debian.new_distribution
        - names: 
          - deb-new-distribution
          - deb_new_distribution
      - datalad_debian.new_package.NewPackage: 
        - class: NewPackage
        - load_error: None
        - module: datalad_debian.new_package
        - names: 
          - deb-new-package
          - deb_new_package
      - datalad_debian.update_distribution.UpdateDistribution: 
        - class: UpdateDistribution
        - load_error: None
        - module: datalad_debian.update_distribution
        - names: 
          - deb-update-distribution
          - deb_update_distribution
    - load_error: None
    - module: datalad_debian
    - version: 0+untagged.18.g54652cc.dirty
  - neuroimaging: 
    - description: Neuroimaging tools
    - entrypoints: 
      - datalad_neuroimaging.bids2scidata.BIDS2Scidata: 
        - class: BIDS2Scidata
        - load_error: None
        - module: datalad_neuroimaging.bids2scidata
        - names: 
          - bids2scidata
    - load_error: None
    - module: datalad_neuroimaging
    - version: 0.3.1
  - ukbiobank: 
    - description: UKBiobank dataset support
    - entrypoints: 
      - datalad_ukbiobank.init.Init: 
        - class: Init
        - load_error: None
        - module: datalad_ukbiobank.init
        - names: 
          - ukb-init
          - ukb_init
      - datalad_ukbiobank.update.Update: 
        - class: Update
        - load_error: None
        - module: datalad_ukbiobank.update
        - names: 
          - ukb-update
          - ukb_update
    - load_error: None
    - module: datalad_ukbiobank
    - version: 0.3.3
  - webapp: 
    - description: Generic web app support
    - entrypoints: 
      - datalad_webapp.WebApp: 
        - class: WebApp
        - load_error: None
        - module: datalad_webapp
        - names: 
          - webapp
          - webapp
    - load_error: None
    - module: datalad_webapp
    - version: 0.3
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220504
## location 
  - path: /home/adina
  - type: directory
## metadata_extractors 
  - annex: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.annex
  - audio: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.audio
  - bids: 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.bids
  - datacite: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.datacite
  - datalad_core: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
  - datalad_rfc822: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
  - dicom: 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.dicom
  - exif: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
  - image: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.image
  - nidm: 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nidm
  - nifti1: 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nifti1
  - xmp: 
    - distribution: datalad 0.16.1+3.g682c9109b
    - load_error: None
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.9.12
## system 
  - distribution: debian/11-updates/n/a
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - max_pathlength: 4096
      - mount_opts: rw,relatime,errors=remount-ro
      - path: /home/adina
      - type: ext4
    - HOME: 
      - max_pathlength: 4096
      - mount_opts: rw,relatime,errors=remount-ro
      - path: /home/adina
      - type: ext4
    - TMP: 
      - max_pathlength: 4096
      - mount_opts: rw,relatime,errors=remount-ro
      - path: /tmp
      - type: ext4
  - max_path_length: 267
  - name: Linux
  - release: 5.16.0-3-amd64
  - type: posix
  - version: #1 SMP PREEMPT Debian 5.16.11-1 (2022-02-25)
```
</details>

**Comment by mslw** [comment]
> ```
> datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c annex.merge-annex-branches=false annex find --not --in . --json --json-error-messages -c annex.dotfiles=true -- file1' failed with exitcode 1 under /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_tree_test_ro_operationsa5gnt_3r/clone [info keys: stdout_json] [err: 'git-annex: This repository is not initialized for use by git-annex, but .git/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.']
> ```
> 
> Posting this error here in order to help find this PR later. But if this has anything to do with this PR, it would be an indication of a runner issue.

This looks like it's caused by a change in Git behavior.

Not sure which test produced the error, but I ran into the same error message on our cluster when cloning a dataset owned by another user (as an input subdataset).

Note that the failing test on MacOS (brew) had git 2.36.1, while the successful one (snapshot) had 2.35.1

In addition to the issues pointed by @adswa , the error appears in a few others. To tie things together: it was succinctly summarized by @yarikoptic in [this issue comment](https://github.com/datalad/datalad/issues/5665#issuecomment-1140086405) and #6708 

The summary (for my presentation of the problem, not sure if appplicable here) is that Git >= 2.35.2 will refuse to operate on `.git` owned by someone else, unless the user explicitly configures the directory containing it as trusted with `git config --global --add safe.directory <path>`. This is due to safety reasons, to avoid situations where a malicious actor could create a .git directory in a shared location above a victim’s current working directory. Context and links which I found useful here: https://stackoverflow.com/a/72299780

**Pull request merged**
