### PR TITLE
BF(TST): use sys.executable and not hardcoded "python"

### PR DESCRIPTION
**Pull request by yarikoptic**
Detected while trying to build 0.14.2 for Debian

Lead to

	======================================================================
	ERROR: datalad.interface.tests.test_run_procedure.test_name_with_underscore
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
		self.test(*self.arg)
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/tests/utils.py", line 578, in _wrap_with_tree
		return t(*(arg + (d,)), **kw)
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/tests/test_run_procedure.py", line 418, in test_name_with_underscore
		ds.run_procedure(spec=["print_args"])
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/distribution/dataset.py", line 503, in apply_func
		return f(**kwargs)
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/utils.py", line 482, in eval_func
		return return_func(generator_func)(*args, **kwargs)
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/utils.py", line 470, in return_func
		results = list(results)
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/utils.py", line 389, in generator_func
		for r in _process_results(
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/utils.py", line 557, in _process_results
		for res in results:
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/run_procedure.py", line 448, in __call__
		for r in Run.__call__(
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/utils.py", line 389, in generator_func
		for r in _process_results(
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/utils.py", line 557, in _process_results
		for res in results:
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/core/local/run.py", line 237, in __call__
		for r in run_command(cmd, dataset=dataset,
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/core/local/run.py", line 685, in run_command
		raise exc
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/core/local/run.py", line 464, in _execute_command
		runner.run(
	  File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/cmd.py", line 408, in run
		raise CommandError(
	datalad.support.exceptions.CommandError: CommandError: 'python /tmp/datalad_temp_tree_test_name_with_underscoreydwd49na/.datalad/procedures/print_args' failed with exitcode 127 under /tmp/datalad_temp_tree_test_name_with_underscoreydwd49na

	----------------------------------------------------------------------
	Ran 1227 tests in 1944.566s

	FAILED (SKIP=142, errors=1)
	D: /a
	D: /a/b/c
	D: /a~
	D: /a b/name
	testing 0
	testing 1
	/tmp/datalad_temp_tree_test_paths_with_forward_slashest42h83pf
	' |;&%b5{}\'" .datc '

### CODE REVIEW

**Comment by kyleam** [comment]
The updated test is failing on windows:

```
[00:15:58] ======================================================================
[00:15:58] ERROR: datalad.interface.tests.test_run_procedure.test_name_with_underscore
[00:15:58] ----------------------------------------------------------------------
[00:15:58] Traceback (most recent call last):
[00:15:58]   File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:58]     self.test(*self.arg)
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\tests\utils.py", line 578, in _wrap_with_tree
[00:15:58]     return t(*(arg + (d,)), **kw)
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\interface\tests\test_run_procedure.py", line 418, in test_name_with_underscore
[00:15:58]     ds.run_procedure(spec=["print_args"])
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\distribution\dataset.py", line 503, in apply_func
[00:15:58]     return f(**kwargs)
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\interface\utils.py", line 486, in eval_func
[00:15:58]     return return_func(generator_func)(*args, **kwargs)
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\interface\utils.py", line 474, in return_func
[00:15:58]     results = list(results)
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\interface\utils.py", line 393, in generator_func
[00:15:58]     for r in _process_results(
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\interface\utils.py", line 561, in _process_results
[00:15:58]     for res in results:
[00:15:58]   File "C:\Python39-x64\lib\site-packages\datalad\interface\run_procedure.py", line 439, in __call__
[00:15:58]     raise ValueError("No idea how to execute procedure %s. "
[00:15:58] ValueError: No idea how to execute procedure C:\DLTMP\datalad_temp_tree__jmpbhkh\.datalad\procedures\print_args. Missing 'execute' permissions?
```

https://ci.appveyor.com/project/mih/datalad/builds/38916950/job/07ft7km2jucgn5q5#L814

**Comment by yarikoptic** [comment]
Thanks for pasting. I will later troubleshoot in a VM.

**Comment by yarikoptic** [comment]
well -- long story (did take some time to tune my fingers to windows again) short -- it was not a proper json in that test. `\\` trips `json.loads`. And because we do not bother with logging while running tests we did not even see that warning.

```shell
$ DATALAD_LOG_LEVEL=WARNING python -m nose -s -v --pdb datalad/interface/tests/test_run_procedure.py:test_name_with_underscore
datalad.interface.tests.test_run_procedure.test_name_with_underscore ... [WARNING] Failed to load DATALAD_CONFIG_OVERRIDES_JSON: Invalid \escape: line 1 column 50 (char 49)
[WARNING] Failed to load DATALAD_CONFIG_OVERRIDES_JSON: Invalid \escape: line 1 column 50 (char 49)
> c:\users\datalad\pycharmprojects\datalad\datalad\interface\run_procedure.py(439)__call__()
-> raise ValueError("No idea how to execute procedure %s. "
```
Pushed a fix for this which would just use `json.dumps`.

IMHO it might be yet another case  supporting our DX-costly (and possibly UX) tendency to prefer just to hope that "things might just work out" even if environment is known to be misconfigured somehow (ref: #5591).

**Comment by yarikoptic** [comment]
restarted one travis job, but otherwise - I think it is ready.

**Review by kyleam — APPROVED** [review]

**Pull request merged**
