### PR TITLE
TST: Show that we are needlessly being inefficient with local file URLs

### PR DESCRIPTION
**Pull request by mih**
Reason: Git disabled some optimizations (hardlinking) for local clones
when it gets a URL. Maybe we want to convert such URL, or force `clone
--local`

### CODE REVIEW

**Comment by bpoldrack** [comment]
I assume, what you are proposing is meant to be implemented in `install`, right? Or do we talk about speeding up the tests?

**Comment by mih** [comment]
I think it more about GitRepo. While the tests are affected, I am concern
about my personal use. I clone a lot and all on the same machine.

On Sep 13, 2016 4:06 PM, "Benjamin Poldrack" <notifications@github.com>
wrote:

I assume, what you are proposing is meant to be implemented in install,
right? Or do we talk about speeding up the tests?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/datalad/datalad/pull/812#issuecomment-246692517>, or mute
the thread

**Comment by bpoldrack** [comment]
Well, but I wouldn't like to see `GitRepo` to care for figuring out, that a URL actually is a local thing. So, if you pass such a thing to `GitRepo`, either use the attribute `localpath` of the `RI` instance or it's a matter of fully supporting to pass options to all git commands to allow for `--local`.

**Comment by mih** [comment]
Why? Anything that starts with file:// can easily be converted to an
absolute path.

**Comment by bpoldrack** [comment]
Yes. `RI('file:///some/where').localpath`

**Comment by mih** [comment]
Rebased on master.

**Comment by mih** [comment]
Tests fail, because human.brain-map.org is practically offline (takes minutes to respond ATM).

**Comment by mih** [comment]
Bounce tests.

**Comment by mih** [comment]
Merging despite failing test: all related to connection to brain-map.org failing. Non-network runs passed.

**Pull request merged**
