### PR TITLE
RF+BF: github - remove user/password authentication, use only tokens

### LINKED ISSUE #3947: FOI: might soon need to remove my recent ENH for github authentication...
Used create-sibling-github today and later received email:
```shell
Date: Wed, 18 Dec 2019 12:46:06 -0800                                                                                                                                                                                              
From: GitHub <noreply@github.com>                                                                                                                                                                                                  
To: Yaroslav Halchenko <debian@onerussian.com>                                                                                                                                                                                     
Subject: [GitHub] Deprecation Notice                                                                                                                                                                                               
...                                                                                                                                                                                                                                   
                                                                                                                                                                                      
You recently used a password to access an endpoint through the GitHub API using PyGithub/Python. We will deprecate basic authentication using password to this endpoint soon:                                                      
                                                                                                                                                                                                                                   
https://api.github.com/user                                                                                                                                                                                                        
                                                                                                                                                                                                                                   
We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.                                                        
                                                                                                                                                                                                                                   
Thanks,                                                                                                                                                                                                                            
The GitHub Team 
```
which is I guess due to us obtaining a token programmatically using https://pypi.python.org/pypi/PyGithub , not sure if there is anything it should do on its end I have [not spotted any related issue related to such an email in their issue tracker](https://github.com/PyGithub/PyGithub/search?q=endpoint+through+the+GitHub+API+using+PyGithub%2FPython&type=Issues)

### LINKED ISSUE #4079: Reenable github integration test
A failing test of special-interest functionality was a blocker to an urgent global fix #4078

I disabled the test with cad795b0f73a952e38214c62fe1a35eef43d258a:

Please bring it back @yarikoptic

### PR DESCRIPTION
**Pull request by yarikoptic**
- minor __doc__ tuneup for typos, and consistent GitHub (not Github)
- also removes storing of a (now "entered", not generated) token into
  git configuration.  If desired to do so - do manually.  To
  centralize entered credentials handling, regular credential store is
  used
- VCR tapes were updated (with token manually replaced after) for two
  tests and 3rd commented out was removed completely (Closes #4079)
- in some cases a little better error reporting now (e.g., giving a
  hint that token likely lack permissions to find a repository while
  creating ;))

Overall, it is not yet "much better" but it should be working and
usable again.

If merged, closes #3947

### CODE REVIEW

**Review by kyleam — APPROVED** [review]
Didn't test out locally, but looks fine to me on a read through.

**Comment by adswa** [comment]
I have adjusted the handbook section that walks through ``create-sibling-github`` accordingly: https://github.com/datalad-handbook/book/pull/626

**Comment by yarikoptic** [comment]
Thank you @adswa for fixups -- FWIW, they look fine to me.

**Comment by kyleam** [comment]
@yarikoptic Are you fine with the change in aed28866a6 (TST: github: Loosen string matching of credential exception, 2020-12-09)?  Or would you like to verify that the original test passed on your end (i.e. you're seeing different results than what happens on Travis and my local machine)?

**Comment by yarikoptic** [comment]
well, I have  [given my blessing](https://github.com/datalad/datalad/pull/5218#issuecomment-741888375) the changes.  I think it would have been nice to keep it a bit more strict, even if just to keep the beginning of the exception string, but I was ok as is with @adswa 's changes... well -- since you are asking, I will add back at least the ` very bad status` , test locally and push ;)

**Comment by kyleam** [comment]
> well, I have [given my blessing](https://github.com/datalad/datalad/pull/5218#issuecomment-741888375) the changes.

You said: "Thank you @adswa for fixups -- FWIW, they look fine to me."

So, it's not clear that you're considering aed2886, which is a commit from me.  Hence why I asked explicitly.

> well -- since you are asking, I will add back at least the ` very bad status` , test locally and push ;)

That part was dropped because it fails on Travis and for me locally.  As aed2886 said:

```
test__make_github_repos() is failing on Travis because the the logged
BadCredentialsException ends with

    very bad status "some data"

instead of

    very bad status some data

I see the same failure locally (PyGithub 1.53 and Python 3.7.3).  I'm
hesitant to change it though, because presumably this passed on
@yarikoptic's local machine.
```

**Comment by yarikoptic** [comment]
ha ha -- and I was thinking "Adina gave such a nice commit message, like Kyle does, good for her" ;)  I have missed the fact that it was commit from you @kyleam not Adina ;)

**Comment by kyleam** [comment]
@yarikoptic Just out of curiosity, do you think the difference in that output is due to the PyGithub version?

**Comment by yarikoptic** [comment]
I do not know and not care much enough ;) FWIW locally I have 1.43.7-1 from debian's python3-github

**Comment by kyleam** [comment]
> I do not know and not care much enough ;)

That's fair, but I hate unsolved mysteries :)

> FWIW locally I have 1.43.7-1 from debian's python3-github

Thanks.  Indeed this comes with PyGithub's a0f01cf9 (Remove more Python version specific code, 2019-08-28).

**Pull request merged**
