### PR TITLE
RF: Normalize logging (levels) for process execution

### PR DESCRIPTION
**Pull request by mih**
For the non-async Runner and its protocols.

Log levels:

- Matching log levels for start and end of an event
- High-level execution -> debug
- Process start/finish -> 8
- Threading and IO -> 5

Exemplary output at log-level 1:

```
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config'] (cwd=/tmp/some) 
[Level 8] Process 110667 started 
[Level 5] ReaderThread(<_io.FileIO name=22 mode='rb' closefd=True>, <queue.Queue object at 0x7faa7f55ed00>, ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config']) started 
[Level 5] ReaderThread(<_io.FileIO name=22 mode='rb' closefd=True>, <queue.Queue object at 0x7faa7f55ed00>, ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config']) exiting (stream end) 
[Level 5] ReaderThread(<_io.FileIO name=19 mode='rb' closefd=True>, <queue.Queue object at 0x7faa7f55ed00>, ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config']) started 
[Level 5] ReaderThread(<_io.FileIO name=19 mode='rb' closefd=True>, <queue.Queue object at 0x7faa7f55ed00>, ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config']) exiting (stream end) 
[Level 5] Read 87 bytes from 110667[stdout] 
[Level 8] Process 110667 exited with return code 0 
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config'] with status 0 
```

At `debug` level (arguably the default one, if "something is wrong") the output is reduced to

```
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config'] (cwd=/tmp/some) 
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config'] with status 0 
```

which is compact, but still verbose enough to show everything without diving "into" a command execution.

Fixes datalad/datalad#5772

### CODE REVIEW

**Comment by mih** [comment]
Forced push an adjustment of two tests that specifically verified the previous log output

**Comment by mih** [comment]
This is ready

**Comment by adswa** [comment]
I can only speak from a user perspective here: I like the debug output with this PR better, it is more readable

**Review by bpoldrack — APPROVED** [review]
I like it. I would, however, *love* it, if this:

> Log levels:
>
>    Matching log levels for start and end of an event
>    High-level execution -> debug
>    Process start/finish -> 8
>    Threading and IO -> 5


was included somewhere in the docs, so that we have a place to shape comprehensive guidelines at.

**Comment by mih** [comment]
> I like it. I would, however, _love_ it, if this:
> 
> > Log levels:
> > Matching log levels for start and end of an event
> > High-level execution -> debug
> > Process start/finish -> 8
> > Threading and IO -> 5
> 
> was included somewhere in the docs, so that we have a place to shape comprehensive guidelines at.

I would not know which place. If you know one, please let me know.

**Comment by mih** [comment]
Thx!

**Pull request merged**
