### PR TITLE
Use datalad/release-action

### LINKED ISSUE #7110: Migrate release workflow to use datalad/release-action@v0
Most of https://github.com/datalad/datalad/issues/7052 are addressed there so we better migrate.  Also would be useful so other developers start to get used to it and file issues there if any detected.

Needs
- [ ] https://github.com/datalad/release-action/issues/8 to get changelog in github release formatted ok
- [x] https://github.com/datalad/release-action/issues/27 to gain @v0 (or v1?) to be used in the workflow here

### PR DESCRIPTION
**Pull request by jwodder**
Closes #7110.

### CODE REVIEW

**Comment by yarikoptic** [comment]
@jwodder thanks! please resolve conflicts and we will proceed.

**Comment by jwodder** [comment]
@yarikoptic Conflicts resolved.

**Comment by yarikoptic** [comment]
Great, thanks! Let's see where it leads us.

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.9.4`](https://github.com/datalad/datalad/releases/tag/0.9.4)

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.9`](https://github.com/datalad/datalad/releases/tag/0.17.9)

**Pull request merged**
