### PR TITLE
BF: Nicer manpages (fixes gh-1187)

### PR DESCRIPTION
**Pull request by mih**
Could be done in many different ways, but this does it in a minimal way

### CODE REVIEW

**Comment by yarikoptic** [comment]
oh -- problem wasn't really (just in) the listing of commands.  It is in too wide lines in DESCRIPTION and below.  So
```shell
$> zcat /usr/share/man/man1/datalad.1.gz | grep -A4 DESCRIPTION
.SH DESCRIPTION
DataLad provides a unified data distribution with the convenience of git\-annex
.br
repositories as a backend.  DataLad command line tools allow to manipulate
.br
```
due to indentation renders as

```
DESCRIPTION
       DataLad  provides  a  unified data distribution with the convenience of
       git-annex
       repositories as a backend.  DataLad command line tools allow to manipu‐
       late
```

those warnings weren't my primary warning

**Comment by mih** [comment]
@yarikoptic Thanks for the hint. I pushed another fix.

While we are at it, maybe someone has a suggestion on how to redo the command list in `datalad.1` -- in tight terminals it doesn't look that well.

**Comment by mih** [comment]
OSX failure is unrelated.

**Comment by yarikoptic** [comment]
Probably the only way is not so it at all (just say COMMAND) and rely on consise list under in description

**Comment by mih** [comment]
Sounds acceptable to me. However, that list in description isn't a beauty either.

**Comment by mih** [comment]
Did the COMMAND change, looking at additional changes now

**Comment by mih** [comment]
Now with extra sweetness.

**Comment by yarikoptic** [comment]
I think it is much better now, but options descriptions is still wrapped not so neatly:
```
...
         --version       show the program's version and license information
         --dbg           enter Python debugger when uncaught exception happens
         --idbg          enter IPython debugger when uncaught  exception  hap‐
       pens
         -C  PATH          run  as if datalad was started in <path> instead of
       the
                               current working  directory.  When  multiple  -C
       options
                               are  given,  each  subsequent  non-absolute  -C
       <path> is
                               interpreted  relative  to  the   preceding   -C
       <path>. This
                               option  affects the interpretations of the path
       names
                               in that they are made relative to the working
                               directory caused by the -C option

```
anything could be done without major pain?

also at some point (not necessarily in this PR) we should probably sort those lists of commands within each section -- now it seems to be pretty much arbitrary:
```
       Commands for dataset operations

         create
             Create a new dataset from scratch
         install
             Install a dataset from a (remote) source
         get
             Get any dataset content (files/directories/subdatasets)
         add
             Add files/directories to an existing dataset
         publish
             Publish a dataset to a known sibling
         uninstall
             Uninstall subdatasets
         drop
             Drop file content from datasets
         remove
             Remove components from datasets
         update
             Update a dataset from a sibling
         create-sibling
             Create dataset(s)'s sibling (e.g., on a web server)
```

**Comment by mih** [comment]
re order of things: they are in the exact order in which we list them in `datalad/interface/__init__.py` -- folowing a divine plan!

**Comment by mih** [comment]
re option description formatting: A little tricky due to the flexibility of the argparse help output depending on the amount of text and length of the option labels. Would prefer to keep this for later entertainment.

**Comment by bpoldrack** [comment]
re divine plan: Please, have a comment on this within `datalad/interface/__init__.py`.

**Comment by yarikoptic** [comment]
almost perfect, thanks @mih!

look though at `man git` and see how sub-sections are demarkated:
```
.SH "HIGH\-LEVEL COMMANDS (PORCELAIN)"
.sp
We separate the porcelain commands into the main commands and some ancillary user utilities\&.
.SS "Main porcelain commands"
.PP
\fBgit-add\fR(1)
.RS 4
```

is there a chance we could gain those .SS's for "Commands for meta data handling" etc? ;)

**Comment by mih** [comment]
sure

**Comment by mih** [comment]
if you look at the synopsis of create you can see that there is more todo. suggestion for that?

**Comment by yarikoptic** [comment]
eh -- indeed.  I have tried non-braking space in between `--some-option` and its `VALUE` but then it start braking at `--some` and `option` etc.  So the only way I think is to see if we could provide manual/improved formatting is to fool argparse probably.... here is a first sketch which seems to do it:
```diff
diff --git a/formatters.py b/formatters.py
index 8ae88693..a06966c1 100644
--- a/formatters.py
+++ b/formatters.py
@@ -56,8 +56,12 @@ class ManPageFormatter(argparse.HelpFormatter):
     def _mk_synopsis(self, parser):
         self.add_usage(parser.usage, parser._actions,
                        parser._mutually_exclusive_groups, prefix='')
-        usage = self._format_usage(None, parser._actions,
-                                   parser._mutually_exclusive_groups, '')
+        try:
+            self._width -= 8
+            usage = self._format_usage(None, parser._actions,
+                                       parser._mutually_exclusive_groups, '')
+        finally:
+            self._width += 8
         # replace too long list of commands with a single placeholder
         usage = re.sub(r'\n\s*{.*}\n\s*', ' COMMAND ', usage, flags=re.MULTILINE)
         usage = usage.replace('%s ' % self._prog, '')
```

**Comment by mih** [comment]
I think latest change makes it look good enough.

**Comment by mih** [comment]
Bottom line: This is nicer enough. Unless it broke something, I will stop here.

**Comment by yarikoptic** [comment]
it is indeed nice enough (thus merging), although I would have gone for my adhoc adjustment to wrapping since currently it would still wrap in the middle of options and thus making it not clear if that is the hyphen for wrapping or a dash within option name, 
```shell
              [-D DESCRIPTION] [-d PATH] [--no-annex] [--nosave] [--annex-ver‐
              sion  ANNEX_VERSION]  [--annex-backend ANNEX_BACKEND] [--native-
              metadata-type   LABEL]   [--if-dirty    COMMAND   ]   [--shared-
```

**Comment by yarikoptic** [comment]
d'oh - was about to merge but then decided to check datalad.1 -- some itemization seems to be broken:
```
   Commands for meta data handling
       search Search  within  available in datasets' meta data aggregate-meta‐
              data Aggregate meta data of a dataset for later query
```

**Comment by mih** [comment]
That is not broken that is how man/troff do it.

**Comment by yarikoptic** [comment]
> That is not broken that is how man/troff do it.
I guess I wasn't clear - search and aggregate-meta now we're clashed into a single paragraph

**Comment by mih** [comment]
Indeed, wtf. Thanks for persistence. Will check,

**Comment by mih** [comment]
@yarikoptic fix in #1201

**Pull request merged**
