### PR TITLE
BF: Pre-population of testrepos already needs HTTP test server setup

### PR DESCRIPTION
**Pull request by mih**
Was broken by https://github.com/datalad/datalad/pull/5332

### CODE REVIEW

**Review by kyleam — DISMISSED** [review]
Confirmed the fix locally running with `DATALAD_TESTS_SETUP_TESTREPOS=1`.

Sorry for not giving you a second set of eyes for the "all known failures" check in gh-5332.

**Comment by kyleam** [comment]
The failure on one of the Travis builds seems reliable (showed up with rerun).  I'll see if I can trigger it locally.

https://travis-ci.com/github/datalad/datalad/jobs/499067701

**Comment by kyleam** [comment]
> The failure on one of the Travis builds seems reliable (showed up with rerun).

That should be gone with the last push (0346605a3b).

**Review by kyleam — APPROVED** [review]

**Comment by kyleam** [comment]
The remaining failures are macOS setup failures on AppVeyor.  I'll merge this in to get master closer to green, but let me know if you think my changes in 0346605a3b should be tweaked.

**Comment by mih** [comment]
Thx @kyleam for the fix. LGTM!

**Pull request merged**
