### PR TITLE
BF: `configure` command (fixes gh-918)

### PR DESCRIPTION
**Pull request by mih**
First crude implementation of a command to configure DataLad and
datasets, interactively.

This is not meant as a replacement for the ConfigManager, nor as a
direct cmdline frontend for it. I believe `git config` works much better
for this case, and supports way more corner cases.

OTOH I think we do need something that bootstraps an initial
configuration for a fresh installation, and maybe for a new dataset
(until with have that templating mechanism).

There are no tests, and I won't write them, because I am not (yet)
confident that this a viable path to go down. In any case, the actual
interaction with the rest of the codebase is minimal (ui, and cfg).
And it already exposed a bug #2270.

This change is complete.

Please have a look @datalad/developers

### CODE REVIEW

**Comment by yarikoptic** [comment]
Just a comment on the description (haven't looked inside yet): I do still feel that we do need `datalad config` and that `git config` is too generic -- we need to be able to provide a list of config options we are aware about, what metadata extractors are available, etc. to make it explicit what config is modified (global/repo/dataset) without relying on user to know where each should go to.

**Comment by mih** [comment]
After the recent changes to make an initial configuration optional, or at least force it, we could probably get away without this command. Closing.

**Comment by yarikoptic** [comment]
well, I think we might like to have it regardless of optionality of the initial configuration.  E.g. present all known config options and let users possibly configure those they are interested in.

**Comment by yarikoptic** [comment]
I think we should reincarnate this one.  I have also pushed 0d5044831d2c81c3c7182cb2dc0d72a1677caf5f  to call `configure` if mode is interactive.  The reason is that for new to git users all that "configuration" complaint is still a dark forest -- is it a github configuration? is that a repository configuration?

**Comment by yarikoptic** [comment]
Re

>  I believe git config works much better for this case, and supports way more corner cases.

I would somewhat disagree.  We do need `config` functionality with --recursive semantics, with clear global/local/dataset separation of where config should go to instead of hoping that user would magically know all the places he could point `git config` to

**Comment by mih** [comment]
I think we can close this again.

**Pull request closed without merging**
