### PR TITLE
WIP: NF XNAT/NITRC-IR support

### PR DESCRIPTION
**Pull request by chaselgrove**
For #1552.

datalad/crawler/pipelines/xnat.py XNATServer.get_projects() contains drop_empty to address the empty XNAT projects (#1552 Point 1).  Defaults to False to preserve old behavior -- do you want it always True?

NITRC pipeline returns more descriptive filenames, but they're long.  Let me know if you'd like to simplify those further.

I've just noticed I'm ignoring subject and experiment metadata in the file information -- to follow.

### CODE REVIEW

**Comment by chaselgrove** [comment]
Including extra metadata in the file crawler.

**Comment by chaselgrove** [comment]
Ready for comment.  I'm not after a code review, but rather a check if we're going in the right direction.  Are the file names sensible and suitable?  Is the extra metadata appropriate and structured to your liking?

**Comment by yarikoptic** [comment]
cool, will do
oh, we crossed in hyperspace -- I was tuning code while reviewing it as well... will resolve and push on top

**Comment by yarikoptic** [comment]
oh, you didn't allow to push into your branch, so I pushed to my remote http://github.com/yarikoptic/datalad , the same branch, just one commit on top : http://github.com/yarikoptic/datalad/commit/c701cfb83e63103baab87a188c6f7521edc01e4c

**Comment by yarikoptic** [comment]
So what do to tick about my comments/todos in the changes I pushed on top @chaselgrove?

**Comment by chaselgrove** [comment]
Need to merge master, but leaving these changes here for now.  Testing takes ~6 hours, even after caching with VCR; perhaps you want a FULL_XNAT_TESTS flag to only run these if desired?

**Comment by yarikoptic** [comment]
All crawler parts were moved away into https://github.com/datalad/datalad-crawler , so the corresponding changes should be done against that code case now. Let me know if you need help

**Comment by yarikoptic** [comment]
migrated to https://github.com/datalad/datalad-crawler/pull/9

**Pull request closed without merging**
