### PR TITLE
-c datalad.runtime.raiseonerror=yes  in command line is not passed into cfg

### PR DESCRIPTION
**Pull request by mih**
#### What is the problem?
I think I entered (copy/pasted actually from the message) it correctly, didn't I?
I expected to end up at ascii.py:decode:26 (ideally) ;)
```shell
$> datalad -c datalad.runtime.raiseonerror=yes aggregate-metadata
[INFO   ] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 
[ERROR  ] Failed to get dataset metadata (bids): 'ascii' codec can't decode byte 0xc2 in position 1188: ordinal not in range(128) [ascii.py:decode:26] 
[ERROR  ] Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately) [aggregate_metadata(/mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053)] 
aggregate_metadata(error): /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 [Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)]
[INFO   ] Update aggregate metadata in dataset at: /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 
aggregate_metadata(ok): /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 (dataset)                                                                                      
[INFO   ] Attempting to save 6 files/datasets 
save(notneeded): /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 (dataset)                                                                                             
action summary:
  aggregate_metadata (error: 1, ok: 1)
  save (notneeded: 1)
datalad -c datalad.runtime.raiseonerror=yes aggregate-metadata  7.57s user 2.24s system 105% cpu 9.312 total
(dev)3 10144 ->1.....................................:Mon 12 Feb 2018 10:46:40 AM EST:.
(git)smaug:\u2026nt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053[master]
$> datalad -c datalad.runtime.raiseonerror=yes --dbg aggregate-metadata
[INFO   ] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 
[ERROR  ] Failed to get dataset metadata (bids): 'ascii' codec can't decode byte 0xc2 in position 1188: ordinal not in range(128) [ascii.py:decode:26] 
[ERROR  ] Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately) [aggregate_metadata(/mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053)] 
aggregate_metadata(error): /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 [Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)]
[INFO   ] Update aggregate metadata in dataset at: /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 
aggregate_metadata(ok): /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 (dataset)                                                                                      
[INFO   ] Attempting to save 6 files/datasets 
save(notneeded): /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 (dataset)
action summary:
  aggregate_metadata (error: 1, ok: 1)
  save (notneeded: 1)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 432, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 413, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)'}]
()
> /home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py(413)generator_func()
-> msg="Command did not complete successfully")
(Pdb) 

```

#### What steps will reproduce the problem?
just try within ds000053

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
0.9.1-740-g39bb73d9

### CODE REVIEW

**Comment by mih** [comment]
I was not able to compose a test that would actually work. I tried with `run_main` in test_main.py via executing the `wtf` plugin. But the helper would not actually catch the output. I have to give up. Manual test, inside and outside a dataset, was successful.

**Comment by yarikoptic** [comment]
Worse comes to worse why not what you did, smth like 
```python
out, err = Runner()('DATALAD_DUMMY=this datalad plugin wtf |grep dummy', shell=True)
```
? seems to "work"
```shell
$> python -c 'from datalad.cmd import Runner; out, err = Runner()("DATALAD_DUMMY=this datalad plugin wtf |grep dummy", shell=True); print out'
datalad.dummy: this

(dev) 3 9700.....................................:Tue 13 Feb 2018 01:57:20 PM EST:.
hopa:~
$> python -c 'from datalad.cmd import Runner; out, err = Runner()("datalad -c datalad.dummy=this plugin wtf |grep dummy", shell=True); print out'        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 181, in __call__
    return self.run(cmd, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 514, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command 'datalad -c datalad.dummy=this plugin wtf |grep dummy' failed with exitcode 1
Failed to run 'datalad -c datalad.dummy=this plugin wtf |grep dummy' under None. Exit code=1. out= err=
```

**Comment by mih** [comment]
@yarikoptic Thanks, that worked!

**Comment by mih** [comment]
Objectively works.

**Pull request merged**
