### PR TITLE
prep-travis-forssh: Support Docker installations using Docker Machine

### PR DESCRIPTION
**Pull request by jwodder**
This change is necessary in order for the script to work when used by datalad/git-annex on GitHub Actions' macOS environments.

cf. https://github.com/datalad/git-annex/issues/42

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo!!! Could you please rebase it against `maint` -- we better fix it there as well

**Comment by jwodder** [comment]
@yarikoptic Base changed to maint.

**Comment by yarikoptic** [comment]
(disregard travis - NFS, and github actions red -- probably initial pre-rebased one marked red)

appveyor is odd... one Mac run is green but then 3 for `MacP38a{1,2,3}` red and even didn't run...  may be it got confused by rebase somehow?  @jwodder, could you force push some change (unless someone has a better idea on what is going on there?)

**Comment by jwodder** [comment]
@yarikoptic Trivial change force-pushed.

**Comment by kyleam** [comment]
The only remaining failure is the nfs stall.

**Pull request merged**
