### PR TITLE
TEMP: try with new annex merged into conda-forge 1h ago

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by kyleam** [comment]
`conda install` isn't finding the new version (probably isn't available yet): https://travis-ci.org/github/datalad/datalad/jobs/710484358#L916

It looks like install-annex.sh needs to detect if the `conda install` fails.

**Comment by kyleam** [comment]
Tried locally, and the new version is there now.  Will restart the Travis build.

**Comment by yarikoptic** [comment]
Something really wrong with this conda build, yet to look in details

```
datalad.support.exceptions.CommandError: CommandError: 'git fetch --verbose --progress --prune --recurse-submodules=no target1' failed with exitcode 128 under /tmp/datalad_temp_test_gh1763rp4bl6a9 [err: 'Bad owner or permissions on /home/travis/.ssh/config
ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/tmp/datalad_temp_op36k3iu/.cache/datalad/sockets/e9cb6b28 datalad-test' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.']
```
attn @notestaff

**Comment by notestaff** [comment]
From the error messages, sounds like this could be due to transient errors -- try restarting?  ("ssh: Could not resolve hostname localhost: Name or service not known")
Also try re-rendering with the latest conda-smithy

**Comment by notestaff** [comment]
P.S.  To see if the error is due to the latest git-annex build  on conda-forge, try requiring the previous version in meta.yaml

**Comment by yarikoptic** [comment]
I have restarted the Travis build but it is unlikely it was something transient with static localhost.

**Comment by yarikoptic** [comment]
As for previous version - will be next step, it default ATM is to test with 7.20190819

**Comment by yarikoptic** [comment]
So resorting to previous didn't help really... We need to retry with current in conda

**Comment by yarikoptic** [comment]
too old, needs a fresh start some time

**Pull request closed without merging**
