### PR TITLE
RF+BF: make cookies db access/closing more robust

### PR DESCRIPTION
**Pull request by yarikoptic**
While running tests under some conda environment, there were errors while closing
cookies DB. Could not reproduce in the native Debian environment with similarishish
Python.  With these changes, cookies_db is a property so it gets properly
loadded before setting any value. And also we catch exceptions upon
close and report them as a warning if there were some cookies to store.

Unfortunately Python in conda env still prints directly the entire traceback, and
on Debian some error message even before throwing the exception so you could see something like

    $> DATALAD_LOG_LEVEL=INFO python -m nose -s -v datalad/support/tests/test_cookies.py
    datalad.support.tests.test_cookies.test_no_blows ... [WARNING] Failed to save possibly updated 1 cookies (best): [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_test_no_blows1_rmfcb2/mycookies.dat' [dumb.py:_setval:178]
    Exception ignored in: <function _Database.close at 0x7f1fe46872f0>
    Traceback (most recent call last):
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/dbm/dumb.py", line 284, in close
        self._commit()
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/dbm/dumb.py", line 135, in _commit
        with self._io.open(self._dirfile, 'w', encoding="Latin-1") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_test_no_blows1_rmfcb2/mycookies.dir'
    ok

### CODE REVIEW

**Comment by yarikoptic** [comment]
attn @notestaff - this is one of the issues I ran into while running datalad tests under conda

**Comment by yarikoptic** [comment]
ok, merged fixed up 0.11.x -- hopefully now it would all get green!

**Comment by kyleam** [comment]
> ok, merged fixed up 0.11.x -- hopefully now it would all get green!

I don't spot any changes in 0.11.x that would help here.  There were two failures: (1) [one appveyor build][0] showed the unrelated test_autoenabled_remote_msg failure that we've been seeing elsewhere and (2) test_cookies.test_no_blows failed on the [Travis nfsmount build][1].

```
======================================================================
ERROR: datalad.support.tests.test_cookies.test_no_blows
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/tests/test_cookies.py", line 37, in test_no_blows
    rmtree(cookiesdir)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 391, in rmtree
    _rmtree(path, *args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 1852, in wrapped
    return f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 1892, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000002b00f80000022b'
```

[0]: https://ci.appveyor.com/project/mih/datalad/builds/26865864/job/8fsb0oqbnyb9gvlm
[1]: https://travis-ci.org/datalad/datalad/jobs/574993309#L1191

**Comment by yarikoptic** [comment]
0.11.x -- I forgot that it was neuroimaging which was triggering the failures fixed by #3616.
thanks for the failure extract -- bloody NFS ;) I guess I will try to ignore OSError for this `rmtree` and see if test still succeeds. alternative would be to rename that directory before trying to remove so it is really "gone" in a sense of the path name.

**Pull request merged**
