### PR TITLE
Github workflow to run benchmarks against master

### PR DESCRIPTION
**Pull request by mih**
I canceled all other CIs

### CODE REVIEW

**Comment by yarikoptic** [comment]
Hm, when I click on green vs-master on the phone it just reloads this page, so can't see actual logs etc

**Comment by yarikoptic** [comment]
In desktop mode guess to Checks tab, which is not present in Mobile view.

**Comment by mih** [comment]
Good to go then?

**Comment by yarikoptic** [comment]
Sure!

**Comment by yarikoptic** [comment]
But ideally we should add "Diff benchmarks" with just `asv compare` call after "Run benchmarks" so when expanded it just shows the diff.  Now you need to scroll for a while to skip all the setup/running

**Pull request merged**
