### PR TITLE
Enh bring gc back

### LINKED ISSUE #3457: Bring back git gc
ATM we explicitly disable git's gc during calls to git/annex since GitPython's state might get outdated and we did experience problems in the past.  But that often, largely after a sweep of git annex actions, leaves **huge** .git/objects behind and then mandates either running some `git` commands manually to get gc triggered or an explicit run to `gc`.  Example after a one large `datalad save` call:
```shell
$ du -scm .git/objects
1978    .git/objects
1978    total

$ git gc --prune=now
Counting objects: 524428, done.
Delta compression using up to 40 threads.
Compressing objects: 100% (520901/520901), done.
Writing objects: 100% (524428/524428), done.
Total 524428 (delta 50448), reused 18895 (delta 1701)
Removing duplicate objects: 100% (256/256), done.
Checking connectivity: 524428, done.

$ du -scm .git/objects
71      .git/objects
71      total
```

Especially if GitPython would be gone, or may be even without it (could have been fixed up in GitPython to react upon gc?) we should consider dropping disabling of automatic gc.  I will submit a test PR to see if things still get crashing (unable to find objects etc) ;-)

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #3457 if we decide to go for it

### CODE REVIEW

**Comment by kyleam** [comment]
Ah, but doing that globally is not a good idea because we don't know which dataset(s) to run it in.

**Comment by yarikoptic** [comment]
So only neuroimaging expected failure.. hm... Will rerun it a few times later when after neuroimaging

**Comment by yarikoptic** [comment]
appveyor failure might be "legit"... restarted

**Comment by yarikoptic** [comment]
I have reran travis a few times and it seems to show no bad signs... should we merge?

**Comment by kyleam** [comment]
> should we merge?

I think so.  Easy enough to revert if the issues pop up again.

**Comment by yarikoptic** [comment]
ok, let's see what would happen ;)

**Pull request merged**
