### PR TITLE
ENH/BF/RF: GitHub authentication

### LINKED ISSUE #2004: datalad create-sibling-github interactive configuration does not support 2FA
#### What is the problem?

I set up two factor authentication (as everybody should! ;)), and the interactive configuration of `datalad create-sibling-github` doesn't work. Also the suggested method in the manpage (using https://github.com/sociomantic/git-hub) fails, because they do not support 2FA yet. The solution is to create manually a personal access token here: https://github.com/settings/tokens/new. 

I can update the manpage if desired.

#### What steps will reproduce the problem?

```terminal
contematto@head1 /data/famface/openfmri/data (master) $ datalad create-sibling-github famface_data
You need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access
user: mvdoc

password:
password (repeat):
[ERROR  ] 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'} [Requester.py:__check:180] (TwoFactorException)
```

### LINKED ISSUE #2005: datalad create-sibling-github doesn't support oauth
#### What is the problem?

Because I have two-factor authentication on (see also #2004), I had to set up a personal access token. I seem to have everything set up correctly, but when I do `datalad create-sibling-github reponame` it still asks me for username and password, and then fails. 

From playing around a bit with the code, it seems that it asks me for user and password here https://github.com/datalad/datalad/blob/33b590557d87eb42ded4821319757e03fcda5121/datalad/distribution/create_sibling_github.py#L85-L90 

even though `github_login` is set to the token

```
(datalad) contematto@head1 /data/famface/openfmri/data (master) $ datalad create-sibling-github famface_data
> /home/contematto/github/datalad/datalad/distribution/create_sibling_github.py(79)_get_github_entity()
-> creds = cred()
(Pdb) l
 74                     cred.enter_new(
 75                         user=github_login,
 76                         password=github_passwd)
 77             # now we should really have it
 78             import pdb; pdb.set_trace()
 79  ->         creds = cred()
 80             github_login = creds['user']
 81             github_passwd = creds['password']
 82
 83         if not github_login:
 84             raise gh.BadCredentialsException(403, 'no login specified')
(Pdb) p github_login
'XXXXXXXXXXXXXXXXXXXXXXa43cde86'
```

and then this happens

```
(Pdb) c
You need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access
password:
You need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access
password (repeat):
> /home/contematto/github/datalad/datalad/distribution/create_sibling_github.py(93)_get_github_entity()
-> try:
(Pdb) c
[WARNING] Authentication failed, deleting stored credential github
[ERROR  ] 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'} [Requester.py:__check:180] (BadCredentialsException)
```

#### What version of DataLad are you using (run `datalad --version`)? 

datalad 0.9.1.dev432

### LINKED ISSUE #3126: Credentials should be tested before being stored
#### What is the problem?

When creating a sibling on GitHub for the first time, the username and password provided are stored. If someone has 2FA enabled, then they actually need a token, and not their password. However, the username and password are now stored in a keychain. The default behavior on the next round is not to ask again, but to attempt to reuse the bad credentials.

#### What steps will reproduce the problem?

Start from a fresh environment with no stored credentials.

```Shell
$ datalad create newrepo
$ pushd newrepo
$ datalad create-sibling-github <github-url>
You need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access
user: USERNAME

password: 
password (repeat): 
[ERROR  ] 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'} [Requester.py:__check:275] (GithubException)
$ datalad create-sibling-github <github-url>
[ERROR  ] 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'} [Requester.py:__check:275] (GithubException)
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

```
# WTF
- path: /Users/markiewicz/Projects/crn/fitlins-test-ds000003
- type: dataset
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.11.1
  - version: 0.11.1
## dataset 
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /Users/markiewicz/Projects/crn/fitlins-test-ds000003
  - repo: AnnexRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:annex: 7.20181212-g2f8c5bd4c
  - cmd:git: 2.18.0
  - cmd:system-git: 2.19.1
  - cmd:system-ssh: 7.9p1
  - git: 2.1.11
  - gitdb: 2.0.5
  - humanize: 0.5.1
  - iso8601: 0.1.12
  - keyring: 17.0.0
  - keyrings.alt: 3.1.1
  - msgpack: 0.6.0
  - requests: 2.21.0
  - six: 1.12.0
  - tqdm: 4.28.1
  - wrapt: 1.10.11
## environment 
  - GIT_PYTHON_GIT_EXECUTABLE: /Applications/git-annex.app/Contents/MacOS/git
  - LANG: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /anaconda3/bin:/anaconda3/condabin:/Applications/freesurfer/bin:/Applications/freesurfer/fsfast/bin:/Applications/freesurfer/tktools:/usr/local/fsl/bin:/Applications/freesurfer/mni/bin:/usr/local/fsl/bin:/Users/markiewicz/bin:/usr/local/bin:/Users/markiewicz/abin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Applications/git-annex.app/Contents/MacOS/
## extentions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3(multipartupload)(storageclasses)
    - WebDAV
    - FsEvents
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.2
    - feed-1.0.1.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 5
  - operating system: darwin x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20181212-g2f8c5bd4c
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## system 
  - distribution:  10.14.2/x86_64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 308
  - name: Darwin
  - release: 18.2.0
  - type: posix
  - version: Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
```

#### Is there anything else that would be useful to know in this context?

I did figure out how to remove the credentials from my keychain. I just don't think I should have had to.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

This is my first attempt to create a dataset on my own.

### PR DESCRIPTION
**Pull request by yarikoptic**
This pull request fixes #2004 , fixes #2005, and I also think it might fix #3126 if @effigies says so ;-)

This pull request proposes to do a more thorough pass over possibly available github authentication mechanisms to achieve the goal.  I have tried to maintain currently present "non standard" handling of authentication for github:

- token - we do not store those in the credentials store, but rely on it/them being present in the (git) config.  But since multiple tokens could be defined (globally, and then within a dataset), we might need to consider multiple (I somehow get 3 values with 2 unique ones)
- user/password could be provided in the command line (we don't do that for any other remote etc)

change in behavior
- provided in cmdline user/password are not stored in the credential store (and thus also not deleted - so no dances with removing some credential if smth doesn't work)

additional changes
- `.ui.question` has now `repeat` option (defaults to `None` to maintain previous behavior) to be able to force or disable repeated entry for a hidden value.  In my case I wanted to get rid of it -- entering 2FA token twice is really not called for
- `.utils.unique` got option `reverse=False` which, if set to `True`, would return unique values while maintaining the order from the back (not from the front as originally)

overall now for `create-sibling-github`:

- multiple ways to authenticate are considered - we pretty much loop until we succeed by offering user to enter new user/password or until we really fail
- unless both user and password are provided in command line, tokens are considered first (if user/password are provided -- no stored tokens are considered)
- if user (no password) is provided, only the token(s) associated with that user will be considered
- regular user/password credential is considered next, if fails, asked to re-enter
- if it is detected that user/password authentication leads to 2FA error, we offer to generate token (with "user" and "repo" permissions) and store it in config ("global", "local", no "dataset) (or not store at all - empty value)
   - we only alert/error out if a token with our note (DataLad) already exists
- if session is non-interactive, we don't do much really, and I guess with 2FA even if user/password are provided - we would simply fail. So token must be set via config first then

In addition to authentication related changes

### TODOs
- [x] Move all the `_` helper functions which now also `import github as gh` into `datalad.support.github_`. I kept that in-place for now with hope to still have some meaningful `diff`
- [x] make it possible to avoid reentering the login name if it was specified (see U1 below)
- [ ] consider reverting aforementioned change in behavior that credentials aren't stored if provided in the cmdline.  May be there should be `ui.question` to either do it or not and if not interactive - an INFO msg.
- [x] Try to come up with at least some rudimentary test for all the authentication logic

I would really appreciate any attempts to use it - once again, I have tried it only in a few scenarios and there were no and remain no tests for all the logic there.

**U1

```shell
$> datalad create-sibling-github --github-login yarikoptic-test --name gh-yarikoptic-test shablona
You need to authenticate with 'yarikoptic-test@github' credentials. https://github.com/login provides information on how to gain access
user: 
```

### CODE REVIEW

**Comment by yarikoptic** [comment]
ok, noone is interested to try/review - so I will just plow forward with RF, so diff would increase ;-)

**Comment by effigies** [comment]
Hmm. Well, I tried using this branch to test out #3126, but it turned out that I was using 0.11.2 from Neurodebian. After making sure I was using your branch, it still opened up the existing keyring, and did not invalidate the credentials:

```Shell
$ datalad create-sibling-github test_repo
Please enter password for encrypted keyring: 
[ERROR  ] module 'github' has no attribute 'TwoFactorException' [create_sibling_github.py:_gen_github_ses:171] (AttributeError) 
$ datalad create-sibling-github test_repo
Please enter password for encrypted keyring: 
[ERROR  ] module 'github' has no attribute 'TwoFactorException' [create_sibling_github.py:_gen_github_ses:171] (AttributeError) 
```

I'll need to figure out where the keyring is to delete it and try again from scratch, but at least this, as currently written, won't lead to a situation where upgrading gets people out of a pre-existing credential jam.

**Comment by yarikoptic** [comment]
Smells like outdated github module, what version do you have? May be it is listed in datalad wtf

**Comment by effigies** [comment]
```Shell
$ conda list | grep github
pygithub                  1.34                     py36_0    conda-forge
```

**Comment by effigies** [comment]
Updated to pygithub 1.43.5:

```
$ datalad create-sibling-github test_repo
You need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access
user: effigies

password: 
password (repeat): 
[ERROR  ] 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'} [Requester.py:__check:275] (GithubException) 
$ datalad create-sibling-github test_repo
[ERROR  ] 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'} [Requester.py:__check:275] (GithubException) 
```

**Comment by yarikoptic** [comment]
FWIW I have python{,3}-github package 1.40-1 from debian buster/sid.

With the changes here, if you already have `hub.oauthtoken` defined in your .git/config (or globally) it should have not come to the user/password authentication AFAIK if you used this branch. Could you please try running with `datalad -l debug ...` -- you should see a message like

```
[DEBUG  ] Selected 1 tokens out of 2 for the login datalad-tester
```
(in my case there is one token defined in ~/.gitconfig as well for another account).
Meanwhile, I've confirmed that with upgraded pygithub to 1.43.5 there is a regression of some kind when there is no token and we try to generate one - instead of `TwoFactorException` it throws `GithubException`.  I have added a workaround (for now at least) in 669fa6d563a5d34648c3d51ad7c7e9bcf17df202 -- it MUST work now ;)

**Comment by yarikoptic** [comment]
@effigies I see now that I have forgotten to bring it to your `@ttention` :-/ the things should work now for you, feedback would be appreciated!

**Comment by effigies** [comment]
@yarikoptic This works for me.

```
$ datalad create-sibling-github test_repo
GitHub credentials - effigies uses 2FA
Generate a GitHub token to proceed? If you already have a token for the account, just say 'no' now and specify it in config (hub.oauthtoken), otherwise say 'yes'  (choices: yes, no): yes

2FA one time password: 
Where to store token f9c...1bd?
Empty string would result in the token not being stored for future reuse, so you will have to adjust configuration manually (choices: global, local, ): global

[INFO   ] Stored hub.oauthtoken=f9c...1bd in global config. 
.: github(-) [https://github.com/effigies/test_repo.git (git)]
'https://github.com/effigies/test_repo.git' configured as sibling 'github' for <Dataset path=/home/cjmarkie/test_repo>
```

Thanks, this is way better UX than navigating GitHub to generate the token and then guess how to insert it into Datalad's prompts.

**Comment by yarikoptic** [comment]
Thank you @effigies for trying it out!  I should now find some time to add basic testing of all that UI logic so we have some assurance that it remains working ;-)

**Comment by yarikoptic** [comment]
Woohoo, so the testing approach seems to work! Please review, in particular to see if I didn't leak anything sensitive. Next I will try to address coverage of more of the diff and may be minor code shuffling/moving I have mentioned in the original message

**Comment by yarikoptic** [comment]
grr, codecov didn't report after my last push with rewrite... will need to push more

**Comment by yarikoptic** [comment]
@mvdoc Would you be kind/interested to test out this PR if it works for you -- should resolve 2FA issues

**Comment by yarikoptic** [comment]
well, indeed, things couldn't become worse with this PR, so -- merging!

**Comment by yarikoptic** [comment]
actually, for paranoid me -- would be nice to know what is in those binary blob responses:
```
+      string: !!binary |
+        H4sIAAAAAAAAA6VTyW7bMBT8F52jSFYdtzYQtIekRQ+FUSCHIhfiSXqSGVOkysWGa+TfO1qSKHGA
+        Au5NpDhDzvKOkTK11NEqKsmTojL27Dzb2Ng6uohkGa3my+Vs8SlLLyJtShbdVvTj5vaw3i4P99nX
+        QL/aTflN7fKHn1fru9tsffN9D2iwCgc33rdulSTUysta+k3ILwvTJGB3ybs3Wm6NE+eAkx6Km3nH
+        2p/JMWBBsjFmeyZHD+3Mcy7wmRwDFiQNNznbM1lG8DEZPh7B14ZcyUL8F+1rjik77dAi+za+ftOl
+        YwGCY1sY7RFS34WQPDXs8+56jieW7AorWy8NeqmDUp2VYsdWVpLRvoqUYyRETqBHpOUf6s6K1poH
+        LryLVt6G8UDfCemNPZz8HlUMrVnNnq2ppes40PfKKGX2cH+ykrruVxvfqDc6J/1+t9qFZfJcCvIY
+        jCydLeN0Hmcf7maLVZphzO67qWkB/ccZf2gZDOuJdiC9wfxCpITbLEZVeKjZa/Cd7j/tvMgtpduK
+        4KgGO4AF1FNuLMG9wYFcKgX9ghuS3XDDWI4H1fFrxV+MZhuck6S7jPtQKwrKDw8bA2HboOd9zBG8
+        KSd1L0iLwa8XhOTnaP3eiIoKvAy/fwdpuUGdBGvK1aQirSJwHyNNTedYZZlxh2upwHL5cXG1yNA9
+        JH/iWgWpsM0hMVw6B2j4Sh8f/wKjzBz6MwUAAA==
```
I will check on that first ;)

**Comment by yarikoptic** [comment]
ok, looked at a few -- seems to be ok
```shell
$> xsel -o | sed -e 's,^+ *,,g' | base64 -d | gunzip | jq '.'
{
  "login": "datalad-tester",
  "id": 22943981,
  "node_id": "MDQ6VXNlcjIyOTQzOTgx",
  "avatar_url": "https://avatars1.githubusercontent.com/u/22943981?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/datalad-tester",
  "html_url": "https://github.com/datalad-tester",
  "followers_url": "https://api.github.com/users/datalad-tester/followers",
  "following_url": "https://api.github.com/users/datalad-tester/following{/other_user}",
  "gists_url": "https://api.github.com/users/datalad-tester/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/datalad-tester/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/datalad-tester/subscriptions",
  "organizations_url": "https://api.github.com/users/datalad-tester/orgs",
  "repos_url": "https://api.github.com/users/datalad-tester/repos",
  "events_url": "https://api.github.com/users/datalad-tester/events{/privacy}",
  "received_events_url": "https://api.github.com/users/datalad-tester/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "http://datalad.org",
  "location": "Cyberspace",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2016-10-19T19:30:33Z",
  "updated_at": "2019-03-04T04:29:37Z",
  "private_gists": 0,
  "total_private_repos": 0,
  "owned_private_repos": 0,
  "disk_usage": 12,
  "collaborators": 0,
  "two_factor_authentication": true,
  "plan": {
    "name": "free",
    "space": 976562499,
    "collaborators": 0,
    "private_repos": 10000
  }
```

**Pull request merged**
