### PR TITLE
Temp test devel annex

### PR DESCRIPTION
**Pull request by yarikoptic**
should be the fixed up bleeding edge 7.20190708+git9-gfa3524b95-1~ndall+1

### CODE REVIEW

**Comment by kyleam** [comment]
Looking good.

**Comment by yarikoptic** [comment]
But what is going on with Travis reporting? May be we need to relink or something?

**Comment by kyleam** [comment]
> But what is going on with Travis reporting? May be we need to relink or something?

I see Travis listed in the checks above, but I did notice it was missing from #3516.  Is that what you're referring to or are you not seeing it on this PR either?

**Comment by yarikoptic** [comment]
I could have sworn that it was not here either, but now I see it reporting failure (-containers, known). So all good -- closing and uploading to neurodebian proper

**Pull request closed without merging**
