### PR TITLE
Command to execute "prepared procedures"

### PR DESCRIPTION
**Pull request by mih**
Rational is in #2593 AKA

- dataset templates
- `run-before`/`run_after`
- `configuration snippets`

The current state of the PR implements the procedural aspects of #1462.

This will not be complete until `run` gets a feature extension discussed in #2593. But already does meaningful things now (but limited to clean datasets right now).

Desired functionality is not limited to dataset management/setup use cases (for which datalad could ship a bunch of procedures), but also targets totally custom user-provided functionality. Example:

A dataset can provided implementations of a bunch of algorithms. Another dataset can include this dataset as a subdataset and configure its own `datalad.locations.dataset-procedures` config to extend search for procedures to the subdataset directory. This can be used to expose a "toolchain" of arbitrary procedures to the new parent dataset. Such procedures can be full blow data processing pipelines...

TODOs (not necessarily all in this PR):

- [x] revive the `run-before`/`run_after` functionality that is commented out right now. This will reenable the configuration handling to run arbitrary procedures before and after other commands, based on user configuration. Use case: "create --run-after mydatasetsetuproutine" -> dataset templates.
- [x] any datalad extension can provide additional procedures
- [x] dataset template for YODA datasets (demo stage)
- [ ] make `run` work with dirty datasets  @kyleam do you have some extra juice for that?
   #2607 
- [x] test to pull procedure config from git config and run before a command

### CODE REVIEW

**Comment by kyleam** [comment]
> make run work with dirty datasets @kyleam do you have some extra juice for that?

I'll take a look at it today.

**Comment by mih** [comment]
OSX looks like spurious connection failure

**Comment by mih** [comment]
All the controversy seems to around #2607 -- hence merging this one. It is impaired by the lack of functionality equivalent to #2607, but nevertheless functional.

**Comment by mih** [comment]
Arrg, forgot that docs were pending... Coming shortly.

**Pull request merged**
