### PR TITLE
DOC: fix EnsureCallable docstring

### PR DESCRIPTION
**Pull request by matrss**
Just a small fix for a copy-paste mistake.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Looks good to me but I think it better goes against `maint` branch.

**Comment by matrss** [comment]
Makes sense. I changed the target branch to maint and rebased onto it.

**Comment by yarikoptic** [comment]
Great, thank you!

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.18.1`](https://github.com/datalad/datalad/releases/tag/0.18.1)

**Pull request merged**
