### PR TITLE
BF: make AnnexRepo.add() raise an IncompleteResultsException if any non-success

### PR DESCRIPTION
**Pull request by yarikoptic**
Initial awareness came from troubleshooting on Windows
https://github.com/datalad/datalad/issues/5015#issuecomment-709436065

Majority of .add (as opposed to .add_ generator) invocations are not
testing/using returned value and GitRepo.add would return only
success-ful results and raise some Exception otherwise.

Since AnnexRepo.add relies on add_ which is going through --json
mode of git-annex to provide both succeeded and not results,
add() just returned records with success: False and did not
raise any exception (even if GitAnnex exited with non-0).  That is not
"in-line" with GitRepo.add and also leads to us not detecting errors
when plain AnnexRepo.add  is used.

I have not figured out a better/less confusing way than to add additional kwarg
expect_success to _run_annex_command_json .  Generator versions then would set
it to False, while outside "procedural" ones, where not "manually" processing
results (e.g. like .copy_to does), should set it to True for the
"centralized" handling.

I have subsequent similar changes (also introducing matching `_` generator forms) to some other AnnexRepo interfaces (eg `get`, `drop`, ...) which IMHO should be done to unify behavior and avoid "errors disregard".  Although some of them should probably go against `maint`, not yet sure if should, or should go against `master`.  First I want to see if any side-effects from `add` "fixup".

<details>
<summary>current version of that further patch</summary> 

```diff
diff --git a/datalad/distribution/drop.py b/datalad/distribution/drop.py
index 64a7292c1..03adec72d 100644
--- a/datalad/distribution/drop.py
+++ b/datalad/distribution/drop.py
@@ -94,7 +94,7 @@ def _drop_files(ds, paths, check, noannex_iserror=False, **kwargs):
 
     opts = ['--force'] if not check else []
     respath_by_status = {}
-    for res in ds.repo.drop(paths, options=opts):
+    for res in ds.repo.drop_(paths, options=opts):
         res = annexjson2result(
             # annex reports are always about files
             res, ds, type='file', **kwargs)
diff --git a/datalad/distribution/get.py b/datalad/distribution/get.py
index 925b61919..60542cbb8 100644
--- a/datalad/distribution/get.py
+++ b/datalad/distribution/get.py
@@ -584,7 +584,9 @@ def _get_targetpaths(ds, content, refds_path, source, jobs):
     for res in ds_repo.get(
             content,
             options=['--from=%s' % source] if source else [],
-            jobs=jobs):
+            jobs=jobs,
+            expect_success=False,
+    ):
         res = annexjson2result(res, ds, type='file', logger=lgr,
                                refds=refds_path)
         success = success_status_map[res['status']]
diff --git a/datalad/plugin/addurls.py b/datalad/plugin/addurls.py
index a401171fe..1843370cf 100644
--- a/datalad/plugin/addurls.py
+++ b/datalad/plugin/addurls.py
@@ -25,7 +25,10 @@ from datalad.interface.base import Interface
 from datalad.interface.base import build_doc
 from datalad.interface.results import annexjson2result, get_status_dict
 from datalad.interface.common_opts import nosave_opt
-from datalad.support.exceptions import AnnexBatchCommandError
+from datalad.support.exceptions import (
+    AnnexBatchCommandError,
+    IncompleteResultsError,
+)
 from datalad.support.network import get_url_filename
 from datalad.support.path import split_ext
 from datalad.support.s3 import get_versioned_url
@@ -522,7 +525,7 @@ def add_urls(rows, ifexists=None, options=None):
         try:
             out_json = ds.repo.add_url_to_file(filename, row["url"],
                                                batch=True, options=options)
-        except AnnexBatchCommandError as exc:
+        except (AnnexBatchCommandError, IncompleteResultsError) as exc:
             yield get_status_dict(action="addurls",
                                   ds=ds,
                                   type="file",
diff --git a/datalad/support/annexrepo.py b/datalad/support/annexrepo.py
index d978f1671..213ed3e52 100644
--- a/datalad/support/annexrepo.py
+++ b/datalad/support/annexrepo.py
@@ -1300,11 +1300,23 @@ class AnnexRepo(GitRepo, RepoInterface):
             If not specified (None), then
         key : bool, optional
             If provided file value is actually a key
+        expect_success : bool, optional
+            If set to False, no IncompleteResultsError will be raise if any
+            file fails to be obtained
 
         Returns
         -------
         files : list of dict
         """
+        # TODO:  should we here compare fetch_files against result_list
+        # and vomit an exception of incomplete download????
+        return list(self.get_(
+            files, remote=remote, options=options, jobs=jobs, key=key,
+            expect_success=True))
+
+    def get_(self, files, remote=None, options=None, jobs=None, key=False,
+             expect_success=False):
+        """Like `get`, but returns a generator"""
         options = options[:] if options else []
 
         if remote:
@@ -1346,18 +1358,14 @@ class AnnexRepo(GitRepo, RepoInterface):
             kwargs = {'opts': options + ['--key'] + files}
         else:
             kwargs = {'opts': options, 'files': files}
-        results = self._run_annex_command_json(
+        yield from self._run_annex_command_json(
             'get',
             # TODO: eventually make use of --batch mode
             jobs=jobs,
             expected_entries=expected_downloads,
             progress=True,
-            **kwargs
-        )
-        results_list = list(results)
-        # TODO:  should we here compare fetch_files against result_list
-        # and vomit an exception of incomplete download????
-        return results_list
+            expect_success=expect_success,
+            **kwargs)
 
     def _get_expected_files(self, files, expr, merge_annex_branches=True):
         """Given a list of files, figure out what to be downloaded
@@ -1444,8 +1452,7 @@ class AnnexRepo(GitRepo, RepoInterface):
         return list(self.add_(
             files, git=git, backend=backend, options=options, jobs=jobs,
             git_options=git_options, annex_options=annex_options, update=update,
-            expect_success=True
-        ))
+            expect_success=True))
 
     def add_(self, files, git=None, backend=None, options=None, jobs=None,
             git_options=None, annex_options=None, update=False, expect_success=False):
@@ -1534,8 +1541,7 @@ class AnnexRepo(GitRepo, RepoInterface):
                     jobs=jobs,
                     expected_entries=expected_additions,
                     expect_stderr=True,
-                    expect_success=expect_success,
-            )
+                    expect_success=expect_success)
 
     @normalize_paths
     def get_file_key(self, files, batch=None):
@@ -1634,6 +1640,8 @@ class AnnexRepo(GitRepo, RepoInterface):
         """
         if not files:
             return
+        # TODO: unify in unlock vs unlock_ behavior -- "higher-level" interface
+        # should just get full records and process them.
         return [j["file"] for j in
                 self._run_annex_command_json("unlock", files=files)
                 if j["success"]]
@@ -1964,6 +1972,7 @@ class AnnexRepo(GitRepo, RepoInterface):
                 opts=options + [files_opt] + [url],
                 progress=True,
                 expected_entries={file_: None},
+                expect_success=True,
                 **kwargs
             )
             if len(out_json) != 1:
@@ -2093,7 +2102,11 @@ class AnnexRepo(GitRepo, RepoInterface):
           'success' item in each object indicates failure/success per file
           path.
         """
+        return list(self.drop_(
+            files, options=options, key=key, jobs=jobs, expect_success=True))
 
+    def drop_(self, files, options=None, key=False, jobs=None, expect_success=False):
+        """Like `drop_`, but returns a generator"""
         # annex drop takes either files or options
         # --all, --unused, --key, or --incomplete
         # for now, most simple test; to be replaced by a more general solution
@@ -2112,25 +2125,21 @@ class AnnexRepo(GitRepo, RepoInterface):
             # one at a time
             files = assure_list(files)
             options = options + ['--key']
-            res = [
-                self._run_annex_command_json(
+            for k in files:
+                yield from self._run_annex_command_json(
                     'drop',
                     opts=options + [k],
-                    jobs=jobs)
-                for k in files
-            ]
-            # `normalize_paths` ... magic, useful?
-            if len(files) == 1:
-                return res[0]
-            else:
-                return res
+                    jobs=jobs,
+                    expect_success=expect_success)
         else:
-            return self._run_annex_command_json(
+            yield from self._run_annex_command_json(
                 'drop',
                 opts=options,
                 files=files,
-                jobs=jobs)
+                jobs=jobs,
+                expect_success=expect_success)
 
+    # TODO: unify? with add/add_ like for uniform expect_success ? (here just assert)
     def drop_key(self, keys, options=None, batch=False):
         """Drops the content of annexed files from this repository referenced by keys
 
@@ -2498,6 +2507,8 @@ class AnnexRepo(GitRepo, RepoInterface):
 
         options = ['--bytes', '--fast'] if fast else ['--bytes']
 
+        # Here we do post-processing and just provide None for records without
+        # 'success', thus not providing expect_success=True
         if not batch:
             json_objects = self._run_annex_command_json(
                 'info', opts=options, files=files, merge_annex_branches=False)
@@ -2550,8 +2561,8 @@ class AnnexRepo(GitRepo, RepoInterface):
         options = ['--bytes', '--fast'] if fast else ['--bytes']
 
         json_records = list(self._run_annex_command_json(
-            'info', opts=options, merge_annex_branches=merge_annex_branches)
-        )
+            'info', opts=options, merge_annex_branches=merge_annex_branches,
+            expect_success=True))
         assert(len(json_records) == 1)
 
         # TODO: we need to abstract/centralize conversion from annex fields
@@ -2565,7 +2576,6 @@ class AnnexRepo(GitRepo, RepoInterface):
                 else:
                     lgr.debug("Size %r reported to be %s, setting to None", k, size)
                     info[k] = None
-        assert(info.pop('success'))
         assert(info.pop('command') == 'info')
         return info  # just as is for now
 
@@ -3160,6 +3170,7 @@ class AnnexRepo(GitRepo, RepoInterface):
             if isinstance(files, str):
                 files = [files]
             # anything else is assumed to be an iterable (e.g. a generator)
+        # ??? expect_success?
         if batch is False:
             for res in self._run_annex_command_json(
                     'metadata', opts=['--json'], files=files):
@@ -3212,11 +3223,13 @@ class AnnexRepo(GitRepo, RepoInterface):
         """
         return list(self.set_metadata_(
             files, reset=reset, add=add, init=init,
-            remove=remove, purge=purge, recursive=recursive))
+            remove=remove, purge=purge, recursive=recursive,
+            expect_success=True,
+        ))
 
     def set_metadata_(
             self, files, reset=None, add=None, init=None,
-            remove=None, purge=None, recursive=False):
+            remove=None, purge=None, recursive=False, expect_success=False):
         """Like set_metadata() but returns a generator"""
 
         def _genspec(expr, d):
@@ -3246,11 +3259,12 @@ class AnnexRepo(GitRepo, RepoInterface):
         # operate on files that were just added.
         self.precommit()
 
-        for jsn in self._run_annex_command_json(
+        yield from self._run_annex_command_json(
                 'metadata',
                 args,
-                files=files):
-            yield jsn
+                files=files,
+                expect_success=expect_success,
+        )
 
     # TODO: RM DIRECT?  might remain useful to detect submods left in direct mode
     @staticmethod
@@ -3363,6 +3377,7 @@ class AnnexRepo(GitRepo, RepoInterface):
             else:
                 opts.extend(['--include', '*'])
 
+        # ??? Do we want expect_success=True here?
         for j in self._run_annex_command_json(cmd, opts=opts, files=files):
             path = self.pathobj.joinpath(ut.PurePosixPath(j['file']))
             rec = info.get(path, None)
diff --git a/datalad/support/tests/test_annexrepo.py b/datalad/support/tests/test_annexrepo.py
index 36ce28d0b..3baed1141 100644
--- a/datalad/support/tests/test_annexrepo.py
+++ b/datalad/support/tests/test_annexrepo.py
@@ -432,7 +432,7 @@ def test_AnnexRepo_web_remote(sitepath, siteurl, dst):
     eq_(len(l), 1)
 
     # now only 1 copy; drop should fail
-    res = ar.drop(testfile)
+    res = next(ar.drop_(testfile))
     eq_(res['command'], 'drop')
     eq_(res['success'], False)
     assert_in('adjust numcopies', res['note'])
@@ -1371,7 +1371,8 @@ def test_annex_drop(src, dst):
     eq_(len([f for f in ar.fsck(fast=True) if f['file'] == testfile]), 1)
 
     # drop file by name:
-    result = ar.drop([testfile])
+    # use generator version so it doesn't raise even if fails
+    result = list(ar.drop_(testfile))
     assert_false(ar.file_has_content(testfile))
     ok_(isinstance(result, list))
     eq_(len(result), 1)
@@ -1383,7 +1384,7 @@ def test_annex_drop(src, dst):
 
     # drop file by key:
     testkey = ar.get_file_key(testfile)
-    result = ar.drop([testkey], key=True)
+    result = list(ar.drop_(testkey, key=True))
     assert_false(ar.file_has_content(testfile))
     ok_(isinstance(result, list))
     eq_(len(result), 1)
```
</details>

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm... 

<details>
<summary>test fails on travis consistently across runs</summary> 

```shell
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_ro_operations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py", line 197, in _wrap_skip_if_on_windows
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py", line 220, in _wrap_skip_if_root
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py", line 573, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 2327, in test_ro_operations
    assert_equal(rec[0]['success'], False)
AssertionError: True != False
```
</details>

<details>
<summary>but passes for me locally, as annex should have not succeeded to `add` a read-only file owned by root</summary> 

```shell
$> python -m nose -s -v datalad/support/tests/test_annexrepo.py:test_ro_operations
datalad.support.tests.test_annexrepo.test_ro_operations ... /home/yoh/.tmp/datalad_temp_tree_test_ro_operations1mwlqb2v/clone             [annex]  master  ✗ 2020-10-17/00:26:12  ✓  5 Bytes/5 Bytes
ok
Versions: annexremote=1.4.3 appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200908+git175-g95d02d6e2-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.28.0 cmd:system-ssh=8.1p1 exifread=2.1.2 git=3.1.0 gitdb=4.0.2 humanize=2.3.0 iso8601=0.1.12 keyring=18.0.1 keyrings.alt=3.4.0 msgpack=0.6.2 mutagen=1.40.0 requests=2.23.0 scrapy=1.7.3 wrapt=1.11.2
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'"

----------------------------------------------------------------------
Ran 1 test in 3.821s

OK
```
</details>
strange... big `grep` lead me to commented out test code in the same test:
```
        # Oh well -- not raised on travis... whatever for now
        #with assert_raises(CommandError):
        #    repo2.repo_info()
```
so it smells like something specific/chronic on travis setup.  I thought to just condition it on travis, but the same happens on github OSX actions.  I guess need to investigate more :-/ (idea: may be chown and/or chmod did not do what they were supposed to , may be group permissions are too permissive.  I will make it `root.root`!)

**Comment by yarikoptic** [comment]
woohoo -- at least reproduced locally. I was special with my umask. setting it to 022 caused me to become less special. (`chgrp` did not help BTW)

**Comment by mih** [comment]
Please see #4872 for an alternative "approach"

**Comment by yarikoptic** [comment]
> Please see #4872 for an alternative "approach"

That approach has the same flaw as our current code -- if there is a faulted run, it would just return a record with `"status": "error"`. All code (e.g. in tests) which uses it as a "just a function to invoke" and relies on it to raise exception if something went wrong would proceed missing that fact that there was an error.

**Comment by yarikoptic** [comment]
And `add` is not the only one - see patch in this PR description. That patch would propose to "harmonize" our *Repo API to have non generator (without `_` suffix) versions of functions to raise an exception if any error happened, and keep yielding without exception in case of a generator. 
An actual alternative I thought of now could be: make `_run_annex_command_json` into a generator, and always raise but AFTER yielding all records available (i.e. with error status as well) -- then outside code would need to try/except, as it already should anyways since there could be other exceptions (CommandError) as well.  That would then provide a "fix" also for `_save_add_`

**Comment by mih** [comment]
We just need to keep in mind that low-level methods should not interfere with high-level error handling. It is still problematic in various cases. Any change should have that on the radar. Otherwise, we need to continue to pull functionality into the high-level commands and further bypass Repo-methods.

**Comment by yarikoptic** [comment]
ok, travis is happy now, but OSX shows its "difference":
```
datalad.support.exceptions.CommandError: CommandError: 'sudo -n chown 501 -R /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_tree_test_ro_operationsgvrkz6pv/repo/d2' failed with exitcode 1 [err: 'chown: -R: No such file or directory']
```
I guess just because -R should precede UID (501), force pushed the fix

**Comment by mih** [comment]
In #5163 I found a similar case: `AnnexRepo.drop()` will not raise an exception when dropping fails. Instead such failure can only be inferred from result inspection. In my rewrite of the annex execution helpers, this will change.

**Comment by yarikoptic** [comment]
yeap, yeap, as I have mentioned in the original description: 

    I have subsequent similar changes (also introducing matching _ generator forms) to some other AnnexRepo interfaces (eg get, drop, ...) which IMHO should be done to unify behavior and avoid "errors disregard"

so the issue is wide-spread

**Pull request closed without merging**
