### PR TITLE
Initial export_to_figshare

### LINKED ISSUE #1473: figshare could be supported as a provider and for export
There is an API wrapper at https://pypi.python.org/pypi/pigshare

I was able to upload a file into a newly created dataset without much trouble, after creating an access token on the figshare site.

### PR DESCRIPTION
**Pull request by yarikoptic**
This pull request fixes #1473 (somewhat)

example with all the typos etc

```shell
(git-annex)hopa:/tmp/test[master]git
$> datalad --dbg plugin export_to_figshare       
[INFO   ] Exporting current tree as an archive since figshare does not support directories 
[INFO   ] Uploading /tmp/test/datalad_a9577654-b90f-11e7-9372-8019340ce7f2.zip to figshare 
Article
Would you like to create a new article to upload to?  If not - we will list existing articles) (choices: yes, no): yes

[INFO   ] Created a new (private) article 5552899 at https://figshare.com/account/articles/5552899. Please visit it, enter additional meta-data and make publish 
                                                                                                                [INFO   ] 'Registering' /tmp/test/datalad_a9577654-b90f-11e7-9372-8019340ce7f2.zip within annex 
                                                                                                                [INFO   ] Adding URL https://ndownloader.figshare.com/files/9631855 for it 
[INFO   ] Registering links back for the content of the archive 
[INFO   ] Adding content of the archive /tmp/test/datalad_a9577654-b90f-11e7-9372-8019340ce7f2.zip into annex <AnnexRepo path=/tmp/test (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Finished adding /tmp/test/datalad_a9577654-b90f-11e7-9372-8019340ce7f2.zip: Files processed: 6, removed: 6, +annex: 6 
[INFO   ] Removing generated and now registered in annex archive 
export_to_figshare(ok): <Dataset path=/tmp/test>
```

to make them public all the fields need to be set... we could regiment and demand them if publishing it right away is desired.

Note: there is no support for "download" from the private repo ATM. Ididn't yet verify if url doesn't change whenever article goes public

### CODE REVIEW

**Comment by yarikoptic** [comment]
She on top of Michael work... Initial since it is good enough for demo. For real use would need more polish and options

**Comment by mih** [comment]
Awesome!

**Comment by mih** [comment]
Needs the conflicts fixed.

**Comment by yarikoptic** [comment]
pushed with resolved conflicts and manual test that it works

**Comment by yarikoptic** [comment]
Could someone give it a shot @mih or @bpoldrack ?  yet to figure out how to test the beast

**Comment by yarikoptic** [comment]
so... @mih @bpoldrack ?

**Comment by mih** [comment]
Let's do it live in hangout today?

**Comment by mih** [comment]
As this beast worked last week, I'll merge now.

**Pull request merged**
