### PR TITLE
0.15.0 Changelog

### PR DESCRIPTION
**Pull request by mih**
The proposed format is a mix of what Kyle did and what `auto` does.

Please do not argue with individual phrasing and other aspects, simply suggest a concrete change.

FTR: I will get officially angry should any automated procedure replace this work of art! ;-)

The release subtitle is non-negotiable.

### CODE REVIEW

**Comment by yarikoptic** [comment]
thank you @mih !

**Comment by yarikoptic** [comment]
Should we may be merge this PR and release an `rc1` so it could be tested etc... might make it easier also to track later what new changelog entries to add?

**Comment by mih** [comment]
I don't mind, but I don't need the merge for better tracking.

**Comment by mih** [comment]
This is now final from my POV. All remaining work for 0.15 is developer-focused or internal and no candidate for this changelog.

**Pull request merged**
