### PR TITLE
ENH: Only evaluate and warn about content availability with explicit paths

### PR DESCRIPTION
**Pull request by mih**
This implements the conclusion in the issue discussion of gh-4508 and thereby fixes gh-4508.

This PR sits on top of #4545 (essential) and #4546 (to limit unavoidable conflicts).

In all cases with no `path=` argument given to `push()` this change avoids an expensive content availability check that can make the difference between minutes and hours of processing large N datasets.

The relevant commit is https://github.com/datalad/datalad/commit/ef04b1e50d8418eb001329d19c578ef2040e9df3

### CODE REVIEW

**Comment by yarikoptic** [comment]
IMHO it is just a bandaid which conflates two semantics as I outlined in https://github.com/datalad/datalad/issues/4551#issuecomment-630404940

**Comment by mih** [comment]
The main purpose of the PR is performance. On sizable repos it can shave of an hour of pre-upload runtime. It would be good to stick that bandaid somewhere, until a superior solution is implemented.

**Comment by yarikoptic** [comment]
Sounds good. Unfortunately GitHub mumbles something about conflicts now

**Comment by kyleam** [comment]
> Unfortunately GitHub mumbles something about conflicts now

I've merged master (conflict was handled by automatic resolution) and pushed .

**Comment by kyleam** [comment]
> I've merged master (conflict was handled by automatic resolution) and pushed .

CrippledFS failed one way and, then on rerun, another.  It passed before the merge (00c78b1) to resolve a conflict that involved only a comment.  So I'll assume it's unrelated and merge this.

**Pull request merged**
