### PR TITLE
BF testrepos --allow to run tests by cloning repos from online

### PR DESCRIPTION
**Pull request by yarikoptic**
As detected by @jgors tests on "installed" datalad didn't work, so this is a workaround

### CODE REVIEW

**Comment by yarikoptic** [comment]
uff -- came out a long one to please Jason ;)  @datalad/developers please review -- you have 24h before I merge it.  Eventually all the testrepos should be refactored to not hit github that much

**Comment by jgors** [comment]
more of an opinion than anything, but i really don't care for using the magic of ```from ..utils import *```/```from .utils import *``` throughout the code.

**Comment by yarikoptic** [comment]
@jgors -- ok -- I fixed up the screw up with basing this change on top of the other PR.  Now it is primarily only commits relevant to this one

**Comment by yarikoptic** [comment]
if you would like to replace `from .utils import *` within the tests (that is where you would see such a pattern to import all needed for testing constructs) -- send a separate PR ;)

**Comment by yarikoptic** [comment]
ok -- no objections, merging

**Pull request merged**
