### PR TITLE
BF/RF: instead of using -c remote..push, pass refspecs into push invocation

### PR DESCRIPTION
**Pull request by yarikoptic**
should fix failing test
  see discussions after merge in https://github.com/datalad/datalad/pull/1308

includes an "easter egg" fix ;)

### CODE REVIEW

**Comment by mih** [comment]
And we are full circle. This is where we started to fix the problem that existing config is ignored when push is called with specific refspecs.

**Comment by yarikoptic** [comment]
Ah... 😁
Did you try to read the ones from config and provide them all then as well?

**Comment by yarikoptic** [comment]
Or may be just push twice ;-)

**Comment by mih** [comment]
Many things were tried, but it needs one brave man to do it right this one
time. I am right behind you!

**Comment by yarikoptic** [comment]
ok -- I will see if I could make an executive decision on what behavior from publish we want ;)  but for now, to avoid broken master we then probably just merge this one, or reset --hard previous merge I have done.  any input on which way? (either is fine with me)

**Comment by yarikoptic** [comment]
ok -- if desire was to push both detected and prescribed, I have for now made two pushes -- if tests pass and no big objections would merge it to bring master back in order -- two more PRs are staggering now ;)

**Comment by bpoldrack** [comment]
Made issue #1339 for further discussion and to link this PR as well as the other to preserve the state of discussion.

I'll merge for the sake of a clean master.

**Pull request merged**
