### PR TITLE
Ensure there's a blank line between the class `__doc__` and "Parameters" in `build_doc` docstrings

### PR DESCRIPTION
**Pull request by jwodder**
Without this change, applying `@build_doc` to a class whose docstring doesn't end in a newline, like so:

```python
@build_doc
class Foo(Interface):
     """Foo all the bars"""

    @staticmethod
    @eval_results
    def __call__():
        pass
```

will result in `__call__` getting a docstring that starts out with:

```
Foo all the bars
Parameters
----------
```

and the lack of a newline between the class docstring and "Parameters" will result in Sphinx producing a warning when trying to build the documentation for the class.  This PR fixes this behavior by ensuring that, if the class docstring doesn't already end with a newline, one is added, so that there are always at least two newlines (i.e., one blank line) before the "Parameters" header.

### CODE REVIEW

**Comment by yarikoptic** [comment]
would you be so kind to rebase against `maint`?  I think we could even try to release since there were a few fixes (we are at 0.15.0-14-geb7a43b09) and we must not grow changelog for `auto` to succeed.

**Comment by yarikoptic** [comment]
also if you could add a basic test to datalad/interface/tests/test_base.py which would demonstrate current issue (and test the fix) so we do not undo it -- would be great

**Review by yarikoptic — APPROVED** [review]

**Comment by yarikoptic** [comment]
Let's wait for the tests to pass, and then we could proceed with merge.

**Comment by yarikoptic** [comment]
Test seems to fail (didn't analyze it always)
```
FAIL: datalad.interface.tests.test_base.test_update_docstring_with_parameters_single_line_prefix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-q0b2i3i0/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-q0b2i3i0/lib/python3.9/site-packages/datalad/interface/tests/test_base.py", line 230, in test_update_docstring_with_parameters_single_line_prefix
    assert_in("This is a single line.\n\nParameters\n", fn.__doc__)
AssertionError: 'This is a single line.\n\nParameters\n' not found in 'This is a single line.'
```

**Comment by jwodder** [comment]
@yarikoptic The test should be fixed now.  It turns out `update_docstring_with_parameters()` doesn't add a "Parameters" block if the function has only one argument, presumably based on the assumption that the argument will always be `self`.  Might want to change that.

**Comment by yarikoptic** [comment]
crawler fail is likely unrelated. one run of travis -- inability to download conda, unlikely to bring surprises, but I restarted the job -- better be safe than sorry ;)  if would turn green -- I think we should proceed with merge. Thank you @jwodder

**Comment by yarikoptic** [comment]
Travis is happy now

**Pull request merged**
