### PR TITLE
TEMP test devel annex 7.20200204+git1-gb2c529b88-1~ndall+1 

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by kyleam** [comment]
The six errors on Travis were due to no output.  I've restarted them.

**Comment by kyleam** [comment]
> The six errors on Travis were due to no output. I've restarted them.

Same result this time :/

**Comment by yarikoptic** [comment]
uff, it gets stuck and we don't even know where:
```
$ http_proxy= PATH=$PWD/../tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -A "$NOSE_SELECTION_OP($NOSE_SELECTION)" --with-doctest --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM
...............
...................................................S........S.........................................................................................
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
I guess we better bring `-v` back for this run

**Comment by yarikoptic** [comment]
seems to happen on
```
datalad.distribution.tests.test_publish.test_publish_depends ... .: target1(+) [ssh://localhost/tmp/datalad_temp_test_publish_depends6qc2cxnk (git)]
```

**Comment by yarikoptic** [comment]
<details>
<summary>grr, unfortunately it doesn't reproduce locally for me, at least by running that test in isolation</summary> 

```shell
(git)lena:~datalad/datalad-master[temp-test-devel-annex]git
$> DATALAD_TESTS_SSH=1 python -m nose -s -v datalad/distribution/tests/test_publish.py:test_publish_depends
datalad.distribution.tests.test_publish.test_publish_depends ... .: target1(+) [ssh://localhost/home/yoh/.tmp/datalad_temp_test_publish_depends00d9llcb (git)]
.: target2(+) [ssh://datalad-test/home/yoh/.tmp/datalad_temp_test_publish_dependshqs20ykd (git)]
.: target3(+) [ssh://datalad-test/home/yoh/.tmp/datalad_temp_test_publish_dependsipyvkvt3 (git)]
ok
Versions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=7.20200204+git1-gb2c529b88-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.24.0 cmd:system-ssh=8.1p1 exifread=2.1.2 git=3.0.5 gitdb=2.0.6 humanize=0.5.1 iso8601=0.1.11 keyring=18.0.1 keyrings.alt=3.1.1 msgpack=0.5.6 mutagen=1.40.0 requests=2.21.0 tqdm=4.30.0 wrapt=1.11.2
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'

----------------------------------------------------------------------
Ran 1 test in 44.701s

OK
DATALAD_TESTS_SSH=1 python -m nose -s -v   27.96s user 13.74s system 92% cpu 45.317 total
```
</details>

**Comment by yarikoptic** [comment]
so, it gets stuck on `annex enableremote` 
```
[Level 9] Running: ['git-annex', 'enableremote', '--debug', '-c', 'remote.target1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/cc0e7a99', 'target2']
| env={'GIT_SSH_COMMAND': 'datalad sshrun'} 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by yarikoptic** [comment]
@joeyh any immediate clue what could have lead to the [aforementioned](https://github.com/datalad/datalad/pull/4116#issuecomment-582791175) stall of `enableremote`?

**Comment by yarikoptic** [comment]
will push a merge update - should be 7.20200204+git62-gcc4521068-1~ndall+1  now

**Comment by yarikoptic** [comment]
Unfortunately stuck `git annex enableremote` is still there so does require more investigation.

**Comment by yarikoptic** [comment]
long story short: for some reason Runner was stuck on `readline()` from git-annex.  I guess git-annex somehow managed to stop producing trailing new line, or there was some other reason why it was not returning.  In the latest commits in this PR I have started to use `WitlessRunner` for `enableremote` call in `AnnexRepo`, and also "improved" `WitlessProtocol`s to respect `datalad.log.outputs` (useful for troubleshooting)   If succeeds, I will prepare them as a dedicated PR for those changes.

**Comment by yarikoptic** [comment]
oh hoh hoh -- it seems to be `git-annex` issue after all of not returning from `enableremote` call since even the glorious `WitlessRunner` didn't return (@mih)?
```
[DEBUG  ] Async run ['git-annex', 'enableremote', '--debug', '-c', 'remote.target1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/3d284eaf', 'target2'] 
[DEBUG  ] Launching process ['git-annex', 'enableremote', '--debug', '-c', 'remote.target1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/3d284eaf', 'target2'] 
[DEBUG  ] Process 16621 started 
[DEBUG  ] Waiting for process 16621 to complete 
[Level 5] Read 46 bytes from 16621[stdout]: 
[Level 9] stdout| (merging target2/git-annex into git-annex...)
|   
[Level 5] Read 28 bytes from 16621[stdout]: 
[Level 9] stdout| (recording state in git...)
|   
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by yarikoptic** [comment]
I am out of ideas on this one, thus filed [an issue against git-annex](https://git-annex.branchable.com/bugs/enableremote_stuck_with_a_recentish_git-annex/?updated)

**Comment by yarikoptic** [comment]
uploaded newer git annex 7.20200219+git135-g34d726cba-1~ndall+1 to -devel

**Comment by kyleam** [comment]
> 7.20200219+git135-g34d726cba-1~ndall+1 to -devel

Note that that will fail for another reason: gh-4185.  I have series in-progress locally that I plan on submitting tomorrow.

**Comment by yarikoptic** [comment]
Great, thanks! Since current master is too much in flux IMHO, could you please initiate 0.12.x branch as late after 0.12.2 as possible and propose compatibility fixes from that point? We might cherry pick a few more fixes and release 0.12.3 after all before master is releasable as 0.13.0. or do you think it would be all wasted effort?

**Comment by kyleam** [comment]
> could you please initiate 0.12.x branch as late after 0.12.2 as possible and propose compatibility fixes from that point?

Okay, but I will call it "maint" unless I receive a strong objection.

> We might cherry pick a few more fixes and release 0.12.3 after all before master is releasable as 0.13.0. or do you think it would be all wasted effort?

I think it's worth picking a _minimal_ set of fixes.  At this point, I'd say it's frustrating to have to now cherry pick things (from an effort, workflow, and history standpoint).  As you know my opinion is that we should _always_ have a maintenance branch, but others disagree.

**Comment by yarikoptic** [comment]
> _always_ have a maintenance branch, but others disagree.

**I** don't, but others might say "I don't disagree, but it is more effort, and I personally have no time for that and/or wait then for the merge into master"

> I will call it "maint" unless I receive a strong objection.

I didn't.  It is just that eventually we might get to the desire to cherry pick (e.g. security fixes etc) and re-release some previous "stable" release(s), and that is where all those `0.?.x` came from.  But I am ok with `maint` as well.  It is better than none ;)

**Comment by kyleam** [comment]
> It is just that eventually we might get to the desire to cherry pick (e.g. security fixes etc) and re-release some previous "stable" release(s), and that is where all those `0.?.x` came from.

But you are still free to do that and call those branches `0.?.x` or (my git.git-biased preference) `maint-0.?`.

**Comment by yarikoptic** [comment]
woohoo -- [build passes](https://travis-ci.org/datalad/datalad/builds/659957998?utm_source=github_status&utm_medium=notification) after the fix in 6a6a6763409690253824f65b131f60d90bdf68ad.  It still doesn't answer the question why before it worked as it was, and now doesn't.  I will submit that fix now against maint and if tests pass there, will reincarnate this PR as new -- there is too much history here now, and version of annex anyways differs from the one in the title.

**Pull request closed without merging**
