### PR TITLE
BF: remove stale dump_graph

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by kyleam** [comment]
The two failed jobs seem spurious.  I've restarted.

**Comment by yarikoptic** [comment]
There is no flatten_metadata_graph even which it conditionally imports - I think all leftovers from previous metadata handling. Afaik there is no graphs anymore ATM

**Comment by kyleam** [comment]
I see.  Thanks for giving more details.

**Comment by yarikoptic** [comment]
Then I will merge, we can revert if it was any useful ;-)

**Pull request merged**
