### PR TITLE
BF: blind attempt - assure there is a trailing new line while joining outputs from batches

### LINKED ISSUE #2301: test_basic_aggregate: json.decoder.JSONDecodeError: Extra data: line 1 column 166 (char 165)
#### What is the problem?
Happened (or may be regularly) in that heavy debug mode matrix run (only):
https://travis-ci.org/datalad/datalad/jobs/353137426

```
======================================================================
ERROR: datalad.metadata.tests.test_aggregation.test_basic_aggregate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 494, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 905, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1057, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/metadata/tests/test_aggregation.py", line 67, in test_basic_aggregate
    base.aggregate_metadata(recursive=True)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 436, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/metadata/aggregate.py", line 732, in __call__
    to_save)
  File "/home/travis/build/datalad/datalad/datalad/metadata/aggregate.py", line 472, in _update_ds_agginfo
    save=False, result_renderer=None, return_type=list)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 436, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/distribution/add.py", line 424, in __call__
    **add_kw
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 300, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 1535, in add
    expect_stderr=True
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2394, in _run_annex_command_json
    json_objects = [j for j in json_objects if 'byte-progress' not in j]
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2394, in <listcomp>
    json_objects = [j for j in json_objects if 'byte-progress' not in j]
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2392, in <genexpr>
    for line in out.splitlines() if line.startswith('{'))
  File "/opt/python/3.5.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/opt/python/3.5.5/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 166 (char 165)
-------------------- >> begin captured logging << --------------------
```

### PR DESCRIPTION
**Pull request by yarikoptic**
of git-annex runs.  It is unlikely the cause but the other possible causes lie even deeper.
Thought to check this one first

This pull request fixes #2301 (if passes upon a few trials). unlikely to be the one at fault

This pull request proposes

### Changes
- [ ] This change is complete

Please have a look @datalad/developers

### CODE REVIEW

**Comment by mih** [comment]
At least it didn't break anything ;-)

**Comment by yarikoptic** [comment]
Well, Travis actually passed.

**Comment by mih** [comment]
True, but it did before 1/10 cases -- hence we don't know for sure yet ;-)

Merge?

**Comment by yarikoptic** [comment]
Let me do a few more reruns... May be it would show it's ugly face

**Comment by yarikoptic** [comment]
FYI: tuned up buildbots setup so it would retry  `pip` commands up to 5 times (a bit adhoc - bash until loop... but seems to work), so there should be no more of spurious errors from buildbots

**Comment by yarikoptic** [comment]
that wasn't it: https://travis-ci.org/datalad/datalad/jobs/361459024

**Pull request closed without merging**
