### PR TITLE
RF: de-wrapt

### PR DESCRIPTION
**Pull request by yarikoptic**
A quick chat with @mih inspired me to look into it.... in a nutshell (more to come if feasible):

- use `inspect.signature` instead of `inspect.getargspec` since that one manages to get args of `functools.wraps`ed functions. Source of information: https://stackoverflow.com/questions/147816/preserving-signatures-of-decorated-functions#comment68410839_147878

- ~~remaining gotcha (TEMPorarily disabled that test ) -- not yet "binding" `__doc__` to `Dataset.method` -- `@build_doc` assigns `__doc__` to `__call__` later than `@datasetmethod` is invoked. So I guess `wrapt` does some magic for `__doc__` to be always be queried for the `wrapt`ed functions.~~ -- I think I came up with a good enough workaround

- reworked `getargspec` is based on the one in #6176 but redone on top - will conflict. If we go with this -- this one should take over ;-)

oh well -- let's see if anything else breaks ;-)

### CODE REVIEW

**Comment by yarikoptic** [comment]
Woohoo, not yet sure what docs are complaining about, but the rest seems to be happy, so it might be viable

**Comment by mih** [comment]
YES! I knew it. This is really cool. Thanks for taking it on!

**Comment by yarikoptic** [comment]
Ha - that test said fails on Windows and Mac so may be it wasn't really wrapt to blame!

```
======================================================================
ERROR: datalad.runner.tests.test_nonasyncrunner.test_popen_invocation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\datalad\datalad\tests\utils.py", line 856, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad\datalad\tests\utils.py", line 856, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "c:\projects\datalad\datalad\runner\tests\test_nonasyncrunner.py", line 180, in test_popen_invocation
    fetching_data.start()
  File "C:\Python39-x64\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python39-x64\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python39-x64\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python39-x64\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python39-x64\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

**Comment by yarikoptic** [comment]
ok, dropped that last TEMP optimistic commit (so test will remain skipped on OSX and windows).  Fixed up docstring so it builds.  Should be ready for tries/review/ and even merge unless some oddity detected

**Review by mih — APPROVED** [review]
I think this should fly. Let's try it it! Thx!

**Pull request merged**
