### PR TITLE
Travis setup minimization

### LINKED ISSUE #2390: Strip down tests matrix
#### What is the problem?

- no v6 testing (may be a single one)
- single python 3.6 run
- join multiple "symlink and space" ones in TMPDIR and may be even with -obscurename
- run allowed failures on sundays

### PR DESCRIPTION
**Pull request by yarikoptic**
- [x] joined some runs together with the most obscure setup
- [x] python 3.6 and v6 is tested only in a single (full) run
- [x] those "optional" matrix runs which we did not run in PRs, now
       - [x] will now run only by a cron job which will run only on master
       - [x] **will not contribute to coverage** -- we would need to cover with what we have in regular tests setups!
       - [x] scheduled weekly runs for master on travis
- [ ] This change is complete

Effectively it should cut down number of matrix runs in half or more for PRs and master, unless it is a cron job where it would do a few more (I now think we might even add more for cron job)

Cons:
- I think it might be confusing whenever we do get master reported failed in recent cron job but then succeed in truncated usual run.   So we will need to strive to keep it green in master all the time, without ignoring it (like done now)

Fixes #2390 

Please have a look @datalad/developers

### CODE REVIEW

**Comment by yarikoptic** [comment]
We have got two "new"(?) failures in v6 mode,
```
======================================================================
ERROR: datalad.distribution.tests.test_uninstall.test_remove_recursive_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 877, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/vcr/cassette.py", line 105, in __call__
    function, args, kwargs
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/vcr/cassette.py", line 120, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/vcr/cassette.py", line 141, in _handle_function
    return fn(cassette)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/vcr/cassette.py", line 113, in handle_function
    return function(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_uninstall.py", line 472, in test_remove_recursive_2
    remove('labs', recursive=True)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 446, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'type': 'file', 'path': '/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr/face_place/README3_0.txt', 'status': 'error', 'action': 'drop', 'message': 'unsafe\nCould only verify the existence of 0 out of 1 necessary copies\nRather than dropping this file, try using: git annex move\n(Use --force to override this check, or adjust numcopies.)', 'annexkey': 'MD5E-s2787--61f8d7421fb06fa09a81ac20dc257717.txt'}, {'type': 'file', 'path': '/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr/face_place/datapackage.json', 'status': 'error', 'action': 'drop', 'message': 'unsafe\nCould only verify the existence of 0 out of 1 necessary copies\nRather than dropping this file, try using: git annex move\n(Use --force to override this check, or adjust numcopies.)', 'annexkey': 'MD5E-s921--04a4b4f1edeaeeedf00381296a2b5718.json'}, {'path': '/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr/face_place', 'type': 'directory', 'status': 'impossible', 'action': 'drop', 'message': ('could not drop some content in %s %s', '/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr/face_place', ['/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr/face_place/README3_0.txt', '/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr/face_place/datapackage.json'])}, {'path': '/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr', 'type': 'dataset', 'status': 'error', 'action': 'uninstall', 'message': ('to be uninstalled dataset %s has present subdatasets, forgot --recursive?', <Dataset path=/tmp/datalad_temp_test_remove_recursive_20889un4k/labs/tarr>)}, {'path': '/tmp/datalad_temp_test_remove_recursive_20889un4k/labs', 'refds': None, 'type': 'dataset', 'status': 'error', 'action': 'remove', 'message': ('to be uninstalled dataset %s has present subdatasets, forgot --recursive?', <Dataset path=/tmp/datalad_temp_test_remove_recursive_20889un4k/labs>)}]
======================================================================
FAIL: datalad.distribution.tests.test_install.test_install_into_dataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 836, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_install.py", line 445, in test_install_into_dataset
    ok_clean_git(subds.path, annex=None)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 286, in ok_clean_git
    eq_(index_diffs, [])
AssertionError: ['INFO.txt\n=======================================================\nlhs: 100644 | eea18436c2875189f6d41e55fa4f5eb25939d589\nrhs: None', 'test.dat\n=======================================================\nlhs: 100644 | 190a18037c64c43e6b11489df4bf0b9eb6d2c9bf\nrhs: None'] != []
```

I guess I will just mark them broken for v6 for now

**Comment by yarikoptic** [comment]
blocked by https://github.com/datalad/datalad/pull/2395 ATM to get the baseline coverage back.

**Comment by yarikoptic** [comment]
ok, succes:
- more than less covered by 2 lines ;)
- runs about 30% faster (so room for improvement remains)
  - was 
       - Ran for 1 hr 44 min 55 sec
       - Total time 7 hrs 8 min 58 sec
   - now
       -  Ran for 1 hr 10 min 30 sec
       - Total time 4 hrs 38 min 13 sec
- we should not get spurious differences in coverage from master since those runs shouldn't contribute.

I think it is some kind of a win, so will merge

**Comment by kyleam** [comment]
Nice!

**Comment by mih** [comment]
Many thanks for this change -- total transformation of the entire experience!

**Pull request merged**
