### PR TITLE
Temp try recent neurodebian devel annex (with custom backends support etc) [maint]

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
not bad.  Only the run with `DATALAD_TESTS_SSH=0 _DL_TMPDIR="/tmp/nfsmount" TESTS_TO_PERFORM="datalad.tests datalad.support"` stalls who knows were.  I will rerun with `-v`

**Comment by yarikoptic** [comment]
actually it is more a BF to CPed to `maint` if works as expected within travis: cba946da3f3dc746038466c3b5dcac1c1d332960

**Comment by yarikoptic** [comment]
apparently travis didn't quite like it (although that didn't fail the job) https://travis-ci.org/github/datalad/datalad/jobs/715355482#L193 :

```
$ export NOSE_OPTS=(
194/home/travis/.travis/functions: eval: line 109: unexpected EOF while looking for matching `)'
195$ export v=
```

which I do not quite reproduce

```shell
$> bash -c "eval 'export NOSE_OPTS=( -v )'; echo \${NOSE_OPTS}"
-v
```

so must be some more `.travis.yml` parsing specific... I am failing to find another way to allow array var to be assigned there :-(  I will define it in the `before_install`

**Comment by yarikoptic** [comment]
so, [one](https://travis-ci.org/github/datalad/datalad/jobs/715532623) ran out of time (at 50 min), the `nfsmount` one did stall again at:

```
datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,) ... 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by yarikoptic** [comment]
@kyleam didn't we have a dedicated issue for nfsmount regression? I fail to find it

**Comment by kyleam** [comment]
> @kyleam didn't we have a dedicated issue for nfsmount regression? I fail to find it

Not that I'm aware of.

**Comment by yarikoptic** [comment]
FWIW, failed to reproduce nfs stall locally while running only that test
```shell
$> mount | grep nfs                                                            
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
localhost:/tmp/nfsmount_ on /tmp/nfsmount type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp6,timeo=600,retrans=2,sec=sys,clientaddr=::1,local_lock=none,addr=::1)

$> TMPDIR=/tmp/nfsmount python -m nose -s -v datalad/support/tests/test_annexrepo.py:test_commit_annex_commit_changed
datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(True,) ... ok
datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,) ... ok
Versions: annexremote=1.4.3 appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200810+git5-gb41f77445-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.27.0 cmd:system-ssh=8.1p1 exifread=2.1.2 git=3.1.0 gitdb=4.0.2 humanize=2.3.0 iso8601=0.1.12 keyring=18.0.1 keyrings.alt=3.4.0 msgpack=0.6.2 mutagen=1.40.0 requests=2.23.0 scrapy=1.7.3 wrapt=1.11.2
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'"

----------------------------------------------------------------------
Ran 2 tests in 24.555s

OK
TMPDIR=/tmp/nfsmount python -m nose -s -v   9.79s user 5.61s system 60% cpu 25.265 total
```

**Comment by yarikoptic** [comment]
pushed a merge, should test against fresh `8.20200810+git47-g27329f0bb-1~ndall+1` not that I expect it to have nfs stall resolved

**Comment by yarikoptic** [comment]
just uploaded `8.20200810+git69-g02a35c9ce` which should have some other stalls due to pidlock addressed, let's see...

**Comment by yarikoptic** [comment]
eh, unfortunately still no good
- first two jobs timed out at 50 min
- the nfs one still stalled after erroring out one of the tests:
```
datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(True,) ... ERROR
datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,) ... 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```
I will now restrict to run only `datalad.support.tests.test_annexrepo:test_commit_annex_commit_changed` with debug level so we could possibly see what is going on

**Comment by yarikoptic** [comment]
eh -- with debug level logging and only those tests ran -- passed (well -- errored since tests took too long). I will disable now debug level - if stalls, must be a race condition of some kind I guess

**Comment by yarikoptic** [comment]
eh, stalled without our logging... bleh

**Comment by yarikoptic** [comment]
merged maint and pushed again -- a fresh annex `8.20200810+git143-gdee38c54d-1~ndall+1` was uploaded to -devel

**Comment by yarikoptic** [comment]
d'oh -- that error is unrelated -- test (`.test_commit_annex_commit_changed(True,)`) taking 10x longer than a threshold: `AssertionError: Test was too slow (took 310.5164s, threshold was 30.0000s)` which isn't good but oh well...  It is also followed with the report `OSError: [Errno 16] Device or resource busy: '.nfs00000000001f6fe200000019'`.  So I think I will now try devel annex on master and see how it goes

**Comment by yarikoptic** [comment]
well, we have tried

**Pull request closed without merging**
