### PR TITLE
Use lgr.info() to get UNIFORM progress reporting

### PR DESCRIPTION
**Pull request by mih**
This means switching to structured log messages similar to our result records. Such message should indicate the start and end of a process, as well as intermediate updates on the progress. Start messages may also give an indication of the "amount" of processing to be expected, and log messages could indicate a more precise state of the progress in such cases.

With such messages and related adjustments it would be possible to uniformly display progress (in contrast to the current mix of logging and progress reporting. We could decide centrally to disable any of that, rate limit progress reports, or switch between progressbars, no progressbars, or line-based log messages. It would also enable us to adopt the habit of using logging in a more structured way -- not with the target of communicating with a user, but to comprehensively document what is going on.

@bpoldrack you looked at logging in the past, correct? Could you look into whether we can have a log handler that could receive dicts with such info as input?

### CODE REVIEW

**Comment by mih** [comment]
We could think about amending the progressbar ID with the name of the logger the message was coming from. This would disallow reporting progress on an effort from two different modules. But this could easily be done in a central code block at any later point.

**Comment by mih** [comment]
I am happy with the status quo.

**Comment by mih** [comment]
So the addition of a loghandler *only for interactive* sessions seems to be break pretty much the entire log test infrastructure. I failed to understand how and why exactly.

I am not sure which part should be fixed (test helpers or actual logging). IMHO the current logging setup is still suboptimal. For example, I seem to be able to log to stderr XOR a file, but most likely we want to make these things orthogonal to each other. We likely want warnings, errors and progress info to come out on std*, and still be able to log everything to a file. The helpers cannot deal with this.

**Comment by mih** [comment]
@yarikoptic any idea on the "swallow_log" issue in here. If we get this resolved, this would be a quick way to beautify the reporting throughout datalad.

**Comment by mih** [comment]
I would love to be able to use this. Any chance you could have a quick look at the swallow_logs issue @kyleam or @bpoldrack (with a fresh attempt)?

**Comment by kyleam** [comment]
> Any chance you could have a quick look at the swallow_logs issue

Fixed in 5190e2bb9, I think.  It makes `nosetests -sv datalad/tests/test_utils.py:test_swallow_logs` pass locally for me.  Let's see about the other tests.

**Comment by kyleam** [comment]
I've started to convert addurls to use `log_progress`.  The one thing I found missing is the ability to update the progress bar's label.  The commit that I just pushed adds support for that.

**Comment by mih** [comment]
Indeed, thanks for adding that. Any idea what is going on with OSX?

**Comment by kyleam** [comment]
> Any idea what is going on with OSX?

No.  Here are the failures, in case others have any idea:

```
======================================================================
FAIL: datalad.plugin.tests.test_plugins.test_wtf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/datalad/miniconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/plugin/tests/test_plugins.py", line 147, in test_wtf
    assert_in(_HIDDEN, pyperclip.paste())  # by default no sensitive info
AssertionError: '<Sensitive data, use -s=some or -s=all to show>' not found in u''
-------------------- >> begin captured logging << --------------------
datalad.distribution.create: INFO: Creating a new annex repo at /private/tmp/datalad_temp_test_wtffBvfVY
datalad.metadata.metadata: WARNING: Metadata query results might be incomplete, initial metadata aggregation was not yet performed in 1 dataset at: ['/private/tmp/datalad_temp_test_wtffBvfVY']
datalad.metadata.metadata: WARNING: Metadata query results might be incomplete, initial metadata aggregation was not yet performed in 1 dataset at: ['/private/tmp/datalad_temp_test_wtffBvfVY']
datalad.metadata.metadata: WARNING: Metadata query results might be incomplete, initial metadata aggregation was not yet performed in 1 dataset at: ['/private/tmp/datalad_temp_test_wtffBvfVY']
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: datalad.tests.test_cmd.test_runner_heavy_output(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/datalad/miniconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 1290, in newfunc
    func(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/test_cmd.py", line 221, in check_runner_heavy_output
    assert not ret[0], "all messages went into `logged`"
AssertionError: all messages went into `logged`
```

**Comment by mih** [comment]
re heavy output failure: My only explanation would be that the separate handling of the filters for the log handler in swallow_logs let's some message leak. But then I wouldn't know why this would happen on OSX only...

**Comment by kyleam** [comment]
I don't think it's a swallow_logs issue because that failure shows up prior to 5190e2bb9 (e.g., e5c9dbc57's [log](http://smaug.datalad.org:8020/builders/datalad-pr-dl-osx-64/builds/3956/steps/nosetests/logs/stdio)).  So, I don't understand how either of these are related to the PR or why they are OSX-specific.

**Comment by mih** [comment]
OSX build in another PR just completed without an issue: http://smaug.datalad.org:8020/builders/datalad-pr-dl-osx-64/builds/4044

**Comment by yarikoptic** [comment]
paperclip - I feel that just recently I dealt with it on osx and pretty much it should have just skipped that test

And the other one as well - it was leaking just some new lines. So might be worth checking what exactly is leaking, since IMHO should have been fixed

**Comment by mih** [comment]
Ah, no -- will do!

**Comment by mih** [comment]
BINGO!

**Pull request merged**
