### PR TITLE
Shadow development master

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by mih** [comment]
Started merging master bit by bit, resolving conflicts... much fun.

Currently no success with 5161c954c19fafd6988806bdf6d692ad6f247cd6

**Comment by mih** [comment]
Pushed another merged PR from master. Code that survives gets less and less. I really hope that the tests cover the essence of the fixes. Otherwise this will all just reintroduce them.

**Comment by mih** [comment]
@bpoldrack @yarikoptic I managed to merge current master into dev-master. I would be glad if some effort could go into making sure that this ends up in master ASAP. I have to admit that I still haven't regained a good concept of possible unfinished jobs in here. A quick review would be much appreciated!

**Comment by mih** [comment]
Test failure is caused by state of master, not this PR.

**Comment by bpoldrack** [comment]
I'm trying to look into this one as well as what's going on in master.
Not easy to review though. ;-)

**Comment by bpoldrack** [comment]
Okay. Failure only during setup for NFS build - as it is always the case ATM.
Strongly vote for merge to end that parallel development. Any objections, @yarikoptic ?

**Comment by mih** [comment]
OK, there is no way back -- merge in 2h. @yarikoptic beware!!!

**Comment by yarikoptic** [comment]
Let's do it... I will curse and whine later

**Pull request merged**
