### PR TITLE
RF: AnnexRepo.get_file_key() as a compat-frontend for get_content_annexinfo()

### PR DESCRIPTION
**Pull request by mih**
The previous implementation did not work on windows, and the desired
information is readily provided by more commonly used methods.

Fixes gh-5068

### CODE REVIEW

**Comment by kyleam** [comment]
Test failures are due to three spots (two tests) needing `FileInGitError -> FileNotInAnnexError`.

**Comment by mih** [comment]
Question is: should we achieve fully compatible behavior through additional inspection at a runtime cost? Or adjust the tests?

**Comment by mih** [comment]
It seems `get_file_key()` is called in `is_available()` and might be replaced in a similar fashion.

**Comment by mih** [comment]
Benchmarks report a 5-10% slowdown across the board. That is surprising. I fail to see this function being used in any core functionality...

https://github.com/datalad/datalad/pull/5069/checks?check_run_id=1292299793

So even if it is slower, the impact should be "not much".

**Comment by kyleam** [comment]
> Benchmarks report a 5-10% slowdown across the board. That is surprising. I fail to see this function being used in any core functionality...
[...]
> So even if it is slower, the impact should be "not much".

Yeah, that doesn't seem plausible based on where it is used.  For the one-call case, `find --json FILE` doesn't appear to be much slower than `lookupkey FILE`.  For the many-separate-calls batch case, I think the difference could be quite large, though as far as I can see, `datalad.metadata.extractors.annex` is the only caller that uses `batch=True` like this.  (And of course none of that is relevant to the general benchmark slowdown.)

**Comment by kyleam** [comment]
Keeping compatibility by raising `FileInGitError` would be nice (and the execution cost would only need to be paid when files aren't known to annex), but I think that's a minor issue compared to fixing this on Windows [*], and so no objections from me if you prefer to leave it as is.  I looked for current callers in -core that would need to be updated, and the only one I spot is `datalad.metadata.aggregate._the_same_across_datasets`.

Also, the docstring's description of `batch` should be updated to mention that it's an obsolete noop now.

[*] Just out of curiosity, presumably the lookupkey call itself was fine on Windows.  I guess it was the post-call handling on our side that was the issue?

**Comment by mih** [comment]
It seems the initial benchmark results were a fluke, all normal now.

**Comment by mih** [comment]
OK, so while I stand by these changes, I have found a windows box that still doesn't work. And probably, appveyor is also not completely fine, as I cannot find a trace of any annexrepo test actually being attempted (:roll_eyes: seriously, wtf!? we are not even anywhere close). I tried multiple git-annex versions, no change. I suspect it is still the preparation of the test repos that is severely fucked. Failure pattern looks like this:

```
AssertionError: 'SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b.dat' != 'SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat'
```

where the former is a hard coded SHA to test against. The change in size suggests that we are looking at different content, and I suspect adjusted branches to be the cause.

**Comment by mih** [comment]
Let's wait with this one until #5073 has landed and rerun the tests.

**Comment by kyleam** [comment]
With gh-5080, `test_annexrepo` is executed on appveyor.

**Comment by mih** [comment]
Rebased on master after merge of various test setup fixes on windows.

**Comment by mih** [comment]
The key test is still not being attempted on appveyor, this time due to the broken testrepo setup (see #5093 for the state of things. spoiler: :vomiting_face: )

**Comment by mih** [comment]
The test passes with #5303 https://ci.appveyor.com/project/mih/datalad/build/job/f7o54hjcfqfhs8e3#L644 without any required fix in the actual implementation -- just the broken test.

**Pull request closed without merging**
