### PR TITLE
Monkey patch nose to avoid need for -s, deprecate ignore_nose_capturing_stdout, make travis output more concise (no -s -v)

### LINKED ISSUE #3213: Make `run_command` tests be tolerated by nose without `-s`
ATM even more tests fail to run `nose` without `-s`. An example:
```
======================================================================
ERROR: datalad.distribution.tests.test_create.test_create_withprocedure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_create.py", line 320, in test_create_withprocedure
    proc_post=[['cfg_metadatatypes', 'xmp', 'datacite']])
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 491, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 479, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 446, in generator_func
    **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/datalad/interface/run_procedure.py", line 462, in __call__
    return_type='generator'
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/datalad/interface/run.py", line 216, in __call__
    sidecar=sidecar):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/run.py", line 546, in run_command
    expected_exit=rerun_info.get("exit", 0) if rerun_info else None)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/run.py", line 385, in _execute_command
    expect_fail=True,
  File "/home/yoh/proj/datalad/datalad/datalad/cmd.py", line 496, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 382, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 818, in _get_handles
    c2pwrite = stdout.fileno()
AttributeError: StringIO instance has no attribute 'fileno'
```
I believe a full list is
```
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_create.py", line 320, in test_create_withprocedure
  File "/home/yoh/proj/datalad/datalad/datalad/interface/tests/test_run_procedure.py", line 138, in test_procedure_discovery
  File "/home/yoh/proj/datalad/datalad/datalad/interface/tests/test_run_procedure.py", line 224, in test_configs
  File "/home/yoh/proj/datalad/datalad/datalad/interface/tests/test_run_procedure.py", line 68, in test_basics
  File "/home/yoh/proj/datalad/datalad/datalad/interface/tests/test_run.py", line 146, in test_py2_unicode_command
  File "/home/yoh/proj/datalad/datalad/datalad/interface/tests/test_run.py", line 169, in test_sidecar
```
this would complement a long list of tests we already marked for being unable to similarly be ran:
```
$> git grep @ignore_nose_capturing_stdout | nl | tail
    25  datalad/support/tests/test_annexrepo.py:@ignore_nose_capturing_stdout
    26  datalad/support/tests/test_annexrepo.py:@ignore_nose_capturing_stdout
    27  datalad/tests/test_cmd.py:@ignore_nose_capturing_stdout
    28  datalad/tests/test_cmd.py:@ignore_nose_capturing_stdout
    29  datalad/tests/test_cmd.py:@ignore_nose_capturing_stdout
    30  datalad/tests/test_cmd.py:@ignore_nose_capturing_stdout
    31  datalad/tests/test_cmd.py:@ignore_nose_capturing_stdout
    32  datalad/tests/test_cmd.py:@ignore_nose_capturing_stdout
    33  datalad/tests/test_cmd.py:@ignore_nose_capturing_stdout
    34  datalad/tests/test_installed.py:@ignore_nose_capturing_stdout
```
of cause we can just mark these newly discovered tests similarly (which I think I will now), but ideally we should look into this problem again.  Here (via  `run_procedure`) , and for all the tests of `run`, problem stems from the run.py:run_command
```
    runner = Runner(cwd=pwd)
    try:
        lgr.info("== Command start (output follows) =====")
        runner.run(
            command,
            # immediate output
            log_online=True,
            # not yet sure what we should do with the command output
            # IMHO `run` itself should be very silent and let the command talk
            log_stdout=False,
            log_stderr=False,
            expect_stderr=True,
            expect_fail=True,
            # TODO stdin
        )
```
so we have both log_stdout and log_stderr False so there is no output collection to a temp file, and thus we bug out with the nose's StringIO as the stdout, which has no .file.

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #3213

### CODE REVIEW

**Comment by yarikoptic** [comment]
WTF with the coverage - what did I break? may be the last commit (no sudo) which I added to the mix? will revert it for a test run

**Comment by kyleam** [comment]
> WTF with the coverage - what did I break? may be the last commit (no sudo) which I added to the mix? will revert it for a test run

Coverage looks better with the new run, though I'm not sure if the sudo really changed anything (don't see why it would) or if codecov was just being finicky.

**Comment by kyleam** [comment]
I wrote:
> stops test_run.py from polluting the output, but feel free to drop it if you'd rather not include it here.

test_run was the worst offender, but there are still some other ones that I didn't look into.

**Comment by yarikoptic** [comment]
Thanks for the `run` tuneup - I am ok to keep it here.  Other offenders could be dealt with separately IMHO

**Pull request merged**
