### PR TITLE
RF: radical - always reuse loop and if pid changes, establish a new one

### PR DESCRIPTION
**Pull request by yarikoptic**
Sits on top of #5350 (wanted to keep it in the git history of struggle), but the actual change is only the 5f6fe634a863281742c0eb7d238c111da6e2e52e

    This might be incomplete solution since we might be "abandoning" original loop
    which is perfectly fine and was somehow tuned by some outside process.  Not
    yet sure what ramifications it would have

I have tested on @djarecka 's use case of testkraken and it works!  Let's see if CI picks up anything

edit -- I did test on `datalad.core.local.tests.test_run` and so no BlockingIOErrors

### CODE REVIEW

**Comment by yarikoptic** [comment]
so -- there is some unhappiness from 3.8 and 3.9 in various scenarios giving out `RuntimeError: This event loop is already running` upon ` event_loop.run_until_complete(` ... always implicates parallel.py - so makes total sense since we use that threaded approach starting with 3.8

<details>
<summary>one popular fail</summary> 

```shell
$> python -m nose -s -v datalad/plugin/tests/test_addurls.py:TestAddurls.test_addurls_deeper
datalad.plugin.tests.test_addurls.TestAddurls.test_addurls_deeper ... ERROR
/usr/lib/python3/dist-packages/smmap/util.py:5: RuntimeWarning: coroutine 'run_async_cmd' was never awaited
  from mmap import mmap, ACCESS_READ
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Versions: annexremote=1.4.3 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20201127+git54-ga1b227171-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.29.2 cmd:system-ssh=8.4p1 exifread=2.3.2 git=3.1.11 gitdb=4.0.5 humanize=0.0.0 iso8601=0.1.13 keyring=21.5.0 keyrings.alt=4.0.1 msgpack=1.0.0 mutagen=1.45.1 requests=2.24.0 scrapy=2.4.1 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'"

======================================================================
ERROR: datalad.plugin.tests.test_addurls.TestAddurls.test_addurls_deeper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 375, in _iter_threads
    raise _FinalShutdown()
datalad.support.parallel._FinalShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/plugin/tests/test_addurls.py", line 692, in test_addurls_deeper
    ds.addurls(
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 482, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 470, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 389, in generator_func
    for r in _process_results(
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 557, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/plugin/addurls.py", line 1324, in __call__
    yield from ProducerConsumerProgressLog(
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 537, in __iter__
    for res in super().__iter__():
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 272, in __iter__
    yield from self._iter_threads(jobs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 424, in _iter_threads
    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 237, in shutdown
    raise exception
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 390, in _iter_threads
    self._pop_done_futures(lgr) or sleeper()
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 465, in _pop_done_futures
    raise exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 336, in consumer_worker
    for r in res:
  File "/home/yoh/proj/datalad/datalad-master/datalad/plugin/addurls.py", line 1254, in addurls_to_ds
    yield from subds.create(result_xfm=None,
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 371, in eval_func
    hooks = get_jsonhooks_from_config(ds.config if ds else dlcfg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 350, in config
    self._cfg = ConfigManager(dataset=None)
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 274, in __init__
    self.reload(force=True)
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 327, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 355, in _reload
    stdout, stderr = self._run(
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 717, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 373, in run
    results = event_loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

----------------------------------------------------------------------
Ran 1 test in 5.609s

FAILED (errors=1)
python -m nose -s -v   4.95s user 2.29s system 104% cpu 6.902 total

```
</details>

so something to see mitigated in case of multithreaded use - I guess multiple threads all try to start the loop

**Comment by yarikoptic** [comment]
<details>
<summary>benchmarks in this PR show some improvement</summary> 

```shell
       before           after         ratio
     [b8fe20e8]       [732e2ce3]
     <bm/merge-target>       <bm/pr>   
       1.36±0.01s       1.32±0.01s     0.97  api.supers.time_createadd
       1.31±0.01s       1.27±0.01s     0.97  api.supers.time_createadd_to_dataset
           failed           failed      n/a  api.supers.time_diff
           failed           failed      n/a  api.supers.time_diff_recursive
       6.58±0.02s       6.39±0.02s     0.97  api.supers.time_installr
          256±1ms          248±5ms     0.97  api.supers.time_ls
       2.38±0.05s       2.33±0.02s     0.98  api.supers.time_ls_recursive
       2.54±0.01s       2.57±0.01s     1.01  api.supers.time_ls_recursive_long_all
           failed           failed      n/a  api.supers.time_remove
       1.26±0.02s       1.25±0.02s     1.00  api.supers.time_status
       2.34±0.02s       2.42±0.03s     1.04  api.supers.time_status_recursive
          115±2ms          112±3ms     0.98  api.supers.time_subdatasets
          410±6ms          385±8ms     0.94  api.supers.time_subdatasets_recursive
          113±1ms          112±2ms     0.99  api.supers.time_subdatasets_recursive_first
       4.43±0.03s       4.50±0.08s     1.02  api.supers.time_uninstall
         716±20ms         718±10ms     1.00  api.testds.time_create_test_dataset1
       4.12±0.06s       4.23±0.02s     1.03  api.testds.time_create_test_dataset2x2
         953±10ms         953±20ms     1.00  core.startup.time_help_np
          171±4ms          173±6ms     1.01  core.startup.time_import
          593±5ms          609±8ms     1.03  core.startup.time_import_api
      3.25±0.07ms      3.01±0.09ms     0.93  core.witlessrunner.time_echo
      3.69±0.08ms      3.39±0.06ms     0.92  core.witlessrunner.time_echo_gitrunner
       3.85±0.4ms       3.95±0.8ms     1.02  core.witlessrunner.time_echo_gitrunner_fullcapture
          531±5ms          515±4ms     0.97  plugins.addurls.addurls1.time_addurls('*')
       2.17±0.02s       2.21±0.02s     1.02  plugins.addurls.addurls1.time_addurls(None)
       18.1±0.2ms       18.2±0.3ms     1.00  repo.gitrepo.time_get_content_info
      7.64±0.03ms      7.63±0.01ms     1.00  support.path.get_parent_paths.time_allsubmods_toplevel
      6.99±0.02ms       7.05±0.2ms     1.01  support.path.get_parent_paths.time_allsubmods_toplevel_only
          366±2ns          358±1ns     0.98  support.path.get_parent_paths.time_no_submods
      5.98±0.03ms      5.95±0.05ms     1.00  support.path.get_parent_paths.time_one_submod_subdir
      5.92±0.03ms      5.92±0.03ms     1.00  support.path.get_parent_paths.time_one_submod_toplevel
        40.2±0.3s          36.9±0s     0.92  usecases.study_forrest.time_make_studyforrest_mockup
```
</details>

<details>
<summary>and as of #5356 -- seems different tradeoffs</summary> 

```shell
       before           after         ratio
     [b8fe20e8]       [970e02a8]
     <bm/merge-target>       <bm/pr>   
       1.17±0.01s       1.17±0.02s     0.99  api.supers.time_createadd
       1.15±0.01s       1.12±0.03s     0.98  api.supers.time_createadd_to_dataset
           failed           failed      n/a  api.supers.time_diff
           failed           failed      n/a  api.supers.time_diff_recursive
          5.73±0s          5.64±0s     0.98  api.supers.time_installr
          229±4ms          218±2ms     0.95  api.supers.time_ls
       2.09±0.02s       2.07±0.05s     0.99  api.supers.time_ls_recursive
       2.29±0.04s       2.24±0.02s     0.98  api.supers.time_ls_recursive_long_all
           failed           failed      n/a  api.supers.time_remove
       1.12±0.01s       1.08±0.01s     0.96  api.supers.time_status
       2.07±0.02s       2.12±0.01s     1.02  api.supers.time_status_recursive
         99.7±2ms         97.9±4ms     0.98  api.supers.time_subdatasets
          352±5ms         362±20ms     1.03  api.supers.time_subdatasets_recursive
        101±0.5ms         96.5±2ms     0.96  api.supers.time_subdatasets_recursive_first
       3.91±0.02s       3.85±0.03s     0.98  api.supers.time_uninstall
          620±6ms         602±10ms     0.97  api.testds.time_create_test_dataset1
       3.71±0.01s       3.66±0.03s     0.98  api.testds.time_create_test_dataset2x2
          945±9ms         940±10ms     0.99  core.startup.time_help_np
          160±2ms          161±2ms     1.01  core.startup.time_import
          578±7ms         598±10ms     1.03  core.startup.time_import_api
      2.97±0.08ms      2.71±0.06ms     0.91  core.witlessrunner.time_echo
       3.50±0.1ms      3.09±0.06ms    ~0.88  core.witlessrunner.time_echo_gitrunner
       3.55±0.2ms      3.27±0.06ms     0.92  core.witlessrunner.time_echo_gitrunner_fullcapture
          490±6ms         499±10ms     1.02  plugins.addurls.addurls1.time_addurls('*')
       2.04±0.01s       2.06±0.01s     1.01  plugins.addurls.addurls1.time_addurls(None)
       16.3±0.5ms       16.6±0.2ms     1.02  repo.gitrepo.time_get_content_info
      7.27±0.05ms       7.93±0.5ms     1.09  support.path.get_parent_paths.time_allsubmods_toplevel
       7.11±0.3ms       7.04±0.1ms     0.99  support.path.get_parent_paths.time_allsubmods_toplevel_only
         347±10ns         371±20ns     1.07  support.path.get_parent_paths.time_no_submods
       6.05±0.1ms       6.18±0.2ms     1.02  support.path.get_parent_paths.time_one_submod_subdir
       5.95±0.1ms       6.19±0.1ms     1.04  support.path.get_parent_paths.time_one_submod_toplevel
       34.7±0.09s       33.2±0.07s     0.96  usecases.study_forrest.time_make_studyforrest_mockup
```
</details>

**Comment by yarikoptic** [comment]
<details>
<summary>benchmarks: still some benefits even with locking overhead ;-)</summary> 

```shell
       before           after         ratio
     [b748922f]       [80e5a92b]
     <bm/merge-target>       <bm/pr>   
          1.00±0s         982±10ms     0.98  api.supers.time_createadd
          970±2ms         961±20ms     0.99  api.supers.time_createadd_to_dataset
           failed           failed      n/a  api.supers.time_diff
           failed           failed      n/a  api.supers.time_diff_recursive
          4.82±0s       4.85±0.03s     1.01  api.supers.time_installr
          193±1ms        192±0.7ms     0.99  api.supers.time_ls
          1.77±0s       1.75±0.01s     0.98  api.supers.time_ls_recursive
       1.93±0.01s       1.91±0.02s     0.99  api.supers.time_ls_recursive_long_all
           failed           failed      n/a  api.supers.time_remove
          937±3ms         922±10ms     0.98  api.supers.time_status
          1.72±0s       1.80±0.01s     1.04  api.supers.time_status_recursive
       84.8±0.4ms       83.4±0.4ms     0.98  api.supers.time_subdatasets
          301±2ms        294±0.9ms     0.98  api.supers.time_subdatasets_recursive
       84.7±0.2ms       83.5±0.3ms     0.99  api.supers.time_subdatasets_recursive_first
       3.29±0.01s       3.30±0.01s     1.00  api.supers.time_uninstall
          528±1ms          521±1ms     0.99  api.testds.time_create_test_dataset1
       3.15±0.02s       3.10±0.01s     0.98  api.testds.time_create_test_dataset2x2
          755±2ms          757±2ms     1.00  core.startup.time_help_np
        133±0.5ms        131±0.7ms     0.98  core.startup.time_import
          473±1ms          473±2ms     1.00  core.startup.time_import_api
-     2.67±0.02ms      2.34±0.01ms     0.87  core.witlessrunner.time_echo
-     3.03±0.01ms      2.70±0.02ms     0.89  core.witlessrunner.time_echo_gitrunner
      3.08±0.01ms      2.83±0.01ms     0.92  core.witlessrunner.time_echo_gitrunner_fullcapture
          403±1ms          401±1ms     0.99  plugins.addurls.addurls1.time_addurls('*')
          1.68±0s       1.68±0.02s     1.00  plugins.addurls.addurls1.time_addurls(None)
       14.3±0.1ms       13.9±0.1ms     0.97  repo.gitrepo.time_get_content_info
      6.44±0.01ms      6.53±0.03ms     1.01  support.path.get_parent_paths.time_allsubmods_toplevel
       5.97±0.1ms      5.98±0.04ms     1.00  support.path.get_parent_paths.time_allsubmods_toplevel_only
        294±0.4ns        299±0.3ns     1.02  support.path.get_parent_paths.time_no_submods
      5.08±0.01ms      5.07±0.01ms     1.00  support.path.get_parent_paths.time_one_submod_subdir
      5.06±0.01ms      5.08±0.01ms     1.00  support.path.get_parent_paths.time_one_submod_toplevel
       29.6±0.01s       28.4±0.09s     0.96  usecases.study_forrest.time_make_studyforrest_mockup
```
</details>

**Comment by yarikoptic** [comment]
<details>
<summary>ok - locking around establishing the loop helps but does not resolve it </summary> 

```shell
$> python -m nose -s -v datalad/core/local/tests/test_save.py:test_add_recursive
datalad.core.local.tests.test_save.test_add_recursive ... ERROR
/usr/lib/python3/dist-packages/exifread/tags/__init__.py:6: RuntimeWarning: coroutine 'run_async_cmd' was never awaited
  from .makernote import apple, canon, casio, fujifilm, nikon, olympus
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Versions: annexremote=1.4.3 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20201127+git54-ga1b227171-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.29.2 cmd:system-ssh=8.4p1 exifread=2.3.2 git=3.1.11 gitdb=4.0.5 humanize=0.0.0 iso8601=0.1.13 keyring=21.5.0 keyrings.alt=4.0.1 msgpack=1.0.0 mutagen=1.45.1 requests=2.24.0 scrapy=2.4.1 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/anaconda-5.2.0-2.7/condabin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'"

======================================================================
ERROR: datalad.core.local.tests.test_save.test_add_recursive
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 375, in _iter_threads
    raise _FinalShutdown()
datalad.support.parallel._FinalShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/core/local/tests/test_save.py", line 579, in test_add_recursive
    res = parent.save(recursive=True, jobs=5)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 482, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 470, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 389, in generator_func
    for r in _process_results(
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 557, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/core/local/save.py", line 349, in __call__
    yield from ProducerConsumerProgressLog(
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 537, in __iter__
    for res in super().__iter__():
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 272, in __iter__
    yield from self._iter_threads(jobs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 424, in _iter_threads
    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 237, in shutdown
    raise exception
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 390, in _iter_threads
    self._pop_done_futures(lgr) or sleeper()
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 465, in _pop_done_futures
    raise exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/parallel.py", line 336, in consumer_worker
    for r in res:
  File "/home/yoh/proj/datalad/datalad-master/datalad/core/local/save.py", line 283, in save_ds
    start_commit = pds_repo.get_hexsha()
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 1856, in get_hexsha
    return self.call_git_oneline(cmd, read_only=True)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 2249, in call_git_oneline
    lines = list(self.call_git_items_(args, files=files,
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 2235, in call_git_items_
    out, _ = self._call_git(args, files, expect_stderr=expect_stderr,
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 2151, in _call_git
    res = runner.run(
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 376, in run
    results = event_loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

----------------------------------------------------------------------
Ran 1 test in 16.093s

FAILED (errors=1)

```
</details>
I just do not yet quite get why it is all nicely working in the original #5350

**Comment by yarikoptic** [comment]
@djarecka I think I will just abandon this approach, at least for now - echoing Python developers, regardless of this PR, it should be the asyncio using process which forks, which should establish a proper "policy" for loops to be established per each fork.

**Comment by djarecka** [comment]
@yarikoptic - with this branch testkaken cli stopped working...:( I should have never opened the issue...;-)

anyway, thanks for working on this! might ask you for help with testkraken, asyncio loops are still very mysterious to me

**Pull request closed without merging**
