### PR TITLE
BF: direct mode/v6 status PR against return value revolution

### LINKED ISSUE #781: Enhance GitRepo.dirty() to be as flexible as GitPython's is_dirty() repo function.
So we can avoid calling it directly, as done in `save()`.

### LINKED ISSUE #1133: *Repo.repo.is_dirty() is broken in direct_mode
Which in turn breaks `save`. The culprit is:

````
cmdline: git -c receive.autogc=0 -c gc.auto=0 diff --abbrev=40 --full-index --raw
  stderr: 'fatal: This operation must be run in a work tree'
````

### LINKED ISSUE #1170: *Repo.commit should report ValueError if instructed to commit untracked content
Currently it looks like this:

````
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', 'set of new files', '/tmp/datalad_temp_clone_url_g9n4z4od/one.txt', '/tmp/datalad_temp_clone_url_g9n4z4od/two.txt'] under '/tmp/datalad_temp_clone_url_g9n4z4od'. Exit code=1. out= err=error: pathspec '/tmp/datalad_temp_clone_url_g9n4z4od/one.txt' did not match any file(s) known to git.
error: pathspec '/tmp/datalad_temp_clone_url_g9n4z4od/two.txt' did not match any file(s) known to git.
````

without such exception users (as in higher-level functions) would need to test upfront whether something is known (which can be pretty expensive) or would not be able to tell what kind error happened.

Affects the implementation of #1169

### LINKED ISSUE #1180: ok_clean_git() broken in direct mode
https://travis-ci.org/datalad/datalad/jobs/191620349

only one test running here and all indirect ones are fine.

````
======================================================================
FAIL: datalad.distribution.tests.test_uninstall.test_kill
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 536, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_uninstall.py", line 339, in test_kill
    ok_clean_git(ds.path)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 183, in ok_clean_git
    ok_(repo.head.is_valid())
AssertionError: None
````

### LINKED ISSUE #1289: we need a better concept than staged/unstaged
As discussed in last hangout, in direct mode there are no unstaged changes.
In general the fact, that we cannot distinguish staged and unstaged changes in direct mode should lead to not use this idea with annex repos at all.

But while trying to rework the Repo classes' `dirty()` methods and the `ok_clean_git` test helper in PR #1277 this is raising questions. There is at least one important place, we use this: `interface/utils.py` in `save_dataset`. There we want to commit if we have either explicitly given paths to commit or there is something staged. As of https://github.com/datalad/datalad/pull/1277/commits/d59cbd5eb4b3f678e654623899a78b6ae901fc29 I keep the current behaviour in indirect mode, therefore still allowing for the parameter `working_tree` for `dirty()` (triggers a warning instead of an exception).
By now this means kind of a correct behaviour, since `dirty(index=True, working_tree=False)` returns `True` whenever there is something staged. It's just different what is staged in direct mode and that's okay - it's direct mode, it should behave like direct mode.

BUT: While the technical behaviour might be okay-ish, it's troublesome to provide it that way. We encourage the idea of distinguishing, what for an annex isn't a valid distinction. As long as we have it that way, the user of an `AnnexRepo` has to be aware of what that means in different annex modes. I don't see us (or even future contributors) having this is mind all the time.

So, I think we need a concept of how to catagorize possible changes in an annex repository in a more fitting way. The minimum would be to rename the parameters (originally coming from GitPython) from `index, working_tree` to `staged, unstaged`, which is still troublesome but at least better than talking about a working tree, that isn't there.
What else can you think of? Perhaps consider especially the situation described in `save_dataset`. Any other conceptional approach on what kind of changes to commit than "staged" ones? Please note, that it has not necessarily to fit into `dirty()`. Once we have an idea, what we are looking for, we can have a dedicated method to do so, of course.

### LINKED ISSUE #1291: Let it be OK to call GitRepo.commit() when there is nothing to commit
See  #1289 for the story.

### PR DESCRIPTION
**Pull request by bpoldrack**
This replaces PR #1277 .

Intense testing/development for `AnnexRepo.status()` and `XXXRepo.dirty()`
Making sure this works in v5 direct mode, v5 indirect mode, v6, v6 adjusted branch.
In all cases includes submodules and even mixed hierarchies of plain git, and different annex type repos. The latter can only fully be achieved with a `status` method at the level of `Dataset`, which will also be a datalad command. Since the things already in here should be merged ASAP, this will be completed by a PR on top of this one. Therefore the following original tasks are to be completed in that next PR, too:
- [ ] ~make submodule recursion despite of direct mode submodules also work when started at a plain git~
- [ ] ~document everything~
- [ ] ~provide proper documentation: what (compound) operations on annexes we can have reliable assumptions about (before state vs after state) and what are these assumptions.~

- [x] Closes #781 
- [x] Closes #1180 
- [x] Closes #1133
- [x] Closes #1291 
- [x] Closes #1170
- [x] Closes #1289 (depends on what else waits to be discovered herein)
- [x] move calls to annex-adjust, annex-lock, annex-unlock to AnnexRepo

Note:
In the former PR (#1277) there was an unfinished discussion on the question of whether to provide a `dirty` property and to rename the method to `is_dirty`. I wont do it herein. This becomes clearer with the full shaped `status` at `Dataset` level and a test helper `ok_status`, which I think should replace the enhanced usages of `ok_clean_git`.

Note2:
This also merges master into rf-returnvalues!

### CODE REVIEW

**Comment by yarikoptic** [comment]
> In the former PR (#1277) there was an unfinished discussion on the question of whether to provide a dirty property and to rename the method to is_dirty. I wont do it herein. This becomes clearer with the full shaped status at Dataset level and a test helper ok_status, which I think should replace the enhanced usages of ok_clean_git.

I really don't get it why not herein....  why now we need to
1. break the API compatibility with anything which could have used `.dirty` property so it becomes `.dirty()`
2. make this diff longer than needed since many changes are just that `dirty` -> `dirty()`
I really don't get it

**Comment by mih** [comment]
PY3 failure is a forgotton? `print`.

**Comment by yarikoptic** [comment]
re `print` statement -- I felt like it was left there on purpose to crash and alert to incomplete yet smth ;)  so I didn't fix it in my "attempt to help" PR

**Comment by bpoldrack** [comment]
@datalad/developers : ATM I have no idea what is going on. Mow a lot of SSH related tests are failing. At the state the both of you commented on last, this didn't happen. But reverting the last two commits doesn't prevent it from happen. So - seems unrelated.

**Comment by yarikoptic** [comment]
https://github.com/datalad/datalad/issues/1456

**Pull request merged**
