### PR TITLE
TEMP: time tests in default (and then bionic)

### PR DESCRIPTION
**Pull request by yarikoptic**
to see if any suspicion (e.g. slower ssh) could find grounds.

I did quick comparison on some basic tests in two xenial (16.04) and bionic (18.04) environments (no ssh tests), and there were no difference 

TODO
- [ ] make a run with bionic (was not sure if I could make a matrix on `dist`)

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm, I do not see drastic difference (well, there is 7% increase with 1 test failed, so may be it could take longer; but it is not something which should lead to time out) between xenial and bionic runs
* [xenial](https://api.travis-ci.org/v3/job/711347499/log.txt)
```
Ran 1111 tests in 1065.426s
OK (SKIP=53)
```
* [bionic](https://api.travis-ci.org/v3/job/711507070/log.txt)
```
Ran 1111 tests in 1146.540s
FAILED (SKIP=53, errors=1)
```
@kyleam - what matrix run was particularly effected by switch to bionic?

**Comment by yarikoptic** [comment]
BTW here are the tests timing on bionic for those which took >= 10 sec, even though AFAIK we excluded all the "slow" and integration tests... (and the only `@turtle`  `test_ria_basics.py:test_gitannex_ssh` with uncommented on timing is completely excluded from all travis runs)
```
[success] 3.79% datalad.distributed.tests.test_create_sibling_ria.test_create_simple('datalad-test',): 42.9331s
[success] 3.66% datalad.distributed.tests.test_ria_basics.test_gitannex_local: 41.3606s
[success] 2.53% datalad.distribution.tests.test_create_sibling.test_target_ssh_recursive(True,): 28.6491s
[success] 2.30% datalad.distribution.tests.test_create_sibling.test_target_ssh_simple: 26.0251s
[success] 1.75% datalad.distribution.tests.test_create_sibling.test_target_ssh_recursive(False,): 19.8421s
[success] 1.54% datalad.distributed.tests.test_ria_basics.test_version_check('datalad-test',): 17.4741s
[success] 1.53% datalad.support.tests.test_annexrepo.test_files_split_exc(<class 'datalad.support.annexrepo.AnnexRepo'>,): 17.3390s
[success] 1.35% datalad.support.tests.test_annexrepo.test_files_split_exc(<class 'datalad.support.gitrepo.GitRepo'>,): 15.3170s
[success] 1.31% datalad.distribution.tests.test_create_sibling.test_replace_and_relative_sshpath(True,): 14.7971s
[success] 1.27% datalad.core.distributed.tests.test_clone.test_ria_postclonecfg('ssh://datalad-test:/tmp/datalad_temp_yaofsq1j', '27d3c223-cdc4-11ea-aeeb-42010a140029'): 14.3383s
[success] 1.23% datalad.local.tests.test_subdataset.test_get_subdatasets: 13.9440s
[success] 1.18% datalad.distributed.tests.test_ria_git_remote.test_bare_git_version_2('datalad-test',): 13.3907s
[success] 1.11% datalad.distributed.tests.test_ria_basics.test_remote_layout('datalad-test',): 12.5726s
[success] 1.08% datalad.distribution.tests.test_publish.test_publish_recursive: 12.2228s
[success] 1.08% datalad.distributed.tests.test_ria_git_remote.test_bare_git_version_1('datalad-test',): 12.1805s
[success] 1.04% datalad.local.tests.test_copy_file.test_copy_file_datalad_specialremote: 11.7139s
[success] 1.03% datalad.distributed.tests.test_create_sibling_ria.test_create_simple(None,): 11.6012s
[success] 0.97% datalad.support.tests.test_repo_save.test_gitrepo_save_all: 11.0039s
[success] 0.97% datalad.support.tests.test_repo_save.test_annexrepo_save_all: 10.9739s
[success] 0.96% datalad.support.tests.test_fileinfo.test_get_content_info: 10.8724s
[success] 0.94% datalad.distribution.tests.test_publish.test_publish_depends: 10.6688s
[success] 0.91% datalad.distribution.tests.test_create_sibling.test_replace_and_relative_sshpath(False,): 10.3215s
[success] 0.89% datalad.distribution.tests.test_create_sibling.test_target_ssh_since(True,): 10.0365s
```
I will annotate all those as `@slow` for maint branch right away - our travis runs for all the slow and integration are on the order of 13 min whenever the "non slow" one (default) above 25 min ATM see eg. https://travis-ci.org/github/datalad/datalad/builds/711248758

**Comment by kyleam** [comment]
> @kyleam - what matrix run was particularly effected by switch to bionic?

The discussion of hitting maximum timeouts with bionic was in the context of the git-annex autobuild jobs to test with recent ssh-fixes in git-annex.  I wasn't making any strong claim about whether our testing in general is slower on bionic or saying I tried to look at it in any systematic way.  Also, with speeds ups from using a non-bundled git-annex, I bet you wouldn't get close enough to the 50 min mark.

Here's an [example][0] of a job with an early iteration of the series at gh-4680.  For the `NOSE_SELECTION= NOSE_SELECTION_OP=not` under python 3.7 and the autobuild git-annex, the xenial job just makes it under the max time at 44 min, while the bionic job exceeds it.

I pushed scratch/autobuild-bionic-xenial (1fb231db3) to see if with the current tip of maint, current autobuild, and `NOSE_SELECTION= NOSE_SELECTION_OP=not` would show something similar.  But in that case, both bionic and xenial exceed the max time:  https://travis-ci.org/github/datalad/datalad/builds/711550410

[0]: https://travis-ci.org/github/datalad/datalad/builds/705850664

**Comment by yarikoptic** [comment]
ok, thanks for the explanation!  Please add `--with-timer` to nose invocation in your run.  Then we could get the timings and see if there is a systematic slow down (all tests somewhat proportionally get slower) or some type (e.g. needing SSH) specifically.

**Pull request closed without merging**
