### PR TITLE
Let `EnsureChoice` report the value is failed validating

### PR DESCRIPTION
**Pull request by mih**
Just that. Feel free to reject. It was just bothering me enough that I had this change in my local deployment to help me figure what is actually happening.

### CODE REVIEW

**Review by yarikoptic — APPROVED** [review]
I am always for more informative error messages. Failing CI should be checked to not be related (if eg we rely somewhere in matching that message)

**Review by bpoldrack — APPROVED** [review]
Approving but not yet merging, since tests aren't finished and I want to see them (for entirely unrelated to this PR reasons, though). Confident, that failures are unrelated (already saw one, that is highly likely to be same as #6599).

**Comment by bpoldrack** [comment]
Ok, still sure the CI failures need addressing elsewhere. Merging.

Thx, @mih.

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.7`](https://github.com/datalad/datalad/releases/tag/0.17.7)

**Pull request merged**
