### PR TITLE
Reimplement the datalad(-archives) special remotes with AnnexRemote

### LINKED ISSUE #5006: Reimplement `archives` special remote based on `AnnexRemote`
This is an old implementation that is based on its own git-annex protocol implementation. The majority of modern special remote implementations is based on `AnnexRemote`. We should make this uniform.

### LINKED ISSUE #5800: `archive` remote related crash
```
% datalad install ///indi/fcon1000
% cd fcon1000
% datalad get AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz
[INFO   ] scanning for unlocked files (this may take some time)                                                            
install(ok): /tmp/fcon1000/AnnArbor_a (dataset) [Installed subdataset in order to get /tmp/fcon1000/AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz]
[ERROR  ] 'path' [get.py:__call__:953] (KeyError) 

% git -C AnnArbor_a annex get sub04111/anat/mprage_anonymized.nii.gz 
get sub04111/anat/mprage_anonymized.nii.gz (from datalad-archives...) 
[INFO] To obtain some keys we need to fetch an archive of size 1.6 GB 

  To obtain some keys we need to fetch an archive of size 1.6 GB

  TRANSFER failed with no reason given

  Unable to access these remotes: datalad-archives

  Maybe add some of these git remotes (git remote add ...):
        ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a
failed
git-annex: get: 1 failed

      % datalad --dbg get AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz
Traceback (most recent call last):                                                                                         
  File "/home/mih/env/datalad-dev/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 440, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 783, in call_from_parser
    ret = list(ret)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 574, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/distribution/get.py", line 953, in __call__
    if res['path'] not in content_by_ds:
KeyError: 'path'

> /home/mih/hacking/datalad/git/datalad/distribution/get.py(953)__call__()
-> if res['path'] not in content_by_ds:
(Pdb) p res
{'type': 'file', 'logger': <Logger datalad.distribution.get (INFO)>, 'refds': '/tmp/fcon1000', 'status': 'error'}
```

I can replicate the crash with `master` and `maint`. Independent of whether the download failure is justified, the crash is not. The generated result is broken, not `action`, no `path`, no `message`, despite being an error.

### PR DESCRIPTION
**Pull request by mih**
This aims to be a faithful reimplementation of both special remotes. It should not change behavior in any way, even though the implementation changes significantly, capitalizing on the protocol implementation readily provided by `AnnexRemote`.

- Fixes #5006 
- Fixes #5800

TODO:

- [x] "Rebase" `datalad` special remote on `AnnexRemote`
- [x] "Rebase" `datalad-archive` special remote on `AnnexRemote`
- [x] Strip obsolete annex protocol implementation
- [x] Consolidate, deduplicate

### CODE REVIEW

**Comment by loj** [comment]
I did some playing around with this, and didn't notice any changes in behavior for the `datalad-archives` or `datalad` special remotes.

**Comment by mih** [comment]
> I did some playing around with this, and didn't notice any changes in behavior for the `datalad-archives` or `datalad` special remotes.

Thx much @loj !

**Comment by mih** [comment]
@yarikoptic it would be useful if you could have a quick look at this. Once merged, I would make it the basis for a rewrite of the ORA special remote, implemented on top this approach.

**Comment by mih** [comment]
OK, let's do this. We better give it ample exposure to real-world usage before it hits a release

**Pull request merged**
