### PR TITLE
Temp test devel annex with mimeencoding support

### PR DESCRIPTION
**Pull request by yarikoptic**
This one should provide mimeencoding support for better detection of text files, see https://github.com/datalad/datalad/issues/3361#issuecomment-488349192

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm, apparently travis isn't running on Draft PRs! Apparently it is "by design" but debated now: https://travis-ci.community/t/draft-pull-requests-not-being-built/2434/9 
So as far as I see it Draft PRs are really for drafting something and not even expecting it to be tested. Moving this PR into an Open one but with do not merge label

**Comment by kyleam** [comment]
@yarikoptic:

> hm, apparently travis isn't running on Draft PRs!

Yep, in fact we've already discussed it :]

https://github.com/datalad/datalad/pull/3208#issuecomment-470866713

**Comment by yarikoptic** [comment]
Oh, missed that lively discussion, thanks

**Comment by yarikoptic** [comment]
so - tests pass (so no bad side effects), coverage differences make no sense to me

**Pull request closed without merging**
