### PR TITLE
Little scripty to generate a demo collection with handles (WiP)

### PR DESCRIPTION
**Pull request by hanke**
All CC or public domain content for handle1.
  Image of a map from wikipedia with history
  Movie from internet archive
  Public domain book

Unmodified Debconf annex for handle2
  Handle with lots of content and lots of clones

### CODE REVIEW

**Comment by yarikoptic** [comment]
What about adding few of annexes we have already: those to demonstrate not versioning but rather access to materials available online otherwise

https://github.com/datalad/mlbooks (was established manually) -- ideally could be improved with annex meta data tags

https://github.com/datalad/nih--videocast    --  2.93 terabytes of videos from NIH -- used to be crawled automagically with datalad, but now needs fixes up for changes in the website

**Comment by hanke** [comment]
Sure, why not. But each of them should show off some feature that is not as
obvious with the others. Just "more" is not necessary as will should have
them as proper handles, not just as demos.

**Comment by yarikoptic** [comment]
videocast one demos access to a vast array of data/videos from online without heavy downloading it all at once, and also updates from the datalad.  handle info sure thing we need to add now .  Also it demontrates ability for a custom files layout, possibly more convenient than original website -- I find it easier to search among files than among some custom web UI

mlbooks -- themed collection of stuff from around the web

**Comment by hanke** [comment]
I will replace this PR with something more recent.

**Comment by hanke** [comment]
Obsolete

**Pull request closed without merging**
