### PR TITLE
TST: gitrepo on windows

### PR DESCRIPTION
**Pull request by mih**
fixes gh-3635 

Tests enabled on appveyor now, too.

### CODE REVIEW

**Comment by mih** [comment]
Underlying SSH handling issues:

```
======================================================================
2143ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_ssh_pull
2144----------------------------------------------------------------------
2145Traceback (most recent call last):
2146  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
2147    self.test(*self.arg)
2148  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 913, in newfunc
2149    return func(*args, **kwargs)
2150  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
2151    return t(*(arg + (filename,)), **kw)
2152  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
2153    return t(*(arg + (filename,)), **kw)
2154  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_gitrepo.py", line 576, in test_GitRepo_ssh_pull
2155    repo.pull(remote="ssh-remote", refspec=remote_repo.get_active_branch())
2156  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 2116, in pull
2157    **kwargs
2158  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 2067, in _call_gitpy_with_progress
2159    if is_ssh(url):
2160  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 896, in is_ssh
2161    _ri = RI(ri) if not isinstance(ri, RI) else ri
2162  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 410, in __new__
2163    cls = _guess_ri_cls(ri)
2164  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 331, in _guess_ri_cls
2165    fields = URL._pr_to_fields(urlparse(ri))
2166  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 655, in _pr_to_fields
2167    return {f: (_getattr(pr, f) or '') for f in cls._FIELDS}
2168  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 655, in <dictcomp>
2169    return {f: (_getattr(pr, f) or '') for f in cls._FIELDS}
2170  File "C:\Miniconda35\envs\test-environment\lib\urllib\parse.py", line 158, in port
2171    port = int(port, 10)
2172ValueError: invalid literal for int() with base 10: '\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\Temp\\\\1\\\\datalad_temp_csyd0886'
2173

======================================================================
2175ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_ssh_push
2176----------------------------------------------------------------------
2177Traceback (most recent call last):
2178  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
2179    self.test(*self.arg)
2180  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 913, in newfunc
2181    return func(*args, **kwargs)
2182  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
2183    return t(*(arg + (filename,)), **kw)
2184  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
2185    return t(*(arg + (filename,)), **kw)
2186  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_gitrepo.py", line 612, in test_GitRepo_ssh_push
2187    pushed = repo.push(remote="ssh-remote", refspec="ssh-test")
2188  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 2194, in push
2189    **kwargs
2190  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 2067, in _call_gitpy_with_progress
2191    if is_ssh(url):
2192  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 896, in is_ssh
2193    _ri = RI(ri) if not isinstance(ri, RI) else ri
2194  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 410, in __new__
2195    cls = _guess_ri_cls(ri)
2196  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 331, in _guess_ri_cls
2197    fields = URL._pr_to_fields(urlparse(ri))
2198  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 655, in _pr_to_fields
2199    return {f: (_getattr(pr, f) or '') for f in cls._FIELDS}
2200  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 655, in <dictcomp>
2201    return {f: (_getattr(pr, f) or '') for f in cls._FIELDS}
2202  File "C:\Miniconda35\envs\test-environment\lib\urllib\parse.py", line 158, in port
2203    port = int(port, 10)
2204ValueError: invalid literal for int() with base 10: '\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\Temp\\\\1\\\\datalad_temp_86nm5hbh'
2205
```

**Comment by yarikoptic** [comment]
I feel like that was also approached to be fixed in https://github.com/datalad/datalad/pull/2870/files#diff-a2327fd281ad2b29b6bb6ff59889d2c5

**Comment by mih** [comment]
One aspect that causes this failure is an inappropriate test setup here: https://github.com/datalad/datalad/blob/master/datalad/support/tests/test_gitrepo.py#L557

It appends an absolute windows path (e.g. `C:\something`) to `ssh://localhost` in an attempt to build a URL -- which leads to garbage.

**Comment by mih** [comment]
With the following change in the test setup we get a little further

```diff
diff --git a/datalad/support/tests/test_gitrepo.py b/datalad/support/tests/test_gitrepo.py
index 86abf1c93..c358495ff 100644
--- a/datalad/support/tests/test_gitrepo.py
+++ b/datalad/support/tests/test_gitrepo.py
@@ -548,6 +548,16 @@ def test_GitRepo_ssh_fetch(remote_path, repo_path):
     assert_in('ssh-remote/master', repo.get_remote_branches())


+def _path2localsshurl(path):
+    from pathlib import Path
+    path = op.abspath(path)
+    p = Path(path)
+    if p.drive:
+        path = '/'.join(('/{}'.format(p.drive[0]),) + p.parts[1:])
+    url = "ssh://localhost{}".format(path)
+    return url
+
+
 @skip_ssh
 @with_tempfile
 @with_tempfile
@@ -555,7 +566,7 @@ def test_GitRepo_ssh_pull(remote_path, repo_path):
     from datalad import ssh_manager

     remote_repo = GitRepo(remote_path, create=True)
-    url = "ssh://localhost" + op.abspath(remote_path)
+    url = _path2localsshurl(remote_path)
     socket_path = op.join(str(ssh_manager.socket_dir),
                           get_connection_hash('localhost', bundled=True))
     repo = GitRepo(repo_path, create=True)

(
```

```
======================================================================
ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_ssh_pull
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 908, in newfunc
    return func(*args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 602, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 602, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\support\tests\test_gitrepo.py", line 586, in test_GitRepo_ssh_pull
    repo.pull(remote="ssh-remote", refspec=remote_repo.get_active_branch())
  File "C:\Users\mih\code\datalad\datalad\support\gitrepo.py", line 2102, in pull
    **kwargs
  File "C:\Users\mih\code\datalad\datalad\support\gitrepo.py", line 2059, in _call_gitpy_with_progress
    ret = callable(**git_kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\git\remote.py", line 809, in pull
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "C:\Users\mih\Miniconda3\lib\site-packages\git\remote.py", line 674, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "C:\Users\mih\Miniconda3\lib\site-packages\git\cmd.py", line 412, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull --progress -v ssh-remote ssh-test
  stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
```

This is gitpy revolting, although Git itself seems fine:

```
(base) C:\Users\mih\AppData\Local\Temp\datalad_temp_owej3g0f>git pull --progress -v ssh-remote ssh-test
mih@localhost's password:
From ssh://localhost/C/Users/mih/AppData/Local/Temp/datalad_temp_mrrluzcu
 * branch            ssh-test   -> FETCH_HEAD
 = [up to date]      ssh-test   -> ssh-remote/ssh-test
```

**Comment by mih** [comment]
SSH issues are only partially resolved, and ultimately the SSH-related tests are disabled on Windows still. But this brings us closer IMHO.

**Comment by bpoldrack** [comment]
LGTM

**Comment by mih** [comment]
Thx!

**Pull request merged**
