### PR TITLE
ENH various enhancements to search and around it

### LINKED ISSUE #912: add some  convenience options to search command (search from the very top of the nested, search central one)
currently (probably rightfully), we search from current dataset (and into subdatasets).  But while playing with it, I found myself more and more often wanting to search the entire collection.  For that I always needed to cd to the top and run it... kinda lame.  So I would suggest to add some command line options to
- search  from the very top of current super-dataset (e.g. -s,--super  or -t, --top, or...)
- instead of local dataset, search (and return paths) for global (~/datalad) dataset. (-g,--global or -u,--user  or -c,--central)
?

There is not that much to do for both of those to happen (there is already code there, which just needs RFing a bit to generalize) besides deciding on the names of the options ;), and I think that it would make interaction with search smoother.

### LINKED ISSUE #964: search should get a list of fields/attributes to search among
e.g. I wanted to find datasets defining 'fundedBy'
```shell
$> datalad search -R funded 
...
openfmri/ds000208:
 foaf:fundedBy: Eli Lilly Pharmaceuticals funded study 2 (IIT number: F1J-US-XO61). This research was partially also supported by grants from National Institute of Neurological Disorders and Stroke (NS035115), and National Center for Complementary and Integrative Health (AT007987) of U.S. National Institutes of Health. P.T. and E.V.-P. were supported by the Canadian Institutes of Health Research.
```
but it didn't return e.g.
```
$> datalad search -R DE019580
openfmri/ds000030:
 foaf:fundedBy: UL1-DE019580, RL1MH083268, RL1MH083269, RL1DA024853, RL1MH083270, RL1LM009833, PL1MH083271, PL1NS062410
```
of cause we could have a dedicated command to report datasets having such a field defined... OR we could just finally add an option to specify among which fields to search, so then I could just do `--regex -f foaf:fundedBy .`... hence the title!

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #964 -- use -s option to specify fields/properties to search)
Closes #912 -- use -d^ to search from the very top of current datasets hierarchy, -d/// to search central one

There were some refactoring along the way (`assert_unicode`, moved `_with_sep` into utils, etc). Overall tried to keep amount of possible conflicts to minimum with WiP work... but no guarantees ;)

Try search now with those options -- it is quite neat IMHO

couldn't resist so now we are spitting out suggestions in case none of the properties was found:

```
(git)hopa:~datalad/datalad[enh-search-fields]git
$> datalad search -d/// -slocati a
2016-09-30 21:01:16,349 [WARNING] Found no properties which matched one of the one you specified (locati).  May be you meant one among: homepage, citation, contributors, license, author, type, description, title, dc:ispartof, id, dc:haspart, version, location, keywords, foaf:fundedby, dc:conformsto, dc:modified, schema:availablefrom, name.
| Suggestions:
|  location for locati (search.py:335)
```

### CODE REVIEW

**Comment by yarikoptic** [comment]
ok -- examples:

```shell
hopa:~
$> datalad search -d/// -sauthors Hank  
2016-09-30 21:14:54,454 [WARNING] Found no properties which matched one of the one you specified (authors).  May be you meant one among: homepage, citation, contributors, license, author, type, description, title, dc:ispartof, id, dc:haspart, version, location, keywords, foaf:fundedby, dc:conformsto, dc:modified, schema:availablefrom, name.
| Suggestions:
|  author for authors (search.py:332)
Nothing to report

$> datalad search -d/// -sauthor Hank                        
datalad/openfmri/ds000113c 
datalad/openfmri/ds000113d 

# and we can pipe
$> datalad search -d/// -sauthor Hank | xargs datalad install
2016-09-30 21:15:11,701 [INFO] Installing subdataset <Dataset path=/home/yoh/datalad/openfmri> in order to get /home/yoh/datalad/openfmri/ds000113c (utils.py:129)
...
2 installed items are available at
<Dataset path=/home/yoh/datalad/openfmri/ds000113c>
<Dataset path=/home/yoh/datalad/openfmri/ds000113d>

$> cd datalad/openfmri/ds000113d

hopa:~/datalad/openfmri/ds000113d
$> datalad search -d^ fMRI           
../../indi/fcon1000       
../../labs/mitchell 
...
```

**Comment by yarikoptic** [comment]
since this patch touches the "main" Dataset class, additional work would be needed to support that sugaring elsewhere:
```shell
$> datalad --dbg install -d/// openfmri/ds000003 
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 11, in <module>
    load_entry_point('datalad', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 258, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 296, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/install.py", line 571, in __call__
    if sm.path == relativepath][0]
IndexError: list index out of range
()
> /home/yoh/proj/datalad/datalad/datalad/distribution/install.py(571)__call__()
-> if sm.path == relativepath][0]
```
which seems to be just a generic problem we have even without sugaring:
```shell
$> python -c 'import datalad.api;from datalad.distribution.dataset import Dataset; Dataset("/home/yoh/datalad").install("openfmri/ds000003")'          
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/dataset.py", line 478, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/install.py", line 571, in __call__
    if sm.path == relativepath][0]
IndexError: list index out of range
```
but I am not sure if I should file an issue against install ATM in light of #959 ;)

**Comment by yarikoptic** [comment]
@mih what do you think?

**Comment by mih** [comment]
Haven't tried it, but looks good.

**Comment by yarikoptic** [comment]
Ok, will merge then, and fix later if issues arise

**Pull request merged**
