### PR TITLE
Tailor help message to API

### LINKED ISSUE #2986: Failed `datalad.api.run()` should log Python invocation (not cmdline)
```shell
$> python -c 'from datalad.api import run; run("touch 1234; exit 1");'
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -r -F .git/COMMIT_EDITMSG .' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 491, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/run.py", line 220, in __call__
    sidecar=sidecar):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/run.py", line 639, in run_command
    raise exc
datalad.support.exceptions.CommandError: CommandError: command 'touch 1234; exit 1' failed with exitcode 1
```
and ideally we should have 
```
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'save(path='.', recursive=True, message_file=".git/COMMIT_EDITMSG")' 
```

### PR DESCRIPTION
**Pull request by mih**
#### 💫 Enhancements and new features
- The `run` command now provides readily executable, API-specific instructions how to save the results of a command execution that failed expectedly. Fixes #2986

### CODE REVIEW

**Review by adswa — APPROVED** [review]
useful addition, thanks!

**Comment by yarikoptic** [comment]
may be make Changelog entry a bit more consistent with wording of other entries? 

- In API mode `run` will now give readily executable, API-specific instructions how to save the results of a command execution that failed expectedly. Fixes #2986

**Review by yarikoptic — APPROVED** [review]
well, besides that such message is not "tested", looks good to me

**Comment by mih** [comment]
Thanks, adjusted the changelog, but in a different way.

**Pull request merged**
