### PR TITLE
TEMP: (maint) - test devel annex 8.20200226+git16-ge156a2b74-1~ndall+1

### PR DESCRIPTION
**Pull request by yarikoptic**
Now that #4262 is merged, we should observe no stalling, and this hopefully would highlight possible left-over (in `maint`) issues

### CODE REVIEW

**Comment by yarikoptic** [comment]
crap, #4262 was not sufficient - I guess there is yet another spot which leads to the same problem :-/

```
datalad.support.tests.test_annexrepo.test_annex_ssh ... 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by yarikoptic** [comment]
Ok, now during annex sync, and I forgot to add logging of stdouts of external commands... Later

**Comment by yarikoptic** [comment]
ok, `sync` stalls on 
```
[Level 9] Running: ['git-annex', 'sync', '-c', 'annex.dotfiles=true', '-c', 'remote.ssh-remote-1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/8157d2a9', '--debug'] 
[2020-03-10 15:05:06.485413058] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.dotfiles=true","-c","remote.ssh-remote-1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/8157d2a9","show-ref","git-annex"]
[2020-03-10 15:05:06.487855401] process done ExitSuccess
[2020-03-10 15:05:06.487971815] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.dotfiles=true","-c","remote.ssh-remote-1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/8157d2a9","show-ref","--hash","refs/heads/git-annex"]
[2020-03-10 15:05:06.490225036] process done ExitSuccess
[2020-03-10 15:05:06.490492999] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.dotfiles=true","-c","remote.ssh-remote-1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/8157d2a9","log","refs/heads/git-annex..591c066409d2a3c63b46f7619d9337074a4349e9","--pretty=%H","-n1"]
[2020-03-10 15:05:06.492827529] process done ExitSuccess
[2020-03-10 15:05:06.499041044] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.dotfiles=true","-c","remote.ssh-remote-1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/8157d2a9","cat-file","--batch"]
[2020-03-10 15:05:06.500268095] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.dotfiles=true","-c","remote.ssh-remote-1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/8157d2a9","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
[2020-03-10 15:05:06.50342035] read: ssh ["datalad-test","-S",".git/annex/ssh/datalad-test","-o","ControlMaster=auto","-o","ControlPersist=yes","-o","ControlMaster=auto","-S","/home/travis/.cache/datalad/sockets/8157d2a9","-n","-T","git-annex-shell 'configlist' 
```
so we do pass socket configuration, but nowhere in the [log](https://api.travis-ci.org/v3/job/660659332/log.txt) I see some explicit call to ssh to create that socket or some preceding `sshrun`.  Just for the fun of it, I will rerun now with `GIT_ANNEX_USE_GIT_SSH=1` and see what happens.

**Comment by yarikoptic** [comment]
ok -- somewhat confirming -- it doesn't hang then but fails the test with
```

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_annex_ssh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 213, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1077, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1077, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/support/tests/test_annexrepo.py", line 1179, in test_annex_ssh
    ok_(exists(socket_1))
AssertionError: None
```
so the socket is not (pre-)generated.  FWIW, it doesn't fail for me locally with either git-annex.
But actually I am a bit confused now how `ssh` "should" work at all on travis.  We do setup a key etc in https://github.com/datalad/datalad/blob/master/tools/ci/prep-travis-forssh.sh assuming that home (`~/`) would be the same while running tests, but in our global `setup_package` [fixture](https://github.com/datalad/datalad/blob/master/datalad/__init__.py#L104) we redefine `$HOME`.  So if there is no ssh-agent (as on travis, since we do not "source" that script):
```shell
$> grep ssh-agent tools/ci/prep-travis-forssh.sh
eval $(ssh-agent)
(dev3) 1 35448.....................................:Tue 10 Mar 2020 11:28:53 AM EDT:.
(git)lena:~datalad/datalad[temp-test-devel-annex-maint]git
$> grep -1 tools/ci/prep-travis-forssh.sh .travis.yml
  - sudo eatmydata tools/ci/prep-travis-forssh-sudo.sh
  - tools/ci/prep-travis-forssh.sh
  # Install grunt-cli
```
I do not even see how ssh could work... confused ;-(   will push some diagnostic print outs and attempts to login (no sockets)

**Comment by yarikoptic** [comment]
I keep fighting "log_online" mode to get output of `annex --debug`, but original stall was happening without `log_online`.  Some observations:
- annex adds `ControlPersist=yes` (whenever we do with a timeout)
- when I ran `python -m nose` with a test having direct invocation to the `ssh` with a similar command git annex calls in `sync`, and if I removed all sockets before, then even when ssh invocation "finished" the whole nose process was hanging until I would kill those ssh processes for the sockets
- you could probably see active sockets after you run nose tests under `~/.cache/datalad/sockets/`

**Comment by yarikoptic** [comment]
now confirmed -- besides that stalling test (which I just skipped for now) no other test seems to be effected: https://travis-ci.org/github/datalad/datalad/builds/661639639?utm_medium=notification&utm_source=github_status 
I will submit a PR which would just skip that test when detects this "problematic" git-annex.
I will resubmit this PR in its previous limited testing case with subsequent devel of git-annex to see first if newer one is effected as well.

**Comment by kyleam** [comment]
> now confirmed -- besides that stalling test (which I just skipped for now) no other test seems to be effected

phew

>  I will submit a PR which would just skip that test when detects this "problematic" git-annex.

Sounds good.  Thanks.

**Pull request closed without merging**
