### PR TITLE
TEMP appveyor: test with python 3.6 on windows (instead of 3.8)

### PR DESCRIPTION
**Pull request by yarikoptic**
inspired by https://github.com/datalad/datalad/issues/5338

### CODE REVIEW

**Comment by mih** [comment]
That "worked". Looking into it.

**Comment by mih** [comment]
I can replicate the particular test failure, but I cannot determine the source of the problem. The repository labeled as "does not appear to be a git repository" is perfectly clonable via `git clone` as well as `datalad clone`. The path is also expanded to the correct location.

That being said: Is there any specific reason for using PY36 on windows? It is approaching its EOL, and IMHO energy is better spent on achieving reasonable functionality on a recent Python, rather than on all Python versions.

**Comment by yarikoptic** [comment]
It's our minimal supported version of python ATM according to setup.py

**Comment by mih** [comment]
> It's our minimal supported version of python ATM according to setup.py

That is true. But I was wondering whether that makes any sense. AFAIK that number is motivated by Debian stable and HPC platform availability concerns. Neither of which have any implications on Windows. The Q for me is: Do we have anyone that cares for PY 3.6/7/8 on Windows, and anyone that cares enough about the functionality that may or may not be available in this specific scenario. I personally do not care, and I am also not aware of anything that would justify spending time on this.

Happy to tag 'wontfix' and move on, from my side.

**Pull request closed without merging**
