### PR TITLE
ENH(TST,BK): test_v7_detached_get to excercise a fixed in recent (7.20190708+git36-g32d526164-1) annex

### PR DESCRIPTION
**Pull request by yarikoptic**
Will fail first on travis, then whenever https://github.com/datalad/datalad/pull/3541 passes and I upload new annex to neurodebian proper, rerun the tests and should get green, and then we merge

### CODE REVIEW

**Comment by yarikoptic** [comment]
BTW, locally takes 2.4 seconds.  Analogous [bash script from kyle](http://git-annex.branchable.com/bugs/get_fails_to_place_v7_unlocked_file_content_into_the_file_tree_in_v7_in_repo_with_detached_HEAD/#comment-13c1704a5838db78bd4c73ff22cea81a) which I believe does pretty much the same takes only 800ms.  So I will just again blame our Runner... eventually we will figure it all out! ;)

**Comment by yarikoptic** [comment]
taking it back -- will blame primarily just us running over 30 `git config` calls some of which take about 20ms, so at least probably a second is wasted on all of that:
```shell
$> DATALAD_LOG_TIMESTAMP=1 DATALAD_LOG_LEVEL=2 python -m nose -s -v --pdb datalad/support/tests/test_annexrepo.py:test_v7_detached_get 2>&1 | tools/dtime| grep 'git.*config' | nl | tail
    66	   21 2019-07-17 14:18:57,683 [Level 9] Running: ['git', 'config', '--local', '--add', 'annex.security.allowed-url-schemes', 'http https file'] 
    67	    1 2019-07-17 14:18:57,704 [Level 8] Finished running ['git', 'config', '--local', '--add', 'annex.security.allowed-url-schemes', 'http https file'] with status 0 
    68	   16 2019-07-17 14:18:57,705 [Level 9] Running: ['git', 'config', '-z', '-l', '--show-origin'] 
    69	    1 2019-07-17 14:18:57,721 [Level 8] Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
    70	   21 2019-07-17 14:18:57,722 [Level 9] Running: ['git', 'config', '--local', '--add', 'annex.security.allowed-http-addresses', 'all'] 
    71	    1 2019-07-17 14:18:57,743 [Level 8] Finished running ['git', 'config', '--local', '--add', 'annex.security.allowed-http-addresses', 'all'] with status 0 
    72	   19 2019-07-17 14:18:57,744 [Level 9] Running: ['git', 'config', '-z', '-l', '--show-origin'] 
    73	    1 2019-07-17 14:18:57,763 [Level 8] Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
    74	   19 2019-07-17 14:18:57,781 [Level 9] Running: ['git', 'config', '-z', '-l', '--show-origin'] 
    75	    1 2019-07-17 14:18:57,800 [Level 8] Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
```
There is about 20 of `git config -z -l --show-origin` calls for these 2 (original + clone) repositories among them.

**Comment by yarikoptic** [comment]
In Joey we trust! 
But I trust no one (myself included) ;-)

**Comment by kyleam** [comment]
>  But I trust no one (myself included) ;-)

I trust then that you'll start reviewing Git's release notes for obscure bugs to add regression tests for :]

**Comment by yarikoptic** [comment]
> > But I trust no one (myself included) ;-)
> 
> I trust then that you'll start reviewing Git's release notes for obscure bugs to add regression tests for :]

not really... but given amount of time we spent tracing this rudimentary operation (`get`) failure, I thought it would be worthwhile to "set it in test".

**Comment by yarikoptic** [comment]
a bit of discovery with this test is that `annex upgrade` seems to not work to go from direct mode while in detached head.  @joeyh -- expected or a bug?

```
datalad.support.exceptions.CommandError: CommandError: command '['git-annex', 'upgrade']' failed with exitcode 1
Failed to run ['git-annex', 'upgrade'] under '/tmp/datalad_temp_test_v7_detached_getdeem2d52'. Exit code=1. out=upgrade (v5 to v6...) 
failed
 err=git-annex: Somehow no branch is checked out
CallStack (from HasCallStack):
  error, called at ./Upgrade/V5.hs:53:35 in main:Upgrade.V5
git-annex: upgrade: 1 failed
```
meanwhile, I will just skip that test in direct mode

**Comment by joeyh** [comment]
I'm a bit surprised you can get to a detached head state in direct mode,
since git checkout cannot be used there, so it's not surprising if the
upgrade from that state does not work.

-- 
see shy jo

**Comment by yarikoptic** [comment]
> I'm a bit surprised you can get to a detached head state in direct mode,

because we are smart a..ses:

```shell
~/.tmp/datalad_temp_test_v7_detached_get3vT3II > git  '-c' 'core.bare=False' '--work-tree=.' checkout 'HEAD^{}'
HEAD is now at 331a5a8 added                         

~/.tmp/datalad_temp_test_v7_detached_get3vT3II > git branch
* (HEAD detached at 331a5a8)
  annex/direct/master
  git-annex
  master
```

but ok, we will not care about this one. Cheers!

**Pull request merged**
