### PR TITLE
BF: Let `save -a` commit modified submodules too (closes: gh-636)

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by yarikoptic** [comment]
I think symlinks strike back
Osx
```

======================================================================
ERROR: datalad.interface.tests.test_save.test_save
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 666, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/tests/test_save.py", line 56, in test_save
    subds = Dataset(opj(ds.path, 'sub ds')).create(add_to_super=True)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/distribution/dataset.py", line 438, in apply_func
    return f(**kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/distribution/create.py", line 172, in __call__
    annex_init_opts=annex_init_opts)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/distribution/dataset.py", line 297, in create_subdataset
    raise ValueError("path %s outside dataset %s" % (path, self))
ValueError: path /var/folders/90/vkz4dwlx0ss72djd8hywgppc0000gp/T/datalad_temp_clone_url_0oZrqP/sub ds outside dataset <Dataset path=/private/var/folders/90/vkz4dwlx0ss72djd8hywgppc0000gp/T/datalad_temp_clone_url_0oZrqP>
-------------------- >> begin captured logging << --------------------
datalad.cmd: ERROR: Failed to start ['git', 'rev-parse', '--show-toplevel']" under '/var/folders/90/vkz4dwlx0ss72djd8hywgppc0000gp/T/datalad_temp_clone_url_0oZrqP/sub ds/..'": [Errno 2] No such file or directory: '/var/folders/90/vkz4dwlx0ss72djd8hywgppc0000gp/T/datalad_temp_clone_url_0oZrqP/sub ds/..' [subprocess.py:_execute_child:1335]
datalad.cmd: ERROR: Failed to start ['git', 'rev-parse', '--show-toplevel']" under '/var/folders/90/vkz4dwlx0ss72djd8hywgppc0000gp/T/datalad_temp_clone_url_0oZrqP/sub ds'": [Errno 2] No such file or directory: '/var/folders/90/vkz4dwlx0ss72djd8hywgppc0000gp/T/datalad_temp_clone_url_0oZrqP/sub ds' [subprocess.py:_execute_child:1335]
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 504 tests in 586.519s
```

**Comment by hanke** [comment]
Hmm, I have no idea. Is there any records of how to deal with this?

**Comment by hanke** [comment]
I cannot replicate the travis failure with `TMPDIR=/tmp/sym link`. It seems to resolve just fine on my machine...

**Comment by yarikoptic** [comment]
Just to make sure, you did have that directory a symlink to /tmp right?

**Comment by yarikoptic** [comment]
https://github.com/datalad/datalad/pull/743/files#diff-3947667888c8ff9d4bfc6c26f2be70f9R391 (pushed a temp PR -- didn't finish messing with it yet) might help with it... feel free to absorb that piece of code if does

**Comment by hanke** [comment]
FTR: this issue sits deeper than expected. Even in the construction of
testrepos there are inappropriate uses of realpath() IMHO. We should talk
about this.

**Pull request merged**
