### PR TITLE
BF+RF: cleanup unsuccesful install attemp before retrying with .git/

### LINKED ISSUE #488: datalad install (without /.git suffix) is still scary due to seems to be different behavior of two calls
#452 addressed the initial scary messages being printed out while sensing for `.git`.  But now I run into this interesting behavior that specifying url without `.git/` seems to do MORE to the actual clone than if with explicit `.git/` and spitting out more of scary messages:

so  with explicit .git -- it is all nice and dandy:
```shell
$> datalad install -l debug http://datasets.datalad.org/openfmri/.git
2016-05-31 10:34:00,603 [DEBUG  ] Installation attempt started (install.py:290)
2016-05-31 10:34:00,604 [DEBUG  ] Single argument given to install and no dataset found. Assuming the argument identifies a source location. (install.py:350)
2016-05-31 10:34:00,604 [DEBUG  ] Resolved installation target: None (install.py:355)
2016-05-31 10:34:00,604 [DEBUG  ] Neither dataset not target installation path provided. Assuming installation of a remote dataset. Deriving destination path from given source http://datasets.datalad.org/openfmri/.git (install.py:364)
2016-05-31 10:34:00,604 [INFO   ] Installing <Dataset path=/tmp/openfmri> (install.py:375)
1 installed item is available at
<Dataset path=/tmp/openfmri>
```
Removing it and now doing install without explicit `.git/` and without `--debug` just to show the scary msg:
```shell
$> rm -rf openfmri

$> datalad install  http://datasets.datalad.org/openfmri/      
2016-05-31 10:37:13,716 [INFO   ] Installing <Dataset path=/tmp/openfmri> (install.py:375)
2016-05-31 10:37:13,780 [INFO   ] Creating a new git repo at /tmp/openfmri (install.py:654)
2016-05-31 10:37:13,807 [INFO   ] Initializing annex repo at /tmp/openfmri (install.py:658)
2016-05-31 10:37:14,004 [ERROR  ] stderr| Failed to get annex.uuid configuration of repository origin
| Instead, got: "core.repositoryformatversion\n0\NULcore.filemode\ntrue\NULcore.bare\nfalse\NULcore.logallrefupdates\ntrue\NULcore.sharedrepository\n2\NULreceive.denynonfastforwards\ntrue\NULreceive.denycurrentbranch\nupdateInstead\NULsubmodule.ds000001.url\n/srv/datasets.datalad.org/www/openfmri/ds000001\NULsubmodule.ds000002.url\n/srv/datasets.datalad.org/www/openfmri/ds000002\NULsubmodule.ds000003.url\n/srv/datasets.datalad.org/www/openfmri/ds000003\NULsubmodule.ds000005.url\n/srv/datasets.datalad.org/www/openfmri/ds000005\NULsubmodule.ds000006.url\n/srv/datasets.datalad.org/www/openfmri/ds000006\NULsubmodule.ds000007.url\n/srv/datasets.datalad.org/www/openfmri/ds000007\NULsubmodule.ds000008.url\n/srv/datasets.datalad.org/www/openfmri/ds000008\NULsubmodule.ds000009.url\n/srv/datasets.datalad.org/www/openfmri/ds000009\NULsubmodule.ds000011.url\n/srv/datasets.datalad.org/www/openfmri/ds000011\NULsubmodule.ds000017.url\n/srv/datasets.datalad.org/www/openfmri/ds000017\NULsubmodule.ds000030.url\n/srv/datasets.datalad.org/www/openfmri/ds000030\NULsubmodule.ds000031.url\n/srv/datasets.datalad.org/www/openfmri/ds000031\NULsubmodule.ds000051.url\n/srv/datasets.datalad.org/www/openfmri/ds000051\NULsubmodule.ds000052.url\n/srv/datasets.datalad.org/www/openfmri/ds000052\NULsubmodule.ds000053.url\n/srv/datasets.datalad.org/www/openfmri/ds000053\NULsubmodule.ds000101.url\n/srv/datasets.datalad.org/www/openfmri/ds000101\NULsubmodule.ds000102.url\n/srv/datasets.datalad.org/www/openfmri/ds000102\NULsubmodule.ds000105.url\n/srv/datasets.datalad.org/www/openfmri/ds000105\NULsubmodule.ds000107.url\n/srv/datasets.datalad.org/www/openfmri/ds000107\NULsubmodule.ds000108.url\n/srv/datasets.datalad.org/www/openfmri/ds000108\NULsubmodule.ds000109.url\n/srv/datasets.datalad.org/www/openfmri/ds000109\NULsubmodule.ds000110.url\n/srv/datasets.datalad.org/www/openfmri/ds000110\NULsubmodule.ds000113.url\n/srv/datasets.datalad.org/www/openfmri/ds000113\NULsubmodule.ds000113b.url\n/srv/datasets.datalad.org/www/openfmri/ds000113b\NULsubmodule.ds000113d.url\n/srv/datasets.datalad.org/www/openfmri/ds000113d\NULsubmodule.ds000114.url\n/srv/datasets.datalad.org/www/openfmri/ds000114\NULsubmodule.ds000115.url\n/srv/datasets.datalad.org/www/openfmri/ds000115\NULsubmodule.ds000116.url\n/srv/datasets.datalad.org/www/openfmri/ds000116\NULsubmodule.ds000117.url\n/srv/datasets.datalad.org/www/openfmri/ds000117\NULsubmodule.ds000119.url\n/srv/datasets.datalad.org/www/openfmri/ds000119\NULsubmodule.ds000120.url\n/srv/datasets.datalad.org/www/openfmri/ds000120\NULsubmodule.ds000121.url\n/srv/datasets.datalad.org/www/openfmri/ds000121\NULsubmodule.ds000140.url\n/srv/datasets.datalad.org/www/openfmri/ds000140\NULsubmodule.ds000148.url\n/srv/datasets.datalad.org/www/openfmri/ds000148\NULsubmodule.ds000149.url\n/srv/datasets.datalad.org/www/openfmri/ds000149\NULsubmodule.ds000158.url\n/srv/datasets.datalad.org/www/openfmri/ds000158\NULsubmodule.ds000170.url\n/srv/datasets.datalad.org/www/openfmri/ds000170\NULsubmodule.ds000172.url\n/srv/datasets.datalad.org/www/openfmri/ds000172\NULsubmodule.ds000200.url\n/srv/datasets.datalad.org/www/openfmri/ds000200\NULsubmodule.ds000202.url\n/srv/datasets.datalad.org/www/openfmri/ds000202\NUL"
| This is unexpected; please check the network transport! (cmd.py:351)
1 installed item is available at
<Dataset path=/tmp/openfmri>
```
So here is the one with `--debug` so you could see all kinds of interesting stuff happening (e.g. "Creating a new git repo at /tmp/openfmri"):

```shell
$> rm -rf openfmri

$> datalad install -l debug http://datasets.datalad.org/openfmri/    
2016-05-31 10:36:35,229 [DEBUG  ] Installation attempt started (install.py:290)
2016-05-31 10:36:35,229 [DEBUG  ] Single argument given to install and no dataset found. Assuming the argument identifies a source location. (install.py:350)
2016-05-31 10:36:35,229 [DEBUG  ] Resolved installation target: None (install.py:355)
2016-05-31 10:36:35,229 [DEBUG  ] Neither dataset not target installation path provided. Assuming installation of a remote dataset. Deriving destination path from given source http://datasets.datalad.org/openfmri/ (install.py:364)
2016-05-31 10:36:35,229 [INFO   ] Installing <Dataset path=/tmp/openfmri> (install.py:375)
2016-05-31 10:36:35,289 [DEBUG  ] Cannot retrieve from URL: http://datasets.datalad.org/openfmri/ (install.py:385)
2016-05-31 10:36:35,289 [DEBUG  ] Attempt to retrieve from URL: http://datasets.datalad.org/openfmri/.git (install.py:389)
2016-05-31 10:36:35,289 [INFO   ] Creating a new git repo at /tmp/openfmri (install.py:654)
2016-05-31 10:36:35,289 [DEBUG  ] Git clone from http://datasets.datalad.org/openfmri/.git to /tmp/openfmri (gitrepo.py:315)
2016-05-31 10:36:35,318 [DEBUG  ] Git clone completed (gitrepo.py:317)
2016-05-31 10:36:35,318 [DEBUG  ] Using existing Git repository at /tmp/openfmri (gitrepo.py:342)
2016-05-31 10:36:35,319 [DEBUG  ] Using existing Git repository at /tmp/openfmri (gitrepo.py:342)
2016-05-31 10:36:35,319 [INFO   ] Initializing annex repo at /tmp/openfmri (install.py:658)
2016-05-31 10:36:35,319 [DEBUG  ] Using existing Git repository at /tmp/openfmri (gitrepo.py:342)
2016-05-31 10:36:35,320 [DEBUG  ] Annex repository was not yet initialized at /tmp/openfmri. Initializing ... (annexrepo.py:160)
2016-05-31 10:36:35,320 [DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--debug'] (cmd.py:351)
2016-05-31 10:36:35,520 [DEBUG  ] stdout| init  (merging origin/git-annex into git-annex...)
| (recording state in git...)
| 
| 
| 
| ok
| (recording state in git...) (cmd.py:351)
2016-05-31 10:36:35,520 [ERROR  ] stderr| [2016-05-31 10:36:35.362788] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
```

Confirmed both with current master (0.2-48-g4718946) and PR #477 (which did implement "correct" `.git/` directory structure -- yeay)

### PR DESCRIPTION
**Pull request by yarikoptic**
Also refactored code so it is less of a spaghetti conditioning and extensible happen we would like to try more than 2 possible candidate urls

Closes #488

### CODE REVIEW

**Comment by bpoldrack** [comment]
I neither see a test to show the "guessing" works nor to show, that it closes #488 ;)

**Comment by yarikoptic** [comment]
If guessing was tested/working before, it is tested now.... so was it tested?

**Comment by yarikoptic** [comment]
did a quick check @bpoldrack  -- nope, the original authors didn't care to test guessing.  to not hold this one long, I will do a test now.

**Comment by yarikoptic** [comment]
only for you and only today @bpoldrack  -- 4b53a1c71f4be2c2e13e5414dbe3cf114a96d8b6

**Comment by hanke** [comment]
@yarikoptic I am ignoring the comments on "spaghetti code"...

**Comment by yarikoptic** [comment]
Please don't ignore comments ;-)
If you see how my code could be better, i would appreciate comments as well or better a suggested improvement with a PR (as in here), possibly with a similarly descriptive characteristic

**Pull request merged**
