### PR TITLE
OPT: Delay Dataset.repo access until necessary

### PR DESCRIPTION
**Pull request by mih**
Results in substantial speedup for recursive processing, as datasets
without any submodules are rejected prior any Repo instantiation.

For a dataset with 42k subdatasets this means going from

```
datalad subdatasets -r  270.45s user 615.64s system 104% cpu 14:07.22 total
```

to

```
datalad subdatasets -r  5.82s user 0.69s system 101% cpu 6.422 total
```

Fixes gh-5075

### CODE REVIEW

**Comment by yarikoptic** [comment]
Awesome! Thank you @mih! Now the problem is only that I need to figure out what to do with all that free time ;-)

**Comment by mih** [comment]
> Awesome! Thank you @mih! Now the problem is only that I need to figure out what to do with all that free time ;-)

Hehe.... #4411 could take a creative thought :eyes:

**Comment by yarikoptic** [comment]
FWIW, even our tiny benchmarks show the gain
```
-         560±7ms          442±4ms     0.79  api.supers.time_subdatasets_recursive
```
which is great, so we don't miss some pessimisation if any comes

**Review by yarikoptic — APPROVED** [review]
only cursory review of code is done -- but benefit is too big to not to just go forward ;)

**Pull request merged**
