### PR TITLE
BF: fix what's wrong with save_dataset

### PR DESCRIPTION
**Pull request by bpoldrack**
Stumbled upon a bug in `save_dataset`, which led to swallowing all exceptions raised by git commit.

Does this ring a bell in relation to other issues, @datalad/developers ?

PR is intended to show the issue and find the implications. Need to fix this outside of PR #1277 , since otherwise there are too many different things at once to solve ...

### CODE REVIEW

**Comment by mih** [comment]
Why not merge? Should be merged ASAP.

**Comment by bpoldrack** [comment]
Not sure yet, whether an actual fix will be done herein. Otherwise: Yes, a fix should be merged ASAP.

**Comment by mih** [comment]
Hmm, in my eyes this IS the fix. The actual improvement needed is to remove this entire try/except construct and have `commit()` do all this.

**Comment by mih** [comment]
From what I can see in the now failing tests (minus the direct mode stuff), would all go away when commit would not log errors, that would not needed to be swallowed, and the error checking would go inside. An immediate merge would break master, but only in the sense that it would make the breakage known, not actually introducing any.

**Comment by bpoldrack** [comment]
> would break master, but only in the sense that it would make the breakage known, not actually introducing any.

Yes.

> would all go away when commit would not log errors, that would not needed to be swallowed, and the error checking would go inside

Not entirely, sadly. This is why I wanted to separate this PR out to see what's actually related to this bug and what might be an incomplete or buggy implementation of the changes to commit().

**Comment by mih** [comment]
We need a bot to assign this tag based on content automatically...

**Comment by bpoldrack** [comment]
:-)

To be a little bit more clear:
There is a second bug in the condition for the second case - it's not (only?) "no changes added ..", but (also?) "nothing added ..."
If I correct this, `save_dataset` doesn't only raise the correct exceptions, it then also swallows the intended ones. But this is leading to the next issue, where `datalad.distribution.tests.test_install.test_failed_install_multiple` for example, results in a lot of failures, trying to explicitly commit unstaged changes ("not known to git").

**Comment by bpoldrack** [comment]
But may be this "correction" is indeed incorrect. I need to figure this out in detail ...

**Comment by bpoldrack** [comment]
Update: Follow up failures seem to come from within `install` which tries to save `installed_items`, that are not staged yet.

**Comment by bpoldrack** [comment]
Okay, decided to catch it from `_save_installed_datasets`, since this is the traceback:
```
distribution/install.py  Install.__call__
distribution/install.py _handle_and_return_installed_items
distribution/install.py _save_installed_datasets
interface/save.py Save.__call__
interface/utils.py save_dataset_hierarchy
interface/utils.py save_dataset
=> exception due to git commit failure ("did not match any file(s) known to git")
```

While ignoring this apparently is okay for install, it certainly isn't in general for save, I think. See next commit.

**Comment by bpoldrack** [comment]
Please note, that changes to `save_dataset` will go into `GitRepo.commit()` via PR #1277 . Nevertheless, this one can go into master. The other one isn't ready yet.

**Comment by bpoldrack** [comment]
%$§"(/"$% !

At a first glance - no idea why that direct mode test fails on OS X, while it passes in all other builds. git versions seem to be fine. Need to dive into it on that box.

**Pull request merged**
