### PR TITLE
ENH(BM)+OPT: benchmarks to measure overhead from our Runner(s), no sleeping in .poll loop

### PR DESCRIPTION
**Pull request by yarikoptic**
Those track_overhead report percents over the duration via a simple
os.system call where all outputs go to /dev/null.  Here is a result from running
on my laptop:

    $> DATALAD_LOG_LEVEL=2 asv run -j 4 -b core.runner
    · Creating environments
    · Discovering benchmarks
    ·· Uninstalling from virtualenv-py2.7
    ·· Installing 6f9ac93e <master> into virtualenv-py2.7.
    · Running 28 total benchmarks (2 commits * 2 environments * 7 benchmarks)
    [  0.00%] · For DataLad commit 6f9ac93e <master>:
    [  0.00%] ·· Building for virtualenv-py2.7, virtualenv-py3.7..
    [  0.00%] ·· Benchmarking virtualenv-py2.7
    [  1.79%] ··· Running (core.runner.time_echo--)..
    [ 14.29%] ··· core.runner.time_echo                                                           2.26±0.1ms
    [ 16.07%] ··· core.runner.time_echo_gitrunner                                                2.65±0.08ms
    [ 17.86%] ··· core.runner.track_overhead_100ms                                                      4.28
    [ 19.64%] ··· core.runner.track_overhead_echo                                                       98.6
    [ 21.43%] ··· core.runner.track_overhead_heavyout                                                    2.8
    [ 23.21%] ··· core.runner.track_overhead_heavyout_online_process                                  146.17
    [ 25.00%] ··· core.runner.track_overhead_heavyout_online_through                                   39.01
    [ 25.00%] ··· asv: forkserver:
    [ 25.00%] ··· [Level 5] Exiting

    [ 25.00%] ·· Benchmarking virtualenv-py3.7
    [ 26.79%] ··· Running (core.runner.time_echo--)..
    [ 39.29%] ··· core.runner.time_echo                                                           1.92±0.1ms
    [ 41.07%] ··· core.runner.time_echo_gitrunner                                                2.17±0.05ms
    [ 42.86%] ··· core.runner.track_overhead_100ms                                                      3.38
    [ 44.64%] ··· core.runner.track_overhead_echo                                                      83.94
    [ 46.43%] ··· core.runner.track_overhead_heavyout                                                   3.25
    [ 48.21%] ··· core.runner.track_overhead_heavyout_online_process                                  210.61
    [ 50.00%] ··· core.runner.track_overhead_heavyout_online_through                                   21.88
    [ 50.00%] ··· asv: forkserver:
    [ 50.00%] ··· [Level 5] Exiting

    [ 50.00%] · For DataLad commit 39e8e8b8 <0.11.x>:
    [ 50.00%] ·· Building for virtualenv-py2.7, virtualenv-py3.7....
    [ 50.00%] ·· Benchmarking virtualenv-py2.7
    [ 51.79%] ··· Running (core.runner.time_echo--)..
    [ 64.29%] ··· core.runner.time_echo                                                          2.17±0.04ms
    [ 66.07%] ··· core.runner.time_echo_gitrunner                                                 2.84±0.5ms
    [ 67.86%] ··· core.runner.track_overhead_100ms                                                       4.1
    [ 69.64%] ··· core.runner.track_overhead_echo                                                      89.11
    [ 71.43%] ··· core.runner.track_overhead_heavyout                                                   1.48
    [ 73.21%] ··· core.runner.track_overhead_heavyout_online_process                                  149.77
    [ 75.00%] ··· core.runner.track_overhead_heavyout_online_through                                    41.6
    [ 75.00%] ··· asv: forkserver:
    [ 75.00%] ··· [Level 5] Exiting

    [ 75.00%] ·· Benchmarking virtualenv-py3.7
    [ 76.79%] ··· Running (core.runner.time_echo--)..
    [ 89.29%] ··· core.runner.time_echo                                                          1.88±0.07ms
    [ 91.07%] ··· core.runner.time_echo_gitrunner                                                2.21±0.03ms
    [ 92.86%] ··· core.runner.track_overhead_100ms                                                      3.06
    [ 94.64%] ··· core.runner.track_overhead_echo                                                      80.28
    [ 96.43%] ··· core.runner.track_overhead_heavyout                                                   4.02
    [ 98.21%] ··· core.runner.track_overhead_heavyout_online_process                                  234.83
    [100.00%] ··· core.runner.track_overhead_heavyout_online_through                                   21.47
    [100.00%] ··· asv: forkserver:
    [100.00%] ··· [Level 5] Exiting

So the interesting one is consistent ~50% extra overhead for python 3.7 over python 2.7
for cases where we process output line by line. Overall our "online" handling is adding
over 100% overhead. So with some "smart" nonblocking/async we might possibly speed things
up twice or more (if I got it right ;-))

### CODE REVIEW

**Comment by mih** [comment]
Jeez, that's a lot of waste...

**Comment by yarikoptic** [comment]
I think that my benchmarking was not "kosher"  - I was just trying to run the underlying script for fixed amount of time instead of fixed amount of output.  So in 170e52a4c4960a3d39c1f6467d36998b014aff72 running it to output fixed (1000) number of lines.  Increasing the number increases overhead even more (probably all the buffering etc effects?) but decided to leave at that. python2 starts to loose.  Not sure yet where differences between 0.11.x and master come out:

        $> DATALAD_LOG_LEVEL=2 asv run -j 4 -b core.runner.track_overhead
        · Creating environments
        · Discovering benchmarks
        ·· Uninstalling from virtualenv-py2.7..
        ·· Installing 6f9ac93e <master> into virtualenv-py2.7.
        · Running 20 total benchmarks (2 commits * 2 environments * 5 benchmarks)
        [  0.00%] · For DataLad commit 6f9ac93e <master>:
        [  0.00%] ·· Building for virtualenv-py2.7, virtualenv-py3.7..
        [  0.00%] ·· Benchmarking virtualenv-py2.7
        [  5.00%] ··· core.runner.track_overhead_100ms                                                      2.17
        [ 10.00%] ··· core.runner.track_overhead_echo                                                      85.01
        [ 15.00%] ··· core.runner.track_overhead_heavyout                                                   6.61
        [ 20.00%] ··· core.runner.track_overhead_heavyout_online_process                                 6828.21
        [ 25.00%] ··· core.runner.track_overhead_heavyout_online_through                                  640.86
        [ 25.00%] ··· asv: forkserver:
        [ 25.00%] ··· [Level 5] Exiting
    
        [ 25.00%] ·· Benchmarking virtualenv-py3.7
        [ 30.00%] ··· core.runner.track_overhead_100ms                                                       3.2
        [ 35.00%] ··· core.runner.track_overhead_echo                                                      61.65
        [ 40.00%] ··· core.runner.track_overhead_heavyout                                                  -0.33
        [ 45.00%] ··· core.runner.track_overhead_heavyout_online_process                                 4722.37
        [ 50.00%] ··· core.runner.track_overhead_heavyout_online_through                                  146.09
        [ 50.00%] ··· asv: forkserver:
        [ 50.00%] ··· [Level 5] Exiting
    
        [ 50.00%] · For DataLad commit 39e8e8b8 <0.11.x>:
        [ 50.00%] ·· Building for virtualenv-py2.7, virtualenv-py3.7.....
        [ 50.00%] ·· Benchmarking virtualenv-py2.7
        [ 55.00%] ··· core.runner.track_overhead_100ms                                                      4.73
        [ 60.00%] ··· core.runner.track_overhead_echo                                                     118.64
        [ 65.00%] ··· core.runner.track_overhead_heavyout                                                  10.74
        [ 70.00%] ··· core.runner.track_overhead_heavyout_online_process                                 6611.27
        [ 75.00%] ··· core.runner.track_overhead_heavyout_online_through                                  662.28
        [ 75.00%] ··· asv: forkserver:
        [ 75.00%] ··· [Level 5] Exiting
    
        [ 75.00%] ·· Benchmarking virtualenv-py3.7
        [ 80.00%] ··· core.runner.track_overhead_100ms                                                      3.91
        [ 85.00%] ··· core.runner.track_overhead_echo                                                      38.07
        [ 90.00%] ··· core.runner.track_overhead_heavyout                                                  10.79
        [ 95.00%] ··· core.runner.track_overhead_heavyout_online_process                                 5334.55
        [100.00%] ··· core.runner.track_overhead_heavyout_online_through                                  158.65
        [100.00%] ··· asv: forkserver:
        [100.00%] ··· [Level 5] Exiting

and here is how it looks when increasing # of lines for the _online_process:
- 1000 - 4561.3
- 3000 - 15789.91
- 5000 - 25372.97
- 10000 - 36555.48

but note about I was silly to run with DATALAD_LOG_LEVEL=2  . Running without it improves indicator a bit (3759.69 instead of 3863.16) 

Anyways -- I guess I will keep this one.  Smells like we could improve more than twice on such cases ;)

**Comment by yarikoptic** [comment]
gy gy -- here is the profile for that benchmark:
profile

around 78% of sleep is in line with my observation for python process being only up to 30% utilization ;-) and ha ha -- sleeping 0.001 sec on each poll for 1000 loops would add that 1 sec ;)  Since we are not having any threads yet, there is nothing to surrender to.  So I will just kick away that sleep altogether. running silly `sleep 2` didn't keep out process at any notable cpu utilization so probably we would be ok.  That drops the overhead here to only ~200%  from ~3000% .

**Comment by yarikoptic** [comment]
and here is how profile there looks after removing that damn sleep:
profile
Not sure how much we are gaining in real case scenarios, but I guess in some cases of --debug runs of annex with lots of output etc might actually getting some benefit now.  Now if only to remove the "twice" effect somehow -- after all we do have multiple cores these days etc ;)  

FTR - overhead is still growing if I increase number of lines to be printed, but it is all largely due to  readline.

**Comment by yarikoptic** [comment]
per @kyleam 's strong recommendation I will strip away OPT commit and submit it separately against 0.11.x branch

**Comment by yarikoptic** [comment]
So this one is ready for merge.  Next step would be to benchmark `BatchedCommand` which is now conveniently a thing on its own thanks @mih and @kyleam so should be easier to benchmark

**Pull request merged**
