### PR TITLE
Adjust for recent git-annex reporting change on non-existent files

### PR DESCRIPTION
**Pull request by adswa**
This is a fix for one of the failing tests reported in #6492. 

A recent git-annex release changed the result of running 'git annex
find' on non-existing paths from an error to exit-code 0 with a more
informative hint:
```
$ git annex find --copies 0 --json --json-error-messages qwdqwd csdc
error: pathspec 'qwdqwd' did not match any file(s) known to git
error: pathspec 'csdc' did not match any file(s) known to git
Did you forget to 'git add'?
```
Previously, in order to determine whether non-existent paths were
queried, datalad relied on catching and parsing the command error.
```
CommandError: 'git -c diff.ignoreSubmodules=none annex find --copies 0
--json --json-error-messages -c annex.dotfiles=true -- nothere' failed
with exitcode 1
[info keys: stdout_json] [err: 'git-annex: nothere not found
find: 1 failed']
```
Because such a CommandError is not thrown anymore, this change parses
the stderror of the output depending on the git-annex version, looking
for files reported as not existing in a similar way to how the command
error is parsed, and assembled an output dictionary to report those
files as missing.

Happy to get feedback on this approach. I feel like it isn't particularly graceful.

## Changelog:

- Corresponding to the change in git-annex that a query of non-existent files will not result in a command error anymore, ``call_annex_records`` will parse the `stderr` of recent git-annex versions to identify operations on non-existing files.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thank you @adswa!  yet to review but meanwhile filed [an issue](https://git-annex.branchable.com/bugs/no_longer_non-0_exit_for___34__find_..._nonexisting__34__/?updated) for @joeyh since I believe that there ideally might be fixes on git-annex side.

**Comment by joeyh** [comment]
The nonzero exit status is fixed in git-annex, but you will still need to look for new error messages when it does exit nonzero.

I'm a bit surprised that datalad is parsing error messages though. It would be better to have an API for this. Error messages can change at any time, or new ones be added that cover additional cases (part of what happened here really), or due to translation. Anywhere that datalad parses error messages feels to me like technical debt that perhaps you would want to address.

Indeed, those messages from git-ls-files that you're making it parse are in fact localized..

I've opened this to discuss such an API: https://git-annex.brachable.com/todo/api_for_telling_when_nonexistant_or_non_git_files_passed/

Also, switching on the git-annex version is not quite right, the new output happens when annex.skipunknown is set to false, which can be the case with older versions of git-annex as well. Only the default value of that config changed in the recent git-annex version.

**Comment by adswa** [comment]
Thanks for fixing the error code!

> Also, switching on the git-annex version is not quite right, the new output happens when annex.skipunknown is set to false, which can be the case with older versions of git-annex as well. Only the default value of that config changed in the recent git-annex version.

Thanks much for this, I will adjust this conditional.

> I'm a bit surprised that datalad is parsing error messages though. It would be better to have an API for this. Error messages can change at any time, or new ones be added that cover additional cases (part of what happened here really), or due to translation. Anywhere that datalad parses error messages feels to me like technical debt that perhaps you would want to address.
Indeed, those messages from git-ls-files that you're making it parse are in fact localized..
I've opened this to discuss such an API: https://git-annex.brachable.com/todo/api_for_telling_when_nonexistant_or_non_git_files_passed/

Thanks a lot! I think we protect ourselves against localizations with
https://github.com/datalad/datalad/blob/c87cf8265a16fa02048b1ba78f564d68c6f07d53/datalad/runner/gitrunner.py#L107-L113 because there are a few places where we need to do it, but it would be great to not have to parse error messages anymore. Thanks for creating the issue, much appreciated!

**Comment by bpoldrack** [comment]
@joeyh 
> I'm a bit surprised that datalad is parsing error messages though. It would be better to have an API for this. Error messages can change at any time, or new ones be added that cover additional cases (part of what happened here really), or due to translation. Anywhere that datalad parses error messages feels to me like technical debt that perhaps you would want to address.

Agreed. To put that into context: That piece of code is part of a generic function calling annex with `--json` and `--json-error-messages` and returning respective dictionaries in the python context. That function is not specific to a particular git-annex command. And what it does with that parsing is pretending that git-annex reported those errors as JSON for the cases where annex doesn't (yet). So, this parsing leads to the creation of something like `{"command": "find", "file": <whatever path was discovered by parsing>, "note": "not found", "success": False}` in order to have higher-level functions deal with annex' output uniformly. If annex could deliver something like that directly, that would, of course, be way better. Ideally, there'd be some indication of the problem that isn't meant to be a message to the user and not (so easily) subject to change - pretty much something that's akin to an exception name. That's because there are possible errors that we can deal with from within datalad if we can "understand" the problem - not everything needs to be passed onto the user.

**Comment by bpoldrack** [comment]
Closing in favor of #6550

**Comment by yarikoptic** [comment]
FTR: "error" ID is coming to git-annex for "not found" https://git-annex.branchable.com/todo/api_for_telling_when_nonexistant_or_non_git_files_passed/?updated#comment-c45982817c12f74bd1bf8d85f68cc92d

**Pull request closed without merging**
