### PR TITLE
RF: report relative paths by default (configurable, 'datalad.runtime.report-pathstyle')

### PR DESCRIPTION
**Pull request by yarikoptic**
I do appreciate the fact that we can have wide terminals now, but working with datalad deep within some hierarchy floods the screen with full paths, causing unpleasant wraps etc.  So I took a first attempt at trying to report relpaths by default to seek your feedback.  E.g. now it would report
```shell
(git-annex)hopa:~/datalad/openfmri/ds000001[master]sub-01
$> datalad get anat/
get(ok): anat/sub-01_inplaneT2.nii.gz (file) [from web...]
get(ok): anat/sub-01_T1w.nii.gz (file) [from web...]
get(ok): anat (directory)
```
instead of 
```shell
$> datalad get anat/                                                                                         
get(ok): /home/yoh/datalad/openfmri/ds000001/sub-01/anat/sub-01_inplaneT2.nii.gz (file) [from web...]
get(ok): /home/yoh/datalad/openfmri/ds000001/sub-01/anat/sub-01_T1w.nii.gz (file) [from web...]
get(ok): /home/yoh/datalad/openfmri/ds000001/sub-01/anat (directory)
```
but I've not yet taken any precautions against cases where I run datalad commands outside providing full paths and thus leading to horrendous
```shell
hopa:/tmp
$> datalad get /home/yoh/datalad/openfmri/ds000001/sub-01/anat
get(ok): ../home/yoh/datalad/openfmri/ds000001/sub-01/anat/sub-01_inplaneT2.nii.gz (file) [from web...]
get(ok): ../home/yoh/datalad/openfmri/ds000001/sub-01/anat/sub-01_T1w.nii.gz (file) [from web...]
get(ok): ../home/yoh/datalad/openfmri/ds000001/sub-01/anat (directory)
```
This is just a first trial to bring discussion back

IMHO ultimately/ideally it should report path inline with the specification in the original request, but for many commands it seems that `orig_request` path is not provided for "subpaths" -- could we retain the last one seen and act from it? I don't think so since those seems to come out of order (here is with the printout of `res` structures):
```shell
$> datalad get /home/yoh/datalad/openfmri/ds000001/sub-0{1,2}/anat
{'status': '', 'orig_request': '/home/yoh/datalad/openfmri/ds000001/sub-01/anat', 'parentds': '/home/yoh/datalad/openfmri/ds000001', 'action': 'get', 'path': '/home/yoh/datalad/openfmri/ds000001/sub-01/anat', 'logger': <logging.Logger object at 0x7f7c42750f50>, 'type': 'directory', 'raw_input': True}
{'status': '', 'orig_request': '/home/yoh/datalad/openfmri/ds000001/sub-02/anat', 'parentds': '/home/yoh/datalad/openfmri/ds000001', 'action': 'get', 'path': '/home/yoh/datalad/openfmri/ds000001/sub-02/anat', 'logger': <logging.Logger object at 0x7f7c42750f50>, 'type': 'directory', 'raw_input': True}
{'status': 'notneeded', 'action': 'get', 'path': u'/home/yoh/datalad/openfmri/ds000001/sub-01/anat', 'logger': <logging.Logger object at 0x7f7c427502d0>, 'type': 'directory', 'message': ('nothing to get from %s', u'/home/yoh/datalad/openfmri/ds000001/sub-01/anat')}
get(notneeded): ../home/yoh/datalad/openfmri/ds000001/sub-01/anat (directory) [nothing to get from /home/yoh/datalad/openfmri/ds000001/sub-01/anat]
{'status': 'notneeded', 'action': 'get', 'path': u'/home/yoh/datalad/openfmri/ds000001/sub-02/anat', 'logger': <logging.Logger object at 0x7f7c427502d0>, 'type': 'directory', 'message': ('nothing to get from %s', u'/home/yoh/datalad/openfmri/ds000001/sub-02/anat')}
get(notneeded): ../home/yoh/datalad/openfmri/ds000001/sub-02/anat (directory) [nothing to get from /home/yoh/datalad/openfmri/ds000001/sub-02/anat]
```
but may be we could retain full list of orig_request and deduce the common base? e.g. if any is full path -- go with full paths; otherwise relative, unless the path is not under any of the ones within `orig_request`ed?

just food for thought (like we do not have enough ;-) )

### CODE REVIEW

**Comment by mih** [comment]
Cannot look i to it now, but we did report relative paths whenever there is a reference dataset, and absolute whenever there is none.

**Comment by yarikoptic** [comment]
FWIW that is correct -- we do report relative to the top of the reference dataset paths whenever it is provided.  My "problem" is that otherwise we always report full paths even whenever specifying relative paths as input to the commands

**Comment by yarikoptic** [comment]
FWIW, also in `search` `{path}` is full path.

**Comment by mih** [comment]
Closing due to inactivity.

**Pull request closed without merging**
