### PR TITLE
ENH/RF: Interface-s - add *  to explicitly separate posargs from kwargs

### PR DESCRIPTION
**Pull request by yarikoptic**
- Sits on top of tiny https://github.com/datalad/datalad/pull/6175 which I thought would be relevant but apparently not really.  Can rebase
- inspired by #5517 when I thought to RF `cmd` into `--cmd` and thus possibly opening the way for ppl to shoot themselves in the foot whenever later I would decide to add `path` pos arg (in CLI etc)
- adding explicit `*` separation would mimic how CLI is specified - you can't specify `--options` as positional arguments.
- may be would give another reason to harmonize interfaces of older interfaces (moved from plugins) -- in most of the cases it is just move of `dataset` from the 0th arg into its due `kwarg` position.
- [x] make sure tests pass
- [x] decide to either issue a DeprecationWarning if an Interface without `*` is encountered: decided not to bother. Now we have some test which sould fail in such case of having some specargs but no kwonly args
- [x] decide what to do if anything about those `TODO*` marked interfaces
  - [x] RFed signature of `clone` to place optional last (REMAINER) posarg to be a kwarg right before `*`
  - [x] RFed signature of `addurls` to have `dataset` as a kwarg as all other interfaces do!
  - [x] RFed other elderlies: add_readme, export_to_figshare, export_archive to also have `dataset` as a kwarg. Rationale: if they are used, most likely via CLI anyways. There it should not matter. Uniformity is good to have
  - [-] Left alone `extract_metadata`  ....
- [x] pay attention to change in the test for `save` where we did allow `message` to be used as posarg (I think - bad idea). But may be do allow for posarg use?  decided against -- no reason to make it different from `git commit -m ...`.
- [ ] (after there is an agreement) Add perspective CHANGELOG.md record to describe this change and breaking changes (if any left).

### CODE REVIEW

**Comment by yarikoptic** [comment]
ok, besides some stuck (installing smth) mac on appveyor CI is green which is great and I would welcome your feedback @datalad/developers to proceed, e.g. to either RF those old plugins into the uniformity.

**Comment by bpoldrack** [comment]
Overall sounds sane to me, but I don't feel confident I get all implications of our layers of dark magic around those methods.

**Comment by bpoldrack** [comment]
> pay attention to change in the test for save where we did allow message to be used as posarg (I think - bad idea). But may be do allow for posarg use?

I lean towards agreement - not a good idea.

**Comment by yarikoptic** [comment]
<details>
<summary>a little code snippet to demonstrate differences introduced by using `*,` in the function signature and return results for getargspec etc </summary> 

```python
#import warnings
#warnings.filterwarnings()
def f0():
    pass


def f1(a1, kw1=None, kw0=1):
    pass

def f1_star(a1, *, kw1=None, kw0=1):
    pass

def f1_starargs(a1, *args, kw1=None, kw0=1):
    pass

import inspect

def pprint(s):
    print("  " + str(s))

for f in (f0, f1, f1_star, f1_starargs ):
    print(f)
    try:
        pprint(inspect.getargspec(f))
    except ValueError as e:
        pprint(str(e))
    pprint(inspect.getfullargspec(f))
    s = inspect.signature(f)
    pprint(s)
    pprint(s.parameters)
    print()

```
</details>

<details>
<summary>output from running the script</summary> 

```shell
<function f0 at 0x7fa6d62b7040>
  ArgSpec(args=[], varargs=None, keywords=None, defaults=None)
  FullArgSpec(args=[], varargs=None, varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
  ()
  OrderedDict()

<function f1 at 0x7fa6d603c0d0>
  ArgSpec(args=['a1', 'kw1', 'kw0'], varargs=None, keywords=None, defaults=(None, 1))
  FullArgSpec(args=['a1', 'kw1', 'kw0'], varargs=None, varkw=None, defaults=(None, 1), kwonlyargs=[], kwonlydefaults=None, annotations={})
  (a1, kw1=None, kw0=1)
  OrderedDict([('a1', <Parameter "a1">), ('kw1', <Parameter "kw1=None">), ('kw0', <Parameter "kw0=1">)])

<function f1_star at 0x7fa6d603c160>
  Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
  FullArgSpec(args=['a1'], varargs=None, varkw=None, defaults=None, kwonlyargs=['kw1', 'kw0'], kwonlydefaults={'kw1': None, 'kw0': 1}, annotations={})
  (a1, *, kw1=None, kw0=1)
  OrderedDict([('a1', <Parameter "a1">), ('kw1', <Parameter "kw1=None">), ('kw0', <Parameter "kw0=1">)])

<function f1_starargs at 0x7fa6d603c1f0>
  Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
  FullArgSpec(args=['a1'], varargs='args', varkw=None, defaults=None, kwonlyargs=['kw1', 'kw0'], kwonlydefaults={'kw1': None, 'kw0': 1}, annotations={})
  (a1, *args, kw1=None, kw0=1)
  OrderedDict([('a1', <Parameter "a1">), ('args', <Parameter "*args">), ('kw1', <Parameter "kw1=None">), ('kw0', <Parameter "kw0=1">)])

```
</details>

**Comment by mih** [comment]
Note to self: Chatting with @yarikoptic convinced me that this is a good thing. Not yet 100% clear where to use immediately, but the coming design doc will offer a path towards figuring this out.

**Comment by yarikoptic** [comment]
pushed all the changes outlined in the description -- let's see if there are any ramifications in CI ;)

**Comment by yarikoptic** [comment]
interesting
<details>
<summary>appveyor ubuntu run got stuck. Let's see what would happen on the next push</summary> 

```shell
...
datalad.distributed.tests.test_ria_basics.test_binary_data('datalad-test',) ... channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
.: store(+) [ora]
.: here(+) [git]
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
ok
datalad.distributed.tests.test_ria_basics.test_binary_data(None,) ... .: store(+) [ora]
.: here(+) [git]
ok
datalad.distributed.tests.test_ria_basics.test_sanitize_key ... ok
datalad.distributed.tests.test_ria_basics.test_initremote_basic_fileurl ... ok
datalad.distributed.tests.test_ria_basics.test_initremote_basic_httpsurl ... /home/appveyor/dlvenv/lib/python3.8/site-packages/urllib3/connection.py:460: SubjectAltNameWarning: Certificate for localhost has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)
  warnings.warn(
ok
datalad.distributed.tests.test_ria_basics.test_initremote_basic_httpurl ... ok
datalad.distributed.tests.test_ria_basics.test_push_url ... .: store(+) [ora]
.: here(+) [git]
ok
datalad.distributed.tests.test_ria_basics.test_url_keys ... 
```
</details>

benchmarks rightfully errorred out since I haven't adjusted for the change in `addurls` -- will do now.

**Comment by yarikoptic** [comment]
eh, no free lunch!  apparently there is a notable penalty on runtime from having `*` in the signature of the function:

```
In [3]: %timeit ut.boring_nostar(1)
85.6 ns ± 0.777 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: %timeit ut.boring_nostar(1)
89.3 ns ± 1.73 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [5]: %timeit ut.boring_star(1)
107 ns ± 3.6 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [6]: %timeit ut.boring_star(1)
112 ns ± 7.61 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

<details>
<summary>source code for those functions</summary> 

```shell
def boring_nostar(a1, a2='something', kw1=None, kw2=2):
    pass

def boring_star(a1, a2='something', *, kw1=None, kw2=2):
    pass
```
</details>

so we are loosing about 20ns, which from original 80 is 25% !  I bet our interfaces have lots of more fun things to do and should offset this penalty but since appveyor testing on mac says otherwise -- I now wonder what to do.  Trying to add `lru_cache`'ing now

**Comment by yarikoptic** [comment]
heh, green.  not sure if caching helped or just that on previous runs CI was busier or ... I guess worth a review first @datalad/developers before proceeding further

**Comment by yarikoptic** [comment]
ping @mih et al @datalad/developers

**Comment by christian-monch** [comment]
@mih looks good to me.

**Pull request merged**
