### PR TITLE
ASV based  benchmarking of DataLad

### PR DESCRIPTION
**Pull request by yarikoptic**
Current state was published to gh-pages: http://datalad.github.io/datalad/
Left smaug running them for ALL commits... not sure if a good idea since currently we have 100 commits nicely sampling previous history and can easily rerun more new benchmarks for them using "EXISTING" argument to "asv run"

TODOs (if we decide to use ASV)
- [x] add .asv submodule with the results (for now just local + smaug clones)
- [ ] automate running benchmarks as the part of the buildbot process (on master, not on PRs to not pull in junk) and pushing results
- [ ] point docs to gh-pages
???

Future TODOs
- Create more benchmarks for basic operations (install, add, get, ...)
- Create few environments with different git annexes. Current just whatever annex is installed on my laptop and smaug. But for these sample benchmarks doesn't matter anyways

### CODE REVIEW

**Comment by mih** [comment]
Very cool, very useful. Feel free to merge when tests pass.

I don't get what you mean by "add .asv submodule with the results" -- I guess I know too little about what ASV can do.

**Comment by yarikoptic** [comment]
Re "add .asv submodule with the results"  -- it is there now ;) https://github.com/datalad/.asv

**Comment by mih** [comment]
Failing test is the Git version issue that I reported in #1169 -- if #1169 is merged this test is relaxed.

**Comment by bpoldrack** [comment]
Nice!

From looking at the results, I wonder whether there is a way to include not just `cpu` but the number of cores/CPUs ...

**Comment by yarikoptic** [comment]
On January 18, 2017 8:20:20 AM EST, Benjamin Poldrack <notifications@github.com> wrote:
>Nice!
>
>From looking at the results, I wonder whether there is a way to include
>not just `cpu` but the number of cores/CPUs ... 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/pull/1189#issuecomment-273473221

Do you mean into description of the machine?

**Comment by bpoldrack** [comment]
Yes!

**Comment by yarikoptic** [comment]
ok -- let me merge it as is for now so you could play with it and add new exciting benchmarks. Then we will put it into automation

**Pull request merged**
