### PR TITLE
BF: Fix add-archive-contents try-finally statement by defining variable earlier

### PR DESCRIPTION
**Pull request by adswa**
Committed by Adina but taken from the patch provided by @mih in https://github.com/datalad/datalad/issues/7113

### CODE REVIEW

**Comment by yarikoptic** [comment]
Change log got lost

**Comment by yarikoptic** [comment]
We know it is good, meeting, thank you @adswa

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.9.4`](https://github.com/datalad/datalad/releases/tag/0.9.4)

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.9`](https://github.com/datalad/datalad/releases/tag/0.17.9)

**Pull request merged**
