### PR TITLE
RF: move AnnexRepo.WEB_UUID constant into consts.WEB_SPECIAL_REMOTE_UUID

### PR DESCRIPTION
**Pull request by yarikoptic**
And adjust some code pieces to make use of it instead of a hardcoded value.

One questionable change was the actual move in the first commit.  But since other UUIDs are defined there I thought it was reasonable.

### CODE REVIEW

**Comment by kyleam** [comment]
> One questionable change was the actual move in the first commit. But since other UUIDs are defined there I thought it was reasonable.

I'm okay with the move, but I think you should keep around the AnnexRepo attribute for compatibility (not just from a nice-to-do standpoint, but also to address the failing -container test).

**Comment by yarikoptic** [comment]
ok, done

**Comment by yarikoptic** [comment]
oh, let's wait for green, I will reword and merge locally and push

**Comment by kyleam** [comment]
> oh, let's wait for green, I will reword and merge locally and push

Sounds good, thanks.  Would you mind squashing in my fixup to your first commit while you're at it?

**Comment by yarikoptic** [comment]
will do -- thanks!

**Comment by yarikoptic** [comment]
appveyor will be good I bet, rebased/reworded/merged/pushed as 8d6756d5103991442628dfe7af01f7cacd0118ef, closing here

**Pull request closed without merging**
