### PR TITLE
TST: Helper to generate a mockup DS tree resembling studyforrest.org

### PR DESCRIPTION
**Pull request by mih**
This should help playing with this monster in the context of #923

The first comment there requests a URL for `datalad install -r ...`. This is to better evaluate what that would mean without any significant file load.

Below is a demo of the result (public facing datasets only). Note that 3 layers of datasets are sufficient, but no more than 2 layers are actually installed in each case. Going full recursive install should yield 4 layers for the present setup (actual studyforrest.org should be no more then 5 layers ATM). The vast majority of all subdatasets would be copies.

Complete publication would be solved by publishing datasets in the first layer only, and all versions of all files in all revisions of these.

The function produces a cartoon representation of the project evolution too -- simulating that different versions of some derived datasets were input into different analyses.

````
public (git)-[master] % datalad ls -r
.                                   [annex]  master  - 2017-02-15/13:40:37  X
aggregate                           [annex]  master  - 2017-02-15/13:40:38  OK
aggregate/src/aligned               [annex]  master  - 2017-02-15/13:40:35  OK
aggregate/src/aligned/src/phase1    not installed
aggregate/src/aligned/src/phase2    not installed
aggregate/src/aligned/src/tnt       not installed
aligned                             [annex]  master  - 2017-02-15/13:40:35  OK
aligned/src/phase1                  [annex]  master  - 2017-02-15/13:39:55  OK
aligned/src/phase2                  [annex]  master  - 2017-02-15/13:40:06  OK
aligned/src/phase2/src/dicoms       not installed
aligned/src/phase2/src/labet        not installed
aligned/src/tnt                     [annex]  master  - 2017-02-15/13:39:59  OK
aligned/src/tnt/src/phase1          not installed
aligned/src/tnt/src/structural      not installed
analysis1                           [annex]  master  - 2017-02-15/13:40:18  OK
analysis1/src/aligned               [annex]  master  - 2017-02-15/13:40:09  OK
analysis1/src/aligned/src/phase1    not installed
analysis1/src/aligned/src/phase2    not installed
analysis1/src/aligned/src/tnt       not installed
analysis1/src/annot                 [annex]  master  - 2017-02-15/13:40:12  OK
analysis1/src/annot/src/media       not installed
analysis1/src/tnt                   [annex]  master  - 2017-02-15/13:40:07  OK
analysis1/src/tnt/src/phase1        not installed
analysis1/src/tnt/src/phase2        not installed
analysis1/src/tnt/src/structural    not installed
analysis2                           [annex]  master  - 2017-02-15/13:40:25  OK
analysis2/src/aligned               [annex]  master  - 2017-02-15/13:40:20  OK
analysis2/src/aligned/src/phase1    not installed
analysis2/src/aligned/src/phase2    not installed
analysis2/src/aligned/src/tnt       not installed
analysis2/src/annot                 [annex]  master  - 2017-02-15/13:40:12  OK
analysis2/src/annot/src/media       not installed
analysis2/src/tnt                   [annex]  master  - 2017-02-15/13:40:07  OK
analysis2/src/tnt/src/phase1        not installed
analysis2/src/tnt/src/phase2        not installed
analysis2/src/tnt/src/structural    not installed
analysis3                           [annex]  master  - 2017-02-15/13:40:33  OK
analysis3/src/aligned               [annex]  master  - 2017-02-15/13:40:27  OK
analysis3/src/aligned/src/phase1    not installed
analysis3/src/aligned/src/phase2    not installed
analysis3/src/aligned/src/tnt       not installed
analysis3/src/annot                 [annex]  master  - 2017-02-15/13:40:12  OK
analysis3/src/annot/src/media       not installed
analysis3/src/tnt                   [annex]  master  - 2017-02-15/13:40:07  OK
analysis3/src/tnt/src/phase1        not installed
analysis3/src/tnt/src/phase2        not installed
analysis3/src/tnt/src/structural    not installed
annotations                         [annex]  master  - 2017-02-15/13:40:12  OK
annotations/src/media               [annex]  master  - 2017-02-15/13:40:09  OK
metaanalysis                        [annex]  master  - 2017-02-15/13:40:34  OK
metaanalysis/src/ana1               [annex]  master  - 2017-02-15/13:40:18  OK
metaanalysis/src/ana1/src/aligned   not installed
metaanalysis/src/ana1/src/annot     not installed
metaanalysis/src/ana1/src/tnt       not installed
metaanalysis/src/ana2               [annex]  master  - 2017-02-15/13:40:25  OK
metaanalysis/src/ana2/src/aligned   not installed
metaanalysis/src/ana2/src/annot     not installed
metaanalysis/src/ana2/src/tnt       not installed
metaanalysis/src/ana3               [annex]  master  - 2017-02-15/13:40:33  OK
metaanalysis/src/ana3/src/aligned   not installed
metaanalysis/src/ana3/src/annot     not installed
metaanalysis/src/ana3/src/tnt       not installed
phase1                              [annex]  master  - 2017-02-15/13:39:55  OK
phase2                              [annex]  master  - 2017-02-15/13:40:06  OK
phase2/src/dicoms                   [annex]  master  - 2017-02-15/13:40:03  OK
phase2/src/labet                    [annex]  master  - 2017-02-15/13:40:02  OK
structural                          [annex]  master  - 2017-02-15/13:39:56  OK
tnt                                 [annex]  master  - 2017-02-15/13:40:07  OK
tnt/src/phase1                      [annex]  master  - 2017-02-15/13:39:55  OK
tnt/src/phase2                      [annex]  master  - 2017-02-15/13:40:06  OK
tnt/src/phase2/src/dicoms           not installed
tnt/src/phase2/src/labet            not installed
tnt/src/structural                  [annex]  master  - 2017-02-15/13:39:56  OK
````

### CODE REVIEW

**Comment by mih** [comment]
Spurious failure in nd80 has happening more than once in the past. Unrelated but some kind of issue with the build bots. Never seen this with travis so far.

**Comment by yarikoptic** [comment]
very lovely -- and I love mockups!!!
nd80 -- indeed, and quite persistent today, and nd80 specific.  I will try to see WTF but may be would need just to skip that one on that elderly beast for my own sanity

**Comment by mih** [comment]
All credit goes to @bpoldrack for the idea.

**Comment by mih** [comment]
Quick demo of recursive install via the mockup from #1301:

````
In [17]: res = install(source=public.path, path='/tmp/huge/recursive', recursi
       : ve=True)
[INFO] Installing dataset at /tmp/huge/recursive from /tmp/huge/public 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/aggregate> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/aligned> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/analysis1> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/analysis2> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/analysis3> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/annotations> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/metaanalysis> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/phase1> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/phase2> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/structural> 
[INFO] Installing subdataset <Dataset path=/tmp/huge/recursive/tnt> 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/aggregate> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned/src/tnt/src/phase1 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/aggregate/src/aligned/src/tnt/src/phase1> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/aggregate/src/aligned/src/tnt/src/structural 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/aggregate/src/aligned/src/tnt/src/structural> failed, skipped 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/aligned> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/aligned/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/aligned/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/aligned/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/aligned/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/aligned/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/aligned/src/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/aligned/src/tnt/src/structural 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/analysis1> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned/src/tnt/src/phase1 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/analysis1/src/aligned/src/tnt/src/phase1> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/aligned/src/tnt/src/structural 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/analysis1/src/aligned/src/tnt/src/structural> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/annot 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/annot/src/media 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/tnt/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/tnt/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/tnt/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/analysis1/src/tnt/src/structural 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/analysis2> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned/src/tnt/src/phase1 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/analysis2/src/aligned/src/tnt/src/phase1> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/aligned/src/tnt/src/structural 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/analysis2/src/aligned/src/tnt/src/structural> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/annot 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/annot/src/media 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/tnt/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/tnt/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/tnt/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/analysis2/src/tnt/src/structural 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/analysis3> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned/src/tnt/src/phase1 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/analysis3/src/aligned/src/tnt/src/phase1> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/aligned/src/tnt/src/structural 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/analysis3/src/aligned/src/tnt/src/structural> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/annot 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/annot/src/media 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/tnt/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/tnt/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/tnt/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/analysis3/src/tnt/src/structural 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/annotations> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/annotations/src/media 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/metaanalysis> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/aligned 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/aligned/src/phase1 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/aligned/src/phase1> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/aligned/src/phase2 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/aligned/src/phase2> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/aligned/src/tnt 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/aligned/src/tnt> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/annot 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/annot/src/media 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/structural 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/aligned 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/aligned/src/phase1 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/aligned/src/phase1> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/aligned/src/phase2 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/aligned/src/phase2> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/aligned/src/tnt 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/aligned/src/tnt> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/annot 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/annot/src/media 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/structural 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/aligned 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/aligned/src/phase1 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/aligned/src/phase1> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/aligned/src/phase2 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/aligned/src/phase2> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/aligned/src/tnt 
[WARNING] Installation of subdatasets <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/aligned/src/tnt> failed, skipped 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/annot 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/annot/src/media 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/tnt 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/structural 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/phase1> underneath . recursively 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/phase2> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/phase2/src/labet 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/structural> underneath . recursively 
[INFO] Obtaining <Dataset path=/tmp/huge/recursive/tnt> underneath . recursively 
[INFO] Installing subdataset /tmp/huge/recursive/tnt/src/phase1 
[INFO] Installing subdataset /tmp/huge/recursive/tnt/src/phase2 
[INFO] Installing subdataset /tmp/huge/recursive/tnt/src/phase2/src/dicoms 
[INFO] Installing subdataset /tmp/huge/recursive/tnt/src/phase2/src/labet 
[INFO] Installing subdataset /tmp/huge/recursive/tnt/src/structural 

In [18]: res
Out[18]: 
[<Dataset path=/tmp/huge/recursive>,
 <Dataset path=/tmp/huge/recursive/aggregate>,
 <Dataset path=/tmp/huge/recursive/aggregate/src/aligned>,
 <Dataset path=/tmp/huge/recursive/aggregate/src/aligned/src/phase1>,
 <Dataset path=/tmp/huge/recursive/aggregate/src/aligned/src/phase2>,
 <Dataset path=/tmp/huge/recursive/aggregate/src/aligned/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/aggregate/src/aligned/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/aggregate/src/aligned/src/tnt>,
 <Dataset path=/tmp/huge/recursive/aligned>,
 <Dataset path=/tmp/huge/recursive/aligned/src/phase1>,
 <Dataset path=/tmp/huge/recursive/aligned/src/phase2>,
 <Dataset path=/tmp/huge/recursive/aligned/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/aligned/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/aligned/src/tnt>,
 <Dataset path=/tmp/huge/recursive/aligned/src/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/aligned/src/tnt/src/structural>,
 <Dataset path=/tmp/huge/recursive/analysis1>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/aligned>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/aligned/src/phase1>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/aligned/src/phase2>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/aligned/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/aligned/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/aligned/src/tnt>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/annot>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/annot/src/media>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/tnt>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/tnt/src/phase2>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/tnt/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/tnt/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/analysis1/src/tnt/src/structural>,
 <Dataset path=/tmp/huge/recursive/analysis2>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/aligned>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/aligned/src/phase1>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/aligned/src/phase2>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/aligned/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/aligned/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/aligned/src/tnt>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/annot>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/annot/src/media>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/tnt>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/tnt/src/phase2>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/tnt/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/tnt/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/analysis2/src/tnt/src/structural>,
 <Dataset path=/tmp/huge/recursive/analysis3>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/aligned>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/aligned/src/phase1>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/aligned/src/phase2>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/aligned/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/aligned/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/aligned/src/tnt>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/annot>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/annot/src/media>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/tnt>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/tnt/src/phase2>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/tnt/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/tnt/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/analysis3/src/tnt/src/structural>,
 <Dataset path=/tmp/huge/recursive/annotations>,
 <Dataset path=/tmp/huge/recursive/annotations/src/media>,
 <Dataset path=/tmp/huge/recursive/metaanalysis>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/aligned>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/annot>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/annot/src/media>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/tnt>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase2>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana1/src/tnt/src/structural>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/aligned>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/annot>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/annot/src/media>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/tnt>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase2>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana2/src/tnt/src/structural>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/aligned>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/annot>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/annot/src/media>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/tnt>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase2>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/metaanalysis/src/ana3/src/tnt/src/structural>,
 <Dataset path=/tmp/huge/recursive/phase1>,
 <Dataset path=/tmp/huge/recursive/phase2>,
 <Dataset path=/tmp/huge/recursive/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/structural>,
 <Dataset path=/tmp/huge/recursive/tnt>,
 <Dataset path=/tmp/huge/recursive/tnt/src/phase1>,
 <Dataset path=/tmp/huge/recursive/tnt/src/phase2>,
 <Dataset path=/tmp/huge/recursive/tnt/src/phase2/src/dicoms>,
 <Dataset path=/tmp/huge/recursive/tnt/src/phase2/src/labet>,
 <Dataset path=/tmp/huge/recursive/tnt/src/structural>]

In [19]: len(res)
Out[19]: 105
````

Failures inside are surprising....

**Pull request merged**
