### PR TITLE
RF: ssh connector code uses WitlessRunner instead of Runner

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by mih** [comment]
Looks like SSH calls stall with PY3.5, which might indicate another hidden issue with `WitlessRunner`

**Comment by mih** [comment]
So, the SSH stalling did not go away with bionic.

**Comment by mih** [comment]
Rebased on master after #4835

**Comment by mih** [comment]
Rebased again, after more witlessness has reached master.

**Comment by bpoldrack** [comment]
FTR: Investigating the stalling in PR #4860.

**Comment by mih** [comment]
Closing this one. Too much going on, too little progress.

**Pull request closed without merging**
