### PR TITLE
TST: Enable testrepos on appveyor

### PR DESCRIPTION
**Pull request by mih**
Sits on top of #5092, only the last commit is relevant.

### CODE REVIEW

**Comment by mih** [comment]
Well, yeah.... https://ci.appveyor.com/project/mih/datalad/builds/35939693

```
[00:52:26] Ran 1031 tests in 2930.050s
[00:52:26] 
[00:52:26] FAILED (SKIP=254, errors=25, failures=18)
```

Let's say it is too early to have any hope. This disaster outcome is likely a combination of the test repo setup, no meaningful support for subdataset modification and other assorted breakage in actual funcationality and/or their tests. Nevertheless insightful to scroll through it:

[tried to make a more readable, slightly curated list, multiple tests that fail in a "similar" way lumped together]

```
[00:52:24] ======================================================================
[00:52:24] ERROR: datalad.tests.test_testrepos.test_clone
[00:52:24] datalad.support.exceptions.CommandError: CommandError: 'addurl' [Error, annex reported failure for addurl (url='file://C/Users/appveyor/AppData/Local/Temp/1/datalad_temp_testrepo_hblqlfew'): {'command': 'addurl', 'note': 'to test-annex.dat', 'success': False, 'key': 'SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat', 'error-messages': ['git-annex: MoveFileEx ".git\\\\annex\\\\tmp\\\\URL-s28--file&c%%C%Users%appveyor%AppData-cb573394cbac312eaa56df322ff87753" Just ".git\\\\annex\\\\objects\\\\8f8\\\\9ce\\\\SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat\\\\SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat": does not exist (The system cannot find the path specified.)'], 'file': 'test-annex.dat'}]

======================================================================
[00:52:24] ERROR: datalad.core.distributed.tests.test_clone.test_clone_into_dataset
[00:52:24] ----------------------------------------------------------------------
[00:52:24] datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[00:52:24] [{'action': 'add_submodule',
[00:52:24]   'message': ('cannot add subdataset %s with no commits',
[00:52:24]               GitRepo('C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_cct7p5hu\\sub')),
[00:52:24]   'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_cct7p5hu\\sub',
[00:52:24]   'status': 'error',
[00:52:24]   'type': 'dataset'}]

======================================================================
[00:52:24] ERROR: datalad.core.local.tests.test_run.test_run_explicit
[00:52:24] ----------------------------------------------------------------------
[00:52:24] datalad.support.exceptions.CommandError: CommandError: 'cat test-annex.dat test-annex.dat >doubled.dat' failed with exitcode 1 under C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_clone_url_bs6axci8

======================================================================
[00:52:24] ERROR: datalad.distribution.tests.test_get.test_get_greedy_recurse_subdatasets
[00:52:24] ----------------------------------------------------------------------
[00:52:24] datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 2 failed:

[00:52:24] [{'action': 'get',
[00:52:24]   'message': 'path does not exist',
[00:52:24]   'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_qxx99bpe\\2',
[00:52:24]   'refds': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_qxx99bpe',
[00:52:24]   'status': 'impossible'},
[00:52:24]  {'action': 'get',
[00:52:24]   'message': 'path does not exist',
[00:52:24]   'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_qxx99bpe\\subm '
[00:52:24]           '1',
[00:52:24]   'refds': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_qxx99bpe',
[00:52:24]   'status': 'impossible'}]

======================================================================
[00:52:24] ERROR: datalad.distribution.tests.test_get.test_get_install_missing_subdataset
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_get.py", line 477, in test_get_install_missing_subdataset
[00:52:24]     file_ = opj(subs[0].path, 'test-annex.dat')
[00:52:24] IndexError: list index out of range

======================================================================
[00:52:24] ERROR: datalad.distribution.tests.test_install.test_install_list
[00:52:24] ERROR: datalad.distribution.tests.test_get.test_get_single_file
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 457, in generator_func
[00:52:24]     msg="Command did not complete successfully")
[00:52:24] datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:

[00:52:24] [{'action': 'get',
[00:52:24]   'message': 'path does not exist',
[00:52:24]   'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_clone_url_r14ajww7\\test-annex.dat',
[00:52:24]   'refds': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_clone_url_r14ajww7',
[00:52:24]   'status': 'impossible'}]

[00:52:24] ======================================================================
[00:52:24] ERROR: datalad.distribution.tests.test_install.test_install_skip_failed_recursive
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_install.py", line 702, in test_install_skip_failed_recursive
[00:52:24]     with open(opj(path, 'subm 1', 'blocking.txt'), "w") as f:
[00:52:24] FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_5yyd5hq6\\subm 1\\blocking.txt'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_is_available
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_migrating_backends
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_get_file_backend
[00:52:24] ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_get_contentlocation(False,)
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 1459, in get_file_key
[00:52:24]     raise IOError(e.code, "File not found.", files)
[00:52:24] PermissionError: [Errno 1] File not found.: 'test-annex.dat'


======================================================================
ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_add_submodule
[00:52:24] ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_add_submodule
[00:52:24] ----------------------------------------------------------------------
[00:52:24] datalad.support.exceptions.CommandError: CommandError: '"git" "submodule" "add" "--name" "sub" "C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_testrepo_dcheuzcz" "sub"' failed with exitcode 1 under C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_a3b3sfgf [err: 'Cloning into 'C:/Users/appveyor/AppData/Local/Temp/1/datalad_temp_a3b3sfgf/sub'...
[00:52:24] warning: You appear to have cloned an empty repository.
[00:52:24] done.
[00:52:24] fatal: You are on a branch yet to be born
[00:52:24] Unable to checkout submodule 'sub'']

======================================================================
[00:52:24] ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_add_to_annex
[00:52:24] ----------------------------------------------------------------------
[00:52:24] FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_clone_url_oac7ad5a\\.git\\annex\\objects\\7ca\\9ce\\SHA256E-s4--a6b46dd0d1ae5e86cbc8f37e75ceeb6760230c1ca4ffbcb0c97b96dd7d9c464b.datc\\SHA256E-s4--a6b46dd0d1ae5e86cbc8f37e75ceeb6760230c1ca4ffbcb0c97b96dd7d9c464b.datc'

[00:52:24] ======================================================================
ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_instance_from_clone
ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_remote_remove
ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_get_indexed_files
[00:52:24] ERROR: [00:52:24] datalad.support.exceptions.CommandError: CommandError: '"git" "clone" "--progress" "C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_testrepo_hiknpl2y\sub dataset1\subm 1" "C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_jc7bf74x"' failed with exitcode 128 [err: 'Cloning into 'C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_jc7bf74x'...
[00:52:24] fatal: 'C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_testrepo_hiknpl2y\sub dataset1\subm 1' does not appear to be a git repository
[00:52:24] fatal: Could not read from remote repository.
[00:52:24] 
[00:52:24] Please make sure you have the correct access rights
[00:52:24] and the repository exists.']

======================================================================
[00:52:24] ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_get_files
[00:52:24] ----------------------------------------------------------------------
[00:52:24] datalad.support.exceptions.InvalidGitReferenceError: Git reference 'origin/master' invalid

[00:52:24] ======================================================================
[00:52:24] ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_pull
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 1835, in get_hexsha
[00:52:24]     raise ValueError("Unknown commit identifier: %s" % commitish)
[00:52:24] ValueError: Unknown commit identifier: HEAD^

[00:52:24] ======================================================================
[00:52:24] ERROR: datalad.support.tests.test_gitrepo.test_get_tracking_branch
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\cmd.py", line 518, in run
[00:52:24]     **results,
[00:52:24] datalad.support.exceptions.CommandError: CommandError: '"git" "checkout" "--track" "-btopic" "master"' failed with exitcode 128 under C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_1c36t_5t [err: 'fatal: 'master' is not a commit and a branch 'topic' cannot be created from it']

[00:52:24] ======================================================================
[00:52:24] FAIL: datalad.tests.test_tests_utils.test_serve_path_via_http(";&%b5{}'.datc",)
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\tests\test_tests_utils.py", line 419, in test_path_and_url
[00:52:24]     assert_false('http_proxy' in os.environ)
[00:52:24] AssertionError: True is not false
[00:52:24] 
[00:52:24] 

======================================================================
FAIL: datalad.distribution.tests.test_install.test_install_dataset_from_instance
[00:52:24] FAIL: datalad.core.distributed.tests.test_clone.test_clone_dataset_from_just_source
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\core\distributed\tests\test_clone.py", line 217, in test_clone_dataset_from_just_source
[00:52:24]     assert_in('INFO.txt', ds.repo.get_indexed_files())
[00:52:24] AssertionError: 'INFO.txt' not found in []

[00:52:24] ======================================================================
FAIL: datalad.support.tests.test_gitrepo.test_submodule_deinit
[00:52:24] FAIL: datalad.core.distributed.tests.test_clone.test_clone_isnot_recursive
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\core\distributed\tests\test_clone.py", line 254, in test_clone_isnot_recursive
[00:52:24]     {'subm 1', '2'})
[00:52:24] AssertionError: set() != {'subm 1', '2'}

[00:52:24] ======================================================================
[00:52:24] FAIL: datalad.core.distributed.tests.test_clone.test_clone_simple_local
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\core\distributed\tests\test_clone.py", line 190, in test_clone_simple_local
[00:52:24]     {'test.dat', 'INFO.txt', 'test-annex.dat'})
[00:52:24] AssertionError: {'INFO.txt', 'test.dat'} != {'INFO.txt', 'test.dat', 'test-annex.dat'}

[00:52:24] ======================================================================
[00:52:24] FAIL: datalad.core.distributed.tests.test_clone.test_notclone_known_subdataset
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\core\distributed\tests\test_clone.py", line 300, in test_notclone_known_subdataset
[00:52:24]     assert_in('subm 1', ds.subdatasets(fulfilled=False, result_xfm='relpaths'))
[00:52:24] AssertionError: 'subm 1' not found in []

[00:52:24] ======================================================================
[00:52:24] FAIL: datalad.distribution.tests.test_install.test_install_recursive_with_data
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1322, in assert_status
[00:52:24]     dumps(results, indent=1, default=lambda x: str(x))))
[00:52:24] AssertionError: Test 1/7: expected status ['ok'] not found in:
[00:52:24] [
[00:52:24]  "action",
[00:52:24]  "path",
[00:52:24]  "type",
[00:52:24]  "status",
[00:52:24]  "source_url",
[00:52:24]  "source",
[00:52:24]  "refds"
[00:52:24] ]

[00:52:24] ======================================================================
[00:52:24] FAIL: datalad.distribution.tests.test_uninstall.test_uninstall_git_file
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_uninstall.py", line 168, in test_uninstall_git_file
[00:52:24]     ok_(exists(opj(path, 'INFO.txt')))
[00:52:24] AssertionError: None

[00:52:24] ======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_file_has_content
FAIL: datalad.support.tests.test_annexrepo.test_annex_drop
[00:52:24] FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_get
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\support\tests\test_annexrepo.py", line 883, in test_AnnexRepo_get
[00:52:24]     ok_(annex.file_has_content("test-annex.dat"))
[00:52:24] AssertionError: None

[00:52:24] ======================================================================
[00:52:24] FAIL: datalad.support.tests.test_annexrepo.test_annex_remove
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\support\tests\test_annexrepo.py", line 1219, in test_annex_remove
[00:52:24]     assert len(file_list) >= 1
[00:52:24] AssertionError: 

[00:52:24] ======================================================================
[00:52:24] FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_is_under_annex
[00:52:24] ----------------------------------------------------------------------
[00:52:24]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\support\tests\test_annexrepo.py", line 339, in test_AnnexRepo_is_under_annex
[00:52:24]     eq_(ar.is_under_annex(testfiles, batch=batch), target_value)
[00:52:24] AssertionError: [False, False, False] != [True, False, False]


[00:52:26] ======================================================================
[00:52:26] FAIL: datalad.support.tests.test_gitrepo.test_GitRepo_fetch
[00:52:26] ----------------------------------------------------------------------
[00:52:26]   File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\support\tests\test_gitrepo.py", line 565, in test_GitRepo_fetch
[00:52:26]     [commit['ref'] for commit in fetched])
[00:52:26] AssertionError: ['origin/master', 'origin/new_branch'] != ['origin/new_branch']

```

**Comment by mih** [comment]
Force-pushed a rebase on current master after the overhaul of the appveyor setup to evaluate the current state of things.

**Comment by mih** [comment]
```
FAIL: datalad.core.distributed.tests.test_clone.test_notclone_known_subdataset
FAIL: datalad.core.distributed.tests.test_clone.test_clone_isnot_recursive
FAIL: datalad.support.tests.test_gitrepo.test_submodule_deinit
AssertionError: 'subm 1' not found in []


ERROR: datalad.core.distributed.tests.test_clone.test_clone_into_dataset
[{'action': 'add_submodule',
  'message': ('cannot add subdataset %s with no commits',
             GitRepo('C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_8petg9vc\\sub')),
  'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_8petg9vc\\sub',
  'status': 'error',
  'type': 'dataset'}]


FAIL: datalad.core.distributed.tests.test_clone.test_clone_simple_local
AssertionError: {'test.dat', 'INFO.txt'} != {'test.dat', 'INFO.txt', 'test-annex.dat'}


ERROR: datalad.core.local.tests.test_run.test_run_explicit
datalad.support.exceptions.CommandError: CommandError: 'cat test-annex.dat test-annex.dat >doubled.dat' failed with exitcode 1 under C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_clone_url_8xviraoh


ERROR: datalad.core.distributed.tests.test_clone.test_clone_dataset_from_just_source
datalad.support.exceptions.CommandError: CommandError: 'addurl' [Error, annex reported failure for addurl (url='file://C/Users/appveyor/AppData/Local/Temp/1/datalad_temp_testrepo_026cfkxo'): {'command': 'addurl', 'note': 'to test-annex.dat', 'success': False, 'input': ['file://C/Users/appveyor/AppData/Local/Temp/1/datalad_temp_testrepo_026cfkxo'], 'key': 'SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat', 'error-messages': ['git-annex: MoveFileEx ".git\\\\annex\\\\tmp\\\\URL-s28--file&c%%C%Users%appveyor%AppData-23dccac8648a0cd2a45b59241d323435" Just ".git\\\\annex\\\\objects\\\\8f8\\\\9ce\\\\SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat\\\\SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat": does not exist (The system cannot find the path specified.)'], 'file': 'test-annex.dat'}]


FAIL: datalad.support.tests.test_gitrepo.test_GitRepo_fetch
AssertionError: ['origin/master', 'origin/new_branch'] != ['origin/new_branch']


FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_is_under_annex
test_AnnexRepo_is_under_annex
3089    eq_(ar.is_under_annex(testfiles, batch=batch), target_value)
3090AssertionError: [False, False, False] != [True, False, False]


FAIL: datalad.support.tests.test_annexrepo.test_annex_remove
assert len(file_list) >= 1
```

**Comment by mih** [comment]
Good news: All core tests that are reported as failing on appveyor do actually pass on a real win10 box. Disabling accordingly. Good that the real situation on windows is much better than expected. Bad that we still have no test environment that actually behaves like a real user desktop.

**Comment by adswa** [comment]
I'm using my Windows machine to try out all those failing tests locally as well. It takes a while, and I'll keep ticking off tests that work throughout the morning.
Here are the tests that work locally for me, but fail on appveyor (with a checkmark). Those tests without a checkmark and a question mark I yet need to run.

- [x] datalad.core.distributed.tests.test_clone.test_clone_dataset_from_just_source
- [x] datalad.core.distributed.tests.test_clone.test_clone_into_dataset 
- [x] datalad.core.distributed.tests.test_clone.test_clone_isnot_recursive
- [x] datalad.core.distributed.tests.test_clone.test_clone_simple_local 
- [x] datalad.core.distributed.tests.test_clone.test_notclone_known_subdataset


- [x] datalad.cmdline.tests.test_helpers.test_get_repo_instance_annex 
- [x] datalad.distribution.tests.test_get.test_get_greedy_recurse_subdatasets 
- [x] datalad.distribution.tests.test_get.test_get_install_missing_subdataset 
- [x] datalad.distribution.tests.test_get.test_get_single_file
- [x] datalad.distribution.tests.test_install.test_install_list
- [ ] datalad.distribution.tests.test_install.test_install_skip_failed_recursive ?
- [ ] datalad.distribution.tests.test_publish.test_publish_plain_git ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_get_contentlocation(False,) ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_get_contentlocation(True,) ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_add_submodule ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_add_to_annex ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_get_file_backend ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_migrating_backends ?
- [ ] datalad.support.tests.test_annexrepo.test_is_available(False,) ?
- [ ] datalad.support.tests.test_annexrepo.test_is_available(True,) ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_remote_add ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_add_submodule ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_get_files ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_get_indexed_files ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_pull ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_remote_remove ?
- [ ] datalad.support.tests.test_gitrepo.test_get_tracking_branch ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_instance_from_clone ?
- [ ] datalad.distribution.tests.test_install.test_install_dataset_from_instance ?
- [ ] datalad.distribution.tests.test_install.test_install_recursive_with_data ?
- [ ] datalad.distribution.tests.test_install.test_install_skip_list_arguments ?
- [ ] datalad.distribution.tests.test_uninstall.test_uninstall_git_file ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_get ?
- [ ] datalad.support.tests.test_annexrepo.test_annex_drop ?
- [ ] datalad.support.tests.test_annexrepo.test_annex_remove ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_file_has_content(False,) ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_file_has_content(True,) ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_is_under_annex(False,) ?
- [ ] datalad.support.tests.test_annexrepo.test_AnnexRepo_is_under_annex(True,) ?
- [ ] datalad.support.tests.test_gitrepo.test_GitRepo_fetch ?
- [ ] datalad.support.tests.test_gitrepo.test_submodule_deinit ?

- [ ] datalad.tests.test_testrepos.test_clone ?

- [ ] datalad.customremotes.tests.test_archives.test_interactions ?
- [ ] datalad.downloaders.tests.test_http.test_HTTPDownloader_basic
- [ ] datalad.downloaders.tests.test_http.test_download_url ?
- [ ] datalad.tests.test_tests_utils.test_nested_with_tempfile_parametrized_surrounded('param1',) ?
- [ ] datalad.plugin.tests.test_addurls.TestAddurls.test_addurls ?
- [ ] datalad.plugin.tests.test_addurls.test_extract ?
- [ ] datalad.plugin.tests.test_plugins.test_no_annex ?

Once done, I'll mark the passing tests accordingly following what you did, mih.

**Comment by adswa** [comment]
I observed 6 failures locally that resemble those on Appveyor. The rest passes fine on my Windows 10 machine.

**Comment by adswa** [comment]
Oh, there are a few missing imports for that decorator. I'll push them shortly (running tests locally to be sure I didn't miss any first)

**Comment by mih** [comment]
I bet there is something serial going on with the testrepo setup on appveyor. I have spent days now, taking turns with @adswa, to marke tests as known failures on appveyor, which pass on real win10 boxes. However, once one test is marked the next appveyor run let's another test fail -- which then also passes on win10.

This seems to suggest that monolithic all-at-once test runs are different from individual execution -- on windows.

**Comment by mih** [comment]
I am taking the milestone association off. This is better approached in conjuction with a more general appveyor update.

**Comment by mih** [comment]
Superseded by #5303

**Pull request closed without merging**
