### PR TITLE
UX: When calling uninstall without nocheck, strip hints for drops reckless parameter

### LINKED ISSUE #6259: Uninstall gives hints from drop that don't apply to uninstall
``uninstall`` is being deprecated, but if one were to use it, they would not necessarily know about the deprecation and get confusing hints that apply to ``drop``, but not ``uninstall``:

```
(handbook2) adina@muninn in /tmp/bc on git:master
❱ datalad uninstall -d some                                                 1 !
uninstall(error): . (dataset) [to-be-dropped dataset has revisions that are not available at any known sibling. Use `datalad push --to ...` to push these before dropping the local dataset, or ignore via `--reckless availability`. Unique revisions: ['master']]
(handbook2) adina@muninn in /tmp/bc on git:master
❱ datalad uninstall -d some --reckless                                      1 !
[ERROR  ] unknown argument: --reckless 
usage: datalad uninstall [-h] [-d DATASET] [-r] [--nocheck]
                         [--if-dirty {fail,save-before,ignore}] [--version]
                         [PATH ...]
(handbook2) adina@muninn in /tmp/bc on git:master
❱ datalad uninstall -d some --nocheck                                       1 !
uninstall(ok): . (dataset)  
```

Not sure what could be done - maybe a deprecation warning that gets displayed by default/at normal log levels?

### PR DESCRIPTION
**Pull request by adswa**
Behavior if one were to use uninstall but forgot ``--nocheck``:

```
datalad uninstall containers                       
uninstall(error): containers (dataset) [to-be-dropped dataset has revisions that are not available at any known sibling. Use `datalad push --to ...` to push these before dropping the local dataset, or ignore via `--reckless availability`. Unique revisions: ['master']]
```

Behavior now:

```
❱ datalad uninstall containers                                              2 !
uninstall(error): containers (dataset) [to-be-dropped dataset has revisions that are not available at any known sibling. Use `datalad push --to ...` to push these before dropping the local dataset, or ignore via `--nocheck`. Unique revisions: ['master']]
```

Fixes #6259

### CODE REVIEW

**Review by bpoldrack — APPROVED** [review]
Looks alright to me

**Comment by adswa** [comment]
The Appveyor failure is unrelated:
```
python -m coverage xml
C:\Python310\python.exe: No module named coverage
Command exited with code 1
```

**Comment by mih** [comment]
Python 3.10? How come?

**Comment by adswa** [comment]
> Python 3.10? How come?

Not sure, but rerunning the test worked:

```
python -m coverage xml
Wrote XML report to coverage.xml
curl -fsSL -o codecov.exe "https://uploader.codecov.io/latest/windows/codecov.exe"
.\codecov.exe -f "coverage.xml"
[2021-12-03T08:09:54.417Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/
  Codecov report uploader 0.1.13
[2021-12-03T08:09:54.447Z] ['info'] => Project root located at: C:/projects/datalad
[2021-12-03T08:09:54.449Z] ['info'] -> No token specified or token is empty
[2021-12-03T08:09:54.477Z] ['info'] Searching for coverage files...
[2021-12-03T08:09:54.525Z] ['info'] => Found 1 possible coverage files:
  __testhome__/coverage.xml
[2021-12-03T08:09:54.526Z] ['info'] Processing C:/projects/datalad/__testhome__/coverage.xml...
[2021-12-03T08:09:54.553Z] ['info'] Detected Appveyor CI as the CI provider.
[2021-12-03T08:09:54.555Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=uploader-0.1.13&token=*******&branch=master&build=jd40g6e7tyckp8a4&build_url=https%3A%2F%2Fci.appveyor.com%2Fproject%2Fdatalad%2Fdatalad%2Fbuilds%2F41756509%2Fjob%2Fjd40g6e7tyckp8a4&commit=b5b9e4a5a9b0a40d0f4a83e21012cf1ee53aa738&job=mih%2Fdatalad%2F1.0.7192&pr=6277&service=appveyor&slug=datalad%2Fdatalad&name=&tag=&flags=&parent=
[2021-12-03T08:09:55.490Z] ['info'] Uploading...
[2021-12-03T08:09:55.749Z] ['info'] {"status":"success","resultURL":"https://codecov.io/github/datalad/datalad/commit/7d84741666236953b0646c0895d018ff225991b5"}
powershell.exe while ((Test-Path "C:\Users\\appveyor\\Desktop\\BLOCK.txt")) { Start-Sleep 5 }
Build success
```

temporary glitch? no clue

**Review by mih — APPROVED** [review]
Cool, thx!

**Pull request merged**
