### PR TITLE
TST+BF: SSH test assumptions invalid on windows/*FAT

### PR DESCRIPTION
**Pull request by mih**
Tested filename not supported by filesystem (see gh-4728)

Test also failed due to the inability to use SSH control master
based connections, but the actual functionality works.

Arguably, SSH tooling should be able to handle that, and this particular
test should not test whether some internal connection mechanism worked.

Fixes gh-4726

### CODE REVIEW

**Comment by yarikoptic** [comment]
Crap, I can't find it... I have a memory of seeing git annex refusing to establish socket on the file system which doesn't support them, and providing an environment (or config?) variable to set alternative path... There is also `git config annex.sshcaching false`

**Comment by yarikoptic** [comment]
Oops, I think I mixed up - above comment is unrelated to this PR.

**Comment by mih** [comment]
I can replicate the travis failure locally:

```
datalad.support.exceptions.CommandError: CommandError: 'scp -o ControlPath=/home/mih/.cache/datalad/sockets/7e2df38e -P 22 'localhost:/tmp/datalad_temp_test_ssh_copyq6gwyx4h.c\ opy/\ \"\'"'"'\;a\&b\&cΔЙקم๗あ\ `\|\ 2' /tmp/datalad_temp_test_ssh_copyq6gwyx4h' failed with exitcode 1 [err: 'zsh:1: unmatched `']
```

Quoting is indeed broken.

**Comment by mih** [comment]
Interestingly, the command giving to the runner seems to be fine:

```
> /home/mih/hacking/datalad/git/datalad/support/sshconnector.py(394)get()
-> return self.runner.run(scp_cmd)
(Pdb) scp_cmd
['scp', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/7e2df38e', '-P', '22', 'localhost:/tmp/datalad_temp_test_ssh_copyoo2yn6jj.c\\ opy/\\ \\"\\\'\\;a\\&b\\&cΔЙקم๗あ\\ `\\|\\ 2', '/tmp/datalad_temp_test_ssh_copyoo2yn6jj']
```

Also confusion, we is `zsh` (for me) and `bash` on travis reporting the error. The runner is invoked with `shell=None` and docs say:

```
836             shell: bool, optional
837                 Run command in a shell.  If not specified, then it runs in a shell
838                 only if command is specified as a string (not a list)
```
and we pass a list.

**Comment by mih** [comment]
Ah, I get it now! This is and error that comes in from the remote! At which point the command obviously was (wrongly) stringified.

**Comment by mih** [comment]
So my original change managed to trip `scp` itself. So I force-pushed a change that slightly simplified the most obscure name to not do that, but still remains pretty obscure.

**Comment by yarikoptic** [comment]
@mih shouldn't this to go over to `maint` so we do not trip bugfix releases testing on windows/FAT?

**Pull request merged**
