### PR TITLE
Delete datalad/install.py (Moved to its own repository)

### PR DESCRIPTION
**Pull request by jwodder**
This code has been moved to https://github.com/datalad/datalad-installer/ as part of #5240.

NOTE: Some workflows in this repository depend on datalad/install.py.  Do not merge until the new version is stable.

### CODE REVIEW

**Comment by yarikoptic** [comment]
probably we should just wait for the datalad-installer to get "released" so we could may be use a versioned release instead of master and so changes to datalad-installer's master would not break datalad CI setup?

**Comment by yarikoptic** [comment]
There is now https://pypi.org/project/datalad-installer/ (thanks @jwodder ) so removing the label

**Comment by yarikoptic** [comment]
@jwodder would you be kind to rebase please, so we have a fresh tests run, time to merge IMHO

**Comment by jwodder** [comment]
@yarikoptic Rebased.

**Pull request merged**
