### PR TITLE
BF+OPT: allow to save change where file becomes a folder, and avoid multiple traversals in _save

### LINKED ISSUE #6558: save would make git crash replacing a file with directory with content
might populate with more details later, for now just a record of reproducing the problem reported in  https://github.com/dandi/dandisets/issues/127#issuecomment-1066934910 and shown in CI runs of https://github.com/dandi/dandisets/pull/134 

<details>
<summary>cut paste of manual reproducing</summary> 

```shell
(git-annex)lena:/tmp/clean[master]git-annex
$> touch path1; datalad save -m 1
add(ok): path1 (file)                                                                                                                                                                
save(ok): . (dataset)                                                                                                                                                                
action summary:                                                                                                                                                                      
  add (ok: 1)
  save (ok: 1)
1 13723 [1].....................................:Wed 16 Mar 2022 02:59:07 PM EDT:.
(git-annex)lena:/tmp/clean[master]git-annex
$> rm path1; mkdir path1; echo 1 > path1/path2; git annex add path1/path2
add path1/path2 
ok                                
(recording state in git...)
1 13724 [1].....................................:Wed 16 Mar 2022 02:59:13 PM EDT:.
(git-annex)lena:/tmp/clean[master]git-annex
$> git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    path1
	new file:   path1/path2

1 13725 [1].....................................:Wed 16 Mar 2022 02:59:16 PM EDT:.
(git-annex)lena:/tmp/clean[master]git-annex
$> datalad save -m 2       
[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none commit -m 2 -- path1/path2 path1' failed with exitcode 128 under /tmp/clean [err: 'error: 'path1' does not have a commit checked out
fatal: updating files failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C. 
[INFO   ] Canceled 0 out of 0 jobs. 0 left running. 
Total: 0.00 datasets [00:00, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none commit -m 2 -- path1/path2 path1' failed with exitcode 128 under /tmp/clean
error: 'path1' does not have a commit checked out
fatal: updating files failed
1 13726 ->128 [1].....................................:Wed 16 Mar 2022 02:59:27 PM EDT:.
(git-annex)lena:/tmp/clean[master]git-annex
$> git -c diff.ignoreSubmodules=none commit -m 2 -- path1/path2 path1
error: 'path1' does not have a commit checked out
fatal: updating files failed
1 13727 ->128 [1].....................................:Wed 16 Mar 2022 02:59:40 PM EDT:.
(git-annex)lena:/tmp/clean[master]git-annex
$> git -c diff.ignoreSubmodules=none commit -m 2 -- path1/path2      
[master a03d813] 2
 2 files changed, 1 insertion(+), 1 deletion(-)
 delete mode 120000 path1
 create mode 120000 path1/path2

```
</details>

which boils down to "not provide path of removed (and staged for removal) directory into 'git commit' call"

<details><summary>DataLad 0.15.5 WTF (configuration, credentials, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, metadata_indexers, python, system)</summary>

# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - kwallet DBusKeyring
      - libsecret Keyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/yoh/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/yoh/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/yoh/.config/python_keyring/keyringrc.cfg
    - data_root: /home/yoh/.local/share/python_keyring
## datalad 
  - version: 0.15.5
## dataset 
  - branches: 
    - git-annex@dc82499
    - master@a03d813
  - id: c625b32c-9d97-4034-aeb9-dd14a0d50b23
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /tmp/clean
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20211123
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.34.1
  - cmd:system-git: 2.34.1
  - cmd:system-ssh: 8.7p1
  - exifread: 2.3.2
  - git: 3.1.24
  - gitdb: 4.0.9
  - humanize: 0.0.0
  - iso8601: 0.1.16
  - keyring: 23.5.0
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.2
  - mutagen: 1.45.1
  - requests: 2.25.1
  - scrapy: 2.5.1
  - wrapt: 1.13.3
## environment 
  - GIT_PAGER: less --no-init --quit-if-one-screen
  - LANG: en_US.UTF-8
  - PATH: /home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20211123
## location 
  - path: /tmp/clean
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.9.10
## system 
  - distribution: debian/testing/bookworm
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 266
  - name: Linux
  - release: 5.15.0-3-amd64
  - type: posix
  - version: #1 SMP Debian 5.15.15-2 (2022-01-30)
</details>

<details>
<summary>The same problem with bleeding edge master datalad and most recent git available in debian ATM</summary> 

```shell
(git-annex)lena:/tmp/clean[master]git
$> git -c diff.ignoreSubmodules=none commit -m 2 -- path1/path2 path1
error: 'path1' does not have a commit checked out
fatal: updating files failed

$> datalad save -m 2                                                 
[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none commit -m 2 -- path1/path2 path1' failed with exitcode 128 under /tmp/clean [err: 'error: 'path1' does not have a commit checked out
fatal: updating files failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C. 
[INFO   ] Canceled 0 out of 0 jobs. 0 left running. 
Total: 0.00 datasets [00:00, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none commit -m 2 -- path1/path2 path1' failed with exitcode 128 under /tmp/clean
error: 'path1' does not have a commit checked out
fatal: updating files failed

$> datalad --version
datalad 0.15.6+829.gb23174877

$> git --version
git version 2.35.1.473.g83b2b277ed
```
</details>

I think we should fix it in DataLad via "remove paths from the call to `commit` which are parents for another path in the call" but that might be too expensive  although I remember we had already done something like that for something else.

<details>
<summary>but I also think it is worthwhile reporting to git folks -- IMHO operation is inconsistent</summary> 

e.g. if I remove the file and regardless either I add that to index or not -- commit works fine

```shell
$> rm path1                
(dev3) 1 13781 [1].....................................:Wed 16 Mar 2022 03:45:14 PM EDT:.
(git-annex)lena:/tmp/clean[master]git
$> git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    path1

no changes added to commit (use "git add" and/or "git commit -a")
(dev3) 1 13782 [1].....................................:Wed 16 Mar 2022 03:45:15 PM EDT:.
(git-annex)lena:/tmp/clean[master]git
$> git add path1 
(dev3) 1 13783 [1].....................................:Wed 16 Mar 2022 03:45:22 PM EDT:.
(git-annex)lena:/tmp/clean[master]git
$> git status   
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    path1

(dev3) 1 13784 [1].....................................:Wed 16 Mar 2022 03:45:24 PM EDT:.
(git-annex)lena:/tmp/clean[master]git
$> git commit -m removed path1
[master 0444c4c] removed
 1 file changed, 1 deletion(-)
 delete mode 120000 path1

```
</details>

### PR DESCRIPTION
**Pull request by yarikoptic**
The primary goal was to address #6558. Fixes #6558 (attn @jwodder, would be nice if you could check if fixes on the dandisets tests use case, didn't try)

But to arrive there without incurring notable runtime performance I decided to RF code in `_save` a bit since I noticed it is doing traversals of the same dict (which was also OrderedDict, no longer needed) over and over again to filter out for files with desired status.  To avoid multiple traversals, I have first groupped into the groups based on status, thus in effect removing many multiple traversals of the same possibly huge dict . I think it could make any `save` faster now. Also removed the need for  a single OrderedDict, but filed https://github.com/datalad/datalad/issues/6566 

#### 🐛 Bug Fixes
- `save` now can commit the change where file becomes a directory with a staged for commit file. Fixes #6558
#### 💫 Enhancements and new features
- `save` code might operate faster on heavy file trees

### CODE REVIEW

**Comment by mih** [comment]
I haven't reviewed the code yet, but the CI failures look real.

**Comment by jwodder** [comment]
@yarikoptic This does fix the problem I was seeing with the Zarr backup tests.

**Comment by yarikoptic** [comment]
ok, I have fixed for immediate failures (with some further RFing) but since I realized that there is a mighty nice test of save operating on the `get_convoluted_situation()` produced use case, I decided that I would just migrate the test over to it...

<details>
<summary>the diff</summary> 

```patch
diff --git a/datalad/core/local/tests/test_save.py b/datalad/core/local/tests/test_save.py
index fbf8a6446..b15502adc 100644
--- a/datalad/core/local/tests/test_save.py
+++ b/datalad/core/local/tests/test_save.py
@@ -170,16 +170,6 @@ def test_renamed_file():
         ds.save(recursive=recursive)
         assert_repo_status(path)
 
-        # https://github.com/datalad/datalad/issues/6558
-        new = (ds.pathobj / "new")
-        new.unlink()
-        new.mkdir()
-        (new / "file").touch()
-        ds.repo.call_git(["add"], files=[str(new / "file")])
-        ds.save(recursive=recursive)
-        assert_repo_status(path)
-
-
     for recursive in False,:  #, True TODO when implemented
         for annex in True, False:
             yield check_renamed_file, recursive, annex
diff --git a/datalad/tests/utils.py b/datalad/tests/utils.py
index 0e48361a4..627c1fa85 100644
--- a/datalad/tests/utils.py
+++ b/datalad/tests/utils.py
@@ -1653,6 +1653,9 @@ def get_convoluted_situation(path, repocls=AnnexRepo):
             'file_deleted': 'file_deleted',
             'file_staged_deleted': 'file_staged_deleted',
             'file_modified': 'file_clean',
+            # TODO: our code cannot handle it and  git pukes too if path is given to commit
+            # 'file_changed_to_subdir': 'file_changed_to_subdir',
+            'file_changed_to_subdir_staged': 'file_changed_to_subdir_staged',
         }
     )
     if isinstance(ds.repo, AnnexRepo):
@@ -1766,6 +1769,17 @@ def get_convoluted_situation(path, repocls=AnnexRepo):
             'file_modified': 'file_modified',
         }
     )
+    for f in glob.glob(opj(ds.path, 'file_changed_to_subdir*')):
+        os.remove(f)
+    create_tree(
+        ds.path,
+        {
+            # TODO:
+            # 'file_changed_to_subdir': {'file_untracked': 'file_untracked'},
+            'file_changed_to_subdir_staged': {'file_staged': 'file_staged'},
+        }
+    )
+    ds.repo.add([opj('file_changed_to_subdir_staged', 'file_staged')])
     return ds
```
</details>

that migration (easy to perform) revealed two issues:
1. fix proposed in this PR would not work for the case whenever file becomes a directory , file under which is **not** staged for commit.  That case is commented out in above diff.  Our status sees directory as added, runs `git add` on it, but then we can't pass that directory name to `git commit` (with then staged file under` since `git` kabooms.  It feels that workaround would be to redo status assessment, or do reassesment of status for every `add`ed directory 
2. leads to failure of the `datalad/support/tests/test_repo_save.py:test_gitrepo_save_all` with one-too-many of "delete" entries 
```
 53  	    # we still have an entry for everything that did not get deleted
 54  	    # intentionally
 55  ->	    eq_(
 56  	        len([f for f, p in orig_status.items()
 57  	             if not f.match('*_deleted')]),
 58  	        len(saved_status))
 59  	    # everything but subdataset entries that contain untracked content,
 60  	    # or modified subsubdatasets is now clean, a repo simply doesn touch
...
AssertionError: 32 != 31

```
since file entry is "deleted" although there is an added file under that new file as a directory.  Not  sure if I should tune up name in the layout or our status should just not say that it was deleted!?

**Comment by yarikoptic** [comment]
@mih -- need your help.  So, in the case of the tricky renames of file into a directory (still need to add a case where it becomes indeed just a directory without content, or may be even with content and submodule), here is what we get by both `git` and `datalad` status.

```shell
(git-annex)lena:~/.tmp/datalad_temp_test_gitrepo_save_allxudp7d1y[dl-test-branch]git-annex
$> datalad status file_changed_to_subdir*
 modified: file_changed_to_subdir (symlink)
    added: file_changed_to_subdir_staged/file_staged (file)
  deleted: file_changed_to_subdir_staged (file)

$> git status file_changed_to_subdir*    
On branch dl-test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    file_changed_to_subdir_staged
	new file:   file_changed_to_subdir_staged/file_staged

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    file_changed_to_subdir

$> git --version; datalad --version
git version 2.30.2
datalad 0.15.6+6.gede2a2a19.dirty
```

git -- consistently reports files as "deleted" (regardless either anything staged under or not) and reports staged filed under as staged, and nothing else about file/now-directory  which has not yet staged file.

datalad - does say 'deleted' for the one which has file staged under, and "modified" for the one which doesn't have file under staged.

I wonder what should our `status` report in such cases of "File to a directory" mutation?

**Comment by yarikoptic** [comment]
it seems to be generally green (known issues with most recent annex on macs)

<details>
<summary>thought that datalad-metalad ERROR is legitely brought by this PR but not</summary> 

```shell
======================================================================
102
ERROR: datalad_metalad.tests.test_extract.test_empty_dataset_error
103
----------------------------------------------------------------------
104
Traceback (most recent call last):
105
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
106
    self.test(*self.arg)
107
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
108
    return t(*(arg + (filename,)), **kw)
109
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad_metalad/tests/test_extract.py", line 53, in test_empty_dataset_error
110
    meta_extract, extractorname="metalad_core")
111
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/unittest/case.py", line 756, in assertRaises
112
    return context.handle('assertRaises', args, kwargs)
113
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/unittest/case.py", line 178, in handle
114
    callable_obj(*args, **kwargs)
115
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 484, in eval_func
116
    return return_func(generator_func)(*args, **kwargs)
117
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 476, in return_func
118
    results = list(results)
119
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 408, in generator_func
120
    allkwargs):
121
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 579, in _process_results
122
    for res in results:
123
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad_metalad/extract.py", line 230, in __call__
124
    source_dataset = check_dataset(dataset or curdir, "extract metadata")
125
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad_metalad/utils.py", line 52, in check_dataset
126
    check_installed=dataset_or_path is not None)
127
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 568, in require_dataset
128
    u"{0}.".format(dataset.path))
129
ValueError: No installed dataset found at /tmp/datalad_temp_test_empty_dataset_errorukltg20b.
```
</details>

but fails exists in other PRs so filed https://github.com/datalad/datalad-metalad/issues/222  .

In principle, this PR is ready for review FWIW.  It doesn't address all file/directory mutation cases, but one fixed is better than none. And I feel that since BF grew into OPT+RF, and "I" was the only affected, I guess I could rebase against `master`.

**Comment by yarikoptic** [comment]
change of base and push of merge somehow confused it so there is no CI run, will resubmit as a new PR

**Pull request closed without merging**
