### PR TITLE
test: refactor test_parallel.py to be abit more pytest'y

### PR DESCRIPTION
**Pull request by yarikoptic**
Got there while working on 
- #7686

### CODE REVIEW

**Comment by yarikoptic** [comment]
appveyor issue is being fixed in
- #7692

**Comment by yarikoptic** [comment]
It was green without changelog entry (besides appveyor, unrelated), but I do not see codecov -- I guess it fell off again :-/

**Comment by yarikoptic** [comment]
trivial PR so I will proceed

**Comment by yarikoptic-gitmate** [comment]
PR released in [`1.1.5`](https://github.com/datalad/datalad/releases/tag/1.1.5)

**Pull request merged**
