### PR TITLE
WiP: dirty draft for alternative paths reporting by default renderer

### PR DESCRIPTION
**Pull request by yarikoptic**
**Warnings**: Don't look at the diff, this is more of a "tech preview", tests guaranteed to fail, diff has unrelated changes etc. Authors of the handbook and/or documentation which hardcoded outputs most likely would start hating me.

Prior attempt was gh-2679 but didn't proceed on that one since then the main problem I was fighting was full paths, and then paths relative to `refds` came to resolve that aspect. I kept running into situations where "relative to refds" made little sense, if not to say that it was misleading since `subds` could differ -- see gh-3442 .  The reason is that although the behavior of "always to refds" is easy to describe, since the actual `refds` is not shown, user is likely to be provided with paths he cannot just cut/paste in majority of the cases IMHO, and would not even know that they are not really such.

So, with this PR output paths would be either relative
- to the CWD
- to the specified dataset, and thus prefixed with an explicit `-d/` prefix (could be anything, but would be nice to have some explicit indication) to signal that.

Behavior: The second case is excercised only if that dataset is outside of the CWD.

Appearance: we could use some other demarkation between the two, e.g. make all relative paths start with `os.curdir` and relative to the dataset not have any `os.curdir` prefix.

<details>
<summary>Here is a demo script which exercises a number of scenarios invoking basic commands with or without `-d` and possibly from within a subdirectory of a dataset</summary> 

```bash
#!/bin/bash

export PS4="> "
set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"

which datalad
datalad --version

set -x
datalad create src
datalad create -d src src/subds
datalad create -d src src/subds/subsubds

(
cd src/subds
touch file
touch subsubds/file

mkdir d1 d2
touch d1/f1 d2/f2
cd d1
datalad save -d^  -r 
#file subsubds/file
)

# now we will try from some very outside directory which has nothing in
# common with the dataset path
mkdir outside

# introduce some changes to the dataset somewhere deep
rm src/subds/d2/f2
touch src/newfile

(
cd outside
datalad save -r -d ../src
)
```
</details>

<details>
<summary>Full output on master</summary> 

```shell
/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin/datalad
datalad 0.12.6.dev611
> datalad create src
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-zHdjBPX/src 
create(ok): /home/yoh/.tmp/dl-zHdjBPX/src (dataset)
> datalad create -d src src/subds
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-zHdjBPX/src/subds 
add(ok): subds (file)
add(ok): .gitmodules (file)
save(ok): . (dataset)
create(ok): subds (dataset)
action summary:
  add (ok: 2)
  create (ok: 1)
  save (ok: 1)
> datalad create -d src src/subds/subsubds
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-zHdjBPX/src/subds/subsubds 
add(ok): subsubds (file)
add(ok): .gitmodules (file)
save(ok): subds (dataset)
add(ok): subds (file)
save(ok): . (dataset)
create(ok): subds/subsubds (dataset)
action summary:
  add (ok: 3)
  create (ok: 1)
  save (ok: 2)
> cd src/subds
> touch file
> touch subsubds/file
> mkdir d1 d2
> touch d1/f1 d2/f2
> cd d1
> datalad save '-d^' -r
add(ok): file (file)
save(ok): subds/subsubds (dataset)
add(ok): subsubds (file)
add(ok): d1/f1 (file)                                                                                            
add(ok): d2/f2 (file)
add(ok): file (file)
save(ok): subds (dataset)
add(ok): subds (file)
save(ok): . (dataset)
action summary:
  add (ok: 6)
  save (ok: 3)
> mkdir outside
> rm src/subds/d2/f2
> touch src/newfile
> cd outside
> datalad save -r -d ../src
delete(ok): d2/f2 (file)
save(ok): subds (dataset)
add(ok): subds (file)
add(ok): newfile (file)                                                                                          
save(ok): . (dataset)
action summary:
  add (ok: 2)
  delete (ok: 1)
  save (notneeded: 1, ok: 2)
bash ../trash/demo-paths.sh  6.36s user 2.32s system 103% cpu 8.372 total
```
</details>

<details>
<summary>Full output on this PR</summary> 

```shell
/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin/datalad
datalad 0.12.6.dev612
> datalad create src
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-Gok1gmK/src 
create(ok): src (dataset)
> datalad create -d src src/subds
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-Gok1gmK/src/subds 
add(ok): src/subds (file)
add(ok): src/.gitmodules (file)
save(ok): src (dataset)
create(ok): src/subds (dataset)
action summary:
  add (ok: 2)
  create (ok: 1)
  save (ok: 1)
> datalad create -d src src/subds/subsubds
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-Gok1gmK/src/subds/subsubds 
add(ok): src/subds/subsubds (file)
add(ok): src/subds/.gitmodules (file)
save(ok): src/subds (dataset)
add(ok): src/subds (file)
save(ok): src (dataset)
create(ok): src/subds/subsubds (dataset)
action summary:
  add (ok: 3)
  create (ok: 1)
  save (ok: 2)
> cd src/subds
> touch file
> touch subsubds/file
> mkdir d1 d2
> touch d1/f1 d2/f2
> cd d1
> datalad save '-d^' -r
add(ok): ../subsubds/file (file)
save(ok): ../subsubds (dataset)
add(ok): ../subsubds (file)
add(ok): f1 (file)                                                                                               
add(ok): ../d2/f2 (file)
add(ok): ../file (file)
save(ok): .. (dataset)
add(ok): .. (file)
save(ok): ../.. (dataset)
action summary:
  add (ok: 6)
  save (ok: 3)
> mkdir outside
> rm src/subds/d2/f2
> touch src/newfile
> cd outside
> datalad save -r -d ../src
delete(ok): -d/subds/d2/f2 (file)
save(ok): -d/subds (dataset)
add(ok): -d/subds (file)
add(ok): -d/newfile (file)                                                                                       
save(ok): -d/. (dataset)
action summary:
  add (ok: 2)
  delete (ok: 1)
  save (notneeded: 1, ok: 2)
bash ../trash/demo-paths.sh  5.91s user 2.00s system 104% cpu 7.599 total
```
</details>

A brief excerpt from the above outputs could be the one where I am saving a number of changes while being in the subdirectory of a dataset:

```
> datalad save '-d^' -r
add(ok): file (file)
save(ok): subds/subsubds (dataset)
add(ok): subsubds (file)
add(ok): d1/f1 (file)                                                                                            
add(ok): d2/f2 (file)
add(ok): file (file)
save(ok): subds (dataset)
add(ok): subds (file)
save(ok): . (dataset)
```
vs
```
> datalad save '-d^' -r
add(ok): ../subsubds/file (file)
save(ok): ../subsubds (dataset)
add(ok): ../subsubds (file)
add(ok): f1 (file)                                                                                               
add(ok): ../d2/f2 (file)
add(ok): ../file (file)
save(ok): .. (dataset)
add(ok): .. (file)
save(ok): ../.. (dataset)
```

Closes gh-3442 (if we get there)

[ci skip]

TODOs:
- [ ] seek feedback and if decided to proceed - may be in some use cases it would make no sense
- [ ] fixup diff to make it sensible
- [ ] fixup tests

### CODE REVIEW

**Comment by kyleam** [comment]
Looking only at the output (as requrested :) and not considering any performance tradeoffs, as a caller I would find the new output preferable in all cases.  The `-d/` is a little odd, but I think it's probably clear enough (or at the very least clear that it's not representing a path relative to the current working directory).

**Comment by yarikoptic** [comment]
thank you @kyleam! 
What about a little improvement idea to avoid odd `-d/`:  Relative paths must be reported with leading `./` or `../`, while paths as relative to the dataset without.  Although less explicit, but if made consistent -- I think it would make total sense as well and as a bonus would be "compatible" with current presentation where it is pretty much the case (there is no leading `./`) just better (be a total path from the top refds).

**Comment by kyleam** [comment]
> Relative paths must be reported with leading `./` or `../`, while paths as relative to the dataset without

I personally would not find that obvious or clear.

**Comment by kyleam** [comment]
> ENH: assure that relpath starts with .


ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure

**Comment by yarikoptic** [comment]
> > Relative paths must be reported with leading `./` or `../`, while paths as relative to the dataset without
> 
> I personally would not find that obvious or clear.

oh, ok.

<details>
<summary> Meanwhile here is a full demo from how it would look like (change in 9b82ae0ce34d9edfa37cc688013e4708e2e56d94)</summary> 

```shell
/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin/datalad
datalad 0.12.6.dev614
> datalad create src
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-WoLWHHa/src 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): ./src (dataset)
> datalad create -d src src/subds
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-WoLWHHa/src/subds 
[INFO   ] Scanning for unlocked files (this may take some time) 
add(ok): ./src/subds (file)
add(ok): ./src/.gitmodules (file)
save(ok): ./src (dataset)
create(ok): ./src/subds (dataset)
action summary:
  add (ok: 2)
  create (ok: 1)
  save (ok: 1)
> datalad create -d src src/subds/subsubds
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-WoLWHHa/src/subds/subsubds 
[INFO   ] Scanning for unlocked files (this may take some time) 
add(ok): ./src/subds/subsubds (file)
add(ok): ./src/subds/.gitmodules (file)
save(ok): ./src/subds (dataset)
add(ok): ./src/subds (file)
save(ok): ./src (dataset)
create(ok): ./src/subds/subsubds (dataset)
action summary:
  add (ok: 3)
  create (ok: 1)
  save (ok: 2)
> cd src/subds
> touch file
> touch subsubds/file
> mkdir d1 d2
> touch d1/f1 d2/f2
> cd d1
> datalad save '-d^' -r
add(ok): ../subsubds/file (file)
save(ok): ../subsubds (dataset)
add(ok): ../subsubds (file)
add(ok): ./f1 (file)                                                                                           
add(ok): ../d2/f2 (file)
add(ok): ../file (file)
save(ok): .. (dataset)
add(ok): .. (file)
save(ok): ../.. (dataset)
action summary:
  add (ok: 6)
  save (ok: 3)
> mkdir outside
> rm src/subds/d2/f2
> touch src/newfile
> cd outside
> datalad save -r -d ../src
delete(ok): subds/d2/f2 (file)
save(ok): subds (dataset)
add(ok): subds (file)
add(ok): newfile (file)                                                                                        
save(ok): . (dataset)
action summary:
  add (ok: 2)
  delete (ok: 1)
  save (notneeded: 1, ok: 2)
```
</details>

with interesting excerpts:
```shell
> datalad save '-d^' -r
add(ok): ../subsubds/file (file)
save(ok): ../subsubds (dataset)
add(ok): ../subsubds (file)
add(ok): ./f1 (file)                                                                                           
add(ok): ../d2/f2 (file)
add(ok): ../file (file)
save(ok): .. (dataset)
add(ok): .. (file)
save(ok): ../.. (dataset)
...
> datalad save -r -d ../src
delete(ok): subds/d2/f2 (file)
save(ok): subds (dataset)
add(ok): subds (file)
add(ok): newfile (file)                                                                                        
save(ok): . (dataset)
```
alternative, at some point we excercised an idea (issue #findout) of using `//` as the indicator for dataset boundary.  So if we go "prefix" route, it could be used instead of `-d/` for a possibly a bit less awkward presentation (I still think we might introduce `//` into urls treatment)

**Comment by yarikoptic** [comment]
> > ENH: assure that relpath starts with .
> 
> ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure ensure

I assure you I will ensure eventually! ;-)

**Comment by mih** [comment]
I think this generally makes sense, and improves the status quo. However, I do not subscribe to the idea that relative paths have to be reported under all circumstances.  In particular, I think it will feel weird rather quickly if I have a Python script that juggles multiple dataset objects, and reports results. We had previous issues with paths like `../../../../../long/path/down/to/the/dataset/...`.

What do you think about mirroring the special-casing of dataset object method calls for path resolution? IOW report absolut paths when a dataset method is called?

**Comment by yarikoptic** [comment]
> I think this generally makes sense, and improves the status quo. However, I do not subscribe to the idea that relative paths have to be reported under all circumstances. In particular, I think it will feel weird rather quickly if I have a Python script that juggles multiple dataset objects, and reports results. We had previous issues with paths like `../../../../../long/path/down/to/the/dataset/...`.

IMHO this might still quite ok.  This would happen only if I invoking the command while being that deep in the dataset (e.g. while referencing the top with `-d^` or just have really heavy in directories dataset) while intending to save something (everything?) in the OTHER subdataset(s) (folders) reachable from the top under `long/path/...` .  Note that you would be getting similar paths if you run `git status` in case of that deeply nested directories in a repository.  It would give me (user) a perspective on how far away from my current location my actions take an effect.

> What do you think about mirroring the special-casing of dataset object method calls for path resolution? IOW report absolut paths when a dataset method is called?

I am really not sure about absolute paths in the reports...  We had them and moved away since they quickly lead to overwhelming the output...
I also had in mind an idea about somehow visualizing the "top level path" in cases where it is not a curdir (i.e. when listing from the top of the specified elsewhere refds) - pretty much disclosing that `-d/` is actually `/some/path/which/was/specified/explicitely/on/the/commandline`, something like

```
hint(-d/): /some/path/which/was/specified/explicitely/on/the/commandline (dataset)
delete(ok): -d/subds/d2/f2 (file)
save(ok): -d/subds (dataset)
add(ok): -d/subds (file)
```

**Comment by mih** [comment]
Ok, given your response, I think you should ignore what I said before, because I am likely not getting it. Here is my scenario:

We have common datasets in places like `/data/project/name/someds`. I tend to run code directly after logging into a machine, hence `CWD == $HOME`. If that code runs `Dataset('/data/projects/name/someds').status()`  would it not use paths like

`../../data/projects/name/someds/...`

instead of just

`/data/projects/name/someds/...`

If that is the case, I am now sure how this statement from above applies:

> IMHO this might still quite ok. This would happen only if I invoking the command while being that deep in the dataset (e.g. while referencing the top with -d^ or just have really heavy in directories dataset) while intending to save something (everything?) in the OTHER subdataset(s) (folders) reachable from the top under long/path/... . Note that you would be getting similar paths if you run git status in case of that deeply nested directories in a repository. It would give me (user) a perspective on how far away from my current location my actions take an effect.

The comparison to `git status` isn't really relevant here. This is a cmdline tool with no notion of a repository object.

**Comment by yarikoptic** [comment]
> We have common datasets in places like `/data/project/name/someds`. I tend to run code directly after logging into a machine, hence `CWD == $HOME`. If that code runs `Dataset('/data/projects/name/someds').status()` would it not use paths like
> 
> `../../data/projects/name/someds/...`
> 
> instead of just
> 
> `/data/projects/name/someds/...`

ATM with the last commit it should produce just paths, without leading `./`under that location unless your home is somewhere along the `/data/projects/name/someds/` path or the entire `/` is a datalad dataset ;-)  In the original version, all of those would be prefixed with `-d/` (click to expand full example in the original post).

> The comparison to `git status` isn't really relevant here. This is a cmdline tool with no notion of a repository object.

As long as we are using `git` and at times claim that "datalad is a thin wrapper on top of git and git-annex` IMHO comparisons to git are relevant. Also `git` has clear notion of a repository object, just a single one.

**Comment by yarikoptic** [comment]
I have pushed fixes to make "forced ./" prefixed paths correctly behave in case of path already with leading `.` or `..`.  But only now I have arrived to the [same conclusion](https://github.com/datalad/datalad/pull/4454#issuecomment-623662115) as @kyleam that `./` prefixed vs not might be not a good idea.  Use case is simple -- `.` ;-)  we wouldn't be able to tell if that is a top path of the "outside dataset" (e.g. for `-d ../src` example) or current path.  So I guess I will get back to `-d/` idea.  
I am still thinking about the "hint" (or may be INFO log message?) or may be instead of `-d/` to just use `//` as indicator for a dataset boundary as I had mentioned it before.  Pushed a change for that as well on top, so now we have a full set to choose from ;)  So for that case, of referencing path within external dataset (the others are still as nice as before ;)), it would look like

```shell
> datalad save -r -d ../src
delete(ok): //subds/d2/f2 (file)
save(ok): //subds (dataset)
add(ok): //subds (file)
add(ok): //newfile (file)                                                                                      
save(ok): //. (dataset)
```
The last one is a bit odd, but  decided to not touch it otherwise I think it might be a winner in my eyes.

**Comment by yarikoptic** [comment]
> Use case is simple -- `.` ;-) we wouldn't be able to tell if that is a top path of the "outside dataset" (e.g. for `-d ../src` example) or current path

although it could be `.` vs `./` ;)

**Comment by mih** [comment]
FTR: Here is what I see in Python:

```
In [3]: ds=dl.Dataset('/tmp/pathrep')                                                                                        

In [4]: ds.create(force=True)                                                                                                
[INFO   ] Creating a new annex repo at /tmp/pathrep 
[INFO   ] Scanning for unlocked files (this may take some time) 
Out[4]: Dataset(/tmp/pathrep)

In [5]: ds.save(recursive=True)                                                                                              
Out[5]:                                                                                                                      
[{'action': 'add',
  'path': '/tmp/pathrep/sub',
  'type': 'file',
  'refds': '/tmp/pathrep',
  'status': 'ok',
  'key': None,
  'reportwd': Dataset(/tmp/pathrep)},
 {'action': 'add',
  'path': '/tmp/pathrep/.gitmodules',
  'type': 'file',
  'refds': '/tmp/pathrep',
  'status': 'ok',
  'key': None,
  'reportwd': Dataset(/tmp/pathrep)},
 {'action': 'add',
  'path': '/tmp/pathrep/mike',
  'type': 'file',
  'refds': '/tmp/pathrep',
  'status': 'ok',
  'message': '',
  'key': 'MD5E-s0--d41d8cd98f00b204e9800998ecf8427e',
  'reportwd': Dataset(/tmp/pathrep)},
 {'action': 'add',
  'path': '/tmp/pathrep/this',
  'type': 'file',
  'refds': '/tmp/pathrep',
  'status': 'ok',
  'message': '',
  'key': 'MD5E-s0--d41d8cd98f00b204e9800998ecf8427e',
  'reportwd': Dataset(/tmp/pathrep)},
 {'action': 'save',
  'type': 'dataset',
  'path': '/tmp/pathrep',
  'refds': '/tmp/pathrep',
  'status': 'ok',
  'reportwd': Dataset(/tmp/pathrep)}]
```

`reportwd` is fully redundant with `refds`. I think the latter should be removed. Its only purpose was reporting (AFAIK), and that is obsolete with this change.

One more thought: Given that `reportwd` is only for internal reporting purposes, should be somehow indicate that (e.g. `_reportwd`)? Or should we generalize the property and label it something like `context` (to indicate the context which a result originated from)?

**Comment by yarikoptic** [comment]
> reportwd is fully redundant with refds

May be ... refds is always a string and I believe logic is different where it is a string or dataset instance. Also I felt that there is some other use of refds. Could check later in more detail or feel welcome to RF add you see fit

**Comment by mih** [comment]
I looked at this PR again, because it is listed as a preconditon for 0.14.0.

My only additional thought to what was said before is re `-d`: I think this is a symbol for a reference dataset, that is intended to be self-evident from the context of an execution. It might be worth considering a non-shell-like symbol to make it more compatible with other execution contexts. Maybe as simple as `<ds>`?

**Comment by mih** [comment]
Closing this after 6+ months of inactivity.

**Pull request closed without merging**
