### PR TITLE
WiP (BK):  tried to make test repos persistent across runs of the tests

### PR DESCRIPTION
**Pull request by yarikoptic**
was a few days already since I have tried and IIRC at that point there were some tests which would fail since them or other tests do in place modifications in those tests, so we would need to catch those few cases and in those case do clean clones or smth like that 

but this could be a start ;)

### CODE REVIEW

**Comment by bpoldrack** [comment]
I absolutely agree on this issue needs to be solved. I'm just not sure, whether this PR is supposed to solve anything regarding the issue or just introduce versioning of testrepos.

**Comment by bpoldrack** [comment]
Plus: Is this actually work in progress?

**Comment by yarikoptic** [comment]
it is .... may be we should make a new label WiBB (work in back burner) though... when I have tried, I have ran into some tests which obviously relied on assumption that they could modify test repos in place, which made a side-effect ruining subsequent test(s).  so what was left IIRC is to identify those tests and fix them up

**Comment by yarikoptic** [comment]
superseded by #1899

**Pull request closed without merging**
