### PR TITLE
Don't move .coverage out of __testhome__

### LINKED ISSUE #4956: Bring back combining coverage reports from special remotes
Discovered in the course of https://github.com/datalad/datalad/pull/4955/files that we fail to merge coverage reports from special remotes:  https://travis-ci.org/github/datalad/datalad/jobs/729780153#L2438
```
6.32s$ if [ -z "${_DL_CRON:-}" ]; then cp __testhome__/.coverage .; coverage combine -a /tmp/.coverage-entrypoints-*; codecov; fi
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/coverage", line 8, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/cmdline.py", line 865, in main
    status = CoverageScript().command_line(argv)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/cmdline.py", line 588, in command_line
    self.coverage.combine(data_dirs, strict=True)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/control.py", line 696, in combine
    combine_parallel_data(self._data, aliases=aliases, data_paths=data_paths, strict=strict)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/data.py", line 117, in combine_parallel_data
    data.update(new_data, aliases=aliases)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/sqldata.py", line 706, in update
    for (file, context), numbits in lines.items()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/sqldata.py", line 706, in <listcomp>
    for (file, context), numbits in lines.items()
KeyError: '/home/travis/build/datalad/datalad/datalad/api.py'
```

so that step fails and we just submit main coverage.

@jwodder - since you dealt with coverage reporting recently, could you please also have a look at this, more obscure case as well?  I have not yet tried to reproduce locally etc.  Look into .travis.yml for more pointers on how we do it (helper scripts etc)

### PR DESCRIPTION
**Pull request by jwodder**
Fixes #4956.

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo -- thanks! Let's see how it goes!

**Comment by yarikoptic** [comment]
I really cannot make sense of 
```
@@            Coverage Diff             @@
##            maint    #4965      +/-   ##
==========================================
+ Coverage   89.47%   89.59%   +0.11%     
==========================================
  Files         289      292       +3     
  Lines       40716    39628    -1088     
==========================================
- Hits        36432    35505     -927     
+ Misses       4284     4123     -161  
```
report.  It says that coverage increases, but also not only that misses went down but also hits!?  I can only guess it is  due to some kind of effect of may be previously files identity was confused due to a moved .coverage file and relative paths inside the coverage file.

Overall I think we should just proceed assuming that "now it is better than before".

**Comment by yarikoptic** [comment]
any further ideas (or a "Merge") @mih @kyleam @bpoldrack ?

**Comment by kyleam** [comment]
> Overall I think we should just proceed assuming that "now it is better than before".

That's fine with me.

**Pull request merged**
