### PR TITLE
ENH: duecredit support for citing datalad itself AND datasets it opens

### LINKED ISSUE #2065: Add duecredit support/entry
#### What is the problem?
I thought we already have it but apparently not.  For now at least we should add a basic support to cite ourselves.
Later on, ideally, we should `.cite` any dataset which gets installed/accessed if it has reference information.  We haven't looked into standardizing/harmonizing that information yet AFAIK, did we?

### PR DESCRIPTION
**Pull request by yarikoptic**
This pull request fixes #2065 - those eyes didn't let me sleep! I will blame @tyarkoni for anything to come.
- includes support for actually DueCrediting any dataset we "instantiate"
- ATM just ad-hoc extraction of metadata fields from `bids` and `datacite` (for CRCNS) records. Proper solution will need integration with extractors or some other harmonization which we do not have ATM
- Relies on changes yet to be merged/released in DueCredit: https://github.com/duecredit/duecredit/pull/144
   - basic support for free text citations (so we could at least point to those datasets etc)
   - access to `due.active`

With those changes and this PR, we are getting smth like:
```shell
> rm .duecredit.p; DUECREDIT_ENABLE=1 datalad ls ~/datalad/openfmri/ds000241 /home/yoh/datalad/crcns/aa-1                                                                        
/home/yoh/datalad/openfmri/ds000241   [annex]  master  1.0.0+1-2-g6bb6937 2018-06-08/07:44:21  ✓
/home/yoh/datalad/crcns/aa-1   [annex]  master  ✗ 2018-06-08/10:23:47  ✓

DueCredit Report:
- DataLad - Data management and distribution platform / datalad (v 0.11.3.dev22) [1]
  - Single-unit recordings from two auditory areas in male zebra finches / datalad:77271f9e (v 1.0) [2]
  - AK6: Animal Kingdom; 6 Species / datalad:f7ccf78c (v 1.0.0+1-2-g6bb6937) [3]

1 package cited
0 modules cited
2 functions cited

References
----------

[1] Visconti di Oleggio Castello, M. et al., 2019. datalad/datalad 0.11.3.
[2] Theunissen, F.E. et al., 2009. Single-unit recordings from two auditory areas in male zebra finches.
[3] Please cite: 'Connolly, A. C., J. S. Guntupalli, J. Gors, M. Hanke, Y. O. Halchenko, Y.-C. Wu, H. Abdi, and J. V. Haxby. The Representation of Biological Classes in the Human Brain. Journal of Neuroscience 32.8 (2012): 2608-618.' and include the following message: 'This data was obtained from the OpenfMRI database. Its accession number is ds000241'
```

```shell
$> duecredit summary --format bibtex              
@misc{https://doi.org/10.5281/zenodo.808846,
  doi = {10.5281/zenodo.808846},
  url = {https://zenodo.org/record/808846},
  author = {Visconti di Oleggio Castello, Matteo and Halchenko, Yaroslav O. and Hanke, Michael and Poldrack, Benjamin and Meyer, Kyle and Solanky, Debanjum Singh and Alteva, Gergana and Gors, Jason and MacFarlane, Dave and Olaf Häusler, Christian and Olson, Taylor and Waite, Alex and De La Vega, Alejandro and Sochat, Vanessa and Keshavan, Anisha and Ma, Feilong and Christian, Horea and Poelen, Jorrit and Skytén, Kusti and Visconti di Oleggio Castello, Matteo and Hardcastle, Nell and Stoeter, Torsten and C Lau, Vicky},
  keywords = {data version control, data distribution, execution provenance tracking},
  title = {datalad/datalad 0.11.3},
  publisher = {Zenodo},
  year = {2019}
}
@misc{https://doi.org/10.6080/k0f769gp,
  doi = {10.6080/k0f769gp},
  url = {http://crcns.org/data-sets/aa/aa-1},
  author = {Theunissen, Frederic E. and Hauber, ME and Woolley, Sarah M. N. and Gill, Patrick and Shaevitz, SS and Amin, Noopur and Hsu, A and Singh, NC and Grace, GA and Fremouw, Thane and Zhang, Junli and Cassey, P and Doupe, AJ and David, SV and Vinje, WE},
  keywords = {Neuroscience, Electrophysiology, auditory area, avian (zebra finch)},
  language = {eng},
  title = {Single-unit recordings from two auditory areas in male zebra finches},
  publisher = {CRCNS.org},
  year = {2009}
}
2019-02-28 23:40:55,436 [WARNING] Failed to generate bibtex for Text(u"Please cite: 'Connolly, A. C., J. S. Guntupalli, J. Gors, M. Hanke, Y. O. Halchenko, Y.-C. Wu, H. Abdi, and J. V. Haxby. The Representation of Biological Classes in the Human Brain. Journal of Neuroscience 32.8 (2012): 2608-618.' and include the following message: 'This data was obtained from the OpenfMRI database. Its accession number is ds000241'", key=u"please cite: 'connolly, a. c., j. s. guntupalli, j. gors, m. hanke, y. o. halchenko, y.-c. wu, h. abdi, and j. v. haxby. the representation of biological classes in the human brain. journal of neuroscience 32.8 (2012): 2608-618.' and include the following message: 'this data was obtained from the openfmri database. its accession number is ds000241'") (io.py:383)
```

Would be fun to see it output for a real use case with Python analysis script which uses DataLad to get the data -- have any in mind? ;)

### TODOs
- [x] Basic unit- or integration/smoke test

Please have a look @datalad/developers

### CODE REVIEW

**Comment by yarikoptic** [comment]
this could cause some disturbance, so I will not rush to merge it without feedback/review

**Comment by yarikoptic** [comment]
but feedback would be welcome so I do not just keep dealing with conflicts (attn: @mih @kyleam )

**Comment by yarikoptic** [comment]
Note sure how/if
<details>
<summary>appveyor failure</summary>

```
Versions: appdirs=1.4.3 boto=2.49.0 cmd:annex=7.20190219-g728228d5d cmd:git=2.17.1.windows.2 cmd:system-git=2.17.1.windows.2 cmd:system-ssh=7.7p1 git=2.1.11 gitdb=2.0.5 humanize=0.5.1 iso8601=0.1.12 keyring=18.0.0 keyrings.alt=3.1.1 msgpack=0.6.1 requests=2.21.0 six=1.12.0 tqdm=4.31.1 wrapt=1.11.1
Obscure filename: str=b' ;abc' repr=' ;abc'
Encodings: default='utf-8' filesystem='mbcs' locale.prefered='cp1252'
Environment: PATH='C:\\Miniconda35\\envs\\test-environment\\Library\\bin;C:\\Miniconda35\\envs\\test-environment;C:\\Miniconda35\\envs\\test-environment\\Library\\mingw-w64\\bin;C:\\Miniconda35\\envs\\test-environment\\Library\\usr\\bin;C:\\Miniconda35\\envs\\test-environment\\Library\\bin;C:\\Miniconda35\\envs\\test-environment\\Scripts;C:\\Miniconda35;C:\\Miniconda35\\Scripts;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\Perl\\site\\bin;C:\\Perl\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\7-Zip;C:\\Program Files\\Microsoft\\Web Platform Installer\\;C:\\Tools\\GitVersion;C:\\Tools\\PsTools;C:\\Program Files\\Git LFS;C:\\Program Files (x86)\\Subversion\\bin;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\ManagementStudio\\;C:\\Tools\\WebDriver;C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.4\\;C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\IDE\\PrivateAssemblies\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\wbin;C:\\Ruby193\\bin;C:\\Tools\\NUnit\\bin;C:\\Tools\\xUnit;C:\\Tools\\MSpec;C:\\Tools\\Coverity\\bin;C:\\Program Files (x86)\\CMake\\bin;C:\\go\\bin;C:\\Program Files\\Java\\jdk1.8.0\\bin;C:\\Python27;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\iojs;C:\\Program Files\\iojs;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;C:\\Tools\\NuGet;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files\\Microsoft DNX\\Dnvm;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Apache\\Maven\\bin;C:\\Python27\\Scripts;C:\\Tools\\NUnit3;C:\\Program Files\\Mercurial\\;C:\\Program Files\\dotnet\\;C:\\Tools\\curl\\bin;C:\\Program Files\\Amazon\\AWSCLI\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\SQLDB\\DAC\\140;C:\\Tools\\vcpkg;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files\\erl9.2\\bin;C:\\Program Files (x86)\\NSIS;C:\\Tools\\Octopus;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Microsoft Service Fabric\\bin\\Fabric\\Fabric.Code;C:\\Program Files\\Microsoft SDKs\\Service Fabric\\Tools\\ServiceFabricLocalClusterManager;C:\\Program Files\\LLVM\\bin;C:\\Program Files (x86)\\Yarn\\bin\\;C:\\Users\\appveyor\\AppData\\Roaming\\npm;C:\\Program Files\\PowerShell\\6\\;C:\\Program Files (x86)\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\appveyor\\.dotnet\\tools;C:\\Users\\appveyor\\AppData\\Local\\Yarn\\bin;C:\\Users\\appveyor\\AppData\\Roaming\\npm;C:\\Program Files\\AppVeyor\\BuildAgent\\' PYTHON_VERSION='3.5.1' PYTHON_ARCH='32' PYTHON='C:\\Python35' GIT_LFS_PATH='C:\\Program Files\\Git LFS'
SKIP: Skipping on Windows
======================================================================
FAIL: datalad.distribution.tests.test_clone.test_clone_crcns
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1244, in assert_status
    assert_in(r['status'], label)
  File "C:\Miniconda35\envs\test-environment\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Miniconda35\envs\test-environment\lib\unittest\case.py", line 665, in fail
    raise self.failureException(msg)
AssertionError: 'error' not found in ['ok']
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 849, in newfunc
    return func(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 109, in __call__
    function, args, kwargs
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_clone.py", line 90, in test_clone_crcns
    assert_status('ok', res)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1250, in assert_status
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Test 1/1: expected status ['ok'] not found in:
[
 {
  "message": [
   "Failed to clone from any candidate source URL. Encountered errors per each url were: %s",
   [
    {
     "http://datasets-tests.datalad.org/": "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v http://datasets-tests.datalad.org/ C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_hxu7v5t2\\all-nonrecursive [cmd.py:wait:415]",
     "http://datasets-tests.datalad.org/.git": "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v http://datasets-tests.datalad.org/.git C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_hxu7v5t2\\all-nonrecursive [cmd.py:wait:415]"
    }
   ]
  ],
  "source_url": "///",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_hxu7v5t2\\all-nonrecursive",
  "action": "install",
  "type": "dataset",
  "status": "error"
 }
]
```
</details>
is related

**Comment by kyleam** [comment]
> this could cause some disturbance

Could you elaborate?  

I know nothing about duecredit, but it looks like you guard against failing with duecredit-related erros.  So perhaps you're talking about performance concerns, but I'd guess that should be negligible when duecredit isn't enabled.

I'm surprised that this much code is needed inside datalad itself, but again I know nothing about duecredit.  I don't have any real objection to this change.

**Comment by yarikoptic** [comment]
> > this could cause some disturbance
> 
> Could you elaborate?

Largely it is just my personal paranoia.  duecredit import is indeed guarded tightly in the `due.py` stub, since the idea of duecredit to not cause the entire 'parent' project to blow if something fails in duecredit.  So far such cases were really rare (but not that many projects use durecredit yet).  I do not think there should be any measurable performance concern unless duecredit is enabled (set `DUECREDIT_ENABLE=1` env var) - then it will impact performance notably due to all the import introspection injections etc.  Actually for the fun of it (may be even for CRON_ run) I should run a single matrix run with `DUECREDIT_ENABLE`.

Disturbance might come also at the packaging/installation stage now that I am thinking about it. 
`duecredit` has few a bit heavy/unpleasant dependencies which is not a problem on debian, but might cause some irritation when installing via pip... so may be I should move it into a section of its own, so typically it wouldn't get installed when installing datalad via pip or conda... will do that shortly

> I'm surprised that this much code is needed inside datalad itself, but again I know nothing about duecredit. I don't have any real objection to this change.

Well, to just take advantage of duecredit to get datalad cited if someone uses datalad and instantiates at least a single GitRepo - it is just the `due.py` copied from duecredit and a single call to `due.cite`. But in this PR I went further to realize the long lasting dream (and somewhat of an initial excuse for duecredit) - to cite DataLad datasets used in the analysis pipelines.  That required that additional code.  Whenever there would be some "harmonized" metadata that code could use - portions of code could go away.

Sure thing there could probably be a `datalad-duecredit` extension which would overload `Dataset` class to provide this single call out.

**Comment by yarikoptic** [comment]
Ok, I guess I will just proceed forward with this one

**Pull request merged**
