### PR TITLE
datalad_core _get_content_metadata - shouldn't it provide paths for all (annexed and not) files?

### PR DESCRIPTION
**Pull request by mih**
#### What is the problem?
initially ran into within https://github.com/datalad/datalad/pull/2190
https://travis-ci.org/datalad/datalad/jobs/342624112#L3010

apparently a basic test starts to fail in direct mode that for some reason in that repository `git annex metadata` does not return empty entries  for the annexed files queried.
But looking at the code I have also realized that because git annex metadata doesn't return any metadata for non-annexed files, no entries will be returned for them either.  But whenever repo is just a pure GitRepo we do return empty entries for each file.
So there is this discrepancy in behavior it seems

For now I will just mark it as failing in direct in #2190 and proceed

### CODE REVIEW

**Comment by mih** [comment]
OK, I will retract that patch. Doing it this way (in low-level code) would mean that I would have to emulate git annex behavior for arbitrary commands. Doing it one level up (in the extractor), I know much better what kind of path arguments will be coming in.

**Comment by mih** [comment]
I won't be able to work on this. And I cannot turn this back into an issue, and it would be wrong to close it. @bpoldrack do you want to take a look at a low-level solution?

**Comment by yarikoptic** [comment]
@bpoldrack - any thoughts on this one which could help us out?

**Comment by mih** [comment]
This is now done properly, with proper semantic markup in -revolution.

**Pull request closed without merging**
