### PR TITLE
Move timeout processing out of exception handler processing

### LINKED ISSUE #7229: Various tests fail on occasion with timeout
Example:
https://ci.appveyor.com/project/mih/datalad/builds/45679300/job/x31hi28vfjn0et99#L2636

This failure is happening with different tests, IIRC, but not reliably. Rerunning the build usually does "solve" it.

@christian-monch: Can you have a look? I think you've addressed this somewhere, but I fail to find it.

### PR DESCRIPTION
**Pull request by christian-monch**
Fixes #7229 

This PR moves the timeout processing in ThreadedRunner out of the `Empty`-exception handler. This is done to prevent raising a `TimeoutError`-exception while handling an `Empty`-exception.

### CODE REVIEW

**Comment by christian-monch** [comment]
appveyor ubuntu errors are due to problems installing `git-annex` via `deb`-tools

**Review by bpoldrack — COMMENTED** [review]
@christian-monch: I may miss something here, but to me it's not clear that this addresses #7229.
It seems to me, that test is failing because there is an unexpected timeout in `response = bc("import time; print('a')")`. That the exception comes with a `__context__` (during handling of ...) doesn't look like a problem to me.

If that's wrong, can you elaborate?

**Comment by christian-monch** [comment]
> @christian-monch: I may miss something here, but to me it's not clear that this addresses #7229. It seems to me, that test is failing because there is an unexpected timeout in `response = bc("import time; print('a')")`. That the exception comes with a `__context__` (during handling of ...) doesn't look like a problem to me.
> 
> If that's wrong, can you elaborate?

The timeout is expected. That is actually what we test for. The issue is that it is raised within a function that is ultimatively called by the Empty-handler in the old `nonasyncrunner.py:627`. That leas to the issue that an exception is raised while another exception is currently handled.

A similar thing could happen in the CommandError handler in the old "cmd.py:544" because when python is shutting down, the log call would trigger an exception. That is usually caught and hidden, but becomes visible within the CommandError-handler. This actually poses the question: "how many log calls do we have in exception handlers where we expect an interpreter shutdown?"

**Comment by christian-monch** [comment]
> @christian-monch: I may miss something here, but to me it's not clear that this addresses #7229. It seems to me, that test is failing because there is an unexpected timeout in `response = bc("import time; print('a')")`. That the exception comes with a `__context__` (during handling of ...) doesn't look like a problem to me.
> 
> If that's wrong, can you elaborate?

You are right. The timeout is actually expected, I just assumed it would not show during the first call. It is a race condition though and depending on the scheduling, it might. So let me fix the patch

**Pull request merged**
