### PR TITLE
ENH+BF: NFS testing on travis + Dataset.close()

### PR DESCRIPTION
**Pull request by yarikoptic**
as NFS testing revealed -- there is an issue with some outstanding git cat-file batched processes held up by GitRepo's which belong to Datasets.  Uninstalling implies that those GitRepo's should disappear, thus as a quick solution I have introduced `Dataset.close` which for now was used only in `uninstall`.

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm... ignoring of failed run somehow doesn't work... may be because of `"`  or ...?

**Comment by yarikoptic** [comment]
## bad news
ignoring failures didn't work

## (somewhat) good news:
there is only 1 failure:
```shell

======================================================================
ERROR: datalad.distribution.tests.test_uninstall.test_uninstall_subdataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 706, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 536, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_uninstall.py", line 187, in test_uninstall_subdataset
    res = ds.uninstall(path=subds_path)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 566, in apply_func
    return f(**kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/uninstall.py", line 272, in __call__
    _uninstall_dataset(ds, check=check, has_super=True))
  File "/home/travis/build/datalad/datalad/datalad/distribution/uninstall.py", line 70, in _uninstall_dataset
    rmtree(ds.path)
  File "/home/travis/build/datalad/datalad/datalad/utils.py", line 283, in rmtree
    shutil.rmtree(path, *args, **kwargs)
  File "/opt/python/2.7.12/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/opt/python/2.7.12/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/opt/python/2.7.12/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/opt/python/2.7.12/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/opt/python/2.7.12/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 2/.git/objects/pack'
-------------------- >> begin captured logging << --------------------
datalad.cmd: ERROR: Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', '[DATALAD] auto-saved changes', u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 1'] under u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 1'. Exit code=1. out=On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
 err=
datalad.cmd: ERROR: Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', '[DATALAD] auto-saved changes', u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 2'] under u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 2'. Exit code=1. out=On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
 err=
datalad.cmd: ERROR: Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', '[DATALAD] auto-saved changes', u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 1'] under u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 1'. Exit code=1. out=On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
 err=
datalad.cmd: ERROR: Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', '[DATALAD] auto-saved changes', u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 2'] under u'/tmp/nfsmount/datalad_temp_test_uninstall_subdatasetr2KyrP/subm 2'. Exit code=1. out=On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
 err=
```

It is only `somewhat` good news **because   there is only one failure** -- I was expecting more since I kept running into various awkward problems and I thought that we are exercising enough.  I will try to see what is going on in the failing test

**Comment by yarikoptic** [comment]
## good news
replicated locally
## somewhat bad news
it took forever, while largely nothing was happening:
```
nosetests -s -v   11.31s user 4.94s system 10% cpu 2:30.17 total
```
so over 2 and 1/2 minutes to run a failing test, which generally takes 
```
TMPDIR=/tmp/ nosetests -s -v   9.09s user 2.82s system 41% cpu 28.888 total
```
well -- which is not fast either but still... I guess some locking mechanisms etc is based on lengthy waits and polls

**Comment by mih** [comment]
Wouldn't it make sense to call `ds.repo.precommit()`

**Comment by yarikoptic** [comment]
@mih
I think I have tried precommit but it wasn't effective since it is not about our batched processes, but batched ls-files ran by GitPython

**Comment by yarikoptic** [comment]
hm -- new failed test which is probably not related to my fix :-/ but could be related to operating under NFS.  So far -- couldn't replicate locally
```shell
======================================================================
FAIL: datalad.tests.test_auto.test_proxying_open_nibabel(<function generate_nii at 0x7fcb3db409b0>, <function verify_nii at 0x7fcb34e66578>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 536, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/test_auto.py", line 109, in _test_proxying_open
    verify_load(fpath1)
  File "/home/travis/build/datalad/datalad/datalad/tests/test_auto.py", line 195, in verify_nii
    ok_(np.all(ni.get_data() == d))

AssertionError: None
```

**Comment by bpoldrack** [comment]
FTR: Yes, `del repo` is supposed to close these GitPython processes, while `repo.precommit()` isn't.

But: The `GitRepo` instance might be used with other `Dataset` instances as well. So, if it is only about closing these, `ds.repo..repo.git.clear_cache()` would do it without killing the `GitRepo` instance.

**Comment by yarikoptic** [comment]
> But: The GitRepo instance might be used with other Dataset instances as well. 

interesting... what would be the value of them since here we are talking about `uninstall/remove` operation -- so the actual repository would be gone from the drive and IIRC we do not maintain *Repo's which do not have physical presence any longer.  So it feels like removing those, even if bound to other Datasets should be correct course of action -- not sure though on ramifications though. One way or another I feel that something would fail if we still have a rogue Repo..
otherwise I would have merged it for now ;)

**Comment by bpoldrack** [comment]
Well, for now it's probably okay as is. In theory the uninstalled Dataset could be subdataset, which is a symlink to the repo, which in return is a "real" (sub-)dataset elsewhere. In that case uninstall should remove the symlinked thing but keep the original. In such a setup there would be two Datasets with the same underlying GitRepo and the second one would still be valid.
But this possibilty is probably not implemented yet in uninstall anyway. So I'm fine with a merge.

**Comment by yarikoptic** [comment]
> Dataset could be subdataset, which is a symlink to the repo

Do we anyhow support this use case in our API or manually created/installed?

**Comment by yarikoptic** [comment]
merging for the progress and safer NFS operations

**Comment by bpoldrack** [comment]
We don't actually support it via API anyhow, I think. But with the RF'ing of Dataset and Repos (flyweights), they are able to cover such a situation now. So, no - that's why merge is okay, but yes-ish - the foundation is layed out. :-)

**Comment by yarikoptic** [comment]
> they are able to cover such a situation now.

not supported, not tested... so should be said "they might be able to cover such a situation now." ;)

**Pull request merged**
