### PR TITLE
push: Assume 0 bytes pushed if git-annex does not provide bytesize

### PR DESCRIPTION
**Pull request by yarikoptic**
Otherwise we can get KeyError and underlying code can provide records without bytesize. Reported in https://neurostars.org/t/datalad-push-causes-keyerror-bytesize-keyerror/23570 with 

datalad==0.15.4
git==2.35.0
git-annex==8.20210903

<details>
<summary>first I failed to reproduce with the following script following user report with --fast</summary> 

```shell
#!/bin/bash
# https://neurostars.org/t/datalad-push-causes-keyerror-bytesize-keyerror/23570
set -eu

cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
set -eu

datalad create -f .

git annex addurl --fast --file sample3.csv https://filesamples.com/samples/document/csv/sample3.csv
datalad save sample3.csv

git remote add --fetch gin git@gin.g-node.org:/yarikoptic/test-push.git
datalad -l debug push --to gin

```
</details>

<details>
<summary>but then reproduced nicely with --relaxed</summary> 

```shell
#!/bin/bash
# https://neurostars.org/t/datalad-push-causes-keyerror-bytesize-keyerror/23570
set -eu

cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
set -eu

datalad create -f .

git annex addurl --relaxed --file sample3.csv https://filesamples.com/samples/document/csv/sample3.csv
datalad save sample3.csv

ls -l 

git remote add --fetch gin git@gin.g-node.org:/yarikoptic/test-push.git
datalad push --to gin --force=all
```
</details>

and verified that with this PR we do not crash.  Given that git-annex unlikely to even provide progress report if not enough time passed, I think I would not bother crafting a unittest which would trigger this condition atm.

### CODE REVIEW

**Comment by yarikoptic** [comment]
uff all travis fails seems to be due to unrelated 

```
____________________________ test_run_datalad_help _____________________________
[gw0] linux -- Python 3.8.6 /tmp/dl-miniconda-q9fqns6s/bin/python
    @assert_cwd_unchanged
    def test_run_datalad_help():
        out, err = check_run_and_get_output("datalad --help")
        ok_startswith(out, "Usage: ")
        # There could be a warning from coverage that no data was collected, should be benign
        lines = [l for l in err.split(os.linesep) if ('no-data-collected' not in l) and l]
>       eq_(lines, [])
../datalad/tests/test_installed.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
first = ["/tmp/dl-miniconda-q9fqns6s/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 ...ported version!", '  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn\'t match a supported "']
second = [], msg = None
    def assert_equal(first, second, msg=None):
        if msg is None:
>           assert first == second
E           assert ['/tmp/dl-min... supported "'] == []
E             Left contains 2 more items, first extra item: "/tmp/dl-miniconda-q9fqns6s/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!"
E             Full diff:
E               [
E             -  ,
E             +  '/tmp/dl-miniconda-q9fqns6s/lib/python3.8/site-packages/requests/__init__.py:102: '
E             +  'RequestsDependencyWarning: urllib3 (1.26.8) or chardet '
E             +  "(5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!",
E             +  '  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) '
E             +  'doesn\'t match a supported "',
E               ]
../datalad/tests/utils_pytest.py:107: AssertionError
```

so may be it was too early for 0f27cd5045883d814b27cb7d678449a98323f768 in #7029 ?

**Comment by yarikoptic** [comment]
no objections, the fix is trivial, let's proceed and retry releasing again!

**Comment by yarikoptic** [comment]
@jwodder -- note that here as well we didn't have github actions ran and changelog entry was pushed by github-actions bot although I thought we should have switched to that yarikoptic-gitmate token/account... will need to check/keep an eye...

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.6`](https://github.com/datalad/datalad/releases/tag/0.17.6)

**Pull request merged**
