### PR TITLE
WiP RF: bring revolution home

### LINKED ISSUE #2926: Bring revolution home?
#### What is the problem?
What is your plan @mih about the https://github.com/datalad/datalad-revolution ?  To keep it as a separate extension for eternity or bring pieces (or entirety) into datalad codebase for perspective future possibly API breaking release?  
As I expressed myself, reviewing those changes is not easy and thus largely is not done. As I stated before, IMHO having them even in `master` branch (aiming e.g. for 0.11 release), while possibly still carrying out bugfixing in 0.10.x branch would be IMHO more preferable long term.

edits to outline steps to see this issue resolved:
- [x] establish `rf-revolution1` branch to contain initial changes
- [x] remove direct mode (#3036) - merge into `rf-revolution1`. WiP
    - [ ] go through leftover '# TODO: RM DIRECT' to see if anything else could/should be removed/refactored
    - [ ] add dedicated tests for handling situations when a repository in direct mode is encountered (directly by AnnexRepo or as a submodule) and assure a consistent/informative blow up
- Workflow for changes propagation
   - [ ] (`rf-revolution1-3rd` branch) bring in revolution code base into the core under 3rd/datalad_revolution (TODO: tools/injest_revolution_code to be reused to suck in the changes)
   - [ ] (`rf-revolution1` branch, to keep merging `rf-revolution1-3rd`) `git mv 3rd/datalad_revolution/datalad_revolution datalad/revolution` (verify that tests pass, needs relative imports)
   - [ ] move out pieces from `datalad/revolution/`  around the core, where needed prefixing with `rev_`
        - [ ] move our `*repo.py` to `core_*repo.py`, while having revolution ones replace ours, while importing the `core_` ones
- [ ] establish rel-0.11 branch to absorb relevant fixes (if possible - submit fixes against that branch when applicable)
- [ ] finalize #3108 and merge into rf-revolution1
- [ ] merge `rf-revolution1` into `master`
- [ ] extend core *Repo classes with the API from revolution
- [ ] investigate mechanism to by default disable "experimental" revolution API within core datalad (config setting `datalad.experimental.revolution` to be enabled by extensions before importing API etc?)
- [ ] **compare intentions/usecases/convergence for the API [google doc API Use-cases convergence: 1st Revolution](https://docs.google.com/spreadsheets/d/1bi3AQK5yMKwTA_6FN1oCPnIGASy9VmN8LbARr15XMKE/edit?usp=sharing)**
- [ ] ...
- [ ] make sure no rev_ files, and no Rev classes are left

### PR DESCRIPTION
**Pull request by yarikoptic**
This pull request fixes #2926 

There is a long road ahead, that issue should provide details on what to be done.

1. This branch should receive periodic merges of `master` branch.  It will be merged into `master` whenever all checkboxes are marked "done".
2. If new changes from revolution to be introduced, bring them in into rf-revolution1-3rd branch first, using `tools/injest-revolution` or better `datalad rerun -m "Injest XXX from revolution" _run_revolution_injest`, where `_run_revolution_injest` is a tag available in this repo pointing to initial injestion invocation (see also #3074 about `--explicit` which you might need)
3. This (rf-revolution1) branch should always be ready to be merged into master, so not for adding broken new features to it.  It is recommended to bring new changes to this branch via a PR (i.e. to be merged into `rf-revolution1` branch)

- [x] no direct mode support
- [x] absorbed datalad-revolution as `datalad.revolution`
- [x] datalad.revolution.tests pass
    - [x] on appveyor
    - [x] on travis: remaining issue seems to be solely reporting of paths from repos that are accessed through a symlink. At first glance everything is actually happening as it should, but the reported `path` has the true location of a file, not the linked path. Needs a careful look what should happen in each of the four situations.
- [x] bring in replacement for `diff` from https://github.com/datalad/datalad-revolution/pull/58
- [ ] RF -core to use -revolution pieces and decide on how "joint" API should look like - checkboxes in #2926

### CODE REVIEW

**Comment by yarikoptic** [comment]
Question: Is there a way somehow to disable running tests on `push` for both appveyor and travis?

**Comment by yarikoptic** [comment]
Sweet, @kyleam ! And it would be possible to move stuff out of it, and git would track that as if it was just a part of the repo, right? Ie there is no magical annotation of some kind to make those subtrees special?
Do you think it is worthwhile to revert and redo?

**Comment by kyleam** [comment]
> And it would be possible to move stuff out of it, and git would track that as if it was just a part of the repo, right? Ie there is no magical annotation of some kind to make those subtrees special?

Right, nothing makes them different from git's perspective. They are special only in `git-subtree`s eyes (e.g., the git-subtree-split metadata in the commit message).

> Do you think it is worthwhile to revert and redo?

Oh, I think either way is fine.  I definitely wasn't posting that as a "you should have done it this way", just when I saw it I thought "that'd work nicely with git-subtree".

**Comment by yarikoptic** [comment]
eh @mih, I think the [plead](1513499bfeb432cd57be81e6a2b0640a3b996f50) didn't help and now time is waiting

**Comment by yarikoptic** [comment]
actually the plead ended up irrelevant (although I think worth re-consideration), the fix is proposed in https://github.com/datalad/datalad-revolution/pull/61 and then I will propagate it here

**Comment by yarikoptic** [comment]
Next need to deal with documentation (happen someone wakes up earlier)
```
pickling environment... done
checking consistency... 
Warning, treated as error:
/home/travis/build/datalad/datalad/docs/source/generated/man/datalad-rev-create.rst:document isn't included in any toctree
make: *** [html] Error 2
```

**Comment by mih** [comment]
FTR: Replicated all remaining failures in https://github.com/datalad/datalad-revolution/pull/62

**Comment by mih** [comment]
Bunch of fixes pushed to https://github.com/datalad/datalad-revolution/pull/62

**Comment by mih** [comment]
I think I have fixed all these issues (and a few more) in -revolution. This PR can be updated.

**Comment by yarikoptic** [comment]
Thanks @mih.  I will do that now.
Note that you should have all super-powers to progress this PR forward without waiting for lazy West to wake up

**Comment by yarikoptic** [comment]
FTR here is my sequence of commands (distilled and tuned up with `&&` to be fetchable
```
git checkout rf-revolution1-3rd && git pull --ff-only  \
&& datalad rerun -m "Injest fixes from mih" _run_revolution_injest \
&& git checkout rf-revolution1  && git pull --ff-only \
&& git merge rf-revolution1-3rd \
&& git push origin rf-revolution1-3rd rf-revolution1
```
note that since we (datalad) fail to work with workdirs - I run it in a full clone

**Comment by mih** [comment]
Travis did not run for some reason.

**Comment by yarikoptic** [comment]
indeed... Also appveyor failed strangely with
```
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--version', '6']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--version', '6'] under 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_4ss_z80e'. Exit code=1.
```
I will rewrite/push again.

**Comment by yarikoptic** [comment]
look at it -- all green! awesome!  whoohoo

**Comment by mih** [comment]
Feel the revolution!

**Comment by yarikoptic** [comment]
I would say merge/resolve repeatedly still for a while until we agree on how to unify the API and actually start using revolution pieces in the core. Until then it would be just two alien things brought together

**Comment by mih** [comment]
You mean "merge into this branch" or "merge into master"?

**Comment by yarikoptic** [comment]
I've clarified (hopefully) in 1.2.3 in the top message

**Comment by mih** [comment]
Hmm, ok. So development has to stay in the extension code base until these API decisions are made (who will make them?). Until then there seems little benefit of keeping this branch up-to-date.

**Comment by kyleam** [comment]
@yarikoptic Did you intend to push the current tip of yarikoptic/rf-revolution1 (e06ba3bdc) to origin/rf-revolution1 (d1d7e76a4)?  The yarikoptic/ one is from gh-3108, but I see it has advanced since then and now contains a resolution of the datalad/customremotes/tests/test_archives.py conflict.

**Comment by yarikoptic** [comment]
Oh, I forgot that this one is on the origin, and my branch I guess is configured now to push to my fork. Please feel welcome to push it here or I will do it later

Cheers

**Comment by kyleam** [comment]
> Oh, I forgot that this one is on the origin, and my branch I guess is configured now to push to my fork. Please feel welcome to push it here or I will do it later

Thanks for confirming.  Pushed.

**Comment by mih** [comment]
If I got it right, the importer script takes all of -revolution and places it into -core. I think it would be more productive to limit this to everything BUT metadata/

All metadata stuff is not cooked enough and will see changes and additions leading up to a resolution of https://github.com/datalad/datalad-revolution/issues/54

**Comment by kyleam** [comment]
> If I got it right, the importer script takes all of -revolution and places it into -core. I think it would be more productive to limit this to everything BUT metadata/

For this PR, the -revolution pieces end up under datalad/revolution/ but aren't actually being integrated.

**Comment by kyleam** [comment]
But, as you may have suspected, it's more complicated because `revolution.metadata.extractors.tests.test_custom.test_custom` isn't happy with this revolution/ structure (because the lack of an entry point in core's setup.py, and maybe other things).  Indeed maybe the best thing to do would to prune revolution/metadata/, but for now I'll just mark that test as a known failure.

**Comment by kyleam** [comment]
I've merged master to deal with a trivial conflict.  

@yarikoptic, IIRC there is nothing left to do in this "remove indirect/take in but do not wire up revolution" phase.  Once tests pass, should we merge this to master so that the indirect mode removal starts getting some exposure/testing?

**Comment by yarikoptic** [comment]
I've pushed a PR for crawler https://github.com/datalad/datalad-crawler/pull/36 which should make it "compatible" with "no direct supported", so in principle we should be good to go if master with the revolution is our goal ;)  when we merge it into master, let's start 0.11.x branch from preceding it commit.

**Comment by kyleam** [comment]
> I've pushed a PR for crawler datalad/datalad-crawler#36 

Thanks.

>  so in principle we should be good to go if master with the revolution is our goal ;)

I'm not sure what to make of this.  Has something changed?  I know @mih has said several times that he is fine either way, but in the last video chat I thought the plan was to move forward with the merge, initially to the point where revolution's GitRepo/AnnexRepo/Dataset replace core's but eventually to where the extension is essentially an entry point wrapper for revolution.

> when we merge it into master, let's start 0.11.x branch from preceding it commit

Of course (though I'd prefer to call it `maint` :)

**Comment by kyleam** [comment]
The next phase would be "wire up Revolution{GitRepo,AnnexRepo,Dataset}".  I've got this done locally and tests pass.  (ATM I do this by adjusting imports, but that is just temporary.)  After this PR is merged, I plan to actually replace GitRepo/AnnexRepo/Dataset with the revolution equivalent and then submitting two PRs: one to datalad core with the additions and one to the revolution extension that removes its gitrepo.py/annexrepo.py/dataset.py in favor of core's.

**Comment by mih** [comment]
Made obsolete by merge of #3225

**Pull request closed without merging**
