### PR TITLE
BF+RF: tollerate spaces (and probably other interesting characters) in filenames

### LINKED ISSUE #673: ssh/create-publication-target fails for a dataset with space in its name
```
2016-07-24 23:06:54,200 [INFO   ] Creating target dataset crawl/indi/fcon1000/Cleveland CCF at /srv/datasets.datalad.org/www/indi/fcon1000/Cleveland CCF (create_publication_target_sshwebserver.py:217)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.2.3', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 234, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 285, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/create_publication_target_sshwebserver.py", line 223, in __call__
    out, err = ssh(["ls", path])
  File "/home/yoh/proj/datalad/datalad/datalad/support/sshconnector.py", line 87, in __call__
    return self.runner.run(ssh_cmd, expect_fail=True, expect_stderr=True)
  File "/home/yoh/proj/datalad/datalad/datalad/cmd.py", line 297, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
CommandError: CommandError: command '['ssh', '-o', u'ControlPath=/home/yoh/.config/datalad/datasets.datalad.org', u'datasets.datalad.org', 'ls', u'/srv/datasets.datalad.org/www/indi/fcon1000/Cleveland CCF']' failed with exitcode 2.
Failed to run ['ssh', '-o', u'ControlPath=/home/yoh/.config/datalad/datasets.datalad.org', u'datasets.datalad.org', 'ls', u'/srv/datasets.datalad.org/www/indi/fcon1000/Cleveland CCF'] under None. Exit code=2. out= err=ls: cannot access /srv/datasets.datalad.org/www/indi/fcon1000/Cleveland: No such file or directory
ls: cannot access CCF: No such file or directory

()
> /home/yoh/proj/datalad/datalad/datalad/cmd.py(297)run()
-> raise CommandError(str(cmd), msg, status, out[0], out[1])
```

 under-tested... ideally use some most obfuscated filename

### PR DESCRIPTION
**Pull request by yarikoptic**
Should probably close #673 and #691, #696

The best way to test that most of the commands can tolerate spaces, was to make our tests repos (submodules) have spaces in their names.  Also made them somewhat unique so later we could quickly RF possibly to add more obscurity etc

### CODE REVIEW

**Comment by hanke** [comment]
Maybe we should go one step further and put non-ascii chars in the names, a proper French word, or even some Chinese unicode?

**Comment by yarikoptic** [comment]
On Wed, 10 Aug 2016, Michael Hanke wrote:

>    Maybe we should go one step further and put non-ascii chars in the names,
>    a proper French word, or even some Chinese unicode?

yes -- that would be lovely.  But I will leave it for another
issue/assignee -- I had a lovely evening due to spaces along already ;)

**Comment by hanke** [comment]
Seems one of the tests should acknowledge a "no network" condition. Otherwise this has my blessing ;-)

**Comment by hanke** [comment]
Travis failure is due to #699

**Pull request merged**
