### PR TITLE
ENH: add message parameter to install

### PR DESCRIPTION
**Pull request by adswa**
This PR tries to do what I outline in #3882  and allows to provide a (optional) commit message for the installation of a subdataset.

TODO
- [ ] add tests should the general idea of this PR be sensible

### CODE REVIEW

**Comment by adswa** [comment]
I suspected that it would be part of a way bigger issue, and that the changes I did in here are rather tackling specific symptoms than the general issue. Your view involves concepts/functions that (to me ;-) ) are *very* complex and wide-ranging, so I'm afraid I can't really engage in a discussion/grasp the overall scope, but take #3882 and this PR as an affirmation that I'd appreciate the possibility to attach more commit messages. :) I don't want to stifle any discussion by closing this, but please feel free to close this, anyone!

**Comment by mih** [comment]
@adswa Not so fast! I just expressed my view on this issue. And we have always sported a diversity of views in this project. Let's see what the conclusion will be.

**Comment by yarikoptic** [comment]
> we have to make it for `create` as well.

I would say "it would be nice to" instead of "have to"

> expose --message, what about -F/--message-file?

Absence of `-F` shouldn't hold `-m` a hostage.  But ideally indeed it should be provided alongside with adding `-m` since `save` has it already.  So there should be a helper to handle those flags uniformly across commands which would absorb

```python
        if message and message_file:
            raise ValueError("Both a message and message file were specified")

        if message_file:
            with open(message_file, "rb") as mfh:
                message = assure_unicode(mfh.read())
```
from current save.

> what we are really missing is to expose Git's own behavior when messages are needed/helpful #3101

I don't think it is a panacea here.  It might be confusing to the user to get messages for sub-operations of multi-commit operations datalad might do.  
And it is IMHO largely orthogonal to being able to specify message from the command line (I use `-m` more than the editor way, which I keep for longer commit messages). 

> * we should consider changing `create` and `install` to not modify a superdataset, because it multiplexes a secondary functionality onto `-d/--dataset` which is hard to comprehend and keep in mind (cannot find the issue with that discussion, sorry)

on one hand I am somewhat agreeing that it would contribute to the purity of DataLad, but then see myself cursing you later for now requiring to run two commands, and often just duplicating the same long paths to re-specify the same `-d pathtodataset pathtosubdataset`.  It would also would be a very notable breakage of behavior and would require any user/downstream to adjust their workflows.  So, not sure if such pains are really worth the purity.
  
NB `install` still has `--nosave` which would pretty much do what you intend here, but `create` lacks it.

So, overall, I would vote to proceed forward with this one ;)

**Comment by mih** [comment]
Fate and further progress depends on resolution of #3896

**Comment by mih** [comment]
Conclusion of yesterday's call is to go ahead with such a change, but do it in a coordinated fashion that leads to any command that modifies a dataset to get a `--message` option, and just this one option for any message related functionality. There was a general tendency to postpone any such changes to after a now imminent 0.12 release.

**Comment by yarikoptic** [comment]
I would have voted to re-open this PR:  No coordinated fashion happened, we are past 0.14.0, I wouldn't keep it as hostage of #3896 (whatever happens for `save` if does, could be adopted for `install`), and `install` was the first one I stumbled upon again just now while trying to provide a message.

**Pull request closed without merging**
