### PR TITLE
BF: Complain if a nonexistent dataset is given to subdatasets()

### PR DESCRIPTION
**Pull request by mih**
or if there is no dataset to query. But retain the previous behavior when called as a bound method of a Dataset instance. The compromise is made to avoid gh-3938 while retaining internal assumptions about the behavior of the command.

Fixes gh-3938

### CODE REVIEW

**Comment by mih** [comment]
Thx @kyleam this provides me sufficient motivation to explore a proper change!

**Comment by mih** [comment]
@kyleam Found the bug in `get()` and hopefully fixed it. Let's see what the tests think.

**Comment by kyleam** [comment]
> @kyleam Found the bug in `get()` and hopefully fixed it. Let's see what the tests think.

Great, thanks.  All the tests seem happy.

The change from 4dd3cd09d (BF: Prevent recursion attempt into uninstalled subdatasets) looks right.  I got a bit mixed up locally when trying to review it.  I think there should be at least one test that fails without that commit, but I was able to find it.

**Comment by mih** [comment]
The test failure that you are looking for was introduced by the core change in this PR: 2713b4a

Here is the resulting failure:

```
(datalad3-dev) mih@meiner ~ % python -m nose -v -s datalad.distribution.tests.test_install:test_install_skip_failed_recursive
datalad.distribution.tests.test_install.test_install_skip_failed_recursive ... ERROR
Versions: appdirs=1.4.3 boto=2.49.0 cmd:annex=7.20191017 cmd:bundled-git=2.23.0 cmd:git=2.23.0 cmd:system-git=2.23.0 cmd:system-ssh=7.9p1 git=2.1.12 gitdb=0.6.4 humanize=0.5.1 iso8601=0.1.12 keyring=19.0.2 keyrings.alt=3.1.1 msgpack=0.6.1 requests=2.22.0 scrapy=1.7.3 tqdm=4.32.2 wrapt=1.11.2
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='en_US.UTF-8' LANGUAGE='en_US:en' PATH='/home/mih/env/datalad3-dev/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/mih/bin:/home/mih/bin/pycharm/bin' GIT_EDITOR='vim' LC_CTYPE='en_US.UTF-8' GIT_PYTHON_GIT_EXECUTABLE='/usr/bin/git'

======================================================================
ERROR: datalad.distribution.tests.test_install.test_install_skip_failed_recursive
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 778, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 602, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/distribution/tests/test_install.py", line 711, in test_install_skip_failed_recursive
    on_failure='ignore', result_xfm=None)
  File "/home/mih/hacking/datalad/git/datalad/distribution/dataset.py", line 526, in apply_func
    return f(**kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 520, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 508, in return_func
    results = list(results)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 442, in generator_func
    result_log_level, **_kwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 551, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/distribution/get.py", line 697, in __call__
    description):
  File "/home/mih/hacking/datalad/git/datalad/distribution/get.py", line 493, in _install_targetpath
    description=description):
  File "/home/mih/hacking/datalad/git/datalad/distribution/get.py", line 397, in _recursive_install_subds_underneath
    refds_path=refds_path):
  File "/home/mih/hacking/datalad/git/datalad/distribution/get.py", line 367, in _recursive_install_subds_underneath
    result_renderer='disabled'):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 442, in generator_func
    result_log_level, **_kwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 551, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/local/subdatasets.py", line 228, in __call__
    dataset, check_installed=True, purpose='subdataset reporting/modification')
  File "/home/mih/hacking/datalad/git/datalad/distribution/dataset.py", line 602, in require_dataset
    u"{0}.".format(dataset.path))
ValueError: No installed dataset found at /tmp/datalad_temp_test_install_skip_failed_recursivexdfsm4ur/subm 1.
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: DEBUG: Maximal length of cmdline string (adjusted for safety margin): 1048576
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '/usr/bin' (no adjustments to PATH if empty string)
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<TextIOWrapper>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 12.877s

FAILED (errors=1)
```

This fix for that failure is 4dd3cd09d070eeba73673018c74be46cc58316ce

**Pull request merged**
