### PR TITLE
TEMP: try most recent release of annex on conda-forge on maint

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
eh heh heh,
```
 git-annex-8.20201007       |alldep_h75db294_101        12.9 MB  conda-forge
```
either
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```
or 
<details>
<summary>errors=31, failures=1</summary> 

some selection
```shell
======================================================================
3741ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_ssh_fetch
3742----------------------------------------------------------------------
3743Traceback (most recent call last):
3744  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
3745    self.test(*self.arg)
3746  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 197, in _wrap_skip_if_on_windows
3747    return func(*args, **kwargs)
3748  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 271, in _wrap_skip_ssh
3749    return func(*args, **kwargs)
3750  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 290, in _wrap_skip_nomultiplex_ssh
3751    return func(*args, **kwargs)
3752  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 1090, in _wrap_with_testrepos
3753    t(*(arg + (uri,)), **kw)
3754  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3755    return t(*(arg + (filename,)), **kw)
3756  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/tests/test_gitrepo.py", line 551, in test_GitRepo_ssh_fetch
3757    fetched = repo.fetch(remote="ssh-remote")
3758  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2290, in fetch
3759    return list(
3760  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2301, in fetch_
3761    yield from self._fetch_push_helper(
3762  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2503, in _fetch_push_helper
3763    out = GitWitlessRunner(cwd=self.path).run(
3764  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/cmd.py", line 505, in run
3765    raise CommandError(
3766datalad.support.exceptions.CommandError: CommandError: 'git fetch --verbose --progress ssh-remote' failed with exitcode 128 under /tmp/datalad_temp_test_GitRepo_ssh_fetchwphemmrh [err: 'Bad owner or permissions on /home/travis/.ssh/config
3767ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/tmp/datalad_temp_dqcesvf6/.cache/datalad/sockets/bbfef380 datalad-test' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]
3768fatal: Could not read from remote repository.
3769
3770Please make sure you have the correct access rights
3771and the repository exists.']
3772
3773======================================================================
3774ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_ssh_pull
3775----------------------------------------------------------------------
3776Traceback (most recent call last):
3777  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
3778    self.test(*self.arg)
3779  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 197, in _wrap_skip_if_on_windows
3780    return func(*args, **kwargs)
3781  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 271, in _wrap_skip_ssh
3782    return func(*args, **kwargs)
3783  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 290, in _wrap_skip_nomultiplex_ssh
3784    return func(*args, **kwargs)
3785  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3786    return t(*(arg + (filename,)), **kw)
3787  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3788    return t(*(arg + (filename,)), **kw)
3789  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/tests/test_gitrepo.py", line 593, in test_GitRepo_ssh_pull
3790    repo.pull(remote="ssh-remote", refspec=remote_repo.get_active_branch())
3791  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2364, in pull
3792    GitWitlessRunner(cwd=self.path).run(
3793  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/cmd.py", line 505, in run
3794    raise CommandError(
3795datalad.support.exceptions.CommandError: CommandError: 'git pull --progress ssh-remote ssh-test' failed with exitcode 1 under /tmp/datalad_temp_test_GitRepo_ssh_pullc84nbrte [err: 'warning: Pulling without specifying how to reconcile divergent branches is
3796discouraged. You can squelch this message by running one of the following
3797commands sometime before your next pull:
3798
3799  git config pull.rebase false  # merge (the default strategy)
3800  git config pull.rebase true   # rebase
3801  git config pull.ff only       # fast-forward only
3802
3803You can replace "git config" with "git config --global" to set a default
3804preference for all repositories. You can also pass --rebase, --no-rebase,
3805or --ff-only on the command line to override the configured default per
3806invocation.
3807
3808Bad owner or permissions on /home/travis/.ssh/config
3809ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/tmp/datalad_temp_dqcesvf6/.cache/datalad/sockets/bbfef380 datalad-test' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]
3810fatal: Could not read from remote repository.
3811
3812Please make sure you have the correct access rights
3813and the repository exists.']
3814
3815======================================================================
3816ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_ssh_push
3817----------------------------------------------------------------------
3818Traceback (most recent call last):
3819  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
3820    self.test(*self.arg)
3821  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 197, in _wrap_skip_if_on_windows
3822    return func(*args, **kwargs)
3823  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 271, in _wrap_skip_ssh
3824    return func(*args, **kwargs)
3825  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 290, in _wrap_skip_nomultiplex_ssh
3826    return func(*args, **kwargs)
3827  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3828    return t(*(arg + (filename,)), **kw)
3829  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3830    return t(*(arg + (filename,)), **kw)
3831  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/tests/test_gitrepo.py", line 632, in test_GitRepo_ssh_push
3832    pushed = list(repo.push(remote="ssh-remote", refspec="ssh-test"))
3833  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2394, in push
3834    return list(
3835  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2405, in push_
3836    yield from self._fetch_push_helper(
3837  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2503, in _fetch_push_helper
3838    out = GitWitlessRunner(cwd=self.path).run(
3839  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/cmd.py", line 505, in run
3840    raise CommandError(
3841datalad.support.exceptions.CommandError: CommandError: 'git push --progress --porcelain ssh-remote ssh-test' failed with exitcode 128 under /tmp/datalad_temp_test_GitRepo_ssh_push51fd8ibj [err: 'Bad owner or permissions on /home/travis/.ssh/config
3842ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/tmp/datalad_temp_dqcesvf6/.cache/datalad/sockets/bbfef380 datalad-test' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]
3843fatal: Could not read from remote repository.
3844
3845Please make sure you have the correct access rights
3846and the repository exists.']
3847
3848======================================================================
3849FAIL: datalad.core.distributed.tests.test_clone.test_reckless(True,)
3850----------------------------------------------------------------------
3851Traceback (most recent call last):
3852  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
3853    self.test(*self.arg)
3854  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3855    return t(*(arg + (filename,)), **kw)
3856  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3857    return t(*(arg + (filename,)), **kw)
3858  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
3859    return t(*(arg + (filename,)), **kw)
3860  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/core/distributed/tests/test_clone.py", line 366, in check_reckless
3861    nok_((ds.pathobj / '.git' / 'annex' / 'index.lck').stat().st_mode \
3862AssertionError: 16 is not false
```
</details>

seems most are due to

```
datalad.support.exceptions.CommandError: CommandError: 'git annex find -c annex.dotfiles=true -c 'remote.ssh-remote-1.annex-ssh-options=-o ControlMaster=auto -S /home/travis/.cache/datalad/sockets/bbfef380' -c annex.retry=3 --json --json-error-messages --in . --not --in ssh-remote-1 -- foo' failed with exitcode 1 under /tmp/datalad_temp_test_annex_ssh2pasci_a/main [err: 'Unable to parse git config from ssh-remote-1
Bad owner or permissions on /home/travis/.ssh/config
ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/tmp/datalad_temp_dqcesvf6/.cache/datalad/sockets/bbfef380 datalad-test' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
git-annex: cannot determine uuid for ssh-remote-1 (perhaps you need to run "git annex sync"?)']
```
but if it was ssh's config issue -- why now with this new git-annex? anyways -- pushed 255709b55f93430d64fe10822c589295d63bc34f to possibly see that.

also, since we are "commercial travis" now - theoretically (haven't tried for years) we could gain an interactive session IIRC.

**Comment by yarikoptic** [comment]
woohoo -- after permissions fix (still not sure why now and not before) -- only a single consistently present failing test: https://github.com/datalad/datalad/issues/5206 . So if that one is addressed we might be getting a new candidate git-annex version to declare datalad-stable ;)

**Comment by yarikoptic** [comment]
actually let me run it against most recent standalone build we have to see may be it was something addressed on annex side since back then

**Comment by yarikoptic** [comment]
eh heh, still running heavy debug one but
- some stall (`The job exceeded the maximum time limit for jobs, and has been terminated.`)

<details>
<summary>some fail including the failure above. Interestingly one is failing on "file_has_content" which was escaping issue in recent PR</summary> 

```shell
======================================================================
ERROR: datalad.customremotes.tests.test_archives.test_annex_get_from_subdir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 573, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/customremotes/tests/test_archives.py", line 179, in test_annex_get_from_subdir
    runner(['git', 'annex', 'get', '--', fn_in_archive_obscure])   # run git annex get
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/cmd.py", line 600, in __call__
    return self.run(cmd, *args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/cmd.py", line 962, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: 'git annex get -- ' |;&%b5{}'"'"'"ΔЙקم๗あ .datc '' failed with exitcode 1 [out: 'get  |;&%b5{}'"ΔЙקم๗あ .datc  (from datalad-archives...) 
  Unable to access these remotes: datalad-archives
  Try making some of these remotes available:
  	c04eb54b-4b4e-5755-8436-866b043170fa -- [datalad-archives]
failed'] [err: '/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s171--7f8038465a5fa037738d165e371e1a79.tar.gz'] [archives.py:_transfer:407]
git-annex: get: 1 failed']
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_reckless(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/core/distributed/tests/test_clone.py", line 367, in check_reckless
    & stat.S_IWGRP)
AssertionError: 16 is not false
======================================================================
FAIL: datalad.customremotes.tests.test_archives.test_basic_scenario
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 573, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/customremotes/tests/test_archives.py", line 125, in test_basic_scenario
    assert_true(annex.file_has_content(fn_extracted))
AssertionError: False is not true
```
</details>
- some succeed 
- note: this is a standalone build, not the conda's "proper", so might be contributing somehow
- life is hard

**Comment by kyleam** [comment]
Thanks for revisiting this.

> actually let me run it against most recent standalone build
> [...]
> some fail including the failure above

This probably isn't worth much given the datalad/git-annex builds are passing with the latest annex, but I ran these three with the same block of exports (`DATALAD_TESTS_OBSCURE_PREFIX`, ...) using a git-annex built from the same commit as the snapshot you used (8.20201117-ga314537cd) and wasn't able to trigger any failures locally.

**Comment by yarikoptic** [comment]
> This probably isn't worth much given the datalad/git-annex builds are passing with the latest annex

unfortunately travis (setup or VMs, or file system) is special somehow apparently :-/

**Comment by yarikoptic** [comment]
- yep - umask was culprit for #5206 - separate PR will come
- stalls are inconsistent, here is the selection from different runs

```
datalad.interface.tests.test_add_archive_content.TestAddArchiveOptions.test_add_delete_after_and_drop ... 
datalad.interface.tests.test_annotate_paths.test_get_modified_subpaths ... 
datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,) ... 
```
- detailed debug one was terminated since log was too long :-/

- remaining two failing tests in https://travis-ci.com/github/datalad/datalad/jobs/455111394 run

<details>
<summary>failing</summary> 

```shell
======================================================================
ERROR: datalad.customremotes.tests.test_archives.test_annex_get_from_subdir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 573, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/customremotes/tests/test_archives.py", line 179, in test_annex_get_from_subdir
    runner(['git', 'annex', 'get', '--', fn_in_archive_obscure])   # run git annex get
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/cmd.py", line 600, in __call__
    return self.run(cmd, *args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/cmd.py", line 962, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: 'git annex get -- ' |;&%b5{}'"'"'"ΔЙקم๗あ .datc '' failed with exitcode 1 [out: 'get  |;&%b5{}'"ΔЙקم๗あ .datc  (from datalad-archives...) 
  Unable to access these remotes: datalad-archives
  Try making some of these remotes available:
  	c04eb54b-4b4e-5755-8436-866b043170fa -- [datalad-archives]
failed'] [err: '/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s171--b8c51765339447b9cc07b25cd4e184d0.tar.gz'] [archives.py:_transfer:407]
git-annex: get: 1 failed']
======================================================================
FAIL: datalad.customremotes.tests.test_archives.test_basic_scenario
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 573, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/customremotes/tests/test_archives.py", line 125, in test_basic_scenario
    assert_true(annex.file_has_content(fn_extracted))
AssertionError: False is not true
```

test_basic_scenario also failed in https://travis-ci.com/github/datalad/datalad/jobs/455111397
</details>

**Comment by yarikoptic** [comment]
as @kyleam kindly pointed out -- those two first are not stalling but ran out of time.  The only one hanging is on NFS run:
```
datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,) ...
```
I will try now conda back again that we have fixed the others

**Comment by yarikoptic** [comment]
oh hoh -- look how green it is! cherish the moment!  I will now submit a PR for master with similar action, to see how well we are there...

**Pull request closed without merging**
