### PR TITLE
RF extensions github action to centralize configuration for extensions etc, use pytest for crawler

### PR DESCRIPTION
**Pull request by yarikoptic**
Also adjusted condition, since anything which is != something, could be anything else
to match so no need for that hirni comparison afaik

### CODE REVIEW

**Comment by yarikoptic** [comment]
damn it --how did I miss that in crawler own CI... will need to figure out/account for

```
__________________ ERROR collecting nodes/tests/test_annex.py __________________
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/datalad_crawler/nodes/tests/test_annex.py:17: in <module>
    from ..annex import initiate_dataset
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/datalad_crawler/nodes/annex.py:28: in <module>
    from datalad.version import __version__
../datalad/version.py:[20](https://github.com/datalad/datalad/runs/7661038459?check_suite_focus=true#step:14:21): in <module>
    DeprecationWarning)
E   DeprecationWarning: datalad.version module will be removed in 0.16. Please use datalad.__version__ (no other __*_version__ variables are to be provided).
```

**Comment by yarikoptic** [comment]
ok -- getting there

- neuroimaging -- need to look why those fail here (and presumably not in prior setup) - look like 2 legit test fails
- pytest testing of metalad works! which is odd since:
- pytest testing of crawler errors out  with `Couldn't read 'tox.ini' as a config file` suggesting that coverage looks for it in curdir and not using it from `../__extension__/tox.ini` as I have provided. But how come it works for metalad. @jwodder -- any hidden knowledge or something obvious I am missing?

<details>
<summary>full output from the run for crawler</summary> 

```shell
cd __testhome__
  python -m pytest -c ../__extension__/tox.ini -s -v --cov=datalad --pyargs ${DL_PACKAGE}
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:3).7.13/x6[4](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:4)
    DL_PIP_INSTALLS: mock
    DL_REPO: datalad/datalad-crawler
    DL_TESTER: pytest
    DL_NEED_SINGULARITY: 
    DL_PACKAGE: datalad_crawler
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/runpy.py", line 8[5](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:5), in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.7.13/x[6](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:6)4/lib/python3.[7](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:7)/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1[8](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:8)7, in console_main
    code = main()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/_pytest/config/__init__.py", line 325, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_callers.py", line 3[9](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:9), in _multicall
    res = hook_impl.function(*args)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/_pytest/config/__init__.py", line [10](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:10)16, in pytest_cmdline_parse
    self.parse(args)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/_pytest/config/__init__.py", line [12](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:13)07, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/opt/hostedtoolcache/Python/3.7.[13](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:14)/x64/lib/python3.7/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pytest_cov/plugin.py", line [14](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:15)9, in pytest_load_initial_conftests
    plugin = CovPlugin(options, early_config.pluginmanager)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pytest_cov/plugin.py", line [20](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:21)0, in __init__
    self.start(engine.Central)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pytest_cov/plugin.py", line 222, in start
    self.cov_controller.start()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
    return meth(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pytest_cov/engine.py", line [21](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:22)2, in start
    config_file=self.cov_config)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/coverage/control.py", line [25](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:26)2, in __init__
    concurrency=concurrency, context=context,
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/coverage/config.py", line [56](https://github.com/datalad/datalad/runs/7674076733?check_suite_focus=true#step:13:57)5, in read_coverage_config
    raise ConfigError(f"Couldn't read {fname!r} as a config file")
coverage.exceptions.ConfigError: Couldn't read 'tox.ini' as a config file
Error: Process completed with exit code 1.
```
</details>

**Comment by jwodder** [comment]
@yarikoptic Based on the traceback, it looks like `coverage` (not pytest) is unable to find any coverage-specific configuration in `tox.ini` for the failing extension.

**Comment by yarikoptic** [comment]
> @yarikoptic Based on the traceback, it looks like `coverage` (not pytest) is unable to find any coverage-specific configuration in `tox.ini` for the failing extension.

ok. But why it is even looking into absent tox.ini locally...? anyways -- it seems it gets worked around by symlinking extension's tox.ini into that directory and using that one. Now I just need to address neuroimaging failing tests I guess.

**Comment by yarikoptic** [comment]
actually to resolve mystery -- the reason is due to use of that relative path within tox.ini of the -crawler extension for coverage! 

```
(git)lena:~datalad/datalad-crawler[no-deprecated]git
$> grep -B4 tox.ini tox.ini
addopts =
    --cov=datalad_crawler
    # Explicitly setting the path to the coverage config file is necessary due
    # to some tests spawning subprocesses with changed working directories.
    --cov-config=tox.ini
```

wil test now using `={toxinidir}/tox.ini`!

**Comment by yarikoptic** [comment]
ok, tox magic didn't help but we reached green state, so i rewrote for shorter history and now without TEMP commits -- ready for review/merge!

**Comment by yarikoptic** [comment]
I would like to bring CI into totally green/legit setup, so will proceed with this merge, and prepare merge of maint into master.  Comments would still be welcome if someone comes from a vacation ;)

**Pull request merged**
