### PR TITLE
ENH: Alias --output-format with -o

### PR DESCRIPTION
**Pull request by mih**
This one is frequently used and quite long to type.

Please merge @datalad/developers

### CODE REVIEW

**Comment by yarikoptic** [comment]
It may be -f? Don't we have a way to redirect kids to a file, so may be eventually -o would make more sense for that.

**Comment by mih** [comment]
True, let's use `-f`. Will also piggy-back another related change.

**Comment by yarikoptic** [comment]
seems to be in need of fixing

**Comment by mih** [comment]
Fixed. Hopefully.

**Comment by yarikoptic** [comment]
For osx fix needs better if 0.9.x into master, otherwise good to go, but can't do in the phone due to above osx failure

**Pull request merged**
