### PR TITLE
UX: If a clean repo is dirty after a failed run, give clean-up hints

### LINKED ISSUE #2924: Give hints on how to revert/cleanup whenever "run" fails
#### What is the problem?
Follow up to https://github.com/datalad/datalad/pull/2922#issuecomment-429996043

If `run` fails, repo could be left in a dirty state with some new  and/or changed (unlocked) files.  User would need to figure out not only how to fix his command to run, but also how to revert back to the clean state.  So it would be nice to give either specific instruction or hints ("Use `git reset --hard && git clean -dfx` to get to the clean state before running the command again")

### PR DESCRIPTION
**Pull request by adswa**
This is an implementation of #2924.
In case where a run command failed in a formerly clean repo, and the repo is
left in a dirty state, log general hints to use 'git clean' and 'git reset'
at INFO level.
Closes #2924.

### CODE REVIEW

**Comment by adswa** [comment]
I have reworded the message to be a bit more careful

**Comment by adswa** [comment]
any opinions on this? We can vote:
- :-1: close this PR altogether
- :+1: merge with the current message
- :confused: close this PR but make a note in #6114 to include a similar warning in an overhaul of how we present hints
- :eyes: reword the current warning further (please include a suggestion)

**Comment by bpoldrack** [comment]
> "The commands 'git reset --hard' and/or 'git clean -dfi' could be used to get to a clean dataset state again. Consult their man pages for more information."

Generally fine with that, but if we are to suggest concrete command options for the "usual/general" case, make it either `git clean -dffi` (two `f`) or `git clean -di`, I think. That's because the second `f` makes `git clean` consider currently untracked subdatasets for removal (but still ask b/c `-i`). Hence, either make a suggestion that allows to clean up everything or a suggestion that is particularly careful about not removing too much (no `f` - AFAIK there's no point in a single  `f` if `i` is given).

So, my vote is on `git clean -dffi`, since creation of (to-be-added) subdatasets within a `run` call doesn't seem particularly outlandish to me.

**Comment by mih** [comment]
Waiting for @bpoldrack to put conclusion into https://github.com/datalad/datalad/issues/6114, such that compliance of this PR can be evaluated

**Comment by bpoldrack** [comment]
FTR: Wrote down the idea in #6114, but I don't think it makes sense to wait for an actual implementation.

So, apart from my preference for minimal rewording, can be merged from my POV.

**Pull request merged**
