### PR TITLE
Test against 3.10 on macos-latest since switched to arm64 without earlier pythons support

### PR DESCRIPTION
**Pull request by yarikoptic**
As only minor CI related -- I will not bother with user facing CHANGELOG

Closes #7585
partially addresses #7400

### CODE REVIEW

**Comment by yarikoptic** [comment]
with brew we have a problem -- I guess not fully worked out arm64 build?

```
==> Pouring libmagic--5.45.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libmagic/5.45: 356 files, 10.2MB
==> Installing git-annex
==> Pouring git-annex--10.20240227.arm64_sonoma.bottle.tar.gz
==> Caveats
To start git-annex now and restart at login:
  brew services start git-annex
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/git-annex/bin/git-annex assistant --autostart
==> Summary
🍺  /opt/homebrew/Cellar/git-annex/10.20240227: 10 files, 1[63](https://github.com/datalad/datalad/actions/runs/8820905835/job/24215546939?pr=7586#step:5:64).5MB
==> Caveats
==> git-annex
To start git-annex now and restart at login:
  brew services start git-annex
2024-04-24T17:42:13+0000 [INFO    ] datalad_installer: git-annex is now installed at /usr/local/bin/git-annex
Or, if you don't want/need a background service you can just run:
2024-04-24T17:42:13+0000 [ERROR   ] datalad_installer: /usr/local/bin/git-annex does not exist!
  /opt/homebrew/opt/git-annex/bin/git-annex assistant --autostart
Error: Process completed with exit code 1.
```

interestingly, `snapshot` way of installing works fine since we enable that rosetta for arch translation and .dmg installs/operates... I will wait for it to finish testing so we know if it passes or not

the easiest resolution would be to just go back to `macos-12` for now.

**Comment by yarikoptic** [comment]
@mslw -- macos tests are good now -- should we merge this?

**Comment by mslw** [comment]
@yarikoptic - happy days! I've just restarted failed workflows in #7585 in case you want to go for a more comprehensive update, but I'll leave the decision to you. Thanks for pushing through the installer problems!

**Comment by yarikoptic** [comment]
superseeded by #7585

**Pull request closed without merging**
