### PR TITLE
BF: explicitely terminate the Popen process if exception (e.g. KeyboardInterrupt)

### LINKED ISSUE #3613: no annex (should be) left behind!
I just found a busy (100-300% cpu busy) git-annex process running on smaug. That is a run away `annex get` invocation for some dataset where I guess I did `datalad get`, then interrupted (Ctrl-C), and then removed that dataset.

<details>
<summary>tree for that process from ps with a bunch of defunct child git processes</summary> 

```shell
$> ps auxw -H | grep -A70 367131[2]
yoh      3671312 66.7  0.2 1077111744 374584 pts/9 Sl Aug19 2074:56   /usr/lib/git-annex.linux/exe/git-annex --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git-annex/git-annex get --json --json-progress -J8 -- .
yoh      3671349  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671350  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671353  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671362  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671363  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671364  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671365  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671366  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671368  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671369  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671370  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671371  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671372  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671373  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671374  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671375  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671376  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671377  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671383  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671384  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671391  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671392  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671393  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671394  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671400  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671401  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671404  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671405  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671407  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671409  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671410  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671412  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671413  0.0  0.0      0     0 pts/9    Z    Aug19   0:00     [git] <defunct>
yoh      3671418  0.0  0.0  11824   788 pts/9    S    Aug19   0:00     /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git --git-dir=.git --work-tree=. --literal-pathspecs cat-file --batch
yoh      3671419  0.0  0.0  11824   788 pts/9    S    Aug19   0:00     /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git --git-dir=.git --work-tree=. --literal-pathspecs cat-file --batch

```
</details>

cwd points to removed dataset:
```shell
$> ls -l /proc/3671312/cwd
lrwxrwxrwx 1 yoh yoh 0 Aug 20 13:55 /proc/3671312/cwd -> /mnt/btrfs/scrap/tmp/ds002000\ (deleted)
```

<details>
<summary>and here is the head of strace for it</summary> 

```shell
$> strace -f -p 3671312 2>&1 | head -n 100
strace: Process 3671312 attached with 46 threads
[pid 3671417] futex(0x7fbcdc000bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671416] futex(0x7fbd10000bcc, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671415] futex(0x7fbd64001168, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671414] futex(0x7fbd54003b08, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671411] futex(0x7fbcec000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671408] futex(0x7fbd84001048, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671403] futex(0x7fbd0c000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671402] futex(0x7fbd4c004ee8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671399] restart_syscall(<... resuming interrupted poll ...> <unfinished ...>
[pid 3671397] futex(0x7fbd18000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671395] futex(0x7fbd38000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671388] futex(0x7fbd08000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671396] futex(0x7fbd08001148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671387] futex(0x7fbd20000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671385] futex(0x7fbd1c000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671381] futex(0x7fbd3c000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671380] futex(0x7fbd40000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671379] futex(0x7fbd24000bcc, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671378] futex(0x7fbd34000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671361] futex(0x7fbd60000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671360] futex(0x7fbd44000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671359] futex(0x7fbd70000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671358] epoll_wait(11,  <unfinished ...>
[pid 3671357] futex(0x7fbd4c000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671358] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671358] epoll_wait(11,  <unfinished ...>
[pid 3671356] futex(0x7fbd8c000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671358] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671358] epoll_wait(11,  <unfinished ...>
[pid 3671355] futex(0x7fbd64000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671354] futex(0x7fbd54000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671346] futex(0x7fbd50000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671344] futex(0x7fbd58000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671343] epoll_wait(35,  <unfinished ...>
[pid 3671342] futex(0x7fbd5c000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671343] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671343] epoll_wait(35, [], 64, 0) = 0
[pid 3671340] futex(0x7fbd68000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671343] epoll_wait(35,  <unfinished ...>
[pid 3671341] epoll_wait(31, [], 64, 0) = 0
[pid 3671339] epoll_wait(27,  <unfinished ...>
[pid 3671341] epoll_wait(31,  <unfinished ...>
[pid 3671339] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671341] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671339] epoll_wait(27,  <unfinished ...>
[pid 3671341] epoll_wait(31,  <unfinished ...>
[pid 3671339] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671339] epoll_wait(27,  <unfinished ...>
[pid 3671338] epoll_wait(20,  <unfinished ...>
[pid 3671337] epoll_wait(19,  <unfinished ...>
[pid 3671338] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671337] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671338] epoll_wait(20,  <unfinished ...>
[pid 3671337] epoll_wait(19,  <unfinished ...>
[pid 3671338] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671337] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671338] epoll_wait(20,  <unfinished ...>
[pid 3671337] epoll_wait(19,  <unfinished ...>
[pid 3671335] futex(0x7fbd9be328a8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671334] futex(0x7fbd80000bac, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671333] futex(0x7fbd9be32698, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671336] epoll_wait(15,  <unfinished ...>
[pid 3671332] futex(0x7fbd9be32488, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671336] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671336] epoll_wait(15,  <unfinished ...>
[pid 3671331] futex(0x7fbd88000ba8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671336] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671329] epoll_wait(4,  <unfinished ...>
[pid 3671336] epoll_wait(15,  <unfinished ...>
[pid 3671329] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671329] epoll_wait(4,  <unfinished ...>
[pid 3671328] futex(0x7fbd9bdb74b8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671329] <... epoll_wait resumed> [], 64, 0) = 0
[pid 3671329] epoll_wait(4,  <unfinished ...>
[pid 3671327] read(3,  <unfinished ...>
[pid 3671312] futex(0x7fbd9bdb7398, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 3671327] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 3671327] read(3, "\1\0\0\0\0\0\0\0", 8) = 8
```
</details>

I wonder @joeyh -- shouldn't git annex process (eventually) die unhappily if its CWD / repo it tries to work on gets removed?

<details>
<summary>annex version details</summary> 

```shell
$> git annex version
git-annex version: 7.20190730+git122-g708fc6567-1~ndall+1
build flags: Assistant Webapp Pairing S3 WebDAV Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.20 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.3 feed-1.0.0.0 ghc-8.4.4 http-client-0.5.13.1 persistent-sqlite-2.8.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: linux x86_64
supported repository versions: 5 7
upgrade supported from repository versions: 0 1 2 3 4 5 6
```
</details>

### PR DESCRIPTION
**Pull request by yarikoptic**
Otherwise it was observed (#3613) that batched parallel `git annex get` instances might still remain
running consuming bandwidth and resources.

I have added try/except around .terminate() call itself, although it might be
an overkill since in normal scenarios I do not expect that to fail.

I have tested locally by interrupting `datalad get` invocations, and it seems to do the trick!

Closes #3613

TODOs
- [ ] test  ~~well, could be done, even if only for smoke testing that code logic, but wasn't in the best traditions of the fast progress~~ I think I will not be lazy, making a test

### CODE REVIEW

**Comment by mih** [comment]
Thanks for doing that! This was a rather annoying behavior that has hit me frequently. Only the PY2 tests are failing (beloved unicode) -- those are not relevant for master.

I now realized that targeting 0.11 for such fixes will bypass all the extended windows tests, such that any potential failure would have to be dealt with in bulk merges from 0.11 into master -- this could easily turn into a nightmare, because of the division of labor we have ATM (I am doing most of the windows work, but I do not touch 0.11). Also, this further introduces more `six` usage into the codebase that needs to be taken out again. How shall we deal with this?

**Comment by yarikoptic** [comment]
> Only the PY2 tests are failing (beloved unicode) -- those are not relevant for master.

and I don't think all these crashes are really "caused" by these changes -- only brought up to surface.
<details>
<summary>
What confuses me is that even though we have `__str__` defined for CommandError, it is not used when we/I do `str(exc)`:
</summary> 

```
*(Pdb) p exc.__str__()
u'CommandError: command \'[\'ssh\', \'-o\', \'ControlPath="/home/yoh/.cache/datalad/sockets/ef2d633e"\', \'localhost\', \'export "PATH=/usr/lib/git-annex.linux:$PATH"; mkdir -p /home/yoh/.tmp/datalad_temp_test_failon_no_permissions2LNBd3/ds\']\' failed with exitcode 1\nFailed to run [\'ssh\', \'-o\', \'ControlPath="/home/yoh/.cache/datalad/sockets/ef2d633e"\', \'localhost\', \'export "PATH=/usr/lib/git-annex.linux:$PATH"; mkdir -p /home/yoh/.tmp/datalad_temp_test_failon_no_permissions2LNBd3/ds\'] under None. Exit code=1. out= err=mkdir: cannot create directory \u2018/home/yoh/.tmp/datalad_temp_test_failon_no_permissions2LNBd3/ds\u2019: Permission denied\n'
*(Pdb) p str(exc)
*** UnicodeEncodeError: UnicodeEncodeError('ascii', u'CommandError: command \'[\'ssh\', \'-o\', \'ControlPath="/home/yoh/.cache/datalad/sockets/ef2d633e"\', \'localhost\', \'export "PATH=/usr/lib/git-annex.linux:$PATH"; mkdir -p /home/yoh/.tmp/datalad_temp_test_failon_no_permissions2LNBd3/ds\']\' failed with exitcode 1\nFailed to run [\'ssh\', \'-o\', \'ControlPath="/home/yoh/.cache/datalad/sockets/ef2d633e"\', \'localhost\', \'export "PATH=/usr/lib/git-annex.linux:$PATH"; mkdir -p /home/yoh/.tmp/datalad_temp_test_failon_no_permissions2LNBd3/ds\'] under None. Exit code=1. out= err=mkdir: cannot create directory \u2018/home/yoh/.tmp/datalad_temp_test_failon_no_permissions2LNBd3/ds\u2019: Permission denied\n', 542, 543, 'ordinal not in range(128)')
```
</details>

ok -- figured it out.  It was failing while converting to bytes after `__str__` returned unicode. Fix pushed, and 6bce96db8932ade3f6b9d008022a69f3e289f785 (ATM) should simply be reverted upon merge into master

> ... How shall we deal with this?

I guess only via the suboptimal workflow you have described. And probably you know that, it will be happening until 0.12 is released and I could use it without reverting to use/maintain 0.11 whenever it takes way too long to accomplish a basic operation.

**Comment by mih** [comment]
> and I could use it without reverting to use/maintain 0.11 whenever it takes way too long to accomplish a basic operation.

Please remember to file issues for these cases. At the moment there is only a single issue with a percentage difference. I cannot fix what I dont know.

**Comment by yarikoptic** [comment]
another aspect is that we have more Popen calls, but I guess it should be a separate issue, so here is #3800 to either have it fixed or just closed because of old age.

**Comment by yarikoptic** [comment]
> Please remember to file issues for these cases. At the moment there is only a single issue with a percentage difference.

yeap -- AFAIK the most grave exponential growth was addressed.

> I cannot fix what I dont know.

sure thing!

**Comment by yarikoptic** [comment]
grr , for some reason datalad-crawler run now gets stuck right away:
```shell
$ http_proxy= PATH=$PWD/../tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -A "$NOSE_SELECTION_OP($NOSE_SELECTION)" --with-doctest --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM
...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

whenever 4 days ago 0.11.x completed just fine.

**Comment by yarikoptic** [comment]
ok, I restricted to non-CommandError and the stall went away, so ready to be merged

**Pull request merged**
