### PR TITLE
INFRA: Modernize readthedocs configuration

### PR DESCRIPTION
**Pull request by adswa**
This is an attempt to fix the readthedocs build failure. I've modernized our readthedocs.yml file into a modern version 2 one. The previous one was the culprit leading to the wrong requirements being installed - I hope this one may fix it.
I will kill all CIs in this PR.

### CODE REVIEW

**Comment by adswa** [comment]
The PR feature of readthedocs isn't enabled here, I fear we have to merge this to see if it works

**Review by mih — APPROVED** [review]
Ouch, this hurts. Now I understand why me setting things in the UI had no impact. Stupid me. Thx, let's merge and see.

**Comment by mih** [comment]
Not yet: https://readthedocs.org/projects/datalad/builds/15303698/

**Comment by mih** [comment]
Please push such changes straight into master, there is no value in working this out via a PR, IMHO

**Comment by adswa** [comment]
will do, thx

**Pull request merged**
