### PR TITLE
Fix datalad --help to not have *Global options* empty and list options in "options:" section

### PR DESCRIPTION
**Pull request by yarikoptic**
Detected while considering #7027 (note: that one is against `master`, this one -- `maint`)

I believe came up as a regression of e89ce439a3b24607e4809a664a961a678063cded and since we had no unittest. So I also added a test.

Without this fix  --help looked like

	options:
	  -c (:name|name=value)
	...
	*Global options*

and nothing at the end after *Global options*.

### CODE REVIEW

**Comment by yarikoptic** [comment]
although changelog commit no longer has `[ci skip]` it seems that github completely skips that updated state in its CI. @jwodder any ideas on why that might be happening?

unfortunately adjusted test fails on travis and appveyor... need to figure why (passes locally). Could be python (argparse) version or how we install for testing... will need to troubleshoot

**Comment by jwodder** [comment]
@yarikoptic I think this may be because the snippet is pushed using `secrets.GITHUB_TOKEN`, so GitHub doesn't trigger any workflows in order to avoid a potential infinite loop of workflows.

**Comment by yarikoptic** [comment]
> @yarikoptic I think this may be because the snippet is pushed using `secrets.GITHUB_TOKEN`, so GitHub doesn't trigger any workflows in order to avoid a potential infinite loop of workflows.

hm, may be, odd though.  I wish there was some log to check on github which might have given explanation. If we would not be able to overcome this limitation, it would be quite suboptimal :-/

**Comment by yarikoptic** [comment]
failures on travis and appveyor unrelated now.

**Review by mih — APPROVED** [review]
Works for me! Thx

**Comment by yarikoptic-gitmate** [comment]
PR released in [`0.17.6`](https://github.com/datalad/datalad/releases/tag/0.17.6)

**Pull request merged**
