### PR TITLE
ENH: merge 0.11.x into master

### PR DESCRIPTION
**Pull request by yarikoptic**
- includes the debated init safety check (#3211)
  - the "switch" will be in an independent PR ~~whenever master acquires fresh revolution with the check done at `rev-create` level~~ (I guess useful for testing within revolution itself, so will bring it whenever this PR is merged)
- reincarnates testing of the revolution in master which was disabled by recent merge into master without adjustment of .travis.yml

### CODE REVIEW

**Comment by kyleam** [comment]
>     * reincarnates testing of the revolution in master which was disabled by recent merge into master without adjustment of .travis.yml

Thanks, but this was already covered by #3216.

**Comment by yarikoptic** [comment]
Oops, my bad, missed it, and it wasn't yet merged when I merged master, will remove and merge again

**Comment by mih** [comment]
This switch is not just useful for testing. -revolution code is actively used and a dependency for other extensions. A merge of this PR will manifest the situation that I wanted to prevent...

**Comment by yarikoptic** [comment]
don't you worry @mih - I will add a switch.  Your precious seconds will be spared

**Comment by yarikoptic** [comment]
doing it now as a separate PR on top of this one

**Pull request merged**
