### PR TITLE
BF: Don't suppress datalad subdatasets output

### LINKED ISSUE #4770: datalad subdatasets output should not just suppress output (or provide info on how to expand)
```
~/proj/nuisance$ datalad subdatasets -r
subdataset(ok): /home/chrispycheng/proj/nuisance/code/simple_workflow (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/QA (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/QA-mriqc (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/bids (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/mriqc (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/simple_workflow (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/sourcedata/dbic-BIDS (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/sourcedata/dbic-BIDS/Chang (dataset)
subdataset(ok): /home/chrispycheng/proj/nuisance/data/dbic/sourcedata/dbic-BIDS/Chang/Chang (dataset)
  [53 similar messages have been suppressed]
action summary:
  subdataset (ok: 63)
```
the whole point of running the command is to see subatasets, so not sure if just suppressing without giving a hint on how to avoid that is a good UX

### PR DESCRIPTION
**Pull request by DisasterMo**
### Changes

Add `custom_result_renderer()` to `Subdatasets` command class as a wrapper for `default_result_renderer()`.
Now `datalad subdatasets` will actually do what it's supposed to: list all present subdatasets without suppressing the output.

### Related Issues

Fixes #4770

### CODE REVIEW

**Comment by mih** [comment]
Thanks much for this PR!

I would say this PR can go against the `maint` branch, given its nature of being a fix.

I have presently no idea re the cause of this failure:

https://app.travis-ci.com/github/datalad/datalad/jobs/541349553
```
======================================================================
2363FAIL: datalad.metadata.tests.test_search.test_within_ds_file_search
2364----------------------------------------------------------------------
2365Traceback (most recent call last):
2366  File "/tmp/dl-miniconda-kkjyqyv4/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
2367    self.test(*self.arg)
2368  File "/tmp/dl-miniconda-kkjyqyv4/lib/python3.9/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
2369    return t(*(arg + (filename,)), **kw)
2370  File "/tmp/dl-miniconda-kkjyqyv4/lib/python3.9/site-packages/datalad/metadata/tests/test_search.py", line 241, in test_within_ds_file_search
2371    assert_equal(
2372AssertionError: Lists differ: ['subdataset(impossible): /tmp/datalad_temp[184 chars].id'] != ['audio.music-artist', 'datalad_core.id']
2373
2374First differing element 0:
2375'subdataset(impossible): /tmp/datalad_temp[142 chars]set]'
2376'audio.music-artist'
2377
2378First list contains 1 additional elements.
2379First extra element 2:
2380'datalad_core.id'
2381
2382+ ['audio.music-artist', 'datalad_core.id']
2383- ['subdataset(impossible): '
2384-  '/tmp/datalad_temp_test_within_ds_file_search8g4h9zzx/.datalad/metadata/objects/da/ds-753090a017914e0862098e811d7237 '
2385-  '[path not contained in any matching subdataset]',
2386-  'audio.music-artist',
2387-  'datalad_core.id']
```

**Comment by mih** [comment]
@DisasterMo You will need to (cherry-)pick the commit with the actual change, and base that off of `maint`. Right now the PR is trying to merge `master` plus that commit into `maint` -- which we cannot do. If you have difficulties achieving the desired state, please let me know -- I can help out. Thx!

**Comment by DisasterMo** [comment]
Oh, now I understand. I won't need help with that, but why merge it into `maint` instead of `master` in the first place?

**Comment by mih** [comment]
I found the cause for the test failure. I cannot push directly to this branch, hence I am attaching the patch.
[0001-Disable-result-rendering-for-internal-subdatasets-ca.patch.txt](https://github.com/datalad/datalad/files/7291229/0001-Disable-result-rendering-for-internal-subdatasets-ca.patch.txt)

```diff

From 1d5081d06aea747c6f02748d0c87eb2ff773c026 Mon Sep 17 00:00:00 2001
From: Michael Hanke <michael.hanke@gmail.com>
Date: Wed, 6 Oct 2021 08:03:18 +0200
Subject: [PATCH] Disable result rendering for internal `subdatasets()` call in
 `get()`

The yielded results are inspected by `get` and evaluated in the context
of a get operation. A premature rendering by `subdatasets()` itself
is undesireable.
---
 datalad/distribution/get.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/datalad/distribution/get.py b/datalad/distribution/get.py
index b550595d9..161ee258e 100644
--- a/datalad/distribution/get.py
+++ b/datalad/distribution/get.py
@@ -859,7 +859,8 @@ class Get(Interface):
                 recursive=True if path else recursive,
                 recursion_limit=None if path else recursion_limit,
                 return_type='generator',
-                on_failure='ignore'):
+                on_failure='ignore',
+                result_renderer='disabled'):
             if sdsres.get('type', None) != 'dataset':
                 # if it is not about a 'dataset' it is likely content in
                 # the root dataset
-- 
2.33.0

```

**Comment by DisasterMo** [comment]
@mih Thanks! Should I squash the commits, or how is the policy here?

**Comment by mih** [comment]
All green. Let's go. Thx much @DisasterMo

**Pull request merged**
